BrightspaceUI/core

.editorconfig, .gitattributes, .gitignore, .travis.yml, CODEOWNERS, LICENSE, components/d2l-hello-world.js, index.html, package.json, polymer.json
Just to get rolling - linting and other things to come.
=> Initial basic setup.

.eslintrc.json, components/helpers/d2l-dom.js, components/localize/localize-mixin.js, components/more-less/more-less.js, index.html, package.json
This is mostly copy-pasted from the polymer 3 component with a few little modifications as necessary.
I added `d2l-dom.js` from `d2l-polymer-behaviors`. This could be potentially be renamed to something to do with ancestry.
I also fixed an issue with localization. I modified `proto.__localizationCache.requests[namespace] = true;` to be the result rather than `true` as this caused issues when multiple `more-less` components on the same page where the second component would go to get the resources, but the cache would say that they have already been fetched but they wouldn't be in `this.__resources` so the button text would be undefined.
=> more-less: add remaining functionality

components/typography/styles.js, components/typography/typography-styles.js, components/typography/typography.js
This PR deals with the original typography mixins.
=> Updates for old mixins.

test/index.html, test/more-less/more-less.html
These are also failing the build with a real error, leaving for now in case people want to check out the error message.  Will add `skip` before merging (and will add a defect).
=> Add moreless tests

README.md
Including some specific info about:
* how to run visual-diff locally
* how to run subset of visual-diff locally (useful while developing)
* how to update local goldens for visual-diff
=> Update readme with some basic testing info.

test/icons/icon.visual-diff.html, test/icons/icon.visual-diff.js
@dbatiste am I visual diffing right? :)
=> visual diff tests for icons

components/meter/meter-linear.js, components/meter/meter-radial.js, demo/meter/meter.html, test/meter/meter-linear.visual-diff.js, test/meter/meter-radial.html, test/meter/meter-radial.visual-diff.html, test/meter/meter-radial.visual-diff.js
Here is the Radial meter:
Use:
`<d2l-meter-radial value="5" max="13"></d2l-meter-radial>`
Out of scope:
Switching between % and x/y.
Adding a white background when x/y overlap the meter.
Secondary text.
Animation.
=> Radial meter initial

helpers/uniqueId.js
Moving over the unique Id generator.
=> Unique Id Generator

components/button/button-styles.js
Corresponding change in core. Will need new goldens.
=> updates to button focus styles for WCAG 2.1

components/button/button-icon.js, components/button/demo/button-icon.html, components/button/test/button-icon.visual-diff.html, components/button/test/button-icon.visual-diff.js
Mirrors the recent change to `d2l-button`, but with visual diff tests. :)
=> making focus box-shadow customizable

components/more-less/more-less.js
* Allows components to respond to the more/less finishing
* Fixes issue where iframeresizer isn't picking up transition events
=> Bubble more-less transition events

.travis.yml, README.md, package.json
This gets everything in place to automatically publish to NPM.
=> setting up automatic tagging and publishing to NPM

components/meter/meter-radial.js
=> Centre Radial Text. Required for lots of text

components/colors/colors.js
I'll hold off on merging this until the version stuff is sorted.
=> Remove deprecated colors. [increment patch]

components/colors/README.md
Also testing out the NPM deployment :)
=> [increment patch] fixing typo

components/meter/meter-circle.js, components/meter/meter-radial.js
- Updated the white space and sizing to max the design website for the radial meter
- Added an optional fill color for the circle meter.
=> White space and Fill for Meters

mixins/localize-mixin.js, mixins/localize-mixin.md, mixins/test/.eslintrc.json, mixins/test/localize-mixin.html, mixins/test/test-elem.js, test/index.html
These were mostly copied from https://github.com/BrightspaceUI/localize-behavior/blob/master/test/d2l-localize-behavior.html
=> LocalizeMixin: add tests

components/button/test/button-mixin.html, components/button/test/test-button-elem.js, mixins/test/localize-mixin.html, test/index.html, wct.conf.json
Resolves https://github.com/BrightspaceUI/core/issues/107
=> Add tests for ButtonMixin

README.md
=> adding badge for total downloads

wct.conf.json
Re-enabling Firefox now that it supports dynamic imports.
=> trying to add Firefox back in

helpers/README.md, helpers/demo/dismissible-test.js, helpers/demo/dismissible.html, helpers/dismissible.js, helpers/test/dismissible.html, index.html, package.json, test/index.html
Ready for review. Check out the README diff or the test element for an example of how this works!
=> Dismissible Helper

components/more-less/more-less.js, components/more-less/test/more-less.html, helpers/dispatchRenderEvent.js
@dbatiste as discussed. Let's revisit for platform-level solutions to things that need to do async work before rendering next week.
=> not centralizing event dispatch code for now

helpers/localization.js, package.json
Second attempt at this, which will hopefully work now that nothing in BSI should be referencing `intl-messageformat` directly.
=> upgrading to latest intl-messageformat

mixins/arrow-keys-mixin.js, mixins/demo/arrow-keys-mixin.html, mixins/demo/arrow-keys-test.js, mixins/test/arrow-keys-mixin.html
* use async/await in arrow-keys mixin and tests to tidy up code
* add a demo for arrow-keys mixin
=> arrow keys mixin async

components/dialog/dialog.js, mixins/localize-mixin.md, mixins/localize-static-mixin.js
* introduces new `LocalizeStaticMixin` to avoid repeated code
* rejig readme to include the new mixin
* update d2l-dialog to use it
=> Add LocalizeStaticMixin and update d2l-dialog to use it

mixins/arrow-keys-mixin.md
Intending to `[increment minor]` so I can get at the dialog component
Let me know if I should do something else (or nothing at all)
=> Small change so I can bump the version

components/menu/demo/menu-item.html, components/menu/menu-item-link.js, components/menu/test/menu-item-mixin.html, components/menu/test/menu-item.html, components/menu/test/test-menu-item-elem.js, test/index.html
This was pretty much copy/pasted over. I also added tests for the menu-item-mixin which were not added in the previous menu-item PR.
=> Add d2l-menu-item-link

templates/README.md, templates/primary-secondary/primary-secondary.js
As discussed in the meeting today. Using these semantic elements will surface ARIA landmarks to screen readers, which can be very handy.
=> using semantic elements in place of divs

components/button/test/button.html, test/index.html
Noticed these tests were failing, was confused, then noticed they were never actually included. 🤷‍♂
=> fixing excluded and broken button tests

.eslintrc.json
Forgot to put `[increment patch]` in my last pr merge commit, so I made this incredibly important change so I could put it in this one.
=> PR for patch increment

components/dropdown/demo/dropdown-menu.html, components/menu/menu.js
On focus d2l-menus with d2l-item-radio children will set focus to the selected menu item instead of the first one
=> Focus radio-menu selection

directives/run-async.js, helpers/README.md, helpers/asyncStateEvent.js, mixins/async-container/README.md
Just a little helper class to help centralize how the `pending-state` event is created.
=> Add AsyncStateEvent helper class

components/demo/demo-snippet.js
Fixes https://github.com/BrightspaceUI/core/issues/478
=> demo-snippet: fix rtl behavior when no template

templates/primary-secondary/primary-secondary.js
Having the primary and secondary panels scroll separately is not ideal as pointed out by the designer, this PR is to correct it.
=> mobile view single scroll bar

components/demo/demo-page.js, components/inputs/demo/input-text.html
Found a couple issues just when poking around our demo pages in aXe. Technically all pages should have a `main` landmark, so I think it makes sense to apply it globally like this?
=> Demo page main landmark

CODEOWNERS
Probably should have done this a while ago... 🎉
=> making Allan a code owner!

components/demo/code-view-styles.js, components/demo/code-view.js, components/demo/demo-snippet.js
Couple minor fixes for lit-analyzer strict mode.
=> removing unnecessary language attribute

components/demo/demo-page.js
The addition of the `<main>` wrapper broke this last week. Thanks for noticing @dbatiste!
=> fixing demo page styles

components/backdrop/backdrop.js
General improvements: 
* uses `updated` as per best practice for observing property changes
* allows initial rendering in `shown` state
* allows `shown` to be toggled while animating
=> Update backdrop to use updated callback.

components/inputs/docs/input-date-time.md
add min-value and max-value for input-date, move properties to table format
=> inputs: date/time: readme updates

templates/primary-secondary/primary-secondary.js
Reverts BrightspaceUI/core#605
=> Revert "stickify footer in FACE mobile"

package.json
=> reverting back to 7

components/meter/meter-circle.js, components/meter/meter-linear.js, components/meter/meter-mixin.js, components/meter/meter-radial.js, components/offscreen/offscreen.js, components/status-indicator/status-indicator.js, components/tabs/tab-panel-mixin.js, components/tabs/tab-panel.js, components/tabs/tabs.js, components/tooltip/tooltip.js, mixins/arrow-keys-mixin.js, templates/primary-secondary/primary-secondary.js
- meter, offscreen, status-indicator, tabs, tooltip, primary secondary page template
- I cleaned up some properties from meter that were also included in the mixin
=> jsdoc comments part 5

components/alert/test/alert.test.js, components/calendar/test/calendar.test.js
Calendar - remove extra axe test (exists in .axe file)
Alert - move `fixture`
Hopefully this reduces flakiness
=> alert and calendar test tweaks

components/breadcrumbs/README.md
Found this catching up on some old PRs... I think this is what we want? 😝
=> Fix Breadcrumbs README

components/list/demo/list-demo-drag-n-drop-usage.js, components/list/list-item-drag-drop-mixin.js, components/list/list-item-drag-handle.js, lang/en.js
- Fixes the `NewPositionEventDetails.announceMove` function
- Adds a default label to the drag button
- Adds an attribute for users to change this label if they want to
=> fix: accessibility for list item dragging

components/alert/README.md, components/backdrop/README.md, components/breadcrumbs/README.md, components/button/README.md, components/dialog/README.md, components/dropdown/README.md, components/expand-collapse/README.md, components/focus-trap/README.md, components/inputs/docs/input-checkbox.md, components/inputs/docs/input-search.md, components/inputs/docs/input-text.md, components/link/README.md, components/loading-spinner/README.md, components/menu/README.md
Part 1 - will do more in another PR
=> Update READMEs to use table for properties

components/inputs/demo/input-number.html, components/inputs/input-number.js
This PR includes the following:
~ _handleChange method implementation
~ handle min/max values attributes (any input values less than min will be set to min and any input values more than max will be set to max)
~ handle min/max fraction digits attributes (input values will be updated based on min/max fraction digits on change)
~ handle number localization (input values will be formatted based on locale)
=> Handle input change, min/max values, min/max fraction digits, localization

components/list/list-item-generic-layout.js
=> fix: Fixing list item for Legacy Edge for 20.20.9

components/alert/test/alert.test.js, components/inputs/test/input-time-range.test.js, karma.bs.conf.js, mixins/test/localize-mixin.test.js, package.json
A fix was merged and released for the problem that caused this to be locked.
Also karma's latest version seemed to have been causing failures and hanging tests so I've locked it for now.
=> unlock mocha version

components/inputs/input-number.js, components/inputs/test/input-number.test.js, components/inputs/test/input-number.visual-diff.html, components/inputs/test/input-number.visual-diff.js
Changes made in this PR:
~ Added visual diff tests
~ Added a couple unit tests (invalid values and re-formatting values)
~ Validate on blur event (for the case when user focuses on a required field then blurs)
~ Fix tooltip position (make it relative host element)
~ Fix validity null error (make sure inner element exists before trying to validate)
=> Visual diff tests and minor bug fixes

components/list/list-item-mixin.js
There was a typo when I was doing actionHref.
=> fix: acitonHref !== actionHref

components/button/test/floating-buttons.visual-diff.js, components/calendar/test/calendar.visual-diff.js, components/form/form-element-localize-helper.js, components/form/form-helper.js, components/list/list-item-drag-drop-mixin.js, components/list/test/list-item-drag-handle.visual-diff.js, components/list/test/list.visual-diff.js, components/menu/test/menu-checkbox.visual-diff.js, components/menu/test/menu-radio.visual-diff.js, components/more-less/test/more-less.visual-diff.js, components/tabs/test/tabs.visual-diff.js, directives/run-async.js, helpers/gestures.js, mixins/async-container/test/async-container-mixin.visual-diff.js, package.json
All of this is rearranging so that variables and classes are not used before they are defined.
=> Move to the new version of eslint config

components/list/list-item-mixin.js
I searched all of core for the word aciton. It is now completely gone!
=> fix: aciton really isn't the same as action.

components/inputs/input-number.js
=> Fix tooltip console warning when invalid

.travis.yml
- Enable deploy on all branches so it will actually get released.
=> 1.85.x Version Bump

.travis.yml, README.md
- Pin node to version 14 until node sass releases support for node 15
- Clarify backporting steps in README
=> Pin node version and clarify README

components/more-less/more-less.js
https://app.circleci.com/pipelines/github/Brightspace/assignments-ui/6/workflows/61410bab-e85d-4017-b971-358c3f68be53/jobs/1835
=> fix null exception in disconnectedCallback

components/card/card.js, components/card/test/card.test.js
This is the cert version of #910.
=> fix: do not render href if null

cli/verify-translations.js
=> ci: fixing case where translations themselves contain a semi-colon

templates/primary-secondary/primary-secondary.js
- Add resize start and resize end events.
- These events are being added so that consumers of the component can listen in and disable pointer interactions for other components that might swallow touches like `iframe`s.
[Its being used here](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/147)
=> Add resize start and resize end events

.travis.yml, components/html-block/html-block.js
[Original PR](https://github.com/BrightspaceUI/core/pull/953).
=> Adding absolute positioning to hidden MathML

components/dropdown/dropdown-content-mixin.js
This was supposed to go to in a PR but I git pushed without realizing I was still on `master`. Reverting so it can go through a proper review.
=> Revert "Fix dropdown content overflowing page when aligned"

.licensechecker.json, .npmrc, .travis.yml, package.json
This adds the d2l license checker to CI. Adds a number of manual overrides for exemptions/corrections. See #923.
=> Add license checker

.eslintrc.json, package-lock.json, package.json
Use latest `eslint-config-brightspace` version.
=> lint: Bump eslint-config-brightspace version

components/inputs/input-number.js, components/inputs/input-styles.js, components/inputs/input-text.js
=> fix: adding a position override for text inputs (cert)

package.json
This PR is just to get the semantic versioning bot to run, because we missed that in the last PR
=> feat: Add file-audio and file-video to tier3 icons

components/dialog/test/dialog-confirm.test.js, components/dialog/test/dialog.test.js, components/focus-trap/focus-trap.js, helpers/focus.js, package-lock.json
Putting this up just in case this ends up being the appropriate fix for [this dialog issue](https://github.com/BrightspaceUI/core/pull/1330#issuecomment-843181215). Else just close it.
=> Check for null in focus-trap focus() method

components/table/test/table.test.js
=> run all the tests

components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js
=> Update dialog scroll when the dialog opens so that content is not initially scrolled.

components/button/README.md, components/button/button-icon.js, components/button/button-mixin.js, components/button/button-subtle.js, components/button/button.js, components/button/demo/button-icon.html, components/button/demo/button-subtle.html, components/button/demo/button.html, components/button/test/button-icon.axe.js, components/button/test/button-mixin.test.js, components/button/test/button-subtle.axe.js, components/button/test/button.axe.js, components/tooltip/test/tooltip.test.js, components/tooltip/tooltip.js
* adds property to buttons for optional tooltip in disabled state
* updates default tooltip delay
=> Add disabled tooltip to buttons

components/filter/filter.js, components/inputs/input-checkbox.js, lang/en.js
When we have just one dimension, we don't need to render the menu - opening the dropdown will show that dimension.
Design: https://xd.adobe.com/view/819a26ff-a0ba-4f8e-b405-ac677da84804-d4c9/screen/b66ee85a-4d6b-42b5-8344-c1bfd3aefe17
=> US122202 - Handle single dimension case

components/table/table-wrapper.js
Currently, if a table is hidden when mutating it, the class names are only applied after it becomes visible for the first time. If the table is hidden and made visible again after the first time, the class names won't re-apply properly.
This PR changes it so the class names are re-applied every time the table becomes visible after being hidden.
Additionally, I added some logic to make sure the mutation observer and the intersection observer are properly disconnected when relevant.
=> fix: Make sure table classnames are applied every time the table becomes visible

.github/workflows/license-checker.yml, .licensechecker.json
Also switch to only analyse production dependencies.
=> Switch to latest d2l-license-checker

components/card/card.js, components/card/test/card.visual-diff.js
- Removes the internal `_active` property on cards. Which doesn't seem to be necessary anymore
- Adds focus visible polyfill
=> Focus visible for card

helpers/getLocalizeResources.js
This will retry fetching any requests that are not cached as "200 OK"
=> Refetch the lang collection if the cached version is not ok

components/button/README.md
This is for after https://github.com/BrightspaceUI/documentation/pull/215 is merged
=> Daylight: Button defaults

components/status-indicator/README.md
Update documentation for daylight site, add new examples to readme
=> Daylight: Status indicator

components/link/README.md, components/link/link.js, components/menu/README.md
I also add `target=_blank` to the menu link items so that the links would open in a new tab.
=> Daylight: Link

components/tabs/README.md, components/tabs/tab-panel-mixin.js, components/tabs/tabs.js
I added a section for tab-panel here so that you would be able to interact with those properties, possible that we remove this since its just selected, text, and the no-padding properties
=> Daylight: Tab and Tab-panel

components/tooltip/README.md, components/tooltip/tooltip.js
There will be a corresponding PR in documentation with some tweaks
=> Daylight: tooltip

components/calendar/README.md, components/inputs/docs/input-search.md, components/inputs/input-search.js
There was also a tweak needed to calendar so I just included that in here.
=> Daylight: Search

components/inputs/demo/input-select-test.js, components/inputs/docs/input-select-styles.md
Similar to radio and table, uses the test component to allow for toggling the styles.
=> Daylight: Select lists

components/breadcrumbs/README.md, components/inputs/docs/input-text.md, components/tooltip/README.md
Related PR https://github.com/BrightspaceUI/documentation/pull/270
Also tweaked input-text to use correct method formatting.
=> Tooltip doc tweaks

components/filter/README.md, components/filter/demo/filter-search-demo.js, components/filter/demo/filter.html, components/filter/filter-dimension-set.js, components/filter/filter.js, components/filter/test/filter.axe.js, components/filter/test/filter.test.js
Adding the ability to turn on a Select All checkbox in the header for the set dimension.
=> US130429 - Add select all to filter

components/filter/filter.js
Looked into this a bit more after @dlockhart saw a weird axe flake.  Went with a more complete cursor fix and a more consistent colour fix.
=> Better cleanup of some leaking menu-item styles

components/status-indicator/README.md
Adds two section from design review, updates some other minor issues on the page
=> Daylight: status indicator fixes

components/meter/README.md
Updates demos to use different values and text property and changes a bunch of the copy text
=> Daylight: Meter review fixes

components/table/README.md
Changes:
- Content rewrite
- Adds sizes to demos to minimize the resizing that happens when the page loads
- Adds responsive behaviour demo (centred table with fixed width)
=> Updates to table page from design review

components/inputs/test/input-date-time.visual-diff.js, components/inputs/test/input-date.visual-diff.js, components/inputs/test/input-time.visual-diff.js
Adding these `await updateComplete`s to hopefully prevent test flakiness
=> input-date and time visual-diffs: await updateComplete

karma.sauce.conf.js
=> Stop testing in legacy Edge

helpers/framed.js
We want a good, performant, and reliable way to indicate whether we're in an FRA, so we can add one in that tries to communicate with the host page to get this information.
=> Add helper to detect if we're in an iframed FRA

components/filter/filter.js, components/filter/test/filter.test.js
Still looking into the axe tests for filter, will update in a separate PR.
=> Add opened attribute to filter

components/offscreen/README.md
Made some minor edits to the intro text. Also removed the demo since I think it's actually clearer without it.
=> Daylight: off-screen edits

components/inputs/docs/input-date-time.md
To potentially fix the loading issue in Daylight
=> fix: date & time inputs: replace const with var

components/dropdown/dropdown-opener-mixin.js, components/dropdown/test/dropdown-content.test.js
Just made some misc, fixes and added some tests for the dropdown opener class. The behaviour should stay the same.
=> US133079: More dropdown opener cleanup

components/filter/filter.js, components/filter/test/filter.axe.js
Now that the keyboard enhancements are in for list, turn on grid mode.
=> US133141 - Turn on grid mode for filter

package-lock.json
We're not quite ready to go to NPM 8 + Node 16, so in the meantime we need to downgrade this.
=> switching lock file back to v1 until we coordinate an upgrade to NPM 8

components/count-badge/test/count-badge-icon.visual-diff.html
Noticed this when doing some searches -- this must have been in your count badge branch Annabel when we scrubbed it from the repo!
=> removing unneeded Edge compatibility thing

components/demo/code-view.js, directives/animate/animate.js, package-lock.json, package.json
Made some tweaks here that seem to be working for me.
I'll add some comments inline!
=> animate fixes

components/breadcrumbs/README.md, components/button/README.md, components/inputs/docs/input-date-time.md, components/inputs/docs/input-numeric.md, components/inputs/docs/input-text.md
Minor fixes to formatting within axe tables that i noticed while building the search records
=> Accessibility property table fixes

controllers/subscriber/test/subscriberControllers.test.js
See if this helps for when Firefox is a bit slower
=> Add additional frame wait

components/colors/README.md
Polyfill was removed in c3e26149b0dc4c974dcc1643aae7db56bea125c6
=> drop mention of ShadyCSS from README

components/inputs/input-number.js, components/inputs/test/input-number.test.js
=> Fix number notation (20.22.2 version)

components/inputs/input-number.js, components/inputs/test/input-number.test.js
=> Fix number notation (20.22.1 version)

README.md
This wont merge until after Daylight MVP announced (March 1).
=> Daylight: Link to Daylight site at top of README

components/scroll-wrapper/README.md, components/scroll-wrapper/scroll-wrapper.js
Being able to set `overflow-y: hidden` mostly resolves this issue https://github.com/BrightspaceUI/core/issues/2096
=> Make vertical scrolling behavior on scroll wrapper configurable

mixins/localize-dynamic-mixin.js, mixins/localize-mixin.md
Fixes https://github.com/BrightspaceUI/core/issues/1544
=> localize-dynamic-mixin: Don't request unsupported langpacks in dev

README.md, components/tag-list/README.md, components/tag-list/demo/tag-list.html, components/tag-list/tag-list-item-mixin.js, components/tag-list/tag-list-item.js, components/tag-list/tag-list.js, components/tag-list/test/.eslintrc.json, components/tag-list/test/tag-list-item-mixin-consumer.js, components/tag-list/test/tag-list.axe.js, components/tag-list/test/tag-list.test.js, index.html
This PR adds the basic tag-list components and simple keyboard navigation.  Additional functionality coming in future PRs.
=> feat: Add d2l-tag-list, d2l-tag-list-item, and TagListItemMixin

.github/workflows/update-package-lock.yml
Once less commit per day which is nice.
=> Switch auto package-lock update to squash

package-lock.json
Attempt 2 as I created `1.x` off the wrong tag previously.
=> fix: updated package-lock

helpers/test/dismissible.test.js
Resolves https://github.com/BrightspaceUI/core/issues/778
~Attempting to re-enable these tests. Will re-run several times to see if the flakiness is still an issue.~
Re-ran 8 times on CI and several more times locally and saw no flake.
=> Issue 778: Re-enable skipped dismissible tests

components/dialog/README.md, components/dialog/demo/dialog.html, components/dialog/dialog-mixin.js
https://d2l.slack.com/archives/C0PHG3QB0/p1649786796542179
=> Added interception of dialog-mixin close event

components/html-block/README.md, components/html-block/html-block.js
Backport of this PR into 1.242.x: https://github.com/BrightspaceUI/core/pull/2439
=> Allow html-block to render inline

mixins/demo/localize-test.js, mixins/localize-mixin.js, mixins/localize-mixin.md, mixins/test/localize-mixin.test.js
Removes the changes from https://github.com/BrightspaceUI/core/pull/2446 from the cert branch
=> fix: remove dynamic localization mixin changes from cert branch

components/tooltip/README.md
=> Help Tooltip > Some documentation tweaks

components/menu/test/menu.test.js
I was thinking more of a test that specifically targeted this one case, vs. adding it to the focus tests. I think it would let you simplify things a bit... was also able to remove a lot of the `nextFrame()` stuff (I think, unless this is flaky in CI).
=> test specifically for slow items

components/tooltip/README.md, components/tooltip/tooltip-help.js
Various tweaks and changes to the Tooltip documentation page, based on discussions with Jeff and Margaree.
=> (Help) Tooltip > Various tweaks and changes to the Tooltip documentation page

components/dialog/README.md
[US140739](https://rally1.rallydev.com/#/?detail=/userstory/641721547587&fdp=true): UI Core dialog - Add autofocus feature
=> feat: Add autofocus to readme

components/calendar/test/calendar.visual-diff.js, components/dropdown/test/dropdown-content-contained.visual-diff.js, components/dropdown/test/dropdown-content.visual-diff.js, components/dropdown/test/dropdown-menu.visual-diff.js, components/dropdown/test/dropdown-openers.visual-diff.js, components/inputs/test/input-date-range.visual-diff.js, components/inputs/test/input-date-time-range.visual-diff.js, components/inputs/test/input-date-time.visual-diff.js, components/inputs/test/input-date.visual-diff.js, components/inputs/test/input-helper.js, components/inputs/test/input-time-range.visual-diff.js, components/inputs/test/input-time.visual-diff.js, components/list/test/list.visual-diff.js, components/selection/test/selection.visual-diff.js, mixins/async-container/test/async-container-mixin.visual-diff.js, templates/primary-secondary/test/primary-secondary.visual-diff.js
Using https://github.com/BrightspaceUI/core/pull/2647 for testing, I added some changes to make every test fail and slowly unskipped batches and compared the new goldens to see which could not be rerun without causing side effects.  This included additional elements being added, scrolling differences, focus differences, timeouts waiting for something that had already happened, etc.
I'm not expecting any visual-diff changes.
=> US141270 - Fixup tests that currently cannot be rerun

components/switch/README.md
Related to this [Rally Story](https://rally1.rallydev.com/#/?detail=/userstory/637810377847&fdp=true)
Added in a separate demo showing the consumer how they can work with the new "conditions" state of the Visibility Switch.
=> fix: Visibility Switch > Documentation Tweaks

components/tag-list/tag-list.js
Releases changes to `tag-list-item` made here: https://github.com/BrightspaceUI/core/pull/2772
=> Forcing release to get `tag-list-item` updates - US141912

components/switch/README.md
Just some tweaks and improvements to the documentation page for the Visibility Switch, after checking in with Jeff.
Note that the new changes are from Jeff.
=> fix: Visibility Switch > additional documentation tweaks

components/description-list/README.md
Update the README for `d2l-dl-wrapper`
=> fix: Description List - Update README

lang/ar.js, lang/da.js
Backporting these translation changes into 22.09 (2.42.x).
=> Updating Translations 2210 06/09/2022 (#2819)

components/selection/selection-mixin.js, components/selection/selection-summary.js
https://rally1.rallydev.com/#/255540250444d/iterationstatus?detail=%2Fuserstory%2F630445451251
Related PRs:
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/522
- https://github.com/Brightspace/ipsis-sis-course-merge/pull/28
=> US137419 - Select courses - Add override for selected count 

components/list/test/list.visual-diff.js
So I'm not sure if this will totally fix the flake for this visual-diff test. I can't reproduce locally and I was initially able to through ci, and then after I'd fixed it I couldn't get it to break again even after removing the fix 🤷.  But it won't make things worse so let's see... 🤞
=> US143412 - Try to fix flaky list visual-diff test

components/more-less/demo/more-less.html, components/more-less/more-less.js, components/more-less/test/more-less.test.js, components/more-less/test/more-less.visual-diff.js
https://rally1.rallydev.com/#/10153049633d/dashboard?detail=%2Fdefect%2F645660620675
=> resolution for more-less component defect which resulted in extra whitespace

components/collapsible-panel/README.md
Some updates to the collapsible panel daylight page.
=> fix: Collapsible Panel docs update

components/filter/filter-dimension-set.js, components/filter/filter.js
Remove exported EmptyStateType constants that aren't needed anymore after some code cleanup previously.
=> Clean up unnecessary EmptyStateType

helpers/localize.js, mixins/demo/localize-mixin-mission.js, mixins/localize-mixin.js
Iteration of #3370
POC using IntlMessageFormat directly for rich HTML with langfiles, with validation of allowed html elements.
=> Localize rich text

helpers/localize.js, mixins/demo/localize-mixin-mission.js, mixins/localize-mixin.js, package-lock.json, package.json
Simple POC using IntlMessageFormat directly for rich HTML with langfiles.
=> Alternative using IntlMessageFormat

components/inputs/input-date.js, components/inputs/input-time.js
Forgot I'd removed this before restoring the `ResizeObserver` uses, and then didn't get Stacey's subtle hints about it in the review. Adding back!
=> fix: adding polyfill back

components/list/list-item-checkbox-mixin.js, components/list/test/list-item-checkbox-mixin.test.js
[DE52841](https://rally1.rallydev.com/#/?detail=/defect/696182335295&fdp=true)
Backport #3478
=> Backport list-item defect for 20.23.4

mixins/localize/README.md, mixins/localize/localize-mixin.js, mixins/localize/test/localize-mixin.test.js
The only usage of `LocalizeStaticMixin` has been removed, so I'm removing it from here as well.
I've taken this opportunity to rework and simplify the `LocalizeMixin` documentation as well.
=> Remove LocalizeStaticMixin

mixins/localize/demo/localize-mixin-mission.js
Looks like we left a bunch of testing junk in the `mission` demo 😬
=> Fix localize-mixin mission demo

components/filter/filter-dimension-set.js, components/filter/test/filter.test.js
Small refactor on the filter component. Looks like the intro-text unit tests were duplicated from a merge.
=> Filter cleanup

helpers/mathjax.js
The only place this was in use was within the HTML editor for rendering math in TinyMCE's iframe. This has been unused for a few months as we've been using a more efficient typesetting method governed by a feature flag. That flag is being removed today, so this function can also go.
=> Remove now unused MathJax typesetting function

.github/workflows/ci.yml, package-lock.json, package.json, web-test-runner.config.js
Recreated from https://github.com/BrightspaceUI/core/pull/3711 to target `main`
=> Create wtr config with @brightspace-ui/testing

.github/dependabot.yml
Thanks @eKoopmans for pointing out that this still requires a dependency name.
=> include wildcard dependency name

components/collapsible-panel/README.md
Had discussions with @geurts to finalize wording.
=> fix: `d2l-collapsible-panel` > update documentation

components/icons/README.md
=> remove IE11 reference

components/alert/README.md
[Rally Story](https://rally1.rallydev.com/#/15545167705ud/custom/21568985922?detail=%2Fuserstory%2F721347482745)
=> US157413 Toast Alerts: Multiple: Documentation

.github/workflows/release.yml
Backporting to our latest release branch.
=> fix: Use new release token

package-lock.json, package.json
Tested in BSI: https://github.com/Brightspace/brightspace-integration/pull/10514
=> fix: Unpin the intl-messageformat version now that the issues are fixed

components/inputs/input-textarea.js, components/inputs/test/input-date-range.vdiff.js, components/inputs/test/input-date-time-range.vdiff.js, components/inputs/test/input-date-time.vdiff.js, components/inputs/test/input-date.vdiff.js, components/inputs/test/input-time-range.vdiff.js, components/inputs/test/input-time.vdiff.js, components/list/list-item-mixin.js
Cleaning up even though I don't think it'll be a Lit 3 requirement.
=> fix: import lit-html things from lit

package-lock.json
Updating manually to isolate golden changes caused by Chrome rendering changes.
=> Update testing with byte-size/determinism changes

components/typography/typography.js, components/typography/typography.scss
=> Update fonts version 0.6.1.

components/filter/test/filter-tags.vdiff.js, components/tag-list/test/tag-list.vdiff.js
Adjust to the slightly longer timeout. Gonna run this a few times to see if it helps.
=> Adjust timeouts to try to reduce vdiff flake

components/filter/test/filter-tags.vdiff.js, components/tag-list/tag-list.js, components/tag-list/test/tag-list.vdiff.js
[GAUD-300](https://desire2learn.atlassian.net/browse/GAUD-300): Fixer: proper solution for filter-tags focus issue
Fixes flake in `tag-list` vdiff tests and focus issues in `tag-list` and `filter-tags`
Largely reverts the quick fix in #4199
[GAUD-300]: https://desire2learn.atlassian.net/browse/GAUD-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix tags flake and focus issues

components/form/form.js, components/form/test/form.test.js
This is a follow-up to #4599, as the original fix didn't fully cover the case in Creator. Explanation in line in the code.
=> fix: further handle nested forms inside custom elements

components/html-block/html-block.js, components/html-block/test/html-block.test.js, helpers/embeds.js
As implied in the title, this is a PoC and shouldn't be merged in this state. I'm just putting this in draft PR form so it's easier for us to collaborate on this and make sure we're all on the same page. :)
=> Introduce HTML embeds framework and implement it in the html-block component

components/inputs/docs/input-color.md, components/inputs/input-color.js
=> fix: inline-help docs for color input

components/dropdown/dropdown-content-mixin.js, components/dropdown/dropdown-content-styles.js, components/dropdown/dropdown-opener-mixin.js, components/offscreen/offscreen.js
[GAUD-6455](https://desire2learn.atlassian.net/browse/GAUD-6455)
This PR updates the fixed position dropdown to move offscreen when the opener is not in view. For instance, when the opener is scrolled out of view.
[GAUD-6455]: https://desire2learn.atlassian.net/browse/GAUD-6455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hide/show the fixed position dropdown depending on whether the opener is in view.

components/filter/README.md
[Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6473)
=> Date Filter: Document how to create a custom preset date range [GAUD-6473]

package-lock.json, package.json
https://desire2learn.atlassian.net/browse/GAUD-6570
=> fix: prune redundant semantic-dom-diff

components/filter/README.md
Tweaks to improve the Daylight demo
=> fix: Filter dates: Demo: Increase height of demo window, add more content

components/popover/popover-mixin.js
[GAUD-6612](https://desire2learn.atlassian.net/browse/GAUD-6612)
This PR adds animation when opening the popover.
[GAUD-6612]: https://desire2learn.atlassian.net/browse/GAUD-6612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add open animation to PopoverMixin.

components/collapsible-panel/README.md
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-6640)
=> Remove styles that patched resizing in demo snippets

.github/workflows/ci.yml, .github/workflows/vdiff.yml, .gitignore, components/form/test/form-element.test.js, components/tooltip/test/tooltip.test.js, d2l-test-reporting.config.json, d2l-test-runner.config.js, helpers/test/dismissible.test.js
Generate and submit a D2L format test report so it appears in https://test-reporting.d2l.dev dashboards.
=> Enable test reporting

d2l-test-runner.config.js, package-lock.json
Testing with the new default for test reporting.
=> Update to latest `@brightspace-ui/testing`

components/button/README.md, components/form/docs/form.md, components/inputs/docs/input-checkbox.md, components/inputs/docs/input-color.md, components/inputs/docs/input-date-time.md, components/inputs/docs/input-numeric.md, components/inputs/docs/input-search.md, components/inputs/docs/input-text.md, components/loading-spinner/README.md
Some sandbox titles that were missing for demos to add them to the sandbox demos
=> Add missing sandbox titles

components/table/table-wrapper.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-6955)
=> Prevent unnecessary updates on mutation

lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
[main branch PR](https://github.com/BrightspaceUI/core/pull/5000)
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7011)
=> fix: Backport translations to 24.24.10 branch

mixins/rtl/README.md
Probably want something like this too.
=> Add obsolete note to RtlMixin

components/tabs/README.md, components/tabs/tab-panel-mixin.js
[Jira ticket](https://desire2learn.atlassian.net/browse/DAYL-128)
=> feat: Tabs: Improve accessibility documentation

lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
Cert fix of https://github.com/BrightspaceUI/core/pull/5113
=> fix: Translation Updates (cert 20.24.11)

eslint.config.js, package-lock.json
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-6252)
With the updated config, some overrides are no longer necessary.
=> fix: use updated shared eslint config

mixins/localize/README.md
Link to docs to determine a proper OSLO collection name
=> Update OSLO collection name docs

components/dialog/dialog-mixin.js
Adding client side FF for dialog resize logic
=> GAUD 7397 > dialog add client side flag

components/dialog/dialog-mixin.js
Move new `updateSize()` to within flag block.
Update name of ff to match lms/darkly ff
=> fix: add updateSize to within flag block

components/form/form.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7473)
=> feat: Form: Clean up dialog form validation reset flag

components/focus-trap/README.md
[Jira ticket](https://desire2learn.atlassian.net/browse/DAYL-104)
=> feat: Focus Trap: Accessibility documentation

components/filter/filter.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7227)
This is an interesting one.
**Problem:**
Width of filter can be different between first and subsequent openings.
**Steps to Reproduce:**
See [Filter demo](https://live.d2l.dev/BrightspaceUI/core/components/filter/demo/filter.html), most consistent in Firefox (though I did observe this in Chrome) and with the second demo ("Single Set Dimension - Single Selection"). To notice it I'd recommend looking at what letter in the code below is covered on first then second opening.
**Investigation Notes:**
On subsequent openings the dropdown is 27px wider than initial opening. This is the difference between the default 15px padding on an input-text vs the 42px padding after calculating the slot width …
=> fix: Filter: Add ResizeObserver due to changing input-search width

components/empty-state/README.md
See defect: https://desire2learn.atlassian.net/browse/GAUD-7520
=> fix: Empty State - Removing unneeded periods

components/collapsible-panel/collapsible-panel.js
Noticed this while reviewing the other panel PR, offscreen styles are not being used.
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7598)
=> fix: remove offscreen styles

components/tabs/README.md, components/tabs/demo/tabs.html, components/tabs/tab.js
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-7483)
Working towards all the changes in this PR https://github.com/BrightspaceUI/core/pull/5435. This is super small pieces that are more boiler plate.
=> Tabs: Add README section on d2l-tab, rename d2l-tab, and add section to demo

components/tabs/tabs.js, components/tabs/test/tabs.test.js
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-7658)
Warn consumers if there are tab/panel mismatches when using the new `d2l-tab`/TabMixin with matching `d2l-tab-panel`  structure.
=> fix: Tabs: New Structure: Warn if tab/panel mismatch

components/tabs/tab-mixin.js, components/tabs/tab.js, components/tabs/tabs.js, components/tabs/test/tabs.vdiff.js
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-7655)
=> feat: Tabs: New Structure: Support skeleton

lang/mi.js
[GAUD-7791](https://desire2learn.atlassian.net/browse/GAUD-7791)
[GAUD-7791]: https://desire2learn.atlassian.net/browse/GAUD-7791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Maori Translation

components/tooltip/demo/tooltip.html
Raised by Dave, we think this might not have ever worked 🤷
=> GAUD-7902 - Fix tooltip demo

components/alert/README.md
=> Clarifying toast best practices

components/list/README.md, components/list/list-item-nav-button-mixin.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7928)
=> feat: List: Add docs for the new list item nav button mixin and component

components/typography/styles.js
GAUD-6540
Ok hopefully the last fix for this.
=> fix: document might not be there

components/typography/demo/typography.html, components/typography/styles.js, components/typography/typography.js, components/typography/typography.scss
[GAUD-7274](https://desire2learn.atlassian.net/browse/GAUD-7274): Support Thai fonts
[GAUD-7274]: https://desire2learn.atlassian.net/browse/GAUD-7274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Noto Sans Thai

components/menu/demo/custom-view.js
This background image was 404-ing and resulting in the whole custom view just being white.
=> GAUD-8059: fix demo

components/inputs/input-time.js, components/inputs/test/input-time.axe.js
=> fix: apply label to time input's menu

components/dialog/dialog-mixin.js, components/dialog/dialog.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8131)
=> fix: remove uses of flag for GAUD-7397

.github/workflows/translation.yml, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/haw.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/mi.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
[GAUD-8129](https://desire2learn.atlassian.net/browse/GAUD-8129): Test `core` with newlines and trim, export in TIE
This is the cleanup for #5823, as described there.
[GAUD-8129]: https://desire2learn.atlassian.net/browse/GAUD-8129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean up translations after #5823

components/popover/demo/popover.html, components/tooltip/demo/tooltip.html
[GAUD-7355](https://desire2learn.atlassian.net/browse/GAUD-7355)
This just fixes a couple demos from some recent changes.
[GAUD-7355]: https://desire2learn.atlassian.net/browse/GAUD-7355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix popover and tooltip demos.

components/button/button-move.js
[GAUD-8330](https://desire2learn.atlassian.net/browse/GAUD-8330)
[GAUD-8330]: https://desire2learn.atlassian.net/browse/GAUD-8330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-button-move.

components/link/link-mixin.js, components/link/test/link-mixin.test.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8457)
=> fix: LinkMixin tests

components/dialog/demo/dialog.html, components/dialog/dialog-mixin.js, helpers/README.md, helpers/dom.js, helpers/focus.js, helpers/test/dom.test.js, helpers/test/focus.test.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8062)
Added helpers to get an alternative node to focus in cases where the node trying to receive focus is not available.
=> feat: add `getFocusAlternative` helper

components/list/list-item-drag-handle.js, components/list/list-item-drag-image.js, components/list/list-item-generic-layout.js, components/list/list-item-mixin.js, components/list/list-item-placement-marker.js
[GAUD-8440](https://desire2learn.atlassian.net/browse/GAUD-8440)
This PR removes `RtlMixin` from the list components.
[GAUD-8440]: https://desire2learn.atlassian.net/browse/GAUD-8440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from list components.

components/link/link-mixin.js, components/link/test/link-mixin.test.js, components/menu/menu-item-link.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8558)
=> fix: add new window text when label is set

components/button/button-add.js, components/list/list-item-mixin.js
[GAUD-8574](https://desire2learn.atlassian.net/browse/GAUD-8574)
[GAUD-8574]: https://desire2learn.atlassian.net/browse/GAUD-8574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove GAUD-7495-add-button-white-background

components/progress/README.md, components/progress/progress.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8401)
=> fix: progress bar docs

components/scroll-wrapper/scroll-wrapper.js
[GAUD-8263](https://desire2learn.atlassian.net/browse/GAUD-8263)
Update the default value for `GAUD-8263-scroll-wrapper-media-print`.
[GAUD-8263]: https://desire2learn.atlassian.net/browse/GAUD-8263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update default for GAUD-8263-scroll-wrapper-media-print.

components/tabs/tab-mixin.js
Testing is completed and flag is getting enabled for 20.25.11 so enabling by default here.
=> feat: Tabs: Enable GAUD-8605 flag by default
