components/backdrop/backdrop.js, components/tag-list/tag-list.js
**Issue:**
At mobile widths, filter appears at the side and uses `d2l-backdrop`. `d2l-backdrop` changes the role of everything behind it to be `presentation`. When a filter change would happen (and `d2l-filter` would remain open), `d2l-tag-list` would look for `listitem`s to do the necessary chomping to 3 lines, but the problem was they would have a role of `presentation` instead of `listitem` and so the `d2l-tag-list` would do no such chomping.
**Solution Notes:**
When `d2l-backdrop` is enabled, it stores the previous role as `d2l-backdrop-role`. This solution uses that to get the list items.
This solution knows a bit too much about how `d2l-backdrop` is working and so is intended to be temporary. One suggestion for a more permanent solution by Stacey is having a `d2l-role` on the list …
=> fix: tag-list: also check d2l-backdrop-role to get list items

components/list/README.md, components/paging/README.md
Changes:
- The `Pageable Lists` section was placed within the `Selection Lists` section so I moved that to be below `Selection Lists`
- Fixed the best practices block in `Paging`
- Removed hiding the properties and events in `Paging` just temporarily until there's an interactive demo that exhibits these so they aren't missing on the page.
I also updated the `Paging` issue in the documentation repo so that it will properly use the new Paging readme.
=> fix: List paging documentation: Small tweaks

components/empty-state/README.md
Made some small changes to the empty state README. Daylight's `playground-preview` component's resize animation was temporarily adding a scroll-bar which was messing with the illustrated empty state's `ResizeObserver` causing it to get caught in a resize loop.
Dealt with a similar issue when I was reworking the selection component tests. Adding a permanent scrollbar to the demo fixes the issue.
=> Empty State README fixes

components/filter/filter-tags.js
The default value used for `tag-list` description within `filter-tags` is `Active Filters`. I also added a bit more information to the description.
=> fix: Daylight: filter-tags: label default

components/typography/styles.js, components/typography/test/styles.test.js
The current approach taken in #2688 requires elements to be styled without adding a class.
This can be achieved by generating styles for a specific CSS selector. ([Lit docs](https://lit.dev/docs/components/styles/#expressions) on using expressions in styles)
Looking for any feedback/thoughts/concerns/gotchas 😄 
- Wrapping the selector in `unsafeCSS`
- Ideally, we'd use `css` string (like in the [docs](https://lit.dev/docs/components/styles/#expressions)), but Stylelint can't parse since `css'.class'` is not _technically_ a valid css block.
- We could mitigate potential issues with `unsafeCSS` by writing validation to ensure the string is safe
=> Add dynamic typography style generation helpers

components/paging/pager-load-more.js, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
This PR updates the `d2l-pager-load-more` component to use `formatNumber` for formatting counts.  It also updates the lang-terms to use the plural type for formatting.
=> Localization fixes for d2l-pager-load-more

components/tooltip/tooltip.js
Note: this is the same PR as #2715, just with the base branch set to the feature branch for Visibility Switch-related changes, rather than `main`.
[Rally ticket](https://rally1.rallydev.com/#/?detail=/defect/643273080983&fdp=true)
This PR attempts to fix, or at least work around, the issue where ordered (`ol`)/unordered (`ul`)/definition(`dl`) list items are not read in `Safari + VoiceOver` within a `Tooltip`. 
Margaree also found out that it's not just the `li` elements within the list element that aren't being announced - it's also any other content, such as plain text before the `li`s.
After discussing with [Margaree and Dave B](https://d2l.slack.com/archives/C03FC0GDVB7/p1659465104621859?thread_ts=1658950757.652959&cid=C03FC0GDVB7), we decided to go with a work around where we can get …
=> fix: List items not read in Tooltip contents for safari and voiceover

components/switch/switch-mixin.js, components/switch/switch-visibility.js
[Rally Story](https://rally1.rallydev.com/#/?detail=/userstory/629821423167&fdp=true)
Similar to our checkbox or radio options, we'd like the Switch component to allow users to click on the label to toggle it on/off. Hovering over the label should also trigger the hover state. 
This PR also updates the cursor to be the default one for both the switch icon/graphic and it's label (including the conditions met opener), as discussed [here](https://d2l.slack.com/archives/C03FC0GDVB7/p1658771035474229?thread_ts=1658519924.626809&cid=C03FC0GDVB7).
Note that the new `click`/`hover` changes specifically _do not_ apply to the `conditions met` opener for the visibility switch, which was how we wanted the requirements for this story to apply.
Also worth noting that when the user clicks on the label …
=> feat: Switch > label hover and click improvements

components/dropdown/dropdown-opener-mixin.js, components/dropdown/test/dropdown-openers.test.js
For many of the LMS dropdowns in the navbar, they actually use the `no-auto-open` property to prevent the default open/close behaviour when the opener is clicked. That's because they have some logic where on the first open they want to do a partial render before actually opening the dropdown.
Unfortunately, when I switched from using a `<d2l-dropdown>` with a custom opener to having `<d2l-navigation-dropdown-button-icon>` actually be the opener (which is better), there's now no way to distinguish between a click on the opener and a click inside the dropdown to manually open/close it.
So this PR introduces a `d2l-dropdown-opener-click` event that consumers who are using `no-auto-open` can listen for to know when the opener was clicked (or ENTER was pressed).
=> feat: add "d2l-dropdown-opener-click" event

controllers/subscriber/subscriberControllers.js, controllers/subscriber/test/subscriberControllers.test.js
When ids ended with a space the error `SyntaxError: Failed to execute 'querySelector' on 'Document': '#' is not a valid selector.` was being thrown.
=> fix: SubscriberControllers: fix error caused by space on end

helpers/README.md, helpers/dom.js, helpers/test/dom.test.js
For the "skip nav" link accessibility fixes, we'd like to change the behavior such that it searches for a `<main>` or `[role="main"]` and then falls back to `<h1>` when moving focus. We'd also like for that search to include those elements inside web component shadow roots, since page or app templates [like our primary/secondary template](https://github.com/BrightspaceUI/core/blob/main/templates/primary-secondary/primary-secondary.js#L939) sometimes render those elements.
This adds a new DOM helper that works just like `document.querySelector` except that it also reaches into custom element shadow roots and queries them as well. I considered adding a `querySelectorComposedAll`, but decided to leave that for when/if the use case comes up.
=> feat: added querySelectorComposed to DOM helpers

components/dropdown/dropdown-content-mixin.js, components/dropdown/test/dropdown-content.test.js, helpers/demo/prism.html
This PR makes the `getContentContainer()` method in `DropdownContentMixin` public. Due to the search changes [here](https://github.com/BrightspaceUI/documentation/pull/988), Daylight needs to get access to `<dropdown-content>`'s scrolling container. This method already exists in the component and just needs to be made public. See the linked PR for additional context on this. 
I also updated the prism demo of the `DropdownContentMixin` with my changes because why not 😛
=> fix: Made getContentContainer() method in DropdownContentMixin public

components/switch/switch-mixin.js
[Rally Defect](https://rally1.rallydev.com/#/?detail=/defect/644299602729&fdp=true)
We noticed a UX bug where parts of the label, if not the entire label + conditions opener tooltip contents, would get highlighted if you toggled the switch sometimes (particularly if you toggled back and forth in a faster pace).
This PR fixes that issue by removing the ability for any text in the label to be highlighted (confirmed with Jeff that we want this behaviour), whether this highlighting occurs by trying to select the label text with the cursor, or when toggling the switch (as per above defect).
=> fix: Visibility Switch > remove ability to highlight text

components/tag-list/README.md, components/tag-list/demo/tag-list.html, components/tag-list/tag-list-item-mixin.js, components/tag-list/tag-list-item.js
This change will allow us to use the `d2l-tag-list` core component instead of `d2l-labs-multi-select-list` component [in d2l-activity-alignments](https://github.com/Brightspace/d2l-activity-alignments/blob/main/src/components/tags/activity-alignment-tag-list.js#L84). 
We require the tooltip to contain separate info than the text displayed on tag item to give the users context on selected standards aligned to a given activity. This PR addresses this gap by adding a `description` property to `d2l-tag-list-item` to better control what we can display in the tooltip. 
See demo for functionality added:
Rally ticket: https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F644105367505
=> Add description property to tag-list-item to better control tooltip - US141912

components/tag-list/README.md
Daylight sight creates property table from code so adding ignore comment on README so it does not get duplicated.
=> Add docs ignore on README for `d2l-tag-list-item` properties

helpers/prism.js
Looks like this was just missed. Came up during failing build of FRA.
=> fix: switch away from using `lit-element`

lang/cy.js, lang/de.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
Back-porting translation from https://github.com/BrightspaceUI/core/pull/2789.
LMS 20.22.9 -> core 2.42.x.
The 2.42.0 branch was created Aug 11, the day before the switch changes were merged, Aug 12th. As a result, it's not necessary to back-port the switch translations.
=> Backport translations.

components/alert/alert-toast.js, components/alert/demo/alert-toast.html, components/alert/test/alert-toast.test.js
Added the `d2l-alert-toast-button-press` event to the `<d2l-alert-toast>` component. The component will listen for the `d2l-alert-button-press` event, stop it from propagating and then dispatch it's own event.
The only existing usage of a button press event in a `d2l-alert-toast` is listening for the `d2l-alert-button-pressed` event which I did not stop from propagating so this change should not break any existing uses of the component. In a later PR, I plan to remove that event from the `<d2l-alert>` component after existing uses have been changed.
=> Added d2l-alert-toast-button-press event

components/list/list-item-generic-layout.js, components/list/list-item-mixin.js
This PR fixes an issue with the `grid` focus logic - specifically when focus is being moved backwards in the list (pressing `[up arrow]` key) and the previous adjacent list-item does not have a focusable element in the corresponding cell. 
The logic would simply use `getPreviousFocusable` with respect to the adjacent list-item as a fallback, which would cause focus to be applied to **any** previous focusable **before** the adjacent list-item, effectively skipping the item. What we really want is for focus to be applied to another cell in that list-item, preferably the primary action, and if that still doesn't work, then do the ultimate generic fallback.
=> Fix the grid focus logic.

components/empty-state/empty-state-styles.js
I added an option to use `<img>` tags in addition to `<svg>` tags in the custom illustration slot so it can be used in the lms with the `Image` control.
I also made a small change to the action slot (default slot) which will now accept the `first-of-type` of the action components instead of the `first-child`. This opens up some room for abuse by putting one of each action component but I don't really foresee that being an issue that comes up. I made this change because previously if you put the custom illustration above the action slot, it would not render the action since it is not the `first-child`. This change should make the component a little easier to use.
=> Added option for img tag in empty state illustration slot

components/html-block/html-block.js, components/html-block/test/html-block.test.js, components/html-block/test/html-block.visual-diff.js, controllers/attributeObserver/htmlAttributeObserverController.js, helpers/mathjax.js, helpers/prism.js
So there's a bit of an issue with how the non-default renderers load in the html-block component. Specifically, they're _very_ order-dependent and we currently don't have a fantastic way to guarantee that ordering.
This PR is the first of a few meant to bridge that gap - it refactors the html-block component to be resilient to asynchronously loaded renders, while leaving the existing logic in place to cover our bases until existing renderers are switched over.
=> Add support for async renderer fetching in html-block component

components/html-block/html-block.js
We always expect this observer to load eventually, so it seems reasonable for us to wait for it. If we don't, we can get into an unfortunate race condition because the observer doesn't trigger a host update when it first registers.
=> Make sure context attribute observer is loaded before rendering

components/description-list/description-list-wrapper.js, components/typography/styles.js, components/typography/test/styles.test.js
Since `descriptionListStyles` are being applied as a global stylesheet, the CSS selectors should be more specific.
In order to support complex CSS selectors in our style generation functions, the regex for `_isValidCssSelector` had to be updated
=> fix: Description List - use more specific css selectors

.gitignore
This was @svanherk 's suggestion:
https://github.com/BrightspaceUI/core/pull/2819#discussion_r965007587
The idea is that this will prevent `fr-on.js` from being included in future translation updates.
Rally: https://rally1.rallydev.com/#/?detail=/userstory/646017396039&fdp=true
=> fix: Ignore fr-on language file

helpers/prism.js
Because we always load the Prism loader, we always set Prism to manual mode whether or not we're actually loading Prism. This causes problems in HTML files where Prism is already loaded and our code samples aren't being used.
=> Don't set Prism to manual mode unless we're loading it ourselves

components/list/test/list.test.js
I was not able to reproduce the failure locally, but I was able to get it to fail in Firefox on a Sauce Labs machine. I was seeing that any list test that clicks an input too early could have the issue, so I applied the fix to all those tests.  The below fixed the issue on Sauce Labs, but we'll have to monitor in CI to see if its actually fixed.
=> US143322 - Fix flaky list tests in Firefox

.github/workflows/ci.yml, .stylelintrc.json, components/skeleton/skeleton-mixin.js
DE50056:
https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fdefect%2F647111877577
For an unknown reason, starting with Safari 16 the pulsing skeleton animation causes FACE (assignments, quizzing) and possibly other pages that make use of skeletons to render a blank page.
I tried a few different alternatives, but in the end disabling the animation was the only thing that worked reliably. I'm hoping that Apple fixes this relatively quickly and we can restore things.
This will be cert-fixed to `20.22.10` and possibly hotfixed on `20.22.09`.
=> DE50056: disable skeleton pulse animation in Safari

.github/workflows/ci.yml, .stylelintrc.json, components/skeleton/skeleton-mixin.js
Rally:
https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fdefect%2F649633827477
This is the `20.22.10` version of #2872.
=> DE50107: disable skeleton pulse animation in Safari

components/object-property-list/object-property-list.js
This PR switches the object-property-list to have a default `display: block` instead of its previous `display: contents`.
Relevant Slack discussion: https://d2l.slack.com/archives/G03Q166G2/p1663788781091659
=> fix: Use display block on object-property-list

components/paging/pager-load-more.js
With Firefox+NVDA, the load-more pager would announce the following when loading more:
> Loading More Items. Unavailable. Loading More Items.
Two issues here:
1. It announces "Unavailable" because we are disabling the button while the user is focused on it. This is potentially confusing for Firefox+NVDA users.
2. It announces "Loading More Items" twice - once for the alert, and once because the alert is contained within the button which is focused
This PR addresses these issues by reverting back to the original solution which doesn't disable the button while loading (originally discussed [here](https://github.com/BrightspaceUI/core/pull/2635#discussion_r919400865)). Instead, it simply bails from the click handler to prevent loading more while already loading. Secondly, it moves the alert …
=> DE50150: Fix d2l-pager-load-more for Firefox+NVDA.

components/inputs/input-number.js, components/inputs/test/input-number.test.js
There's some logic in the LMS that needs to listen for a number input's `change` event, and then perform different actions based on whether the value the user entered is valid or not. And by invalid, I mean if a min/max is set and the user enters a number outside that range.
The issue is that the input's `invalid` property gets updated in the `updated()` lifecycle callback, which was happening _after_ the event was fired. This change just waits for that to run before firing the event.
=> fix: wait for "invalid" to be updated before firing change event

components/inputs/input-number.js
Follow-up to #2910.
Turns out just waiting for `this.updateComplete` doesn't quite cut it in all scenarios. If the input blurs and triggers a `change` event, it works. But if the user presses ENTER and that triggers the `change` event, then `this.invalid` hasn't been updated yet.
I can't quite get to the bottom of why these two different scenarios behave differently, but it's consistent in all browsers. I think the reason it's not enough makes sense though:
1. `change` event fires, at which point input-number parses the raw value, sets `this.value` to the new value and decides whether to fire its own `change` event. Before doing that, we need to wait for the internal `invalid` state to get updated.
2. If we just wait for `this.updateComplete`, we're waiting for our own `updated()` …
=> fix: wait even longer for validity to resolve

mixins/localize-mixin.js, mixins/localize-mixin.md, mixins/test/localize-mixin.test.js
The `awards-public-ui` repo renders a component on a public-facing page that should be localized based on the viewing-user's preferences, not the creator's account settings or the default tenant settings.
- Allows the `localize-dynamic-mixin` to get its `possibleLanguages` from the browser with `useBrowserLangs`
- Moves `documentLocaleSettings` to a static property
- Refactors `generatePossibleLanguages`, moves it to a static method, and calls it only where needed
- Replaces `hasOwnProperty` calls
- Adds `useBrowserLangs` docs
[DE50422](https://rally1.rallydev.com/#/?detail=/defect/662854795259&fdp=true): [awards-public-ui] Spanish is not getting translated properly
=> Add support for localizing based on browser settings

mixins/localize-dynamic-mixin.js, mixins/test/localize-mixin.test.js
Initially thought this was fine, but 404s shouldn't happen at all with normal usage of `useBrowserLangs` in dev, and if they do it's likely something to fix, not ignore.
=> Remove language filtering when using browser langs

components/tooltip/tooltip.js
[Rally ticket](https://rally1.rallydev.com/#/?detail=/defect/664018732801&fdp=true)
Re-adding the changes from #2927 in addition to adding `overflow: hidden`, `height: 0`, `width: 0` when the tooltip is not shown. The failing visual diff tests seemed to be caused by some text overflowing when the tooltip is hidden. JAWS works as expected after this change.
The additions of `overflow: hidden` and `width: 0`, `height: 0` were messing up `force-show` positioning so I added an exception for that attribute where it will never be hidden
This PR fixes an issue where JAWS was not reading tooltip labels of interactive elements.
=> Re-add tooltip display fix for a11y

mixins/localize-mixin.js
Fixes older Safari errors (in SauceLabs) on `hasOwn`.
=> Replace Object.hasOwn with Object.prototype.hasOwnProperty

components/card/card.js
[DE50590](https://rally1.rallydev.com/#/?detail=/defect/666104817131&fdp=true)
This PR removes the transform hover style on cards that do not have the `href` attribute set. This was likely a regression from this [commit](https://github.com/BrightspaceUI/core/commit/d68ebc7ab249a4f544bd275af9e186e84a321bb3) which added support for reduced motion in the component.
=> Remove card hover style when href is not set

components/dialog/dialog-mixin.js, helpers/focus.js
[DE50625](https://rally1.rallydev.com/#/15545167705ud/custom/21568985922?detail=%2Fdefect%2F667903731881&fdp=true)
Our dialog components (ex `d2l-dialog-confirm`) have been failing to place focus on workflow buttons in Safari. This boils down to some changes that are being made by the browsers to what `offsetParent` will return when inside of web component slots/shadowDOM and an ancestor is `position: fixed;`. See: [Chromium Issue 1331803: modal dialog inside shadow root results in elements having a null offsetParent](https://bugs.chromium.org/p/chromium/issues/detail?id=1331803).
This change breaks our dialog focus logic because we rely on our [isFocusable](https://github.com/BrightspaceUI/core/blob/main/helpers/focus.js#L178) helper method to identify focusable elements within the …
=> Fix dialog initial focus behaviour for Safari.

components/inputs/docs/input-search.md, components/inputs/input-search.js, components/inputs/test/input-search.axe.js, components/inputs/test/input-text.axe.js
This just adds a new `description` property to `d2l-input-search` that gets passed down to the underlying `d2l-input-text` element.
=> Add description property to d2l-input-search.

components/selection/selection-observer-mixin.js, components/selection/test/selection-component.js, components/selection/test/selection.test.js
This PR replaces #2966. It improves the `SelectionObserverMixin` to automatically subscribe any of its selection-observer children, if it receives a subscription event from them. This is to support the case where a selection-observer is using `selection-for="some-id"` and has children in its shadow DOM that need to subscribe to that ID, which would otherwise be outside of their visible scope.
The PR also improves a few existing issues identified in #2966, with added test cases to cover them (see the first commit).
There is one possible edge case where the new behaviour may affect existing usages:
- a selection-observer is **nested** inside a selection-provider (e.g. `<selection-provider id="some-id1">`)
- it subscribes to a different provider instead, using `selection-for="some-id2"`
- …
=> feat: Pass provider to selection-observer children

helpers/announce.js
Oscar previously noticed that duplicate messages would not be announced in DataList File Drag & Drop test page as per https://github.com/Brightspace/lms/pull/28986#discussion_r998579192. This PR applies the fix he suggested for the DataList case, but to our `announce` helper.
I did a bunch of testing around this and was only able to reproduce this issue using VO. I observed the expected behaviour when testing with NVDA. I tried a bunch of things to reproduce this in the core demo page, but was only able to reproduce in the DataList page - eventually I gave up and just tested it in the context of that page.
=> Add another fix to ensure actual duplicate messages are announced.

components/backdrop/backdrop.js, components/backdrop/test/backdrop.test.js
This PR fixes an issue where non-`form`/`a` elements that previously had `aria-hidden="true|false"` would not have their `aria-hidden` attributes properly restored when "showing" the accessible elements upon hiding the backdrop. 
The root of the issue is that the `showAccessible` method was assuming that any element should have their `aria-hidden` attribute removed, regardless of whether or not `d2l-backdrop-aria-hidden` was set, but this attribute would only be set for `form` and `a` elements.  
Example case:
```html
<button aria-hidden="true">...</button>
<div>
<div id="target">...</div>
<d2l-backdrop for-target="target"></d2l-backdrop>
</div>
```
I think it is worth looking into whether we should just be setting `role="presentation"` and `aria-hidden="true"` on all elements. I think …
=> Fix the backdrop showAccessible method.

components/inputs/input-number.js, components/inputs/test/input-number.test.js
[DE50582](https://rally1.rallydev.com/#/?detail=/defect/666083170587&fdp=true)
This PR updates the `d2l-input-number` component to reset validity if the `min`, `minExclusive`, `max`, or `maxExclusive` properties are updated. i.e. if these properties are updated, they may change the state from invalid to valid or vice versa depending on the current value.
=> Update the d2l-input-number component to recheck validity.

components/form/form-element-mixin.js, components/inputs/input-number.js, components/inputs/input-text.js, components/inputs/test/input-number.test.js
[DE50568](https://rally1.rallydev.com/#/?detail=/defect/666002656097&fdp=true)
This PR updates the `d2l-input-number` component so that it's `invalid` property properly reflects the validation rules defined for both `d2l-input-number` as well as the underlying `d2l-input-text` element. When the validity of the underlying element changes (ex. due to `required`), we need to update the validity of `d2l-input-number`.
=> Fix d2l-input-number so that invalid property reflects internal d2l-input-text validation state.

components/selection/selection-observer-mixin.js, components/selection/test/selection-component.js, components/selection/test/selection.test.js
There was a defect in #2979, where children are still not being correctly subscribed.
I was using `e.target` instead of `e.composedPath()[0]` when determining whether to process the event (skipping the case where the target is `this`). It works in regular cases but doesn't work when the event is coming from within `this`'s shadow DOM.
I've also fixed the unit tests to catch this specific case.
Rally: https://rally1.rallydev.com/#/?detail=/userstory/668445846425&fdp=true
=> fix: selection-observers are not correctly subscribing their children

tools/dom-test-helpers.js
This new `getUpdateCompleteAll(node)` helper function walks the composed tree and `await`s any elements that have `updateComplete`. The motivation for this is that sometimes in tests we need to wait arbitrary amount of time for all the components to update - it is not enough to just wait for the root element's `updateComplete`. This is kinda costly, so I was reluctant to add this to our component helpers.
=> Add helper to enable waiting for updateComplete on all elements in a sub-tree.

components/html-block/demo/html-block.html
I think we broke this when we changed to enable loading the renderers `async`. It's also broken in the [user's demo page](https://github.com/BrightspaceHypermediaComponents/users/blob/main/demo/d2l-user-profile-html-block.html) for its renderer - I will be making a separate fix for it along with some other changes.
=> Fix the renderer loader in the d2l-html-block demo page.

helpers/mathjax.js
We want the HTML editor to be able to use MathJax to render equations within the editor window directly. This requires embedding MathJax within TinyMCE's iframe, so we need to generalize the MathJax helpers to allow external sources to manage typesetting, as well as to specify a different target window for typesetting.
=> Refactor MathJax helpers to allow consumers to typeset math directly, including in different windows

.github/actions/comment-on-pr/action.yml, .github/actions/publish-to-s3/action.yml, .github/workflows/ci.yml, .github/workflows/release.yml
This PR adds a publish step to the CI and release workflows. This builds and publishes a static version of core to S3.
I've created two separate actions for this purpose:
- publish-to-s3
- comment-on-pr
I've designed both actions to be theoretically reusable in the future, but keeping them internal for now. No readmes for them at the moment as they're just internal.
For publishing to S3, I made these decisions:
- no caching, so that changes can be seen immediately without refreshing the cache
- though I'd be open to putting say a default 2-minute cache on everything if we prefer
- yes to the default compression
Rally: https://rally1.rallydev.com/#/?detail=/userstory/670846679185&fdp=true
=> feat: Publish to S3 for PRs and main branch

components/demo/demo-snippet.js
This change fixes the demo-snippet so that elements stack properly in demos. This was a regression from https://github.com/BrightspaceUI/core/pull/2999. This original change created a stacking context that would result in snippet code floating on top of open dropdowns (check dropdown demo page). This change limits the stacking context to the dropdown itself.
=> Fix demo-snippet stacking

.github/workflows/ci.yml, .github/workflows/release.yml, README.md
Small follow-up to #3011: adding a link to the demos into the readme, and removing an unused var I was passing.
Rally: https://rally1.rallydev.com/#/?detail=/userstory/670846679185&fdp=true
=> chore: Add demo link to readme and remove AWS_ROLE

.github/workflows/release.yml
Fixing a small defect from #3022 - currently the stated version on [our demo page](https://brightspace-ui-core.d2l.dev/) is one version behind.
In the release workflow, we need to force `publish` to happen after `release`, so that the version has been correctly updated before publishing.
=> chore: Publish after release for correct version

components/list/demo/list-item-actions.html, components/list/list.js, components/list/test/list.axe.js
This moves the list header and the list's pager out of the actual list, as both were being counted as list items and causing axe tests to fail.  We didn't actually have an axe test for the header so I've added one, fixed a demo that was broken, and removed an unused class.
In a separate PR, I'm going to try to add a description for the list toolbar.
=> DE51092 - Correct List Count

components/list/demo/list-nested.html, components/list/list.js, index.html
Fixes https://github.com/BrightspaceUI/core/issues/3034. In `grid` mode, the user navigates a list with the arrow keys, and tabbing forward/backwards will bring them to the first focusable element after/before the list.  This was working properly for backwards-tabbing because we were passing in the list `slot` to `getPreviousFocusable`, to account for the header.  But forward tabbing was skipping over the load-more pager, because we were passing `this` into `getNextFocusable`.  This would have worked fine until the pager was added, so now we just pass the list `slot` into both.
=> DE51137 - Fix list to load more pager focusing in grid mode

rollup/rollup.config.js
The table demo was broken on the static build (PR previews) - turns out it's because `table-test.js` was being excluded from the build. I've changed the pattern to only exclude `*.test.js`, instead of `*test.js`.
=> fix: File pattern was excluding table-test.js

components/tag-list/README.md
Without the `clearable` attribute it doesn't allow removal so it doesn't show the clear actions on the daylight site.
=> Add `clearable` to `d2l-tag-list` clear demo

mixins/demo/localize-mixin.html
Now that `<d2l-demo-page>` has a built-in language selector, the localize mixin demo page doesn't need its own!
=> remove double language selector

components/tag-list/README.md
The `listitem` role was removed from tag-list-item in #2875. The code demos were using this role for the "Clear All" button which was recently updated to be shown in the demos so these were not working correctly. I updated the demos and also removed some documentation that was referencing the removed role.
=> Remove listitem role from tag-list documentation

components/more-less/demo/more-less.html, components/more-less/more-less.js
[US146805](https://rally1.rallydev.com/#/?detail=/userstory/673763145497&fdp=true)
This PR removes the `__init_setBaseHeight()` call on the first update of `<d2l-more-less>`. This function was being called twice on initialization. Once from `firstUpdated()` and once from `__adjustToContent()`. `__init_setBaseHeight()` calls `this.__init_measureBaseHeight()` asynchronously with `requestAnimationFrame()` and was causing some odd behaviour where the `__baseHeight` was not being set correctly specifically when using an explicit height attribute.
Removing the call from `firstUpdated()` ensures the function is only called once and the baseHeight is set as expected. I removed it from `firstUpdated()` rather than `adjustToContent()` since it ensures that `adjustToContent()` does not run until the …
=> Fix More-Less bug where it was not setting base height correctly 

package-lock.json, package.json
I've confirmed that rollup@3.8.0 has introduced a defect for the specific combination of settings we use (`preserveModules` + `resolve()` + `lit`), and filed an issue:
https://github.com/rollup/rollup/issues/4765
This defect won't affect BSI because it's locked on rollup@2 currently, and may not be a widespread issue because of the specific combination of settings involved.
In the meantime, locking to 3.7.5 will unblock the PR previews again. I'll open a draft PR to restore rollup's version so we remember to unlock it when the defect is resolved.
=> fix: Lock to rollup 3.7.5 until defect is fixed

components/dialog/dialog-mixin.js, components/selection/selection-observer-mixin.js, mixins/localize-mixin.js, templates/primary-secondary/primary-secondary.js
Re-applying fixes from #3128 for the January release. We added one new null coalescing usage in the primary/secondary page template, so fixed that as well.
=> fix: remove optional chaining and null coalesc

components/demo/demo-passthrough-mixin.js, components/table/README.md, components/table/demo/table-test.js, components/table/table-header.js
This PR:
- makes several changes to the table readme:
- live demos now target the underlying components instead of their wrappers (requires [documentation#1175](https://github.com/BrightspaceUI/documentation/pull/1175) to be merged)
- added `display:block` to table-header demo to improve appearance
- minor renames to avoid collision with existing `d2l-test-table`
- removes unused `name:d2l-test-table` on the responsive demo
- adds `DemoPassthroughMixin` to simplify how properties are passed through in `d2l-test-table`
- this was originally going to be used for documentation too (in a modified form), but is no longer necessary there
Rally: https://rally1.rallydev.com/#/?detail=/userstory/675086171663&fdp=true
=> fix: Broken docs for table

components/list/list-item-mixin.js
I want to move this component: https://github.com/Brightspace/d2l-outcomes/blob/main/src/components/outcomes-management/outcomes-management-list-item.js to use list-item-mixin. But the actions piece of `this._renderListItem` breaks the actions: https://github.com/Brightspace/d2l-outcomes/blob/main/src/components/outcomes-management/outcomes-management-list-item.js#L88-L110 because the actions selector applies the grid styles to all the children.
Relevant Rally story: [US145754](https://rally1.rallydev.com/#/?detail=/userstory/671769625799&fdp=true)
=> Fix list-item-mixin setting grid styles to all actions children

components/collapsible-panel/README.md
My incorrect understanding of daylight demos meant this page was causing the daylight build to fail.
I didn't understand how daylight uses `docs: demo live name:___`. Every demo does _not_ need a `name`.
=> fix: Update collapsible panel README

.github/workflows/update-package-lock.yml
We are changing `D2L_GITHUB_TOKEN` to use more limited permissions.  We need to update all places that don't _need_ to be using it, like here.
I can't merge this until I see the new token appear, after the `repo-settings` run is approved.
=> Update token for update-package-lock workflow

components/inputs/demo/input-search.html, components/inputs/docs/input-search.md, components/inputs/input-search.js, components/inputs/test/input-search.test.js
[US147299](https://rally1.rallydev.com/#/?detail=/userstory/675741349677&fdp=true)
This PR adds the `search-on-input` property to `d2l-input-search`. This changes the component to trigger searches after input changes rather than after pressing Enter. A delay was added to the search events so that the event will only trigger after a user stops typing. The exact delay timing is still being ironed out.
=> Add search-on-input to d2l-input-search

rollup/rollup.config.js
While investigating #3134 , I noticed the PR preview visual-diff page for `object-property-list` was missing some styles:
https://pr-3134-brightspace-ui-core.d2l.dev/components/object-property-list/test/object-property-list.visual-diff.html
Discovered the cause, which is that it's looking for `test/styles.css`, and we weren't including the `test` directory in rollup, so I've added it.
=> fix: Add test directory to rollup

components/list/list-item-generic-layout.js
- `d2l-list` with `grid` enabled
- Within the actions slot, add a `d2l-dropdown-more` component
- Focus element with keyboard and try to toggle dropdown state with ENTER/SPACE keys
- Component state is not toggled
(this can be tested on the first demo on list expand collapse page)
`d2l-dropdown-more` listens to `mouseup` event to toggle state [here](https://github.com/BrightspaceUI/core/blob/main/components/dropdown/dropdown-opener-mixin.js#L77). This becomes an issue since the `d2l-list-item-generic-layout` component listens to keyboard events and calls `node.click()` on ENTER/SPACE keyboard actions [here](https://github.com/BrightspaceUI/core/blob/main/components/list/list-item-generic-layout.js#L454). (only when grid is enabled) 
Dispatch `mouseup` event on node so that …
=> Fix keyboard accessibility issue with grid enabled `d2l-list` and `d2l-dropdown-more` component

templates/primary-secondary/primary-secondary.js
[DE51555](https://rally1.rallydev.com/#/?detail=/defect/675441395861&fdp=true): Primary-Secondary > Mobile view secondary tray does not open when clicked if slide down hidden
This solves two defects with the primary secondary template in the Mobile view when resizing with the mouse.
=> fix: primary secondary resizing defects

components/collapsible-panel/collapsible-panel.js
This property had a leftover `REQUIRED` doc tag. IT's not a required attribute, so this is just confusing.
=> fix: Collapsible Panel - make `expand-collapse-label` optional

components/collapsible-panel/README.md, components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/demo/collapsible-panel.html, components/collapsible-panel/test/collapsible-panel.visual-diff.html
It can be unclear that `padding` is a "type selector" rather than an extension of the css property.
By renaming to `padding-type`, this becomes more clear.
=> fix: Collapsible Panel - rename `padding` to `padding-type`

components/backdrop/backdrop.js, components/backdrop/test/backdrop.test.js
[DE51746](https://rally1.rallydev.com/#/?detail=/defect/681718782515&fdp=true)
Hotfix for 20.23.1 for the backdrop fix from https://github.com/BrightspaceUI/core/pull/3203
=> fix: Hotfix for 20.23.1 - Change backdrop to use aria-hidden instead of role=presentation

components/backdrop/backdrop.js, components/backdrop/test/backdrop.test.js
Update core to push this backdrop fix from https://github.com/BrightspaceUI/core/pull/3203 into the 20.23.2 release.
=> fix: Certfix 20.23.2 - Change backdrop to use aria-hidden instead of role=presentation

.github/actions/comment-on-pr/action.yml
This PR should fix the PR previews! They've started failing because `third-party-actions@actions/github-script` was upgraded yesterday to v6 (from v3), and the Octokit API moved a lot of commands e.g. `github.issues` to `github.rest.issues`.
=> fix: github-script usage after upgrade to v6

components/inputs/input-label-styles.js, components/inputs/input-text.js
[DE51662](https://rally1.rallydev.com/#/?detail=/defect/676000972225&fdp=true): Input-text > Fix tooltip hover area
This PR moves the tooltip in the `d2l-input-text` component from the `input` element up to the host so that hovering anywhere in the component will open the tooltip. This makes the behaviour consistent with the validation tooltips that are used in the `d2l-input-number` component. There was an edge case where if you opened the tooltip and then turned on skeleton, the tooltip would still appear on hover so I added a check to the tooltip to confirm that the input is not in skeleton.
A separate inconsistency was noticed. Hovering inside of the component but outside of the label and bordered input area, such as to the right of the label, will open the tooltip (if warranted), but …
=> Move input-text tooltip location

components/filter/filter.js
Rally: [US148183](https://rally1.rallydev.com/#/?detail=/userstory/684760630163&fdp=true): list-item > backport selection-disabled property
=> Change disabled to selection-disabled

components/list/README.md, components/selection/README.md, components/selection/test/selection.visual-diff.html
This PR is just cleanup - it should have no functional effect on the docs or visual-diffs. I've made three changes:
1. **list readme:** Switch from `style="width: 100%"` to `display: block`
- the 100% width was only required because the demo blocks use `display: flex` by default
- having that inline style in there could have been confusing to consumers
2. **selection readme:** Switches tabs to double-spaces
3. **selection visual-diff:** Fixes some incorrectly closed html tags
Rally: https://rally1.rallydev.com/#/?detail=/userstory/684983995587&fdp=true
=> chore: Cleanup formatting in list readme and selection readme/visual-diff

components/selection/README.md
Updating readme with `disabled` property information after adding `reflect:true` properties for `d2l-selection-input` component in a previous PR.
https://github.com/BrightspaceUI/core/pull/3246
=> Updating Readme after adding in new reflection properties.

components/list/list-controls.js, components/list/list-header.js
This PR removes `d2l-list-header` from core! [All consumers ](https://search.d2l.dev/search?full=%22d2l-list-header%22&defs=&refs=&path=&hist=&type=&xrd=&nn=8&si=full&searchall=true&si=full) have been renamed to `d2l-list-controls` except for:
- `manager-view-fra`, where I raised [an issue](https://github.com/Brightspace/manager-view-fra/issues/2564) with migration details (they're still stuck on core v1)
- historical references in `blog.d2l.dev`
- a ".har" file in `har-filter-k6`, which is a demo "HTTP Archive" from 2022 before the renaming
I've also removed the import from the [List issue on BrightspaceUI/documentation](https://github.com/BrightspaceUI/documentation/issues/138).
This is technically a breaking change for any external consumers of `core`, but we've resolved all usage …
=> feat: Remove d2l-list-header

components/menu/menu-item-selectable-mixin.js, components/menu/test/menu-item-selectable-mixin.test.js
I have just run npm update on a repo and am now getting a failing axe test:
> Required ARIA attribute not present: aria-checked
on default unselected `<d2l-menu-item-radio>`s.
Adding aria-checked in my `render()` doesn't seem to work (it vanishes), and the Daylight page doesn't mention it, so I suppose it is managed by the component. I see a change handler here that sets the property here. Nothing in our code seems to have changed recently, but the MDN docs seem to suggest that the property should be present with a value of "false" for unselected items, whereas our code removes it in that case - so I think it's just that the axe lib just got more picky.
=> fix: menu-item-selectable-mixin aria-checked

components/inputs/input-textarea.js
This PR removes the `z-index` from `d2l-input-textarea` to avoid some stacking context issues. It looks like they were introduced when the component was initially converted to Lit, but it appears they aren't actually needed.
There's really two contributing factors to this issue:
1. `d2l-input-textarea` creating a stacking context that is higher than other things on the page when we don't want it to
2. `d2l-card` creating a stacking context for nested `d2l-tooltip`s, effectively overriding the effectiveness of it's `z-index`. It would be good to eliminate this as well, but if it's possible, it will be more involved and can be dealt with separately.
**Before:**
**After:**
=> Remove z-index from d2l-input-textarea.

components/collapsible-panel/collapsible-panel.js, components/list/list-item-mixin.js, templates/primary-secondary/demo/integration.html
[DE51932](https://rally1.rallydev.com/#/?detail=/defect/684982721887&fdp=true)
This PR adds a `z-index` to `d2l-collapsible-panel`'s sticky header so that it floats on top of `d2l-card`, or `d2l-list-item` with dropdown or tooltips open. This is similar to what is required for the `d2l-list-controls`.
**Before:**
**After:**
=> Assign d2l-collapsible-panel's sticky header a z-index.

components/demo/demo-snippet.js
[DE51507](https://rally1.rallydev.com/#/?detail=/defect/675164420957&fdp=true)
This PR updates the styles for `d2l-demo-snippet` so that the fullscreen container fills the screen and is the bounding ancestor for things like dropdowns. 
The `DropdownContentMixin` uses the [getBoundingAncestor](https://github.com/BrightspaceUI/core/blob/main/helpers/dom.js#L67) helper in its logic to determine the space available for the dropdown content. Previous to this change, the `main` element (which gets `overflow: hidden;` and `height/width: 0;` in fullscreen) would be identified as the bounding ancestor with 0x0px dimensions. The change here will cause the fullscreen container to fill the full height of the viewport and become the bounding ancestor.
**Before:**
**After:**
=> Fix fullscreen d2l-demo-snippet so that dropdowns bounding ancestor is resolved correctly.

components/list/README.md, components/selection/README.md, components/table/README.md, components/table/table-controls.js
On our `list`, `selection`, and `table` demos, the sticky behaviour of the "controls" component wasn't being properly demonstrated. It was the worst of both worlds: the controls don't stick to the top of the page, but it still gets styled as if it's stuck, adding a shadow underline that looks out of place.
This PR fixes those by using `no-sticky` in most demos, and making the demo container scrollable in the demo of the controls itself.
I've also included two other fixes for the table demo specifically:
1. Fixed the logic of the `<d2l-sample-table-with-controls>` itself, which wasn't handling selection correctly
2. Added a `z-index` to the `d2l-table-controls`, to make it float properly over the table
- This is sort of a placeholder, I have a whole other story to improve …
=> fix: Sticky behaviour in selection header demos

components/list/list-item-checkbox-mixin.js, components/list/test/list-item-checkbox-mixin.test.js
Remove support for `disabled` property replacing it with the `selection-disabled` property to have clearer semantics. Consumers of the property have been changed to consume the new one.
Rally:https://rally1.rallydev.com/#/?detail=/userstory/684760630163&fdp=true
Changes occur in `ListItemCheckboxMixin`, whose only consumer is `ListItemMixin` whose descendants are:
| Consumer | PRs |
| - | - |
| [`TargetCourseListItem`](https://search.d2l.dev/xref/Brightspace/ipsis-sis-course-merge/components/target-course-list-item.js?r=1114e188) defining [`target-course-list-item`](https://search.d2l.dev/search?full=%22target-course-list-item%22+disabled&defs=&refs=&path=&hist=&type=&xrd=&nn=8&searchall=true) | 8 |
| [`CourseListItem`](https://search.d2l.dev/xref/Brightspace/ipsis-sis-course-merge/compone …
=> fix: remove support for disabled property

components/hierarchical-view/hierarchical-view-mixin.js
[DE51798](https://rally1.rallydev.com/#/?detail=/defect/683148898117&fdp=true)
This PR updates `HierarchicalViewMixin` to make it more resilient to race conditions that can arise when the view is connected, but disconnected before it's had a chance to fully initialize. The `HierarchicalViewMixin` relies on `requestAnimationFrame` to delay some of the initialization, however in certain contexts (ex. `d2l-overflow-group`) it is possible for the view to be disconnected before that frame runs. Per the Rally defect, this was observed in the Email tool in the reading frame.
=> Fix race condition with HierarchicalViewMixin.

components/list/demo/list.html, components/tooltip/demo/tooltip.html, components/tooltip/tooltip.js
[DE51993](https://rally1.rallydev.com/#/?detail=/defect/685233504963&fdp=true)
This PR fixes the `d2l-tooltip` component so that only one tooltip is displayed at once. Previous to this change, more than one tooltip could be displayed but it was never really supported - as such, tooltip collisions could occur. In addition, logic in `ListItemMixin` assumes only one tooltip is displayed at a time when it adds its `_tooltip-showing` attribute to elevate `z-index` for list-items.
The following screenshots show the results when a tooltip is shown by clicking followed by showing a second tooltip by subsequently hovering.
**Before:**
**After:**
=> Fix d2l-tooltip so that only one tooltip is displayed at a time.

components/tooltip/tooltip.js
This PR updates `d2l-tooltip` code that enforces only one tooltip being displayed at once. This is an alternate, simpler solution than what I previously implemented in this PR https://github.com/BrightspaceUI/core/pull/3310. It tracks the active tooltip so that it can be hidden if/when another tooltip is shown.
=> Update solution for only showing one tooltip at a time.

components/dialog/README.md
[US148599](https://rally1.rallydev.com/#/?detail=/userstory/685344794269&fdp=true): Update Daylight Core UI docs for accessibility
Add a section to the `d2l-dialog` page about how to use `describe-content` to make sure the text content is announced.
**Context**
Updating as a result of https://github.com/BrightspaceUI/core/issues/3156, in particular https://github.com/BrightspaceUI/core/issues/3156#issuecomment-1380700267. This change will hopefully prevent any such confusion in the future.
Also see the recommendation from @geurts 
https://github.com/BrightspaceUI/core/issues/3156#issuecomment-1423478779
=> Add a section "announcing dialog text"

components/dialog/dialog-fullscreen.js, components/dialog/dialog-styles.js
A few CSS transition tweaks for the dialog open/close, coming from design feedback from Jeff.
Rally: https://rally1.rallydev.com/#/?detail=/defect/685414266339&fdp=true
=> fix: Improve CSS transitions for dialogs

components/filter/README.md
This extra `<script>` block was breaking the filter empty state demo and needed to be combined into a single `<script>` block. Can't verify this due to PATs being blocked on BrightspaceUI which prevents us from running the repo locally, but this should fix the issue.
=> fix: filter empty state documentation

components/filter/README.md
This PR aligns the filter empty state demo to the top of the container.
=> fix: filter empty state demo alignment

components/dialog/dialog-fullscreen.js, components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js
This PR moves the dialog full-height behaviour to an internal class, instead of sprouting the `full-height` attribute on the component; recommended by @dbatiste. There should be no functional changes.
Rally: https://rally1.rallydev.com/#/?detail=/defect/685414266339&fdp=true
=> fix: Move dialog full-height to an internal class

components/inputs/input-color.js
These events are only used internally by the MVC code, and will go away when the palette can be rendered as a component.
=> fix: hide events from Daylight Site

components/filter/filter.js
In the filter component when the search does not return empty, the search empty state is rendered off-screen so that a screenreader message is still read. In the default case, the description will switch to something like "3 search results" instead of "No results".
The custom empty state was using the same message both when the search is empty and when it is not. This PR adds a check so that the custom empty state description is used when shown on-screen and the default description is used when the search is non-empty and the empty state is rendered off-screen.
=> Fix custom filter empty state screenreader bug

package.json
Now that `en-GB` is a thing, we're getting an untranslated warning for every line. This disables the warnings as they're not particularly useful anyway.
=> ignore untranslated warnings

components/inputs/docs/input-search.md
"Label" in Accessibility Properties was not properly formatted as `code` to get the purple background
=> Formatting fix

components/table/table-controls.js, components/table/test/table.test.js, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
This PR adds a unique aria-label for `d2l-table-controls`, overriding the default one provided on `d2l-selection-controls`.
Rally: https://rally1.rallydev.com/#/?detail=/userstory/673796873161&fdp=true
=> feat: Add aria-label for table-controls

helpers/localize.js, mixins/demo/localize-mixin-mission.js, mixins/localize-mixin.js
Here's one more for the recursive stack of PRs! Some proposed cleanup and changes to the `localizeHTML` approach.
There's also still some naming to be discussed, e.g. I'm not sure about the general `markup` as opposed to something more explicit like `localizeMarkup` - but that can be a separate discussion 😄.
=> Localize rich text tweaks

components/scroll-wrapper/demo/scroll-wrapper-test.js
Missed this earlier. This test element is being focused on from visual-diff tests that are now using the `focusWithKeyboard()` helper, so there should be no need to `forceFocusVisible` from there.
=> remove forceFocusVisible from scroll-wrapper test

components/button/button-icon.js, components/button/button-styles.js, components/count-badge/count-badge-icon.js, components/count-badge/count-badge.js, components/dialog/dialog-confirm.js, components/dialog/dialog-mixin.js, components/html-block/html-block.js, components/inputs/input-color.js, components/link/link.js, components/menu/menu-item-styles.js, components/scroll-wrapper/scroll-wrapper.js, components/switch/switch-mixin.js, components/tabs/tab-internal.js, components/tabs/tabs.js, components/tag-list/demo/tag-list.html, components/tooltip/tooltip-help.js, directives/animate/animate.js, helpers/README.md, helpers/focus.js, helpers/test/focus.test.js, templates/primary-secondary/primary-secondary.js
This removes `forceFocusVisible` from the last usage in dialogs, and removes it entirely as something core supports. `tryApplyFocus` also goes away as it was using `forceFocusVisible` and was only used in 1 place in dialogs.
For dialogs specifically, we'd still like a focus ring when a dialog opens and focus gets placed on one of the buttons. To accomplish this, I've created a dialog-specific implementation in the dialog mixin, and used a `.force-dialog-focus-visible` CSS class to be very explicit about what we're doing.
Once this merges, I'll remove the `.focus-visible` CSS class from any other repos that were using it.
=> fix: remove forceFocusVisible

components/tabs/demo/tabs.html, components/tabs/tabs.js
This PR fixes the stacking of elements in `d2l-tabs` ext `slot` due to the stacking context that is/was created by the `transform` that is used for animation when showing/hiding the tabs bar (going from 1 to many or many to 1 tabs).
**Before:**
**After:**
**Extra background...** we got bitten by [this transform behaviour again](https://developer.mozilla.org/en-US/docs/Web/CSS/transform):
> If the property has a value different than none, a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) will be created. In that case, the element will act as a [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) for any position: fixed; or position: absolute; elements that it contains.
=> Fix d2l-tabs extension slot stacking.

components/expand-collapse/README.md, components/more-less/README.md
Very simple restructuring of READMEs.
[US147050](https://rally1.rallydev.com/#/?detail=/userstory/675147239973&fdp=true): Collapsible Panel > Refactor the "Collapsible Container" docs
=> fix: move `more-less` to its own README file

components/demo/demo-snippet.js
This PR updates the `d2l-demo-snippet`'s demo flex item to not use the implicit `min-width` as determined by its contents so that it doesn't unexpectedly push other flex items out of their containing blocks.
**Before:**
**After:**
=> Update the demo-snippet demo flex item to remove implicit min-width.

components/list/list-item-drag-drop-mixin.js
This PR fixes a defect where list drag-and-drop was broken in Safari. This was a regression introduced [here](https://github.com/BrightspaceUI/core/commit/e24344da7f99b89619d4b1ec32a71f4b4118679d) as part of #3046 (expand/collapse list). Turns out Safari is a bit different in how it triggers `'dragleave'`, which was causing the drop-target to continually be rendered and derendered.
The solution is to clean up where the `_draggingOver` state is being updated - we've moved it inside of the `DragState` class, and also now trigger a cleanup whenever the drop-target becomes invalid (e.g. when an item is hovering over itself).
Joint effort with @svanherk @oelhanafey @dbatiste. Tested on Chrome (Windows + Mac) and Safari.
Rally: https://rally1.rallydev.com/#/?detail=/defect/694750082045&fdp=true
=> fix: Safari list drag-and-drop

.github/dependabot.yml, package-lock.json, package.json
We'd like to use the latest `intl-messageformat` library in order to leverage version 8's ability to do rich formatting. The release of this PR into BSI will need to be coordinated with [a similar change in `@brightspace-ui/localize-behavior`](https://github.com/BrightspaceUI/localize-behavior/pull/38). No [other BSI things](https://github.com/search?type=code&q=saved%3A%22D2L+Code%22+%22intl-messageformat%22+path%3A%2F%5Epackage.json%2F&saved_searches=%5B%7B%22name%22%3A%22D2L+Code%22%2C%22query%22%3A%22org%3ABrightspace+OR+org%3ABrightspaceUI+OR+org%3ABrightspaceHypermediaComponents+OR+org%3ABrightspaceUILabs%22%7D%5D&expanded_query=org%3ABrightspace+org%3ABrightspaceUI+org%3ABrightspaceHypermediaComponents+org%3ABrightspaceUILabs+%22intl-messageformat%22+path%3A%2F%5Epackage.json%2F) …
=> feat: upgrade intl-messageformat

components/collapsible-panel/collapsible-panel.js, components/list/list-item-mixin.js
Reverts BrightspaceUI/core#3426
Reverting these changes as per Mango's standup discussion as they end up creating a very undesirable/unusable experience in Firefox.
=> Revert "[DE52324] Update CSS to allow _focusing attribute to be elevated to a…"

components/dialog/dialog-mixin.js
Small PR fixing what appears to be a typo in dialog-mixin, since `_updateComplete` doesn't exist.
=> fix: updateComplete typo in dialog-mixin

components/list/list-item-generic-layout.js
Rally: [DE52025](https://rally1.rallydev.com/#/?detail=/defect/685395612691&fdp=true)
Some recent styling changes broke drag and drop in rubrics. It's a specific issue with the `drag-target-handle-only` attribute (of which Mango is currently the only consumer) where the drag target gets pushed out to a width of zero because of the use of `fit-content` between two containers taking up the `outside-control` slot. I don't have any way of knowing why the default width was originally set, but without it I don't see any glaring issues; I'm assuming the grid cell defaults to the content width in this scenario i.e. the size of the drag handle.
I've tested the fix with list-drag-and-drop, list-expand-collapse, and rubrics. Let me know if there are any specific integration points we would need to …
=> DE52025 - Unset list item outside control width

mixins/arrow-keys-mixin.js, mixins/focus-mixin.js, mixins/labelled-mixin.js, mixins/provider-mixin.js, mixins/rtl-mixin.js, mixins/theme-mixin.js, mixins/visible-on-ancestor-mixin.js
Looks like we need to do this in two parts in order to preserve history. I'll merge part 1 but not release, then merge part 2 shortly after.
Part 1: move the mixin files into their own directories and adjust all paths within core
Part 2: restore the original mixin files but just have them export from the new location
=> Put mixins in their place (part 2)

mixins/arrow-keys-mixin.js, mixins/localize-static-mixin.js, mixins/theme-mixin.js, mixins/visible-on-ancestor-mixin.js
I've adjusted the places that were using these to use the new locations. The rest have far too many references to realistically update for the time being.
=> fix: remove unused exports

mixins/localize/localize-mixin.js, mixins/localize/test/localize-mixin.test.js
Setting `formattedMessage` before top-level validation allowed `html` template errors to be logged but the result was still returned.
Anything inside a `localizeMarkup` template fails validation while formatting, meaning they are caught before `formattedMessage` was set.
=> Fix localizeHTML validation

components/inputs/input-text.js, components/inputs/test/input-text.test.js
Currently, if a `d2l-input-text` element's properties are changed, the `value` is updated outside of the lit update cycle, beating other properties, like `type`. If the previous (yet un-updated) `type` and the new `value` are not compatible (e.g. `number`, `"Text"`, respectively), the `input` will not only fail to update its `value` but will remove its current `value`.
Waiting for `updateComplete` to update the `value` ensures compatibility.
You can see this on the [S3 version](https://pr-3503-brightspace-ui-core.d2l.dev/mixins/localize/demo/localize-mixin.html) of #3503 in the Localize Mixin Sandbox demo by loading the Nested template, and then immediately loading the Ordinal template.
=> Fix d2l-input-text value update

components/button/floating-buttons.js, components/dropdown/dropdown-content-styles.js, components/list/list-item-drag-image.js, components/list/list-item-mixin.js, components/skeleton/skeleton-mixin.js
[DE52725](https://rally1.rallydev.com/#/?detail=/defect/694583527535&fdp=true)
This PR fixes a defect where dropdowns with `no-auto-close` would stay open when a dialog opened and since their z-indices were higher than `backdrop` they would not be faded with the rest of the background.
`d2l-backdrop` has `z-index: 999` which is shared by many components. I'm proposing to change the upper layer of our web components to `z-index: 998` and then have the backdrop layer 1 higher. If we need to put something higher than the upper level in the future, then we can push those components down a layer and still use `z-index: 998` as the upper layer.
Proposed layers:
```
...
upperLayer - 2: 996
upperLayer - 1: 997
upperLayer: 998
backdropLayer: 999
dialogLayer: 1000
tooltipLayer: 1001
``` …
=> Fix z-indices of upper layer components

components/inputs/input-time.js, components/overflow-group/overflow-group-mixin.js, mixins/interactive/interactive-mixin.js
This PR adds the `RtlMixin` to core components that rely on it due to their use of `offscreenStyles`. Even once we update `offscreenStyles` to include using logical properties, it would be good for the `offscreenStyles` to work properly for all core components in browsers that do not support them.
=> Add RtlMixin to components that are using offscreenStyles since they require it.

components/tooltip/demo/tooltip.html, components/tooltip/tooltip.js
This PR updates the `d2l-tooltip` to not dispatch events when first initialing its `showing` property. This avoids `d2l-tooltip-hide` from being dispatched when the element is initialized.
Initially I tried to just set `this._showing = false` in the `constructor`, however this results in `aria-hidden` not being initialized correctly on the host since `_showingChanged` wouldn't get called initially.
Confirmed that `d2l-tooltip-show` is still dispatched when `force-show` is used, which effectively shows the tooltip upon first rendering. It is important that this event is still dispatched initially, since list-items rely on it to track whether or not tooltips are open, even though `force-show` is discouraged in that context.
=> Update d2l-tooltip to not dispatch the hide event when first rendering.

components/paging/pageable-mixin.js, components/selection/demo/selection.html, controllers/subscriber/subscriberControllers.js, controllers/subscriber/test/subscriberControllers.test.js
While backporting the table-load-more to some consumers, I found a strange race condition that was preventing the load-more pager from subscribing to the table. This PR fixes that race condition.
In short:
- in the backport, the pager is being rendered **before** the table-wrapper
- this is because it's being passed as a slot to a component that internally renders the table-wrapper
- so the outer component renders the pager first, then the inner component renders table-wrapper and slots the pager in place
- that means when the subscription event fires, there's nothing to catch it!
I chatted with @dbatiste and we landed on this fix: keep firing the subscription event until it's caught, for some fixed amount of time. In my testing 20ms was usually enough, I've set the retry window to 100ms …
=> fix: Event subscription before registry is ready

components/object-property-list/object-property-list.js
Small fix - I noticed there was no jsdoc for the OPL status slot.
=> doc: Add status slot annotation for OPL

components/icons/README.md
We darkened Ferrite and a few of the other dark grey colours a while back, and opted to keep icons at #494C4E which became the new Tungsten. We missed updating this in the documentation.
=> Correcting "Ferrite" to "Tungsten"

components/demo/demo-snippet.js
I noticed that the demo snippet's border doesn't show up when the whole page is in RTL mode:
Before:
After:
=> fix: demo RTL border

components/selection/selection-mixin.js, components/selection/selection-select-all-pages.js
[DE52842](https://rally1.rallydev.com/#/?detail=/defect/696182478911&fdp=true)
This PR applies focus to the `d2l-selection-select-all` checkbox when the `d2l-selection-select-all-pages` button is clicked so that focus isn't lost when the button is hidden/removed from view.
=> Focus the select-all checkbox when select-all-pages is clicked so focus isn't lost

components/list/test/list.visual-diff.js
I'd like to propose this "quick fix". We've seen this test flake occasionally for well over a year. I'm optimistic this would be fixed by the next version of `visual-diff` where our `fixture` waits for everything to update, so I don't mind fixing it like this for now.
I've rerun visual-diff 5 times, but the true test will be over the next few weeks. If this does show up again, then I think this might be an issue in the selection component itself.
=> Try to fix flaky list test

components/list/list-item-mixin.js
[DE53209](https://rally1.rallydev.com/#/?detail=/defect/699523809885&fdp=true)
This extend-separators style was being overridden by a separate RTL style due to CSS specificity. Added a check for RTL to increase the specificity. This was preventing non-selectable list-items in lists with `extend-separators` from being tabbed forward in RTL.
Before:
After:
=> Increase CSS specificity of list extend-separator styles

components/switch/switch-mixin.js, components/switch/test/switch.test.js
Context from Jeff:
> We recently had a usability test participant complain that she needed to use the `space` key to activate a switch, and expected the `enter` key to work instead. Would it be problematic to allow both keys to work? [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role) specifies only the space key, but [the W3C](https://www.w3.org/WAI/ARIA/apg/patterns/switch/) lists the enter key as an optional additional way to activate a switch.
If it doesn’t present any additional issues, it would be nice to add support for the enter key.
=> fix: handle ENTER key to toggle switch

components/list/list-item-checkbox-mixin.js, components/list/test/list-item-checkbox-mixin.test.js
[DE53334](https://rally1.rallydev.com/#/?detail=/defect/700493301447&fdp=true)
This PR updates the list-item checkboxes so that `Enter` key does not toggle the checkbox. This is to make them behave the same as native checkboxes.
=> Update ListItemCheckboxMixin so that Enter key does not toggle the checkbox.

components/filter/filter.js
[DE52350](https://rally1.rallydev.com/#/?detail=/defect/690468457635&fdp=true)
Previously, the introductory text in filter was not very accessible since it can appear before any other focusable elements which makes it easy to miss for screen reader users. This PR changes the filter component to announce the introductory text on dimension open. 
Carin and Jeff tested this out and are happy with where it ended up.
=> Announce introductory text when opening single dimension

components/list/list-item-drag-drop-mixin.js, components/list/list-item-generic-layout.js, components/list/list-item-mixin.js, components/list/test/list.test.js
[DE53222](https://rally1.rallydev.com/#/?detail=/defect/699633940503&fdp=true)
When navigating a list with arrow keys, the list item will try to focus on the next/previous list item sibling. If that list item is not focusable, it will skip the list item and focus the next focusable element.
The list does not check that the next focusable belongs to the same list. If that non-focusable element is at the start or end of the list, you are able to arrow outside of the list and not able to get back into it.
This PR adds a check to confirm that the next focusable element belongs to the same list as the currently focused element.
=> Add check that next focusable list item belongs to the same list

templates/primary-secondary/primary-secondary.js
[DE53314](https://rally1.rallydev.com/#/?detail=/defect/700334191725&fdp=true): Magnifying the page causes the adjustable split view separator element to be unable to be triggered by enter/spacebar
We can get keyboard input on mobile when using a desktop with small screensize (or zoomed in which gives mobile view). In this case, we make ENTER or SPACE on the divider handle work the same as a click (i.e. collapse entirely, or restore to original position).
=> DE53314 divider handle mobile on enter and space

components/collapsible-panel/README.md
Update documentation to show the properties for `d2l-collapsible-panel-summary-item` now that it includes the skeleton property.
=> fix: update documentation for collapsible panel summary item

tools/web-test-runner-helpers.js
This fixes the following error from occurring on our local machines when running the unit tests:
> Error while executing command reset-mouse: 'left' is not pressed.
The reason it doesn't happen in CI is because it's Puppeteer-specific and CI runs happen with Playwright.
`resetMouse` rather aggressively [just calls `mouse.up` on all 3 buttons](https://github.com/modernweb-dev/web/blob/master/packages/test-runner-commands/src/sendMousePlugin.ts#L170) regardless of whether they were pressed or not. That wasn't a problem until [Puppeteer recently decided to throw](https://github.com/puppeteer/puppeteer/pull/10021/files#r1184418245) if `up` is called on a non-down button.
This has been [raised as a defect](https://github.com/modernweb-dev/web/issues/2262) in `@web/test-runner-commands` and is …
=> fix: avoid resetMouse bug by doing it ourselves

components/overflow-group/overflow-group-mixin.js
[DE53422](https://rally1.rallydev.com/#/?detail=/defect/701287303215&fdp=true)
This PR fixes an issue where items briefly wrap within the `d2l-overflow-group` during resizing, resulting in some FOUC. This happens because the browser is wrapping the items before the overflow-group chomping results are applied. 
The solution is to use use `flex-wrap: nowrap` except when we know items will wrap instead of being chomped. In practice, items are almost never expected to wrap because `min-to-show="0|1"` in the wild, and the `auto-show` attribute/`d2l-button-group-show` class is only applied to force show the item in the LMS for the primary button. Aside: we don't really support the wrapping edge case very well, but that's a separate issue.
=> Update `d2l-overflow-group` to not wrap items while resizing unless necessary.

components/dropdown/dropdown-content-styles.js
In mobile devices part of the dropdowns were being blocked by the navbar at the bottom. Tested solution on safari on iphone and android+chrome on sauce labs.
Rally: [DE53342](https://rally1.rallydev.com/#/?detail=/defect/700609792545&fdp=true)
=> fix: prevent dropdown from getting blocked by mobile navbar

components/overflow-group/overflow-group-mixin.js
[DE50816](https://rally1.rallydev.com/#/?detail=/defect/668749858657&fdp=true)
This PR fixes the `d2l-overflow-group` chomping when in RTL. The root cause of this issue was that the calculation of the width of the items was incorrect - it was not correctly factoring in the size of the margin in RTL.
Due to the timing of when measurements are taken, it is necessary to test this by setting `dir="rtl"` before loading the page. If one tries to test simply by toggling to the Arabic language in the demo page, it will be using LTR measurements and not a valid test.
**Before:**
**After:**
Note: before my [previous change to how the items wrap](https://github.com/BrightspaceUI/core/pull/3650), this would have incorrectly wrapped below...
**Before:**
**After:**
=> Fix d2l-overflow-group chomping in RTL.

components/list/list-item-generic-layout.js, components/list/test/list.test.js
[DE53222](https://rally1.rallydev.com/#/?detail=/defect/699633940503&fdp=true)
This is a follow-up to #3605. I added a check that it will only focus the next item if the next focusable belongs to the same list, but this doesn't account for other non list-item components that can be placed in the d2l-list like list-controls.
This PR fixes the check so it confirms that the next focusable is a list item and that list item belongs to the same list as the currently focused list item.
=> Check that next focusable is a list item

components/inputs/input-search.js, components/inputs/test/input-search.test.js
As described in DE53398, there's nothing preventing a user from holding down the ENTER key in a search input and having hundreds/thousands of change events fire. In certain scenarios, those change events could cause downstream work to be done over and over, which we don't want.
This rate limits the handling of the ENTER key such that it only fires the event once per second OR if the value has changed since the last time it was fired.
=> feat: suppress duplicate ENTER presses

components/list/README.md, components/list/list.js, components/list/test/list.test.js
[US152804](https://rally1.rallydev.com/#/?detail=/userstory/701306059915&fdp=true)
This PR adds the `label` property to `d2l-list` which adds an accessible label that can be used to provide additional context when it is not obvious.
Adding an `aria-label` to nested lists was causing the label to replace the child content and skip over all of the nested content. Since there doesn't seem to be a use case for labels on nested lists, we decided to only permit the property on top-level lists. Adding the property to a nested list should have no effect.
=> Add label to d2l-list

components/list/list.js
This removes the initialization of undefined for the list label. The web-component-analyzer interprets the default value as a string `"undefined"` which is shown on the doc site. Removing the initialization entirely does not set a default in it.
We are initializing to `undefined` instead of `''` to simplify some of the code that uses it.
=> Remove initialization of list label

components/dialog/dialog-mixin.js, components/dropdown/dropdown-content-mixin.js, components/dropdown/dropdown-opener-mixin.js, templates/primary-secondary/demo/integration.html
[DE51920](https://rally1.rallydev.com/#/?detail=/defect/684873597487&fdp=true)
This PR updates `DialogMixin` and `DropdownContentMixin` to stop bubbling of the `touchstart` event so that external elements such as `d2l-template-primary-secondary` (aside panel) do not react to it when they shouldn't. Without this change, users cause the mobile secondary/aside panel to resize when they touch-start within an open dialog or dropdown nested within the panel. 
I confirmed with Jeff that we still want the `d2l-template-primary-secondary` secondary panel behaviour that resizes the panel, just not when dialogs or dropdowns are open (removing that behaviour and just targeting the divider would have been an alternative solution).
=> Update dialogs and dropdowns to stop bubbling of touchstart.

components/filter/demo/filter-search-demo.js, components/filter/filter.js, components/filter/test/filter.test.js
This adds the ability to display all keys in the filter callback without providing the keys yourself. This will help in avoiding unnecessary API calls since we are changing search to dispatch search events when the search value is empty as well.
This was done by changing the `searchCompleteCallback` to use a deconstructed object as the parameter which allows us to use named function parameters. We would only want to pass one of `keysToDisplay` or `displayAllKeys` in the search callback and this approach allows us to maintain a single callback function.
This change would be breaking and the 2 other places that use manual search would need to be merged in close succession:
1. [my-courses](https://search.d2l.dev/xref/Brightspace/d2l-my-courses-ui/src/search-filter/d2l-my-courses-filter.js?r=a …
=> Add displayAllKeys to filter search callback

.github/workflows/ci.yml
Pull requests triggered by Dependabot will always fail to publish the preview site due to lack of credentials.
This change will skip the publish step in this scenario, which seems like a good compromise since we rarely care about the preview site for Dependabot PRs. If the tests are passing, that should be enough.
This follows [GitHub's recommendation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions) for checking this, and by using `triggering_actor` instead of `actor` if one of us re-runs it the static site will publish.
=> skip preview site if triggered by Dependabot

components/inputs/input-text.js
[DE53636](https://rally1.rallydev.com/#/?detail=/defect/703500672771&fdp=true)
Currently, validation messages are not announced to screen readers for the `d2l-input-text` elements. This PR adds the `announced` attribute to its usage of `d2l-tooltip` so that it will announce the message using our `announce()` helper. It does not wire it up using `for` (which would in turn use `aria-describedby`) because we do not want validation messages buried behind VoiceOver's "More Content Available" menu.
=> Update d2l-input-text so validation messages are announced

.github/workflows/ci.yml, README.md, package-lock.json, package.json
Reasons:
- The project is abandoned and Lit-labs is working on a new one
- It's buggy
- I can't remember it ever catching anything
- It's forcing us to include TypeScript as a dependency
- I thought it was needed to generate `custom-elements.json` but `wca` does that separately so... goodbye!
=> remove lit-analyzer

components/icons/icon.js
Simplifies `d2l-icon` by using safe built-in Lit Element directives instead of the custom build `runAsync`.
This fixes a race condition in which, if an icon is set to two different new values quickly, sometimes the older of the two new values will permanently (or until the icon changes again) be rendered instead of the newer one.
=> Fix a race condition in d2l-icon that can cause the wrong icon to be shown

helpers/test/contrast.test.js, helpers/test/dismissible.test.js
I _expect_ we'll still need to export `assert` from `@brightspace-ui/testing` as it's highly likely other projects are using it, but might as well use `expect` in these 2 places in core.
=> use expect instead of assert

components/collapsible-panel/README.md, components/collapsible-panel/collapsible-panel-group.js
The `SkeletonMixin` wasn't being used in this component.
Also, update the docs to show the live properties for `d2l-collapsible-panel-group`.
[US153600](https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fuserstory%2F703942502753)
=> fix: `d2l-collapsible-panel-group` > remove unnecessary `SkeletonMixin`

components/expand-collapse/expand-collapse-content.js
If the component is expanding but is empty, the height of the contents will be `0`, and therefore there is nothing to animate, and the `transitionend` event will not be dispatched.
This led to an issue where the component was stuck in an "expanding" state with `height: 0`.
If we detect this scenario, we simply move to the end "expanded" state with `height: auto`. Any subsequent addition of elements to the panel would then be displayed immediately.
[DE53776](https://rally1.rallydev.com/#/15545167705d/custom/21568985922?Iteration=%2Fiteration%2F668139821167&Release=u&cpoid=15545167705&detail=%2Fdefect%2F704665648499&rankScope=%2Fiteration%2F668139821167&typeDef=7362609627)
=> fix: `d2l-expand-collapse-content` > set expanded state in another spot

package-lock.json, package.json
Core should have an explicit dependency here, since it calls `web-test-runner` itself. Without it, when you link `@brightspace-ui/testing`, calling `web-test-runner` fails.
=> add back web-test-runner

mixins/localize/test/localize-mixin.test.js
Calling the new `fixture` outside of `it`, `before` or `beforeEach` causes it to blow up when trying to reset and call into the wtr server commands. I spent a bunch of time trying to figure out why and how to detect it but came up short for now -- will spend more time later. In the meantime, just moving these tests.
=> move fixture call into beforeEach

components/list/test/list-item-expand-collapse-mixin.test.js, components/list/test/list.test.js
In some scenarios, if tests are slow enough the missing labels actually end up throwing while tests are still executing and because the exception doesn't get thrown by `LabelledMixin` for 3 seconds it can actually fail a totally unrelated test, which is very confusing! Don't ask me how I know.
=> adding keys/labels to reduce logs in test results

components/list/test/list-item-drag-handle.test.js
I'm noticing some super rare flake in these tests in Firefox. I'm hoping that switching them to use the actual keyboard to trigger things instead of faking it out like it was doing will improve things.
=> switch to keyboard helpers

components/list/test/list.test.js
More relatively rare flake in Firefox with these list tests. 🤞 that switching them to use the real keyboard makes them more reliable.
=> fix flakey tests with key utilities

components/dropdown/test/dropdown-content.test.js, components/filter/test/filter.test.js, components/list/test/list-item-drag-handle.test.js, components/list/test/list.test.js, components/menu/test/menu.test.js, components/switch/test/switch.test.js, components/tooltip/test/tooltip.test.js, directives/animate/test/animate.test.js, package-lock.json, package.json
Now that all the keyboard & mouse commands are surfaced from `@brightspace-ui/testing`, this switches core over to use them instead of `@web/test-runner-commands`. We also renamed `focusWithKeyboard` to `focusElem` and removed `focusWithMouse`.
I ended up uncovering a some flake unrelated to these changes in Firefox & Webkit, so there are a couple fixes here. More to come later though as these seem to mostly just happen locally and I'm hoping the switch to the new `fixture` will resolve some of them.
=> switch to @brightspace-ui/testing mouse and keyboard commands

components/calendar/calendar.js
The combination of Chromium and NVDA was causing `d2l-calendar` to not read dates when navigating with the calendar with arrow keys.
* remove `role="presentation"` from the `table` element
* this was forcing us to set our own functionality, and in some situations was preventing the screen reader from reading anything out.
- https://github.com/BrightspaceUI/core/pull/602
<details>
<summary>Current screen reader behavior</summary>
* Windows
* NVDA
* Chromium 
* tabbing in:  does not read anything 
* moving:  does not read anything 
* Firefox
* tabbing in: Saturday 9. Selected. May 2020  row 2  column 7
* moving: Friday 8. Not Selected. May 2020  not selected  column 6
* JAWS
* Chromium
* tabbing in: Saturday 9. Selected. May 2020 selected contains controls
* moving: Friday 8. Not Selected. …
=> fix: `d2l-calendar` > Use more semantic elements and roles

components/list/test/list-item-drag-handle.test.js, package-lock.json, package.json
Removing these retries now that we've uncovered the source of the problem -- that Firefox + Playwright in a multithreaded environment causes focus to be randomly lost. The testing library [has been updated](https://github.com/BrightspaceUI/testing/pull/35) such that Firefox always runs single-threaded.
=> remove retries

components/dropdown/test/dropdown-content.test.js, components/dropdown/test/dropdown-menu.test.js, components/filter/test/filter-overflow-group.test.js, components/filter/test/filter-tags.axe.js, components/filter/test/filter-tags.test.js, components/filter/test/filter.test.js, components/form/test/form-element.test.js, components/inputs/test/input-date-time.test.js, components/list/test/list-item-drag-mixin.test.js, components/list/test/list-item-expand-collapse-mixin.test.js, components/list/test/list-item-generic-layout.test.js, components/list/test/list.test.js, components/more-less/test/more-less.test.js, components/paging/test/pager-load-more.test.js, components/selection/test/selection.axe.js, components/selection/test/selection.test.js, components/tooltip/test/tooltip.test.js, controllers/subscriber/test/subscriberControllers.test.js, helpers/test/dom.test.js, mixins/arrow-keys/test/arrow-keys-mixin.test.js, mixins/interactive/test/interactive-mixin.test.js
Now that everything is using the new `fixture` that automatically `await`s nested Lit components' `updateComplete`s, all of our tests that were doing that manually can... not do that.
=> Remove unnecessary awaits for updateComplete

components/list/test/list-item-drag-handle.test.js, components/list/test/list.test.js, components/menu/test/menu.test.js, components/switch/test/switch.test.js, package-lock.json, package.json
We updated the testing library to have `elem` be the first argument in order to be consistent with the other APIs.
=> flip sendKeysElem arguments around

components/list/list-item-generic-layout.js, components/list/list-item-mixin.js
[DE52324](https://rally1.rallydev.com/#/?detail=/defect/689632043385&fdp=true): Html emoji editor can get cut off by the rubric
[US151482](https://rally1.rallydev.com/#/?detail=/userstory/698053793761&fdp=true): Spike > Update d2l-list item rendering to avoid z-index
Removes all usage of `z-index` (and any internal stacking contexts) in list items to allow all descendants, and the list item itself, to stack organically within the document. This means no more special handling is needed to support open dropdowns, tooltips, or other overflowing descendants.
CSS `order` achieves essentially the same result as `z-index`, but it is scoped to the grid items and simply re-orders them instead of continually increasing their priority compared to everything else, so there is no arms race.
=> Remove `z-index` and stacking contexts from list-items

components/tag-list/test/tag-list.test.js
Uses proper browser mouse/keyboard interactions from the testing library instead of javascript methods/events to simulate them.
=> Move tag list tests to proper browsers interactions

components/button/test/button-move.test.js, mixins/arrow-keys/test/arrow-keys-mixin.test.js, mixins/interactive/test/interactive-mixin.test.js, tools/dom-test-helpers.js
Switch all uses of `keydown` to `switchKeysElem`.  We can't remove `keydown` yet - it's still used in `copy-role` (removed with https://github.com/Brightspace/copy-role/pull/98) and [`d2l-polymer-behaviors-ui`](https://github.com/Brightspace/d2l-pdf-viewer/blob/6cf0a246f150c8167c7bf9beef305c1cb8e9222d/d2l-pdf-viewer-toolbar.js#L4).
=> Switch keydown uses to sendKeysElem

components/switch/switch-mixin.js
Removed `z-index` use in `d2l-switch` to prevent overlap with other floating parts of the page.
Rally: [DE53483](https://rally1.rallydev.com/#/?detail=/defect/702021897315&fdp=true)
=> fix: remove z-index from switch

components/skeleton/skeleton-group-mixin.js, components/skeleton/skeleton-mixin.js
I wanted to play around with a couple ideas to simplify things:
- It should remove the need for the `_readyToDisplay` tracker
- `_skeletonActive` doesn't need to be a state property and cause re-renders
- I've renamed `updateDisplay` / `waitForDisplay` to `updateSkeletonActive` / `skeletonWait` just to align with the new terminology
=> Attempt to simplify

components/list/test/list.test.js
Now that #3808 and #3798 have been merged, opening this to move list tests to proper browser interactions, which is what caught the Safari bug to begin with.
=> Move list tests to proper browser interactions

components/more-less/more-less.js
This is a bit of an odd one (for some reason GitHub doesn't want to embed the video):
https://github.com/BrightspaceUI/core/assets/19732724/60f7b0b2-6f04-404a-9f98-4bd804d14163
I was able to reproduce the above behaviour on Firefox (no other browser) on my Mac's retina display with standard zoom using the following HTML:
`<p style="margin: 0cm 0cm 8pt; line-height: 107%; font-size: 11pt;">Test</p>`
I could not reproduce the same issue when moving the demo page over to my second 1080p monitor.
Through copious amounts of logging, the issue here seems to be how Firefox measures the `scrollHeight` of the content when a `max-height` is applied to the component. When the content has enough space to fully display (`max-height > scrollHeight`), Firefox measures the content's `scrollHeight` as …
=> Increase the more-less component's max height to allow room for rounding errors

components/list/list-item-mixin.js, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
This line was confusing because you press enter for links and buttons, space for checkboxes, and either for interactive content.  Confirmed with Jeff that we just want to remove this line altogether.
=> US155185 - Remove Enter instructions from list navigation tooltip

components/inputs/input-styles.js, components/inputs/input-text.js, components/inputs/input-textarea.js
Apply the input hover effects when hovering over anywhere on the component, not just the input or label.
Rally: [US148080](https://rally1.rallydev.com/#/?detail=/userstory/684245679355&fdp=true)
=> feat: apply hover effects anywhere on the component

components/list/list-item-generic-layout.js
Another casualty of the `z-index` removal, the keyboard-mode drag and drop buttons should also be usable with pointer devices, but their container had `pointer-events: none;`. It seems safe (and just better overall) to swap the DOM order of `outside-control` and `outside-control-action` here, which allows events to hit the action first, when it exists, and then the control when the action doesn't exist, which is the case in keyboard mode.
=> Fix list keyboard buttons

components/list/demo/list-item-actions.html, components/selection/selection-mixin.js, helpers/focus.js
[DE54118](https://rally1.rallydev.com/#/?detail=/defect/709376015737&fdp=true)
This PR fixes an issue where `SelectionMixin` manages the focus order of `d2l-selection-input` (radios) incorrectly. The current logic relies on the `Map` of selectables to determine the next/previous item to focus, and it incorrectly assumes that the order within the map (subscription order) is the DOM order.
This fix changes the logic to find the next/previous `d2l-selection-input` (radio) based tree-walking when the key is pressed. An alternate solution that sorts the subscribed selectables based on DOM order is: https://github.com/BrightspaceUI/core/pull/3813
=> Update SelectionMixin to focus radios based on DOM order instead of subscription order.

components/inputs/demo/input-text.html, components/inputs/docs/input-text.md, components/inputs/input-date.js, components/inputs/input-text.js, components/inputs/test/input-date-range.visual-diff.html, components/inputs/test/input-date-range.visual-diff.js, components/inputs/test/input-date-time-range.visual-diff.html, components/inputs/test/input-date-time-range.visual-diff.js, components/inputs/test/input-date.visual-diff.html, components/inputs/test/input-helper.js, components/inputs/test/input-text.axe.js, components/inputs/test/input-time-range.visual-diff.html, components/inputs/test/input-time-range.visual-diff.js
[DE53316](https://rally1.rallydev.com/#/?detail=/defect/700336570793&fdp=true)
This PR adds the `control-instructions` advanced property to the `d2l-input-text` component which wires the tooltip directly up to the input via `aria-describedby`. It also updates `d2l-input-date` to provide the `control-instructions` property instead of rendering a disconnected flakey tooltip for improved accessibility.
This does not remove the `description` property from `d2l-input-text` - that is a separate set of work as mentioned in the Rally ticket.
=> Add instructions to d2l-input-text.

components/filter/README.md, components/filter/filter-dimension-set.js
Include a section in the filter documentation to emphasize the expected use of paging and manual search.
Rally: [US151801](https://rally1.rallydev.com/#/?detail=/userstory/698648089311&fdp=true)
=> fix: update filter docs with paging

components/inputs/input-color.js, components/inputs/test/input-color.test.js
Jake noticed that when `<d2l-input-color>` is inside a `<d2l-form>`, its value isn't properly reflected in the value that gets submitted with the form. For inputs that don't have an explicit native `<input>`, we need to manually keep that in sync.
=> fix: reflect input-color's value to formValue

components/paging/README.md
The demo at the top of the page on the Paging page on Daylight doesn't actually show anything, so this adds a more exciting demo. This change mostly uses the test example https://github.com/BrightspaceUI/core/blob/main/components/paging/test/pageable-component.js for the demo.
=> fix: Daylight: Paging top level demo

components/filter/filter.js
Wait for dropdown menu to finish its positioning after loading the items before focusing on the first newly loaded item.
Rally: [US153373](https://rally1.rallydev.com/#/?detail=/userstory/703321522879&fdp=true)
=> fix: wait for positioning before scrolling in filter load more

components/dropdown/dropdown-content-mixin.js
When `<d2l-dropdown>` has "auto-close" enabled, clicking outside the dropdown should close it. To do this, the code attaches a click handler to the `body` that when triggered, closes the dropdown.
This works in most scenarios, except when the body is very short and therefore doesn't span the full height of the viewport. In this case, clicking does nothing.
The [generally accepted solution to this](https://stackoverflow.com/questions/5215117/is-binding-a-click-event-to-document-better-than-binding-it-to-body) is to addithe click handler to the `document` instead of the `body`, which is what this PR does.
=> fix: use document instead of body to auto-close dropdown

components/collapsible-panel/collapsible-panel-group.js
Make `d2l-collapsible-panel-group` a "skeleton group". Any time a collapsible panel is in a `skeleton` state, all panels will also be in a skeleton state.
[US156732](https://rally1.rallydev.com/#/15545167705d/dashboard?detail=%2Fuserstory%2F720188082449&parentRef=%2Fportfolioitem%2Ffeature%2F705085592923)
=> feat: Add skeleton grouping to `d2l-collapsible-panel-group`

.github/workflows/ci.yml, .github/workflows/release.yml, README.md
This moves core's static builds to the `d2l.dev` S3 bucket, as part of standardizing the PR Preview process. This will let us delete the custom `brightspace-ui-core.d2l.dev` bucket.
This is step 2 of a multi-step process for UI core:
1. `repo-settings`: Get d2l.dev S3 access (https://github.com/Brightspace/repo-settings/pull/1250)
2. `BrightspaceUI/core`: Switch core's CI and Release to publish to d2l.dev S3
3. `d2l.dev`: Swap the `d2l.dev` routes to point to the new S3 locations
4. `repo-settings`: Remove the assumable role `brightspace-ui-core.d2l.dev-githubactions-access`
5. AWS console: Delete the `brightspace-ui-core.d2l.dev` bucket and IAM roles
- I'll need help with this last step, I don't have access to the relevant account anymore …
=> ci: Move static builds to d2l.dev bucket

components/calendar/calendar.js
This leaves the effect for `selected dates (for https://github.com/BrightspaceUI/core/pull/684) but removes it for all other disabled dates.
=> Try to fix the focus effects for disabled dates (other than selected)

components/card/README.md
[Rally story](https://rally1.rallydev.com/#/15545167705ud/dashboard?detail=%2Fuserstory%2F704544740341)
- Switches dot-separated metadata to use the newer object property list
- Removes fixed heights in demos
I'll be opening a PR in documentation to includes the object property list and object property list item on the card page.
=> fix: Card: fix demo metadata and fixed heights

.github/workflows/release.yml
This ensures the version in the demos matches the latest release version. Right now it can be 1 behind.
=> Pass the new git HEAD to the publish site checkout

components/html-block/test/html-block.vdiff.js
Just waiting `150ms` for MathJax to render math in `html-block`s is still flaking out sporadically. Unfortunately, this uses the nuclear option of waiting until the elements are the exact size we're expecting them to be when the math has rendered.
=> Fix flaky math vdiffs

components/link/link.js
- Match the host `white-space` style
- Don't underline the space between the link text and icon
The only downside is that it doesn't update with changes to the host `white-space`, but that should basically not be an issue in practice.
Alternative to the alternatives #4050 and #4045
=> Link - new window fixes

components/filter/test/filter.vdiff.js
Try to fix some flaky filter tests by waiting for the _exact_ menu height we expect.  Is this going to break if we adjust buttons, menu, list, etc. heights?  Yes, probably.
I could try to make them a bit more flexible (`waitUntil(() => menu.clientHeight > aBitLowerThanExpectedHeight);`) but that might still be flaky.
=> Try to fix flaky filter vdiff test

components/list/list-item-mixin.js
There's an issue in Rubrics where the drag handle doesn't appear when hovering the rows (it only appears when hovering over the controls container).
I think this is what's required to fix.
After making this change, I played around with hover/focus on vanilla lists. I didn't see any issues, but someone more well-versed in `d2l-list` can put this through its paces more rigorously.
[DE55064](https://rally1.rallydev.com/#/15545167705d/custom/21568985922?detail=%2Fdefect%2F723654980255)
=> fix: `d2l-list-item` > add `mouseenter`/`mouseleave` events to content

components/overflow-group/overflow-group-mixin.js
Adding `getLoadingComplete` to `overflow-group` to wait until after the first chomp. This means the additional chomp menu that gets added is then included in the children `fixture` will wait for. If this isn't enough, Ill need to add something similar to `d2l-icon`, but at least now `d2l-icon` is being included in the `fixture` wait calculations at all.
=> Try to fix flaky overflow-group test

components/tooltip/test/tooltip.test.js, components/tooltip/tooltip.js
I ran into this case while migrating visual diffs.
This fixes an edge case where a tooltip is initially rendered and its target already has focus. This may not happen too often in practice, but in tests where things execute quickly it definitely can.
Previously this worked only if the target itself was the active element, but `<d2l-text-input>`'s validation tooltip has the `<d2l-text-input>` itself as the target (for complicated reasons but mostly because we wanted hovering over the whole thing to show the tooltip) but the actual element that gets focused is the underlying `<input type="text">`.
=> fix: show tooltips if initialized while target descendants have focus

components/alert/alert-toast.js
Closing toasts that aren't the bottom toast will now a 200ms opacity transition rather than 600ms to prevent ghost toast.
Opening and lowest closing keep the same animation as before.
=> Toast Alerts: Multiple Toasts: Update Animations

.github/CODEOWNERS
Gaudi is taking over OSLO, so update `helpers/getLocalizeResources.js` codeowners
[US154660](https://rally1.rallydev.com/#/?detail=/userstory/706269970679&fdp=true): OSLO Codeowner Changes
=> Update OSLO codeowners

mixins/labelled/labelled-mixin.js
Because there is a hard [3-second delay](https://github.com/BrightspaceUI/core/blob/ef076269421ed0ceb07c28fed82367c5b9fed612/mixins/labelled/labelled-mixin.js#L204) in `lablledMixin` before throwing a missing label error, the error can be thrown between tests, or in other tests entirely, causing tests to fail in a confusing way. Checking that the host component is still connected before throwing prevents this.
=> Don't throw missing label error if host is no longer connected

rollup/rollup.config.js
We originally set up rollup to ignore visual-diff goldens and test files... but then with the new vdiff, the identifying path changed from `screenshots` to `golden`, and files changed from `visual-diff.js` to `vdiff.js`. As a result, we've been bundling a bunch of (probably unnecessary) vdiffs with every static build, e.g.:
https://live.d2l.dev/BrightspaceUI/core/components/card/test/golden/card/chromium/link.png
This PR goes back to filtering those out.
**Edit:** Confirmed, the equivalent file was not included in this PR's bundle:
https://live.d2l.dev/prs/BrightspaceUI/core/pr-4144/components/card/test/golden/card/chromium/link.png
=> fix: Exclude visual-diff goldens from rollup

mixins/localize/localize-mixin.js
The `d2l-file-input` component requires a special button rendered in the upload instruction. In order to facilitate localizing this text, we need to add native `button` to the allowed list.
=> Allow native button in localizeHTML.

components/demo/demo-snippet.js
I'm not even sure why I added this selector originally. Seems quite unnecessary. Firefox doesn't support `:has()` and breaks the whole rule.
=> Fix firefox demo snippet fullscreen

package-lock.json, package.json
Copy of #4183 to publish static site
Bumps [rollup](https://github.com/rollup/rollup) from 3.29.4 to 4.0.2.
- [Release notes](https://github.com/rollup/rollup/releases)
- [Changelog](https://github.com/rollup/rollup/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rollup/rollup/compare/v3.29.4...v4.0.2)
---
updated-dependencies:
- dependency-name: rollup dependency-type: direct:development update-type: version-update:semver-major ...
=> chore(deps-dev): bump rollup from 3.29.4 to 4.0.2

components/filter/test/filter-tags.vdiff.js, components/tag-list/tag-list.js, components/tag-list/test/tag-list.vdiff.js
I definitely don't love this solution, so interested in other ideas as well.
With Chrome 118, when filter tags are chomped (or unchomped) and focus is moved from the "show more"/"show less" button to either the last item before showing more or the "show more" button the focus now fails.
I _think_ it's because the chomping is triggering the resize observer which in turn does a bunch of recalculation and in the process actually sets `visibility: hidden` on everything. And browsers don't like to focus on hidden things and if a hidden thing has focus, they remove it. What I can't explain is why this just started failing or why it's not failing in other browsers. I also can't find a good way to test if it's about to happen, and no amount of `requestAnimationFrame`s waited long enough -- I …
=> fix: wait for hidden items to appear before focusing

d2l-test-runner.config.js, package-lock.json, package.json
Now that `d2l-test-runner` supports implicit groups and excludes files in `node_modules`, we can simplify the `pattern` and get rid of the explicit `axe` group.
=> Simplify d2l-test-runner.config.js

mixins/provider/README.md, mixins/provider/provider-mixin.js, mixins/provider/test/provider-mixin.test.js
This PR updates the `ProviderDelegate` to returned a cached value. This avoids consumers having to do their own short-circuiting. Optionally, the consumer can opt out of caching by passing true for the `noCache` parameter.
=> Update ProviderDelegate to return cached value.

.github/workflows/release.yml
It looks like this broke with the release of `web-component-analyzer` [version `2.0.0` last week](https://www.npmjs.com/package/web-component-analyzer/v/2.0.0). Which makes sense as to why it was hard to track down a commit that broke it - we install this as part of the `release` workflow, so not tied to any code change on our part.
I don't know why removing the escape fixes it, but it works locally after I do this.
=> fix: Try to fix generation of custom-elements.json file

components/form/form.js
This event is now showing up on Daylight. According to the [Daylight docs](https://daylight.d2l.dev/about/adding-component/#component-code) this should hide the event from the site.
=> fix: Form: Hide d2l-form-connect from Daylight

components/focus-trap/focus-trap.js, components/focus-trap/test/focus-trap.test.js
This PR updates `d2l-focus-trap` to only trap focus if it's the last activated focus trap. This prevents focus traps that are not nested from stealing focus and causing an infinite loop. 
While nested focus traps are already supported and handled (for nested `d2l-dialog-*` components), it is possible for consumers to use a `d2l-dialog` in their app component, which subsequently uses an LMS/legacy helper to render a `d2l-dialog-fullscreen` at the root. In such a case, the dialog components are not nested, and therefore they compete for focus in an endless loop.
=> Only trap focus if last activated trap

.github/workflows/release.yml
Already removed `brightspace-bot` as a collaborator and removed access to `D2L_GITHUB_TOKEN`. Because of this, we'll need to backport this change to any maintenance branches for the release to work. I'm thinking I'll proactively do it for `2.154.x`, but none of the others.
=> feat: US158339 - Move to new release token

components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js
[DE53579](https://rally1.rallydev.com/#/?detail=/defect/702733926307&fdp=true)
This PR adds a work-around for this old [Safari bug](https://bugs.webkit.org/show_bug.cgi?id=160953) where nested fixed position elements that are overflowing are incorrectly clipped. This arises when we have a mobile dropdown showing inside an overflowing dialog.
**Before:**
**After:**
=> Add Safari fix for nested fixed position content within overflowing dialogs

.github/workflows/license-checker.yml
Bump the timeout of this workflow to work-around this issue: https://github.com/actions/setup-node/issues/878
=> Increase the timeout of the license checker workflow.

components/list/list-item-drag-drop-mixin.js, components/list/list-item-drag-handle.js
[DE55479](https://rally1.rallydev.com/#/?detail=/defect/729253956433&fdp=true)
This PR fixes an issue where the `d2l-list-item-drag-handle`'s up/down arrows are not clickable.
These arrows should be clickable with the mouse... but they are no longer. Clicking them causes the drag handle to revert its rendering back to drag mode (the dots icon).
For Chrome and Firefox, this appears to be a regression from this recent change: https://github.com/BrightspaceUI/core/pull/4100.
For Safari, there's more - it also suffers from [this long-standing terrible issue that Apple refuses to fix](https://bugs.webkit.org/show_bug.cgi?id=22261), where clicking a button that has focus will actually cause it to lose focus, which in this case, causes the drag-handle to toggle out of the `d2l-button-move` …
=> Fix d2l-list-item-drag-handle mouse interaction.

.github/workflows/ci.yml
GitHub removed the legacy way of doing this. [New method](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
Example before when note lost all it's fancy styling
=> Update note message about site

components/inputs/input-color.js, mixins/labelled/labelled-mixin.js, mixins/property-required/property-required-mixin.js, mixins/property-required/test/property-required-mixin.test.js
This is another flavour of #4272.
Instead of consumers calling `addRequiredProperty('name, opts)` in their constructor, this lets them define that a property is required right in the `static properties` Lit definition.
```javascript
static properties = {
someProp: { type: String, required: true }
};
```
If options are needed, then `required` can be an object:
```javascript
static properties = {
someProp: {
type: String,
required: {
validator: () => ...
}
}
};
```
=> PropertyRequiredMixin Option 2

helpers/README.md, helpers/plugins.js, helpers/test/plugins.test.js
[US160427](https://rally1.rallydev.com/#/?detail=/userstory/731548187981&fdp=true)
This PR adds plugins helpers - `registerPlugin`, `getPlugins`, and `getPlugin` to enable implementors to define plugins without consumers of those plugins being required to import them directly. BSI or a higher level module is responsible for importing the registrations.
Other options were considered, including deferring the registrations or by accepting an async provider method for the plugin, however we do not want plugin implementors assuming that if the registration is deferred, that it would be safe to synchronously import dependencies within the registration module. Typically, we expect projects registrations to be aggregated into a single public export, which means that unrelated plugins could be …
=> Plugins helpers

components/alert/test/alert-toast.vdiff.js, package-lock.json
Can't merge until #4261, but this uses the new `setViewport` in this vdiff test.
=> uses setViewport

components/button/button-mixin.js, components/button/button-move.js, components/calendar/calendar.js, components/form/form-errory-summary.js, components/inputs/demo/input-number.html, components/inputs/demo/input-percent.html, components/inputs/docs/input-numeric.md, components/inputs/docs/input-text.md, components/inputs/input-number.js, components/inputs/input-percent.js, components/inputs/input-text.js, components/inputs/test/input-number.test.js, components/list/demo/demo-list-nested-iterations-helper.js, components/list/demo/demo-list-nested.js, components/list/demo/list-drag-and-drop.html, components/list/demo/list-expand-collapse.html, components/list/demo/list-nested.html, components/list/list-item-drag-drop-mixin.js, components/list/list-item-generic-layout.js, components/list/list-item-role-mixin.js, components/list/test/list.vdiff.js, components/menu/menu-item-mixin.js, components/menu/menu.js, components/meter/meter-linear.js, components/meter/meter-radial.js, components/object-property-list/object-property-list-item.js, components/tabs/tab-internal.js, components/tabs/tab-panel-mixin.js, mixins/rtl/rtl-mixin.js
This updates core to adhere to the changes in an upcoming `1.0.0` release of `eslint-config-brightspace`. There were two new rules that this specifically addresses:
[prefer-nothing](https://github.com/43081j/eslint-plugin-lit/blob/master/docs/rules/prefer-nothing.md): pretty straightforward -- use `nothing` whenever possible.
[no-native-attributes](https://github.com/43081j/eslint-plugin-lit/blob/master/docs/rules/no-native-attributes.md): ideally, we'd never be duplicating native attribute names on custom elements. In practice, we've done this in a few "legitimate" cases (like `role`), a few mistakes (like `draggable`) and a few places we thought were OK but in reality we shouldn't have (`autofocus`, `title`).
For the most part, I've added ignore comments. For number/percent inputs …
=> Fix lint errors for upcoming changes

components/button/README.md, components/button/button-add.js
[Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-330)
Adds the `add-button` to the button README. There will be a corresponding PR in documentation repo to add `button-add` import to the button page.
=> GAUD-330: Add Button: Documentation

components/hierarchical-view/hierarchical-view-mixin.js
Curious about thoughts on this one, because I'm not super sure if there are ramifications here that I'm not thinking of. To keep a long story short, it looks like there can be some interesting timing shenanigans that go on when something extends both `HierarchicalViewMixin` and `LocalizeDynamicMixin`, in which we end up trying to hook up the resize observer before the element has actually rendered (all that exists is the shadowroot).
This cropped up in the HTML editor ages ago and we worked around it at the time (https://github.com/BrightspaceUI/htmleditor/blob/main/components/toolbar/table-create.js#L88), but in some testing I did today, I noticed a couple things:
- When this fails (`content` is null), it seems to always be caused by the Lit update triggered by the lang terms being …
=> Don't try to set up resize observer if there's no content to observe

components/list/list-item-mixin.js
**Problem**:
Can be seen in the [drag and drop demo](https://live.d2l.dev/BrightspaceUI/core/components/list/demo/list-drag-and-drop.html) "Add Button" demo at the bottom of the page. Drag the two nested items out of the bottom nested list and note that the border isn't full length and there is a console error.
The issue was that it actually no longer had a nested list and was failing when checking for `add-button` attribute.
=> Add Button: List: Fix drag and drop border bug

components/dropdown/README.md
Removing the reference to https://github.com/BrightspaceUI/tabs. Also fixing the menu link, which doesn't work at all on the Daylight site.
=> fix: Remove reference to BrightspaceUI/tabs

components/tooltip/tooltip.js
Before, the animation would only play once, now whenever the user hovers over the tooltip the animation will play
https://github.com/BrightspaceUI/core/assets/24593380/ec447607-b46d-4457-b831-e6b3a859ce98
=> fix: show animation on tooltip hover

components/more-less/demo/more-less.html
> This is just for testing at the top of the page/scrolling up. I'll remove it before merging.
[Oops](https://github.com/BrightspaceUI/core/pull/4455#discussion_r1491024961).
=> Remove more-less testing demo

components/menu/README.md, components/menu/menu-item-checkbox.js, components/menu/menu-item-link.js, components/menu/menu-item-radio.js
The "supporting" slot is supported by link, checkbox and radio menu items but it's not included in the Daylight Site documentation.
=> fix: add docs for "supporting" slot

.github/workflows/ci.yml
See [comment-on-pr#post-mode](https://github.com/BrightspaceUI/actions/tree/main/comment-on-pr#post-mode) and https://github.com/BrightspaceUI/actions/pull/148 for details. Made sure to re-run the workflow posting the comment to test behaviour was correct.
=> Switch to new `post-mode` for live site comment

mixins/loading-complete/README.md, mixins/loading-complete/loading-complete-mixin.js
This expands the mixin for more general use. We already have [a number of uses](https://github.com/search?q=saved%3AD2L+%2F%5Cw*%5C.getloadingcomplete%2F&type=code&saved_searches=%5B%7B%22name%22%3A%22D2L%22%2C%22query%22%3A%22org%3ABrightspace+OR+org%3ABrightspaceUI+OR+org%3ABrightspaceUILabs+OR+org%3ABrightspaceHypermediaComponents%22%7D%5D&expanded_query=org%3ABrightspace+org%3ABrightspaceUI+org%3ABrightspaceUILabs+org%3ABrightspaceHypermediaComponents+%2F%5Cw*%5C.getloadingcomplete%2F) of `getLoadingComplete` outside of tests, so we can't rely on it only being used there.
=> Rework loading complete mixin

components/tooltip/tooltip.js
[Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6196)
**Problem**:
In the tag-list the truncation tooltip is always showing (other than on first focus). For example:
This was also causing the keyboard instructional tooltip to not show.
Our expectation seems to be that generally `scrollWidth` of the clone is equal to `offsetWidth` of the target. However, Safari seems to be adding 1px to the `scrollWidth`. I couldn't find a why for this, but let me know if there's something I missed there.
=> fix: Tooltip: Safari: show-truncated-only not working [GAUD-6196]

components/alert/alert-toast.js
[Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6138)
**Problem:**
When a toast alert closes, generally the role does not reset and this can cause unexpected screen reader behaviour. 
It was noted as an issue on Chrome + NVDA (inconsistent experience; didn't say "Alert" on second opening and read the close button text twice). This seems to no longer be an issue (Chrome + Windows seems to be reseting `role` for some reason?), but I noticed on VoiceOver + Chrome it was only reading the alert the first time it was shown. 
I also am having trouble with VoiceOver + Safari reading the text at all (seems like it can be super delayed) but that seems like a separate issue.
**Solution notes:**
This removes the `role` attribute when the …
=> fix: Alert-toast: Reset role when closed [GAUD-6138]

components/list/list-item-mixin.js
When in grid mode, there should be an instructional tooltip displayed when the user first tabs in. This did not work as expected with button-add.
Worth noting is that button-add does normally have its own tooltip that says "Add Item" by default. This one does seem like it should take priority for this first focus. I also think the position start is okay here because otherwise it seems too much related specifically to the add button itself if it's centred but adding in @geurts to see if there's any thoughts on that.
=> fix: Add Button in List: Grid mode tooltip

components/tooltip/tooltip.js
We're getting this warning in prod but I'm not sure how to track down the offending element.
https://d2l.slack.com/archives/C0PHG3QB0/p1712752935956559
=> tooltip-include-target-in-warning

lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js, templates/primary-secondary/primary-secondary.js
This addresses two problems with the primary/secondary template:
The first is that when the panels aren't resizable, the divider was still there and discoverable to assistive technology. In this scenario, I've updated it to render a "readonly" version of the divider, also known as "a grey line".
While fixing the first thing, I discovered that the "separator" ARIA role we were using for the divider simply wasn't working as expected. It seems like support for it was never really ironed out or implemented widely. To address this, we've converted it to a "slider" role. We've also:
- Added a "secondary panel" label to the `<aside>` element
- Removed the keyboard instructions for using the divider since it's a standard ARIA thing and simplified its label to "Secondary panel divider" which …
=> GAUD 5465: use "slider" ARIA role and only render divider when resizable

components/form/form.js, components/form/test/form.test.js
@rileyodonnelld2l noticed this issue. The scenario: they had a form which contained a HTML Editor, which could launch the "insert link" dialog which contained a nested form that "joined" the outer form (aside: it probably should have had `no-nesting` on it since joining the parent form is weird, but regardless). Even after the insert link dialog was closed and it was totally removed from the DOM, the outer form would still include it in its validation.
The reason for this is that the logic that handles disconnected nested forms never worked, and this fell into a special edge case that required it to work.
The main reason for that was a mismatch between the event being dispatched (`d2l-form-disconnected`) and the event being listened for (`d2l-form-disconnect`). Beyond that though, the …
=> fix: don't validate disconnected nested forms (GAUD-6271)

helpers/mathjax.js, tools/mathjax-test-context.js
MathJax offers experimental support for some MathML elements via an mml3 extension. This gives us at least some support for symbols like long division that we wouldn't get otherwise (stock MathJax yields a math input error if you try to use, say, `<mlongdiv>`. It's likely ideal for us to support this rather than not.
=> Add experimental support for MML3 features within MathJax (including mlongdiv)

.github/workflows/release.yml
Rally is gone and can no longer be relied upon to provide us with the current active development release of the LMS. I've [updated the action](https://github.com/Brightspace/lms-version-actions/pull/33) to query a new S3 bucket which will be the source of truth for the release calendar.
This PR switches to that new updated version by passing the proper AWS credentials in place of the `RALLY_API_KEY`.
=> fix: switch to Rally-free version of semantic-release

components/selection/selection-mixin.js, components/selection/selection-summary.js
Overall goal: 
Remove an override that is no longer in use (sorry this took so long)
Backstory:
A few years ago we had added an override for the selection count for this component meant to be temporary. We then temporarily disabled the select-all button on our `d2l-list` (which removed our usage of this override) with the intention of undoing that. However, we never got to undoing that which meant we never got to fixing/removing this override.
PR where this was added:
https://github.com/BrightspaceUI/core/pull/2846
[Usages](https://search.d2l.dev/search?full=%22selection-count-override%22&defs=&refs=&path=&hist=&type=&xrd=&nn=8&searchall=true) of this property. Seems like it's not actually in use and the same definition is somehow in two other places that I don't think we really need to …
=> feat: Remove unused override

package-lock.json, package.json
`@babel/eslint-parser` is a peer dependency of `eslint-config-brightspace` so shouldn't be required here. Likely a holdover from ancient times.
=> Try removing eslint-parser depdendency

components/focus-trap/focus-trap.js, components/focus-trap/test/focus-trap.test.js
[GAUD-6323](https://desire2learn.atlassian.net/browse/GAUD-6323): equatio chrome extension not functioning in quizzing tool
To allow specific elements outside a focus trap container to be focused, we can add an exemption list. This allows for mouse clicks and roundabout screenreader navigation to focus the exempted elements, but not normal keyboard navigation (tabbing).
[GAUD-6323]: https://desire2learn.atlassian.net/browse/GAUD-6323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow exemptions to focus trapping

components/backdrop/backdrop.js, components/dialog/demo/dialog.html, components/dialog/dialog-mixin.js
Currently, backdrop methods to control body scrolling can register and track the same host multiple times, which can be disconnected from the DOM before all `scrollKeys` for that host can be removed, leaving an orphaned `scrollKey` that prevents the body scrolling from returning to its original value.
This change instead uses a `Set` to store references to host instances themselves rather than generating unique string ids for each `preventBodyScroll` call.
There are two uses of these methods outside core. Namely, `htmleditor` and `nova`, which I have updated and will open PRs for once this is approved.
[GAUD-6349](https://desire2learn.atlassian.net/browse/GAUD-6349): Fix d2l-backdrop `scrollKey` registration
[GAUD-6349]: https://desire2learn.atlassian.net/browse/GAUD-6349?atlOrigin=eyJpIjo …
=> Fix backdrop body scrolling methods

components/scroll-wrapper/scroll-wrapper.js
The [MediaQueryListEvent API isn't supported until Safari 14](https://caniuse.com/mdn-api_mediaquerylistevent), which is why were were trying to protect against it not existing here. Except the optional chain is on `PRINT_MEDIA_QUERY_LIST`, not the method that will be missing. This switches the chain to the method.
=> fix: protect against missing addEventListener on MediaQueryList

components/inputs/demo/input-radio-spacer-test.js, components/inputs/docs/input-radio.md
[GAUD-6341](https://desire2learn.atlassian.net/browse/GAUD-6341)
This PR updates the docs and demo to show the correct usage of `d2l-input-radio-spacer`. To summarize, the `d2l-input-radio-spacer` is meant to be used in conjunction with the `.d2l-input-radio-label` CSS class - they will both apply the same whitespace to achieve the alignment. If they are not used together, the consumer will not get the desired alignment.
Updated demo showing correct usage:
[GAUD-6341]: https://desire2learn.atlassian.net/browse/GAUD-6341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update docs and demo for d2l-input-radio-spacer

components/inputs/demo/input-radio-spacer-test.js, components/inputs/docs/input-radio.md, components/inputs/input-checkbox.js, components/inputs/input-color.js, components/inputs/input-fieldset.js, components/inputs/input-inline-help.js, components/inputs/input-radio-spacer.js, components/inputs/input-text.js, components/inputs/input-textarea.js, components/inputs/input-time.js, components/typography/styles.js
[GAUD-6341](https://desire2learn.atlassian.net/browse/GAUD-6341)
This PR makes styling and usage of the `d2l-input-radio-spacer` clearer based on conversation with @geurts . It makes it easier for us to update inline-help styles in the future, rather than having consumers using the less semantic `d2l-body-small`.
Specifically:
* update example to show typical wire-up using `aria-describedby`
* factor out the inline help styles into `inlineHelpStyles`
* add `_generateBodySmallStyles` to support `inlineHelpStyles` implementation
* update to show usage of `inlineHelpStyles` & `.d2l-input-inline-help` CSS class
Although not strictly required, this is the expected typical setup:
```html
<label class="d2l-input-radio-label">
<input type="radio" aria-describedby="desc1" name="myGroup" …
```
=> Update inline-help and radio-spacer to make styling more fool proof.

components/collapsible-panel/collapsible-panel.js
From the docs I knew these events existed, but they weren't showing up in code search because their names were dynamically built up. Switching to a static definition to help with code searching.
=> use a static event name

components/collapsible-panel/README.md
Noticed this stuff is present in [daylight](https://daylight.d2l.dev/components/collapsible-panel/) but not here, adding for clarity
=> Document collapsible panel events

components/collapsible-panel/README.md
Moving the "hide from Daylight" comment down so we don't end up with a duplicated event section.
=> fix: Collapsible Panel: Hide events from Daylight

mixins/localize/README.md
I want to clarify the Lit lifecycle implications for `LocalizeMixin`, to make it clear when we are guaranteed to have valid terms.
This came up when we were trying to troubleshoot where to update `document.title`, which some of our components were doing too soon in `connectedCallback` - some Slack conversation here:
https://d2l.slack.com/archives/C0PHG3QB0/p1715891946771899
=> chore: Add lifecycle info to localize mixin

package-lock.json, package.json
Only breaking change is that it requires Node 18.
Release notes:
https://github.com/modernweb-dev/web/releases/tag/%40web%2Fdev-server%400.4.0
=> upgrade to @web/dev-server 0.4

components/inputs/docs/input-checkbox.md, components/inputs/docs/input-date-time.md, components/inputs/docs/input-numeric.md, components/inputs/docs/input-search.md, components/inputs/docs/input-text.md, components/inputs/input-checkbox.js, components/inputs/input-text.js, components/inputs/input-textarea.js, components/inputs/input-time.js
Noticed that we weren't consistent documenting the `inline-help` slots, either in the code or READMEs. I think this is all of them now.
=> fix: add missing docs for inline-help slots

components/html-block/demo/html-block.html, helpers/mathjax.js
There's a bug in MathJax's experimental `[mml]/mml3` package that can cause equations to fail to render if extra spaces are added to equations via `<mo>` and `<mi>` elements containing non-breaking spaces. We don't really want this behaviour anyways, since adding extra spaces just messes up MathJax's rendering, so the simplest option here is to just remove these elements if we find them.
It does look like there's a fix for this, but only in MathJax 4, which is still in beta, so not something we'll be updating quite yet.
=> Strip out mo/mi elements when rendering MathML if they only contain non-breaking space characters or other whitespace

components/scroll-wrapper/scroll-wrapper.js, components/table/table-controls.js
[MAN-2993](https://desire2learn.atlassian.net/browse/MAN-2993)
Related to https://d2l.slack.com/archives/C04511G83KR/p1717183794167289
The `sticky-headers-scroll-wrapper` attribute is causing issues with tooltip display in mastery view.
One possible workaround is to instead [manually wrap the d2l-table in a scroll-wrapper](https://github.com/Brightspace/d2l-outcomes/pull/1287). This appears to work for our particular use case.
However since both the table sticky headers and the scroll-wrapper actions both have [z-index: 4](https://github.com/BrightspaceUI/core/pull/3635), the sticky headers take precedence in the render order, blocking out the left-side chevron:
Promoting the z-index for the scroll-wrapper-actions is the most straightforward (naive?) way to solve the issue.
DISCLAIMER: …
=> MAN-2993: Promote z-index for scroll-wrapper-actions

components/dropdown/dropdown-context-menu.js, components/table/demo/table-test.js, components/table/table-wrapper.js
Related to [backport](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6126)
Similar to `d2l-button-icon` components in table cells, we want to also be able to make `d2l-dropdown-context-menu` usages a certain size. This adds css vars in order to do so. Let me know if there's a better way to do this that I've missed - I don't love having to set the default for `--d2l-button-icon-min-height` and width, I just want to be able to set an override.
=> feat: dropdown: add ability to override inner button-icon height, use in table-wrapper

helpers/error.js, helpers/test/error.test.js
Whenever we include the composed path to an element in the error message -- for example a missing attribute like a label -- we included the FULL path of all ancestors. That was resulting in error messages like this:
> Uncaught TypeError: <d2l-input-text>: "label" attribute is required. Path: "div > div > div > div > div > div > div > div > div > d2l-expand-collapse-content > div > div > slot > div > d2l-my-courses > d2l-my-courses-container > d2l-all-courses > d2l-dialog-fullscreen > div > d2l-focus-trap > slot > div > div > div > slot > div > div > div > d2l-my-courses-search > d2l-dropdown > slot > div > d2l-input-search > d2l-input-text". (@brightspace-ui/core:PropertyRequiredMixin)
Very useful, but also very long. The index where we store these errors in OpenSearch had a character …
=> fix: shorter error messages when they contain composed path to elements

components/dropdown/dropdown-content-mixin.js, components/dropdown/dropdown-opener-mixin.js
[GAUD-6454](https://desire2learn.atlassian.net/browse/GAUD-6454)
This PR updates the fixed position dropdown to reposition itself when it observes DOM mutations in its ancestor path. It wires up the observer in each DOM scope, however it _does not_ wire-up to sibling scopes.
[GAUD-6454]: https://desire2learn.atlassian.net/browse/GAUD-6454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reposition fixed position dropdown when DOM mutations occur in the ancestor path

components/inputs/input-date-range.js, components/inputs/input-date-time-range.js, components/inputs/input-date-time.js, components/inputs/input-date.js, components/inputs/input-time-range.js, components/inputs/input-time.js
Part of [Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6474)
This adds a `prefer-fixed-positioning` attribute to all the date and time range components and passes it down to the base `input-date` and `input-time` components to be added to the dropdown-content and dropdown components in order to enable that behaviour when the flag is also true.
I added this to `input-time-range` as well even though it's not in scope for the filter work since it seems like it would be needed eventually.
Let me know if there would be a preferred way of doing this rather than passing it all the way through the components.
=> feat: Date and time inputs: Add prefer-fixed-positioning attribute

components/filter/filter.js
Part of [Jira ticket](https://desire2learn.atlassian.net/jira/software/c/projects/GAUD/boards/330?selectedIssue=GAUD-6474)
If a filter value has `additionalContent` then this adds a `d2l-expand-collapse-content` wrapper around the content.
This attempts to hide the date-time pieces away in the date-time value. Let me know if there are other suggestions for this.
If you wish to test this out with the date-time range, it can be seen [here](https://live.d2l.dev/prs/BrightspaceUI/core/pr-4742/components/filter/demo/filter.html) in the last demo on the page ("Date Filter"). Note that the css is a bit different there. I think I've simplified it here and it should work with those changes with a bit of tweaking.
=> Filter: Add ability to have expand/collapse content within a filter list item

components/dropdown/dropdown-content-mixin.js, components/dropdown/dropdown-menu.js, components/dropdown/dropdown-tabs.js
[GAUD-6558](https://desire2learn.atlassian.net/browse/GAUD-6558)
This PR updates the fixed position dropdown contents so that their container height is not updated as the user scrolls.
[GAUD-6558]: https://desire2learn.atlassian.net/browse/GAUD-6558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update fixed position dropdown so that the height is not updated as the user scrolls

components/inputs/input-date.js, mixins/interactive/interactive-mixin.js
Part of [Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-6576)
**Problem:**
When navigating the date filter with keyboard, down arrow sometimes opens the date dropdown (usually first time when empty) and sometimes moves focus to the next radio button.
**Expected Behaviour:**
Down arrow always opens date input dropdown when focus is on date input.
=> fix: Date filters: Input date: down arrow should open date input dropdown

components/meter/meter-circle.js, components/meter/meter-linear.js, components/meter/meter-mixin.js, components/meter/meter-radial.js, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
Screen readers can read out fractions like "3/10" as "3 slash 10, division", or "3 divided by 10", so for `aria-label` we use a text-based representation of the fraction i.e. "3 out of 10"
I searched CLDR data briefly for data to represent fractions but didn't find anything, so this may be the best solution.
[GAUD-6609](https://desire2learn.atlassian.net/browse/GAUD-6609): Update `MeterMixin` to use explicit aria-label text
[GAUD-6609]: https://desire2learn.atlassian.net/browse/GAUD-6609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `meter`: Use text-based fraction messages for screen readers

components/popover/popover-mixin.js, components/popover/test/popover-mixin.test.js
[GAUD-6561](https://desire2learn.atlassian.net/browse/GAUD-6561)
This PR updates the `PopoverMixin` so that they can be dismissed using the `[Escape]` key.
[GAUD-6561]: https://desire2learn.atlassian.net/browse/GAUD-6561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update popover to be dismissible using Escape key.

components/dropdown/dropdown-content-styles.js
[GAUD-6626](https://desire2learn.atlassian.net/browse/GAUD-6626)
This PR fixes an issue with fixed positioned dropdowns where they would disappear if opened above and the view-port is narrower than the mobile breakpoint (616px). The root cause is that we have some styles that override the `bottom` CSS property when not rendering as the `mobile-tray`.
[GAUD-6626]: https://desire2learn.atlassian.net/browse/GAUD-6626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix dropdown fixed positioning for mobile positioning (non-tray).

components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/test/collapsible-panel.test.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-5115)
The collapsible panel uses an offscreen button with the same label as the panel that when focused/blurred applies the focus styles to the actual container. The browser likely doesn’t know what to do when something offscreen gets focus like that, and certainly doesn’t know to scroll so that the container is visible.
- `scrollIntoView`: breaks the page layout when component is inside an iframe
- Using the header as a focus: Will read aloud the contents of the header + should not focuse on non-interactive components
- Move the offset button somewhere else in the component to hopefully scroll into its container: no dice
=> fix: Focus on collapsible panel out of view port doesn't scroll it into view

components/switch/README.md, components/switch/switch.js
One of the current initiatives of the Accessibility Llamas is to improve the Daylight site's documentation when it comes to accessibility, which includes adding a new [accessibility icon](https://github.com/BrightspaceUI/core/blob/main/components/icons/images/tier3/accessibility.svg) whenever `ACCESSIBILITY:` is added and decided to move the Accessibility Properties table into the main table. In addition, we've decided to create a new Accessibility section below everything else and include some helpful information about the component. This PR is obviously just for the Switch component, there will be changes to other components when we find more time to do other ones as well.
Currently this is waiting for https://github.com/BrightspaceUI/documentation/pull/1697 to be merged in so that it …
=> [a11y docn] Update switch component's readme for accessibility project

components/button/button-icon.js, components/button/test/button-icon.test.js
This morning, an automated accessibility test failed because text wasn't being provided to a `d2l-dropdown-context-menu`, which internally uses `d2l-button-icon`.
This change makes `text` required, which will cause a delayed exception to be thrown in the console and hopefully help developers catch this problem earlier. I specifically didn't also make it required on `d2l-dropdown-context-menu` since then there'd be two errors tied to the same issue, but am open to doing that if others think it would be useful.
=> fix: make text and icon required attributes on button-icon

components/list/list-item-generic-layout.js, components/list/test/list-item-generic-layout.test.js
[GAUD-6690](https://desire2learn.atlassian.net/browse/GAUD-6690)
This PR fixes an issue where the `d2l-list-item-generic-layout` could enter an infinite loop when trying to find the previous flattened list item to apply focus when the previous item contains an empty nested list. This infinite loop would result in the browser becoming unresponsive.
Without this fix, this code would result in an infinite loop using the `up` arrow key.
```html
<d2l-list grid>
<d2l-list-item label="Test Label" href="http://d2l.com" key="item2">
<div class="d2l-list-item-text d2l-body-compact">Root item 2.</div>
<d2l-list grid slot="nested"></d2l-list>
</d2l-list-item>
<d2l-list-item label="Test Label" href="http://d2l.com" key="item3">
<div class="d2l-list-item-text d2l-body-compact">Root item 3.</div> …
```
=> Fix infinite loop issue in list grid mode containing empty nested lists

components/inputs/docs/input-search.md, components/inputs/input-search.js
One of the current initiatives of the Accessibility Llamas is to improve the Daylight site's documentation when it comes to accessibility, which includes adding a new [accessibility icon](https://github.com/BrightspaceUI/core/blob/main/components/icons/images/tier3/accessibility.svg) whenever `ACCESSIBILITY:` is added and decided to move the Accessibility Properties table into the main table. In addition, we've decided to create a new Accessibility section below everything else and include some helpful information about the component.
This PR is obviously just for the `d2l-input-search` component, changes to other ones will come when we get more time to review them.
=> [a11y docn] Update the input-search docn for a11y project

.github/workflows/ci.yml
I couldn't find a nicer way to do this. If I just use `(failure() || success())` it will double submit since github will still run this step cause the last "unskipped" step succeeded or failed. This binds the submission step directory to the outcome of the associated test step.
https://desire2learn.atlassian.net/browse/QE-251
=> QE-251: Handle step failure better for test reporting submit

components/backdrop/backdrop.js
[GAUD-6698](https://desire2learn.atlassian.net/browse/GAUD-6698): d2l-backdrop does not always clean up after itself
[GAUD-6698]: https://desire2learn.atlassian.net/browse/GAUD-6698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure backdrop cleanup is performed

components/menu/README.md, components/menu/menu-item-mixin.js, components/menu/menu.js
One of the current initiatives of the Accessibility Llamas is to improve the Daylight site's documentation when it comes to accessibility, which includes adding a new [accessibility icon](https://github.com/BrightspaceUI/core/blob/main/components/icons/images/tier3/accessibility.svg) whenever `ACCESSIBILITY:` is added and decided to move the Accessibility Properties table into the main table. In addition, we've decided to create a new Accessibility section below everything else and include some helpful information about the component.
This PR is obviously just for the `d2l-menu` and all of its item components changes to other ones will come when we get more time to review them.
=> [a11y docn] Update the menu a11n documentation

components/menu/README.md
After being brought up by someone else, I've made some small fixes to the menu a11y section:
- Made the section title not all uppercase
- Switched the order of the bullet points in the a11y section since the second point is more significant.
=> Make a11y section title not all caps & rearrange the bullet points

components/button/button-move.js
It was [noticed here](https://d2l.slack.com/archives/C0PHG3QB0/p1722466706352229) that the click target for these "move buttons" is only `26px` wide by `22px` high, while WCAG 2.2 criteria 2.5.8 for minimum target size requires at least 24x24.
If you dig into the details, since we have a `2px` gap between the up/down click targets, there does appear to be an exemption that covers this case:
> Spacing: Undersized targets (those less than 24 by 24 CSS pixels) are positioned so that if a 24 CSS pixel diameter circle is centered on the [bounding box](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-minimum-bounding-box) of each, the circles do not intersect another target or the circle for another undersized target;
However, we'd rather not fall into an exemption case …
=> fix: increase height of button-move icons

rollup/rollup.config.js
I think it would be cool/useful to include `custom-elements.json` in the "live" sites that we generate. That way automation that doesn't have access to NPM could always grab the latest and easily get a list of elements.
=> include custom-elements.json in static sites

helpers/README.md, helpers/focus.js, helpers/test/focus.test.js
This PR adds a `getFocusables` helper that will be used as part of the fix for defects in `d2l-list` `grid` mode keyboard behaviour when list-item content contains various focusable arrangements ([GAUD-6697](https://desire2learn.atlassian.net/browse/GAUD-6697)).
[GAUD-6697]: https://desire2learn.atlassian.net/browse/GAUD-6697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add getFocusables helper.

components/table/table-col-sort-button.js
The problem with putting the sort direction in `aria-label` is that it becomes part of the column's label. That's nice when you're navigating the columns themselves, but when you're down navigating table cells in that column, having it repeat the sort direction each time isn't appropriate.
This alternate solution uses `aria-describedby` instead.
=> Alternate solution that uses describedby

components/table/table-col-sort-button.js
When rendering our table sort buttons, the sort direction is placed as a `title` (OS tooltip) on the `<button>` element, which is only inconsistently read by screen readers.
While we experimented with putting the sort direction in `aria-label`, it became part of the column's label. That's nice when you're navigating the columns themselves, but when you're down navigating table cells in that column, having it repeat the sort direction each time isn't appropriate.
This alternate solution uses `aria-describedby` instead.
=> fix: add sort direction to the label of table sort buttons

components/paging/pager-load-more.js
[GAUD-6833](https://desire2learn.atlassian.net/browse/GAUD-6833)
This PR updates `d2l-pager-load-more` to wait a frame before locating the element to apply focus. This improves the resiliency of the focus behaviour by allowing sub-components (for example `d2l-selection-input` inside of a `<tr>...</tr>` to fully render. While consumers can/should wait for their component to update, they aren't necessarily aware of sub-components.
[GAUD-6833]: https://desire2learn.atlassian.net/browse/GAUD-6833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update d2l-pager-load-more to wait a frame before locating and applying focus

components/demo/demo-page.js, components/demo/test/demo-page.test.js
Sets a flag to indicate that we're in a demo environment. This will allow places [like feature flags](https://github.com/BrightspaceUI/lms-core/pull/160) to operate slightly differently.
=> feat: set isD2LDemoPage flag

components/html-block/html-block.js, components/html-block/test/html-block.vdiff.js
Targets #4922
This is an alternative to "[Reset renderer processing state on update](https://github.com/BrightspaceUI/core/pull/4922/commits/a5d5a91d62e1fe71c84f3e65215777834638033c)".
Note that I reset this branch to undo that commit, but it would need to be done again in the target branch if we want to merge this. Or I can re-apply it here to keep the history.
=> Call updated after embeds are processed

.github/dependabot.yml
This dependency was [recently moved to the Intl library](https://github.com/BrightspaceUI/core/pull/4932).
=> remove plural-rules from dependabot config

components/button/button-icon.js, components/button/test/button-icon.test.js
When we added error checking to ensure that the `icon` attribute on `<d2l-button-icon>` was always provided, the fact that a custom icon can be provided in a slot was overlooked. This includes a custom validator to allow that case to pass.
=> fix: icon is not required if slotted custom icon is provided

components/dropdown/dropdown-opener-mixin.js
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-6944)
Part 2 of [this Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-6886)
**Problem:**
Dropdown menus when interacted with with VoiceOver do not announce expand/collapse state. This is due to the use of `aria-haspopup` in addition to the `aria-expanded` state. When only `aria-expanded` is present, its state is properly read.
**Solution:**
This removes `aria-haspopup`. Jeff found [this article](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/expanded/#adding-haspopup-optional) which recommends against the usage of `aria-haspopup` in cases like this since it does not add anything (and in this case actually removes useful information).
Also worth noting is that when testing with Firefox + …
=> fix: Dropdown opener: remove aria-haspopup

components/inputs/input-number.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-5091)
Adjusting the width of the internal `d2l-input-text` makes the tooltip display next to the input rather than the very end of the component. This change maintains the external `width` at 100%.
=> Position tooltip on right side correctly

components/dialog/dialog-styles.js
This PR applies `height: 100%` to the content container element when `full-height` is used. This enables consumers to place an element in the dialog with `height: 100%` so that it actually fills the available space defined by the vertical flex layout.
=> Update the dialog content container to 100% height when full-height is used.

components/inputs/docs/input-search.md
Fixing a typo in the Accessibility section heading
=> Fix accessibility typo

components/focus-trap/focus-trap.js, components/focus-trap/test/focus-trap.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-6775)
**Context:**
It was found in the accessibility audit that with NVDA (and possible other screen readers; not VoiceOver) when the focus wraps to either the start or end (depending on focus direction), NVDA would read "blank" because of the brief focus on `d2l-focus-trap-start` or `d2l-focus-trap-end`. NVDA does this in order to communicate to a user that their focus action was successful.
After some discussion and consideration of options (e.g., an announced wrapping label) it was decided to remove the `setTimeout` since the case where there is only one item in the focus trap should be fairly rare. Jeff has added extensive notes to the Jira ticket for further reading if wanted.
=> fix: Focus trap: remove delay when focusing on first/last item when wrapping focus

components/form/demo/form-panel-demo.js
The form panel demo was using a stand alone collapsible panel that was throwing errors due to missing text value. This PR replaces it with a `d2l-collapsible-panel`
=> Fix form panel demo

components/inputs/docs/input-date-time.md, components/inputs/input-date-range.js, components/inputs/input-date-time-range.js, components/inputs/input-date-time.js, components/inputs/input-date.js, components/inputs/input-time-range.js, components/inputs/input-time.js, mixins/labelled/labelled-mixin.js
[Jira ticket](https://desire2learn.atlassian.net/browse/DAYL-97)
Adds `ACCESSIBILITY: ` prefix to accessibility-related properties and adds Accessibility section.
=> feat: [a11y docs] Date and time inputs: Improve accessibility documentation

components/list/README.md
Adding missing demo titles for some of the `d2l-list` demos
=> Fix: List > Add sandbox demo titles

components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/demo/collapsible-panel.html
[GAUD-6986](https://desire2learn.atlassian.net/browse/GAUD-6986)
This PR fixes 3 things:
1. Pointer cursor not being applied on the opener
2. Header styles not honouring `:focus-visible`
3. `[space]` and `[enter]` keys not working as expected after clicking on the header
[GAUD-6986]: https://desire2learn.atlassian.net/browse/GAUD-6986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Focus fixes for collapsible panel.

components/meter/README.md
Added missing sandbox title for Light Foreground demo and renamed existing ones so they all start with "Meter".
=> Fix: Meter > Missing sandbox title + tweaks

components/filter/README.md
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-6989)
=> fix: Filters: Document requestFilterClearAll and requestFilterValueClear methods

components/dialog/test/dialog-confirm.axe.js, components/dialog/test/dialog-fullscreen.axe.js, components/dialog/test/dialog.axe.js
Part of [this Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7001)
Adding axe tests prior to doing the work to make the dialog content container focusable if no focusable elements within it.
=> Dialogs: Add axe tests

components/dialog/demo/dialog-confirm.html, components/dialog/dialog-fullscreen.js, components/dialog/dialog.js, components/dialog/test/dialog-fullscreen.axe.js, components/dialog/test/dialog-fullscreen.test.js, components/dialog/test/dialog.axe.js, components/dialog/test/dialog.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7002)
This overrides the DialogMixin `title-text` property in `dialog` and `dialog-fullscreen` to make it required.
Reasoning: it is an accessibility violation to not have some sort of label on a dialog. `dialog-confirm` falls back to `text` in the case where there is not `title-text` so it's fine, but these two cases are not.
Notes:
- I did a search for where dialog and dialog-fullscreen we NOT currently using `title-text` and only found one case [here](https://github.com/Brightspace/lego-registry/blob/b2c3ef4de18ea7cbc00aeaed94d761b7bc771683/app/src/brick-request-dialog.js#L51) (though the GitHub search sometimes misses things so it's possible this will cause an uptick in js errors, in which case we can find these cases and …
=> feat: Dialog and Dialog-fullscreen: Make title-text required [GAUD-7002]

components/inputs/docs/input-checkbox.md, components/inputs/input-checkbox.js
[DAYL-93](https://desire2learn.atlassian.net/browse/DAYL-93)
This PR is updating the documentation for the `d2l-input-checkbox` component to denote the a11y aspects of the component. Adding the `ACCESSIBILITY:` prefix in from of a11y properties and a small Accessibility section at the end.
[DAYL-93]: https://desire2learn.atlassian.net/browse/DAYL-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [a11y docs] DAYL-93 Input Checkbox  a11y docn

components/inputs/docs/input-date-time.md, components/inputs/input-time.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7028)
Removes reference to a placeholder in `input-time` since `input-time` does not use a placeholder. Let me know wording alternative ideas or thoughts on if I should more specifically define how the fallback time is calculated.
=> fix: input-time docs: remove reference to a placeholder [GAUD-7028]

components/html-block/html-block.js, components/html-block/test/html-block.vdiff.js
Backport of this PR: https://github.com/BrightspaceUI/core/pull/5032
Note: There is a 3.39.x branch, but I'm not sure what purpose it serves. BSI is using 3.38.x for 20.24.10. Either way, I'm going to align this with 20.24.10 BSI for now, with the expectation that the Lessons FRA can either update core to align with what BSI is using, or do whatever other backports they may need.
=> Switch from Lit-managed rendering to direct DOM manipulation in html-block to avoid conflicts with MathJax

components/html-block/html-block.js
This was still generating some console errors under some circumstances when an html-block was relatively quickly rendered and then updated again in quick succession. Here's what I think is happening: Before our async renderers can act, Lit is wiping out the value of the ref during its re-render. This leads to NREs in various places, since our renderers also do a bunch of asnyc things, so this can cause failures in a number of places.
While I could do something like `const renderContainer = this._renderContainerRef.value` to snag a direct reference to the element instead, I also think that throws away basically all of the value of using the `ref` directive anyways. 🤷 
Let me know if you would find it preferable for me to switch to the above, but for now I think it makes more sense to just …
=> Use direct element reference when updating render container

components/table/table-wrapper.js
[GAUD-7064](https://desire2learn.atlassian.net/browse/GAUD-7064): Table style updates causing performance issues
Details in [Slack thread](https://d2l.slack.com/archives/C0PHG3QB0/p1725475530489959)
This particular selector was creating performance issues in larger tables for somewhat obvious reasons, given how CSS processes selectors. Instead of forcing it to jump up and down the tree we can instead use a general sibling selector to set the property, then `unset` the property when a separate sibling selector matches.
[GAUD-7064]: https://desire2learn.atlassian.net/browse/GAUD-7064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Rework col-sort-button :last-child padding styles for performance

components/paging/pager-load-more.js, components/paging/test/pager-load-more.test.js
Discovered this in the Movie Tool where the rows in the table currently have no focusable descendants, so the load-more pager was simply leaving focus on the "load more" button.
After chatting with @dbatiste, we decided that focusing on the "first new item" that was loaded is the best we can do here.
=> fix: load-more pager should fall back to focusing on item

components/paging/README.md, components/paging/pager-load-more.js, components/paging/test/pager-load-more.test.js, components/paging/test/pager-load-more.vdiff.js
I found myself needing to know when the items had actually loaded when writing a vdiff test.
=> feat: add event to load-more-pager for when new items are loaded

components/alert/README.md
Makes some changes to UX content like best practices and introductory blurbs, and adds a new Accessibility section.
In addition to the changes I've already proposed here, we could also consider adding a "Known Gaps" sub-section in Accessibility to call out a couple areas we lack:
- Both alert types use colour to convey the "type" of alert, but the "type" is not conveyed any other way (for example, our "critical" dialogs use colour in a similar way, but we also prepend `Critical!` to the dialog title)
- Inline alerts don't have any semantics to help screen reader users understand the text is special (the equivalent of the visual treatment with the border and colour)
- Toast alerts disappear after 4 seconds, and users can't change this timing in any way. This is not a AA failure since it's …
=> feat: alerts: Doc'n improvements for a11y & UX content

components/table/README.md, components/table/table-col-sort-button.js
[Jira ticket](https://desire2learn.atlassian.net/browse/DAYL-127)
This does the following:
- Improves jsdoc comments in `table-col-sort-button` component
- Adds accessibility section to the Table page
- Updates `table-col-sort-button` documentation to use live demo rather than static properties and slots tables
=> feat: table: Improve accessibility documentation

components/dropdown/README.md
I noticed this demo was importing tabs components that were not being used in the demo. This PR removes them.
=> docs: Remove unnecessary imports from d2l-dropdown-menu demo

components/dropdown/dropdown-menu.js, components/filter/demo/filter.html, components/filter/filter.js, components/filter/test/filter.axe.js, components/filter/test/filter.test.js, components/hierarchical-view/demo/hierarchical-view.html, components/hierarchical-view/hierarchical-view-mixin.js, components/inputs/input-time.js, components/menu/menu.js
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-7124)
**Problem:**
When the `input-time` component is nested in a hierarchical-mixin (as in a nested filter dimension set) it doesn't open properly. This is due to it being a child-view and the logic of the dropdown menu and hierarchical mixin for child views taking over.
**PR Notes:**
I added `ignore-hierarchy` attributes to `dropdown-menu` and `hierarchical-mixin` for this case and used this in `input-time`. A safer option if we want to reduce risk would be to also pass this through from `d2l-filter-dimension-set-date-time-range-value` all the way to the nested `input-time`, though I believe we would want this behaviour to always be the case.
This is a bit of a complex situation and I'm very open to other thoughts on how to …
=> fix: input-time/hierarchical mixin: add rootView property to allow menus to specify that they are the root view

components/focus-trap/focus-trap.js, mixins/loading-complete/loading-complete-mixin.js, mixins/localize/localize-mixin.js, package-lock.json
This PR bumps `eslint-config-brightspace` to v1.2.0 so that private members defined with `#` are identified as private for linting. Otherwise, eslint will expect these private members to be sorted among the public properties and methods.
=> Fix the order of private members for linting.

components/count-badge/demo/count-badge.html, components/demo/code-view.js, components/demo/demo-snippet.js
[GAUD-7138](https://desire2learn.atlassian.net/browse/GAUD-7138)
This PR aims to eliminate the warnings arising from `d2l-demo-snippet` and `d2l-code-view` in demos. I chose to address these because they clutter up the console in all of our demo pages, and updating them is relatively low risk. We should address these warnings for other components as well, but changes to them carry a bit more risk so I didn't go down that rabbit hole for this change.
[GAUD-7138]: https://desire2learn.atlassian.net/browse/GAUD-7138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Avoid unnecessary demo/code-view rerendering

components/button/button-toggle.js, components/button/demo/button-toggle.html, components/button/test/button-toggle.test.js
Reverts BrightspaceUI/core#5143
Reverting for two reasons:
1. This is causing double click event handler triggering in the LMS in Toggle
2. This can actually just be done with an LMS change (adding an e.stopPropagation) so I'll be doing that instead.
If this seems like a pattern others end up needing and are unsure how to implement then we can document it.
=> fix: Revert "feat: button toggle: Allow consumer to control pressed state"

components/button/button-toggle.js, components/button/demo/button-toggle.html, components/button/test/button-toggle.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7170)
Still needs docs and test(s) but just wanted to make sure I was going down the right path from [this comment](https://github.com/Brightspace/lms/pull/59102#issuecomment-2474425007) before I went too far.
=> feat: Button Toggle: Add ability for consumers to handle toggling pressed state

components/switch/demo/switch.html, components/switch/switch-mixin.js, components/switch/switch-visibility.js, components/switch/switch.js, components/switch/test/switch.test.js
[GAUD-7204](https://desire2learn.atlassian.net/browse/GAUD-7204)
This PR adds the `d2l-switch-before-change` event to give consumers the ability to control the state. For instance, the consumer may display a confirmation dialog, and then toggle the switch state depending on the user's choice.
This approach mirrors what we recently did for `d2l-button-toggle` for the same type of scenario.
The demo page shows it in action.
[GAUD-7204]: https://desire2learn.atlassian.net/browse/GAUD-7204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add d2l-switch-before-change event to give consumers control of state

components/table/demo/table-test.js, components/table/table-wrapper.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-6681)
Related PR: https://github.com/Brightspace/lms/pull/59520
**Context:**
This came up in the accessibility audit in the context of the LMS Rubrics table. When a select all textbox is in a th, it causes all the checkboxes within the column to also read whatever the "select all" text is on the checkbox.
**Solution Notes:**
The auditor recommended that these select all checkboxes should be in a `th` rather than a `td`. Currently we only style `th` cells within a table header to have background color etc so this updates those and also fixes our example table.
=> fix: Tables: style td in table header as th, use td instead of th for select all headers

components/backdrop/README.md, components/backdrop/backdrop.js, components/backdrop/test/backdrop.test.js
Recently, Chrome & Edge starting putting errors in the console if an element has `aria-hidden="true"` applied while focus is somewhere inside. Since `aria-hidden` hides an element and all its descendants, it seems like browsers were always applying some kind of exception when elements had focus -- but now they're notifying us of this.
The fix here to `<d2l-backdrop>` is to wait a short period of time for the consuming component to move focus inside the target before applying `aria-hidden`. After `200ms` if focus is still outside the target, we just hide them anyway and the developer may get a console error to investigate.
There are still a lot of consumers of `<d2l-backdrop>` that are using it purely as a specialized loading spinner, where the target has no focusable elements inside. In …
=> fix: don't hide backdrop elements until focus is inside target

components/object-property-list/demo/object-property-list.html, components/object-property-list/object-property-list-item-link.js
[GAUD-7228](https://desire2learn.atlassian.net/browse/GAUD-7228)
Due to not using the `d2l-link` component, when `target="_blank"`, we weren't showing the "open in a new tab" functionality, so I've switched the `object-property-item-link` to use the `d2l-link` component instead of just the styling.
[GAUD-7228]: https://desire2learn.atlassian.net/browse/GAUD-7228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Switch to using d2l-link in object-property-item-link

helpers/mathjax.js
This PR aims to (partially) address an issue we see when MathJax contexts end up nested. A good example of this is when an `html-block` ends up nested within a Content file that already has our MathJax helper injected. The helper tries to reach into the html-block and render the math, but fails horribly because of the shadowDOM boundary. This change forces the outer renderer to skip any `html-block`s when trying to render.
It's important to note that this doesn't fully solve the problem. MathJax still gets the styling wrong in this case because (unfortunately) the outer renderer ends up setting some kind of internal global configuration that causes the renderer running inside the `html-block` to miscalculate its styles.
I think a more robust solution would also require having the outer …
=> Prevent MathJax from reaching into html-block shadowDOM for rendering

components/dialog/dialog.js
[GAUD-7337](https://desire2learn.atlassian.net/browse/GAUD-7337)
We need to provide more guidance on when to use `describe-content` because:
* users do not want a wall of text announced to them upon entering dialogs
* `describe-content` uses `aria-describedby` under the covers so...
* browsers ignore complex HTML semantics in `aria-describedby` - they expect text content
* some screenreaders seemingly have limits/bugs on the amount of `aria-describedby` content that it will announce (ex. [Jaws](https://github.com/FreedomScientific/standards-support/issues/705) limits to 267)
[GAUD-7337]: https://desire2learn.atlassian.net/browse/GAUD-7337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update d2l-dialog describe-content doc comment

components/popover/demo/popover.html, components/popover/popover-mixin.js, components/popover/test/popover.js
[GAUD-7123](https://desire2learn.atlassian.net/browse/GAUD-7123)
This PR introduces the initial tray positioning. It does not include the backdrop, the close button, or animation of the tray - planning to do those separately.
This tray logic is basically a direct port from `DropdownContentMixin`.
[GAUD-7123]: https://desire2learn.atlassian.net/browse/GAUD-7123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Initial popover support for tray positioning.

components/empty-state/empty-state-illustrated.js, components/empty-state/test/empty-state-illustrated.vdiff.js
I noticed when using the illustrated empty state in a vdiff that it didn't wait for the SVG to render.
=> fix: add getLoadingComplete support to empty-state-illustrated

components/list/list-item-drag-handle.js, components/list/test/list.test.js
[GAUD-7353](https://desire2learn.atlassian.net/browse/GAUD-7353): List drag handle is broken in Safari
In #4238, @dbatiste fixed an issue with the drag handle arrows no longer being clickable. I'm not sure why this caused different behavior between Chrome and Safari, but Safari started always placing the handle on top of the action layer (which actually seems more correct) while Chrome left it below but somehow also made the arrows clickable again. I've stopped trying to understand how/why.
[More details on the Safari behavior being perceived as a bug](https://d2l.slack.com/archives/C0PHG3QB0/p1734460877556369).
This moves Dave's `pointer-events` fix from the `d2l-list-item-drag-handle` host to _only_ the `d2l-button-move` handle (with the arrows) within. This appears to fix the Safari …
=> Fix Safari drag handle, maintaining clickable drag arrows

components/demo/demo-snippet.js
This PR fixes the `d2l-demo-snippet` sanitation RegEx so that it doesn't get confused by `target="_blank"`. Background: the purpose of this replacement is to exclude sprouted private properties/attributes from the formatted code sample displayed in the demo-snippet. The original RegEx would replace too much in this case.
**Before:**
**After:**
=> Fix demo snippet sanitation for target="_blank"

components/popover/popover-mixin.js
[GAUD-6563](https://desire2learn.atlassian.net/browse/GAUD-6563)
This PR adds the backdrop to the Popover mobile tray.
**inline-start**
**inline-end**
**block-end**
[GAUD-6563]: https://desire2learn.atlassian.net/browse/GAUD-6563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Show the backdrop while displaying the popover as mobile tray

components/dialog/dialog-mixin.js, components/dialog/dialog.js
This handles the additional case where the dialog is `async` and the additional components that have just been loaded asynchronously need each of their `updateComplete`s (and `getLoadingComplete` if they have it) to be awaited.
Trying to rush this in before branching. I'll follow up with tests.
=> fix: additional waitForUpdateComplete in async dialogs

components/popover/demo/popover.html, components/popover/popover-mixin.js, components/popover/test/popover.js
[GAUD-7122](https://desire2learn.atlassian.net/browse/GAUD-7122)
This PR adds the tray's Close button to the test popover component. 
[GAUD-7122]: https://desire2learn.atlassian.net/browse/GAUD-7122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add close tray button to popover test.

components/expand-collapse/README.md
[Jira Story](https://desire2learn.atlassian.net/browse/DAYL-102)
Similarly to many of the other PRs, this is another improvement to the a11y docn of the `d2l-expand-collapse-content` component. Due to the nature of the component, the only changes are in the readme and mostly instruct the users how to implement the component in an accessibility-friendly way.
=> feat: DAYL-102 Update Expand-Collapse A11y Docn

components/tooltip/test/tooltip.test.js, components/tooltip/tooltip.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7453)
Requested by Jeff. He noticed that the current tooltip behaviour is that if a user is hovering over a tooltip target for > 1000ms and then goes to an adjacent target then there is a delay opening the next tooltip. We want the user to be able to quickly see the next tooltip contents if looking at a tooltip already, no matter how long they've been hovering over the current.
Desired behaviour:
- No delay when user hovers over adjacent tooltip openers as long as they reach the adjacent opener within 1000ms (this is different than previous where if the user hovered for > 1000 ms there would be a delay on adjacent opener)
- Delay on initial open (same as previous)
- Delay on subsequent opens if 1000ms has passed and no other …
=> fix: tooltip: Tooltip delay should be reset on close

components/backdrop/README.md
Added an Accessibility section and improved the introductory blurb.
=> feat: DAYL-88 Backdrop > Improve a11y docn

components/table/table-wrapper.js
Removes the "table-update-filter-GAUD-6955" flag from code, which was due in January.
Related:
- Removal from LMS: https://github.com/Brightspace/lms/pull/63414
- Recycle: https://github.com/Brightspace/lms-launch-darkly-flags/pull/16930
=> GAUD-7562: remove flag

components/dropdown/dropdown-content-styles.js
This avoids scrolling the outer page (or outer container) when the scroll point reaches the bottom or top of the dropdown.
=> GAUD-7576: use overscroll-behavior on dropdowns

components/dropdown/dropdown-content-mixin.js, components/dropdown/dropdown-content-styles.js
In the end, we decided to pull this feature entirely. It wasn't adding much for the vast majority of users, and could have negative side effects in certain edge cases.
=> GAUD-7576: remove feature

components/card/README.md, components/card/card-footer-link.js, components/card/card.js
[DAYL-92](https://desire2learn.atlassian.net/browse/DAYL-92)
Similar to other past stories, I'm updating the docn of the card component to include the `accessibility` tag in front of properties with a11y considerations. I've also updated the `text` property to be `Required`, an update to the component will be handled in [GAUD-7574](https://desire2learn.atlassian.net/browse/GAUD-7574) to have it use the required mixin, so that errors occur if the user doesn't have a value set for `text`
[DAYL-92]: https://desire2learn.atlassian.net/browse/DAYL-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GAUD-7574]: https://desire2learn.atlassian.net/browse/GAUD-7574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> feat: DAYL-92 Update Card A11y Docn

components/inputs/input-checkbox.js, components/inputs/test/input-checkbox.test.js
When I added the `disabled-tooltip` stuff I forgot that because the input isn't actually disabled anymore that it'll be toggle-able. 🤦
=> GAUD-7573: don't allow toggling when disabled

components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/test/collapsible-panel.test.js
The issue this is addressing is that if a VoiceOver user navigates using the Heading List directly to the collapsible panel's heading, there's no indication that it's interactive. That's because the heading _isn't_ interactive, the button is. But it can still be confusing, and JAWS/NVDA do still function.
This change moves the button inside the heading, which matches what the [W3C's Accordion Example](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/) does. With this change, VO does treat the heading as interactive and the user can toggle using VO-Space. Note though that the button doesn't have focus, so pressing ENTER/Space still does nothing. Once VO-Space is hit though, then focus does move to the button and ENTER/Space do work.
=> GAUD-5322: render collapsible panel's button inside the heading

components/tabs/tab-mixin.js, components/tabs/tab-panel-mixin.js, components/tabs/tab.js
Part of [this Jira task](https://desire2learn.atlassian.net/browse/GAUD-7483)
Does the following:
- Add labelled-by attribute to tab panel
- Update tab-panel docs
- Add `text` property to `d2l-tab` (default implementation of the `d2l-tab` / `d2l-tab-panel` method)
No impact is expected as `d2l-tab` is not in use.
=> feat: Tabs: Minor tweaks to tab and tab-panel

components/collapsible-panel/collapsible-panel-group.js, components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/test/collapsible-panel-group.test.js, components/collapsible-panel/test/collapsible-panel.test.js
When collapsible panels are arranged in a group, and they're of type "inline", then one of the borders between the items is "collapsed" (i.e. hidden), except for the last item.
This is currently accomplished with a `slotchange` event on the group which then iterates over the items and based on the type of the first item, sets a reactive state property on each one to potentially hide some borders.
When using these in the LMS however, because things can be slower there I noticed that often (always) the `slotchange` event fired _before_ the panels had even initialized their properties, so the borders were never hidden. Another issue is that if the type changed to `inline` (or from `inline`) later, the `slotchange` event wouldn't fire and the borders would be incorrect.
This change updates …
=> GAUD-7584: collapsible panel borders when inline status changes

components/tabs/demo/tabs.html, components/tabs/tab-mixin.js, components/tabs/tabs.js, components/tabs/test/tabs.test.js, components/tabs/test/tabs.vdiff.js
Part of [this Jira task](https://desire2learn.atlassian.net/browse/GAUD-7483)
This adds the slots for `d2l-tab` and `d2l-tab-panel` and handles them in a very basic way. All that is supported is the basic pairing of the tab and panel, as well as clicking on a tab to change.
Note that the vdiffs didn't actually change, I just created a way to more easily test both scenarios locally.
=> feat: Tabs: Add initial functionality for supporting d2l-tab/d2l-tab-panel

components/tabs/demo/tabs.html, components/tabs/tabs.js, components/tabs/test/tabs.axe.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7657)
Implements the [W3C Tabs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)
Adds the following which were not yet implemented from the bullet point list near the bottom of the page:
- Adds `aria-controls` to the tabs
- Adds `aria-label` to the `tablist` element. Note that we don't yet anticipate a usecase for a visible label at this point.
The `text` property would be required, but since it hasn't been until this point I have not yet added the required mixin to enforce this. I'll be going through all the usages of tabs, at which point I can add the `text` property as I go.
=> feat: Tabs: New Structure: Add aria-label to the tablist and aria-controls to the tab

components/button/button-icon.js, components/overflow-group/overflow-group.js, components/selection/selection-controls.js
I'm going to be making some fixes in these components and in order to simplify those changes it made sense to switch them to use CSS logical properties instead of the `RtlMixin`. Hopefully no vdiffs here.
=> GAUD-7676: switch to CSS logical properties

components/table/demo/table-test.js
Load-more paging in the table demo happens too quickly so the loading spinner doesn't have a chance to render.
=> GAUD-7676: add table loading delay for demo

components/empty-state/empty-state-action-button.js, components/empty-state/empty-state-action-link.js, components/empty-state/empty-state-illustrated.js, components/empty-state/empty-state-mixin.js, components/empty-state/empty-state-simple.js, components/empty-state/empty-state-styles.js, components/empty-state/test/empty-state-illustrated.test.js, components/empty-state/test/empty-state-simple.test.js
Thanks @KaiPrince for raising this.
When managing focus (especially when a list becomes empty for example), sometimes it's required to place focus on an empty state.
This fix makes both the simple and illustrated empty states focusable. Internally, they'll focus on the first action and fall back to the description text.
=> GAUD-7682: add ability for empty states to focus

components/card/card.js
[GAUD-7690](https://desire2learn.atlassian.net/browse/GAUD-7690)
This PR removes `d2l-card`'s hover vertical translation (-4px) because:
* The `transform` creates a containing block that interferes with `fixed` position dropdown calculations, and
* We prefer not to have it for aesthetic reasons
[GAUD-7690]: https://desire2learn.atlassian.net/browse/GAUD-7690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove translateY from d2l-card.

components/popover/popover-mixin.js
[GAUD-6564](https://desire2learn.atlassian.net/browse/GAUD-6564)
This PR fixes an issue where the dropdown would close if focus is moved to the opener, or would close and re-open if the user clicked the opener while the popover is open. This change makes the logic identical to the previous (non-popover) implementation which addresses this defective behaviour and maintains compatibility with the various dropdown openers.
For ref, the original impl: https://github.com/BrightspaceUI/core/blob/main/components/dropdown/dropdown-content-mixin.js#L573
[GAUD-6564]: https://desire2learn.atlassian.net/browse/GAUD-6564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix PopoverMixin auto-close handler to not close the popover if focusing on opener

components/button/button-styles.js, components/button/button.js
[GAUD-7681](https://desire2learn.atlassian.net/browse/GAUD-7681)
If buttons hide their borders -- like we do with ours -- then WHCM doesn't know to apply a border around them like it should. That results in this, where buttons just look like normal text:
Because adding a border can impact the height and width of buttons, we decided to only apply this change when we detect that a high-contrast mode is being used.
Result:
Note: I'll be fixing the fact that `<d2l-button-icon>`'s icon is grey with a separate fix.
Not expecting any vdiffs. 🤞 
[GAUD-7681]: https://desire2learn.atlassian.net/browse/GAUD-7681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: apply a border on buttons in WHCM

components/dropdown/dropdown-popover-mixin.js, components/popover/popover-mixin.js
[GAUD-6564](https://desire2learn.atlassian.net/browse/GAUD-6564)
This PR fixes and issue when using `PopoverMixin` for `d2l-dropdown-menu` content would be scrolled when opening with [spacebar] in Firefox. This event was delayed in the original implementation ([here](https://github.com/BrightspaceUI/core/blob/main/components/dropdown/dropdown-content-mixin.js#L639)), so this change maintains compatibility/timing for that event, which can be important for `d2l-dropdown-menu` and potentially other consumers.
[GAUD-6564]: https://desire2learn.atlassian.net/browse/GAUD-6564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Delay dispatching d2l-dropdown-open to fix Firefox scroll issue

components/inputs/demo/input-time.html, components/inputs/docs/input-date-time.md, components/inputs/input-time.js, components/inputs/test/input-time.test.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7697)
Adding the option to hide the time zone on the dropdown selection when the input's time zone does not match the one set by the document.
=> feat: Add `timezone-hidden` attribute

mixins/visible-on-ancestor/visible-on-ancestor-mixin.js
[GAUD-7690](https://desire2learn.atlassian.net/browse/GAUD-7690)
This PR fixes a dropdown flicker due to the VOA hide `transform` that is applied when a user dismisses the VOA dropdown via soft-close. The VOA `transform` would create a containing block during the animation, resulting in the browser briefly repositioning the dropdown within that new containing block.
Discussed with Jeff and we agreed to remove the `transform` translation when hiding the VOA items. We're keeping the translation when showing VOA items since dropdowns cannot be open during that animation. We're also keeping the `opacity` animation while hiding VOA items since it does not create a containing block. This keeps the code relatively simple and still provides a nice animated experience.
Other options considered:
* …
=> Fix dropdown reposition flicker that results from voa hide transform

components/dropdown/dropdown-content-mixin.js, components/dropdown/test/dropdown-content.test.js
[GAUD-6658](https://desire2learn.atlassian.net/browse/GAUD-6658)
This `--d2l-dropdown-verticaloffset` property is no longer supported since we switched to fixed positioning. Consumers are expected to use the `vertical-offset` attribute/property if they need a custom offset.
[GAUD-6658]: https://desire2learn.atlassian.net/browse/GAUD-6658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean up unsupported --d2l-dropdown-vertical-offset property

components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js
[GAUD-7745](https://desire2learn.atlassian.net/browse/GAUD-7745)
This PR fixes an issue where mobile dialog content would become unscrollable after dismissing a nested mobile dropdown. This issue can be observed in our demo pages, but more importantly, the My Courses widget. It removes the code that was added in [this PR](https://github.com/BrightspaceUI/core/pull/4234) to address a Safari clipping issue - I have confirmed that this is no longer an issue for us.
This broken scroll behaviour was the result of our fix setting `overflow: hidden` on the dialog content while the mobile dropdown was open, but never actually removing it when the dropdown is dismissed.
[GAUD-7745]: https://desire2learn.atlassian.net/browse/GAUD-7745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> Remove previous Safari fix that causes mobile dropdown content to become unscrollable

helpers/mathjax.js
Backport of this PR: https://github.com/BrightspaceUI/core/pull/5493
While this issue is at minimum a couple years old, it looks like there's a need to pull it back to the previous release.
=> SHIELD-10825 - Convert none elements in MathML sub/superscripts to mrow so they properly render

components/inputs/input-fieldset.js, components/inputs/test/input-fieldset.test.js
[GAUD-7757](https://desire2learn.atlassian.net/browse/GAUD-7757)
While investigating how to solve spacing between fields/inputs, I noticed some places using `<d2l-input-fieldset>` but not providing a label. This is going to result in an empty `<legend>` and really defeats the purpose of using it in the first place.
Separately I'm going to go through the places that weren't using this correctly and fix them.
[GAUD-7757]: https://desire2learn.atlassian.net/browse/GAUD-7757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: require label on fieldset

components/menu/menu-item-mixin.js, components/menu/menu-item-return.js
[GAUD-7763](https://desire2learn.atlassian.net/browse/GAUD-7763)
This PR eliminates most of the menu-item warnings by moving several updates to `willUpdate`:
> Element d2l-menu-item scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.
There is still one instance of this warning that arises with nested menus, which I think is unavoidable (at least without more significant changes) because the parent menu-item `slot` needs to be rendered before it can determine if there are child-views.
[GAUD-7763]: …
=> Update menu-items to avoid some inefficient updates

components/tag-list/tag-list-item-mixin.js, components/tag-list/test/tag-list-item-mixin-consumer.js
[GAUD-7768](https://desire2learn.atlassian.net/browse/GAUD-7768)
Updates `TagListItemMixin` to use CSS logical properties.
[GAUD-7768]: https://desire2learn.atlassian.net/browse/GAUD-7768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cleanup tag-list-item RTL styles.

components/tabs/README.md
[Jira task](https://desire2learn.atlassian.net/browse/GAUD-7488)
The space at the end of the comment block is causing the build to fail here: https://github.com/BrightspaceUI/documentation/pull/1938
I haven't dug into why. There's other cases where we have the space, but I believe all those cases are the `demo code properties name` style.
=> fix: Tabs docs: Remove space causing docs site build error

components/dialog/demo/dialog.html, components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js
[GAUD-7784](https://desire2learn.atlassian.net/browse/GAUD-7784)
This PR adds the `no-content-scroll` property/attribute to `DialogMixin` to give consumers the ability to turn off the content scrollbar. The primary motivation is to avoid potential scrollbar flickering while they are changing dialog contents and resizing. 
As shown in the demo, they apply `no-content-scroll`, make their changes, call the dialog's `resize()` method, and then remove `no-content-scroll`.
In testing, the scrollbar flickering is not consistent. It happens maybe 10-25% of the time.
[GAUD-7784]: https://desire2learn.atlassian.net/browse/GAUD-7784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add no-content-scroll property to DialogMixin

components/form/demo/form-demo.js, components/inputs/input-date-time.js, components/inputs/test/input-date-time.test.js
[GAUD-7790](https://desire2learn.atlassian.net/browse/GAUD-7790)
This PR fixes a JavaScript error that would happen in `d2l-date-time`'s `validate()` method when validating a `form`. The root cause of this error is that the `d2l-input-time` is `null` if the user has not selected a date, resulting in a JavaScript error when trying to call `validate()` on it. This error would occur regardless of whether the input is required.
[GAUD-7790]: https://desire2learn.atlassian.net/browse/GAUD-7790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix d2l-input-date-time validation (JavaScript error)

components/inputs/input-checkbox.js, components/inputs/test/input-checkbox.test.js
[GAUD-7778](https://desire2learn.atlassian.net/browse/GAUD-7778)
With the introduction of the new `supporting` slot for checkbox inputs, there are some use cases where they're nesting other checkboxes or inputs inside that slot. When those components fire their own `change` events, it propagates up and appears to originate from the checkbox itself. That often causes consumers to flip the state of the checkbox, which isn't what we want!
[GAUD-7778]: https://desire2learn.atlassian.net/browse/GAUD-7778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: prevent change events within supporting slot from propagating

components/offscreen/offscreen.js, components/overflow-group/overflow-group-mixin.js
[GAUD-7802](https://desire2learn.atlassian.net/browse/GAUD-7802)
* The `d2l-offscreen` component extends `RtlMixin` but it doesn't need to (since https://github.com/BrightspaceUI/core/pull/4192)
* The `OverflowGroupMixin` includes the `offscreenStyles` (i.e. `d2l-offscreen` CSS class) but it doesn't use them
* The `OverflowGroupMixin` extends `RtlMixin` when it doesn't need to
[GAUD-7802]: https://desire2learn.atlassian.net/browse/GAUD-7802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin usage that is not needed anymore.

components/filter/test/filter.axe.js, components/list/list-item-generic-layout.js, components/list/list-item-mixin.js, components/list/list-item-role-mixin.js, components/list/list.js, components/list/test/list-item-role-mixin.test.js, components/list/test/list.axe.js
[GAUD-7712](https://desire2learn.atlassian.net/browse/GAUD-7712)
This PR updates the list components to use the correct `row` and `gridcell` roles as per Aria guidelines. It does not update to use the `grid` role (we're still using `role="application"`) due to Safari+VO ignoring the grid content (See [Webkit Issue](https://bugs.webkit.org/show_bug.cgi?id=291591)), which can be reproduce in the Lit Playground [here](https://lit.dev/playground/#project=W3sibmFtZSI6ImdyaWQtY29tcG9uZW50cy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcblxuY2xhc3MgVGVzdEdyaWQxIGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cdHJlbmRlcigpIHtcblx0XHRyZXR1cm4gaHRtbGBcblx0XHRcdDxkaXYgcm9sZT1cImdyaWRcIj5cblx0XHRcdFx0PHNsb3Q-PC9zbG90PlxuXHRcdFx0PC9kaXY-XG5cdFx0YDtcblx0fVxufVxuY3VzdG9tRWxlbWVudHMuZGVmaW5lK …
=> Update list grid mode to use row and gridcell roles.

components/alert/alert-toast.js, components/alert/test/alert-toast.axe.js
[GAUD-7279](https://desire2learn.atlassian.net/browse/GAUD-7279)
This PR moves the `role="alert"` from the host element `d2l-alert-toast` to the internal `d2l-alert`.
I tried lots of other options, some improved one browser but completely broke another browser. Overall this is an improvement, albeit still not perfect. The use of `role="alert"` is apparently extremely finicky, as described in Margaree's Jira comments.
These are my test results, with reduced motion preference both on/off.
Announcement before:
```
chrome+vo - not announced
safari+vo - not announced
firefox+vo - 1x text; 2x close
chrome+nvda - 3x text; 5x close
edge+nvda - 3x text; 5x close
firefox+nvda - 1x text; 1x close
```
Announcement after:
```
chrome+vo - 1x text; 1x close (improved)
safari+vo - 1x text; 2x close …
```
=> Move toast's alert role to d2l-alert for improved announcement ux.

components/dialog/dialog-fullscreen.js
Not tied to the wording here at all, suggest away!
This property is not on the dialog README - see my question in our team slack thread on whether we care about this or not.
=> GAUD-7836 - Update width docs for dialog-fullscreen

components/inputs/test/input-time.vdiff.js
Locally this test works fine, but we've seen lots of flake in CI.
=> GAUD-7838 - Fix input-time Flake

components/list/list-item-button-mixin.js, components/list/list-item-link-mixin.js, components/list/test/list.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7846)
**Problem**:
Recent work to list items ([here](https://github.com/BrightspaceUI/core/pull/5520)) impacted the `click` event such that it is now dispatched from the content rather than the list-item. This is because of the removal of `pointer-events: none` on the content. The event target is now the content being clicked rather than the list item (e.g., `d2l-list-item`) and so any consumer relying on getting the top-level list item as the click event target would no longer work as expected.
Consumers should be listening for `d2l-list-item-button-click` and `d2l-list-item-link-click` but that pattern is not always being followed.
**Solution Summary**:
When the click was on the list item (not an interactive element with in …
=> fix: List item: Dispatch click event from ListItemLinkMixin and ListItemButtonMixin to maintain previous functionality in consumers

components/html-block/README.md, components/html-block/demo/html-block-code.html
Just fixing up a couple places where the html-block demo had mangled output. In one case this was due to a bad configuration, and in the others it was due to malformed encoding of various kinds.
=> SHIELD-11083 - Fix html-block demo samples

components/calendar/README.md, components/calendar/calendar.js, components/calendar/test/calendar.test.js
SHIELD-11093
This method returns the shown year and month as an object instead of converting it to an ISO date string.
Converting the date to UTC was problematic for timezones with a positive offset from UTC, resulting in code thinking that the month being shown was off by a month.
=> fix: Add method to return year and month as object

mixins/localize/localize-mixin.js, mixins/localize/test/localize-mixin.test.js, package-lock.json
[GAUD-7785](https://desire2learn.atlassian.net/browse/GAUD-7785): Make pseudo-l10n work in our Internationalization (i18n) methods
Because component instances need to share resources, we need to set up `pseudoLocalization` slightly differently from the base class in `intl`.
Depends on [@brightspaceui/intl](https://github.com/BrightspaceUI/intl/pull/248)
[GAUD-7785]: https://desire2learn.atlassian.net/browse/GAUD-7785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add pseudoLocalization

components/inputs/input-text.js
The issue raised was for `d2l-input-number`, but that uses `d2l-input-text` under the hood. The invalid tooltip will no longer appear on hover if the input is disabled after it becomes invalid.
I tried adding a test for this, but it was pretty slow because I needed to wait long enough to confirm the tooltip does or does not show and I wasn't confident it wouldn't flake.
=> GAUD-7848 - Stop invalid tooltip from appearing when the input-text becomes disabled

components/tooltip/tooltip.js
[GAUD-7903](https://desire2learn.atlassian.net/browse/GAUD-7903)
It is possible (at least from the demo) for the content to still be null when trying to initially update the position when `force-show` is used. 
[GAUD-7903]: https://desire2learn.atlassian.net/browse/GAUD-7903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix possible tooltip JavaScript error when force-show is used.

components/inputs/docs/input-radio.md
GAUD-7815
I removed this demo with the new radio input stuff, but the Daylight Site breaks now trying to import it. This just fixes up this particular demo -- I'm still in the process of rewriting the rest of the docs in this file.
=> fix: imports for Daylight Site demo

components/inputs/README.md, components/inputs/docs/input-checkbox.md, components/inputs/docs/input-radio.md, components/inputs/docs/styling-native-inputs.md, components/inputs/input-radio-group.js
[GAUD-7783](https://desire2learn.atlassian.net/browse/GAUD-7783)
Now that checkbox groups and the new radio inputs/group components exist, this aligns their documentation. It will require a couple minor corresponding changes in the Daylight Site when this change gets picked up.
[GAUD-7783]: https://desire2learn.atlassian.net/browse/GAUD-7783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improve checkbox/radio documentation

components/inputs/docs/input-color.md, components/inputs/docs/input-date-time.md, components/inputs/docs/input-numeric.md, components/inputs/docs/input-search.md, components/inputs/docs/input-text.md, components/inputs/docs/styling-native-inputs.md, components/inputs/input-text.js
[GAUD-7783](https://desire2learn.atlassian.net/browse/GAUD-7783)
The changes are mostly focused on text/textarea documentation alignment, but because I don't intend to touch the other input docs (just generic form/layout ones), I'm aligning them here too.
This will require some small tweaks to the Daylight SIte to align the titles and imports.
[GAUD-7783]: https://desire2learn.atlassian.net/browse/GAUD-7783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: align input documentation

components/list/demo/demo-list-nav.js, components/list/demo/list-demo-scenarios.js, components/list/demo/list-nested.html
Part of [this Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7928)
Does the following:
- Improves on existing demos based on Mark's feedback (padding around tooltip-help, improve tooltip-help content)
- Adds a more complex demo that implements nested drag & drop (and removes draggable from the simple demo since it isn't actually working)
=> List item nav > Add more complex example

components/filter/test/filter.vdiff.js, components/inputs/input-date-time-range-to.js, components/inputs/test/input-date-time-range.vdiff.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7959)
**Problem:**
cds-session-management-ui was experiencing ResizeObserver undelivered notification errors. We generally can ignore this error, but I thought I'd try to get rid of it.
**Solution Notes:**
This debounces the ResizeObserver parent change callback in date-time-range-to. I did find that was only necessary to do this to one of the resizeobservers to get rid of the error in cds-session-management-ui, and also it went away if the timeout was 0. Having it 5 seems to not be perceptible visually, while also reducing the number of calls by about a third.
Let me know any thoughts or if my logic is totally flawed here.
=> fix: date-time-range-to: debounce resizeobserver callback calls

components/collapsible-panel/collapsible-panel.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7700)
Use inherited color for chevron on WHCM. 
Before:
Fix:
=> fix: collapsible panel chevron grey in WHCM

components/typography/styles.js, components/typography/typography.js
This removes one copy of our "blockquote" styles (used [in all of 3 places!](https://github.com/search?q=saved%3AD2L+%22blockquotestyles%22&type=code&saved_searches=%5B%7B%22name%22%3A%22D2L%22%2C%22query%22%3A%22org%3ABrightspace+OR+org%3ABrightspaceUI+OR+org%3ABrightspaceUILabs+OR+org%3ABrightspaceHypermediaComponents%22%7D%5D&expanded_query=org%3ABrightspace+org%3ABrightspaceUI+org%3ABrightspaceUILabs+org%3ABrightspaceHypermediaComponents+%22blockquotestyles%22)) by centralizing them into a generator function and adopting CSS logical properties.
=> GAUD-6540: share blockquote styles

components/colors/colors.js, components/typography/styles.js, eslint.config.js, package-lock.json, package.json
GAUD-6540
No sooner than I removed one use of `document` than I introduced another! 🤦 
This introduces a new linting rule for core that prevents us from referring to the `document` global and anytime we use `window.something` will complain that we should use `globalThis` instead. I'm limiting this to just the 3 files that get imported from `typography/styles.js` as that's all BSI will currently care about, but we could expand it if needed.
=> fix: prevent referring to "document" or "window"

components/menu/demo/menu.html, components/menu/menu-item-mixin.js, components/menu/menu.js, components/menu/test/menu.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7938)
**Problem:**
In Chrome or Safari on the menu demo page:
1. Tab into a menu
2. Arrow key down to a non-first item
3. Press tab; note that focus goes to the first item of the list
**Expected Behaviour:**
Pressing tab would go to the next focusable item in the document.
**Solution Notes:**
This bug is strange. It seems that there can be a browser expectation that when an item is receiving keyboard focus it should also have a tabindex of 0. I noticed a w3c pattern that follow this solution behaviour.
=> fix: Menu: Move tabindex around to correspond with focus

components/collapsible-panel/collapsible-panel.js, components/collapsible-panel/test/collapsible-panel.test.js, components/collapsible-panel/test/collapsible-panel.vdiff.js
New strategy for [this Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-7882)
**Problem:**
NVDA and JAWS treat enter on a button as a click. With the new focus implementation, `this._clicked` was being set to `true` and so the `focused` class wasn't being added.
**Solution notes:**
This adds a tab event listener, as used in other places like tag-list. When focus occurs, it checks for if it was a tab focus and then adds the `focused` class. It also keeps `focused` if the button blurs due to a click on the header.
=> fix: Collapsible-panel: Fix focus-visible with NVDA

components/inputs/input-checkbox.js, components/inputs/input-label-styles.js, components/inputs/sass/label.scss, components/tooltip/tooltip.js, components/typography/styles.js, components/typography/typography.js, components/typography/typography.scss
GAUD-8015
The presence of this flag is making some of the typography Sass removal much more difficult, and in some places impossible. So removing it a bit earlier than we normally would.
Related:
- https://github.com/Brightspace/lms/pull/67211
- https://github.com/Brightspace/lms-launch-darkly-flags/pull/18149
=> fix: remove 'input-style-tweaks' flag from code

components/typography/typography.scss
[GAUD-7274](https://desire2learn.atlassian.net/browse/GAUD-7274): Support Thai fonts
In #5690 I did a copy-paste whoopsie-doodle and made Thai use the Japanese font in the sass file.
[GAUD-7274]: https://desire2learn.atlassian.net/browse/GAUD-7274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Thai font in sass file

components/menu/menu-item-mixin.js, components/menu/menu.js, components/menu/test/menu-item-checkbox.test.js, components/menu/test/menu-item-mixin.test.js, components/menu/test/menu-item-radio.test.js, components/menu/test/menu.axe.js, components/menu/test/menu.test.js
GAUD-8044
This throws errors if `<d2l-menu>` isn't provided a `label`, although nested menus get their label automatically from the parent `<d2l-menu-item>` so they are exempt. Similarly, `<d2l-menu-item>` now requires that `text` be set.
=> fix: require that menu be provided a label and menu-item be provided text

components/inputs/demo/input-select-test.js, components/inputs/input-select-styles.js, components/typography/styles.js
GAUD-8056
With the [recent WHCM fixes](https://github.com/BrightspaceUI/core/pull/5653) to `<select>`s , we updated the padding to use CSS logical properties while the background image for the chevron needed to continue to rely on `:host([dir="rtl"])` styles.
That meant that components using `selectStyles` needed to extend `RtlMixin`. This was always true, but by doing things both ways, any places not extending `RtlMixin` would now have the chevron positioned in the wrong spot but the padding in the correct spot.
Requiring consumers to extend `RtlMixin` was always less than ideal, and our docs don't even mention it. So this takes a different approach by leveraging a CSS variable set in our typography styles -- similar to what we've done for other things.
~This will initially fail vdiffs …
=> fix: update select styles to not require RtlMixin

components/inputs/docs/input-radio.md
GAUD-7815
Realized while writing the SotUI that this should be `value` not `name`.
=> fix: radios have values not names

components/object-property-list/README.md, components/object-property-list/object-property-list-item-tooltip-help.js, components/tooltip/README.md, components/tooltip/tooltip-help.js
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8023)
Add documentation for `d2l-object-property-list-item-tooltip-help`.
Add documentation for icon support on `d2l-tooltip-help`
=> fix: update docs for OPL help tooltip item

components/button/README.md
Trying to propose these changes to the buttons README, but not sure if it's going to work. I have to create a new branch, but not sure if I can do that without adding new SSH keys.
I also have some questions about these links I added to the buttons README file:
"Don’t use toggle buttons for unrelated actions, navigation, or as form inputs — use [checkboxes](../../components/checkbox-input) or [radio buttons](../../components/radio-inputs) for form selection"
* These don’t seem to exist on git like they do on the daylight site
"Consider using a [Split Button](../../components/button/#d2l-button-split) if there are several related actions (such as Save, Save As...)"
* Is it possible to link to an anchor on the page? Doesn’t work in the README file (goes to the main buttons directory)
=> GAUD-7381: Update README.md

components/list/list-item-generic-layout.js, components/list/test/list-item-generic-layout.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8229)
Problem:
Focus keyboard behaviour isn't working as expected in the previous direction (up arrow, page up) when there is a nested list that is closed.
Solution Notes:
This uses the same logic as in `_getNextFlattenedListItem` above to determine if the nested list should actual be looked in for determining the prior element.
To do:
=> fix: List: Focus on the correct item when focusing previous and previous item is nested but not visible

helpers/mathjax.js
Straightforward flag removal here. The flag populating this context parameter is being removed this release and this behaviour is becoming the default.
=> SHIELD-11830 - Remove WIRIS sub/superscripts feature flag (defaulting on)

mixins/localize/localize-mixin.js
[GAUD-8136](https://desire2learn.atlassian.net/browse/GAUD-8136): Call `Object.freeze` on localize resources to prevent unsafe hacking
Prevents hacking `localizeMarkup` objects to inject unsupported tags. This appears to already be at least partially the case for `html` templates, but we lose the freeze when we spread it into our new object.
[GAUD-8136]: https://desire2learn.atlassian.net/browse/GAUD-8136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Freeze localizeMarkup object

components/list/demo/demo-list-nav.js, components/list/demo/demo-list-nested.js, components/list/list-item-mixin.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8190)
The timeouts still weren't behaving reliably. This follows the pattern dialog uses and adds a `waitForUpdateComplete` which checks for children being loaded. The drag & drop demo then waits for that in the moved list item before activating the drag handle. In local testing this seems to be working reliably.
=> fix: List item drag & drop: Show handle on nesting change

components/tabs/tab.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8304)
The `text` property was used as the `title` in the old tab/tab-panel structure [here](https://github.com/BrightspaceUI/core/blob/main/components/tabs/tab-internal.js#L147) but did not get used with the new structure. This causes a problem when there is text past the max-width as it is not able to be seen in any way. 
It was discussed [here](https://github.com/BrightspaceUI/core/pull/5224#discussion_r1890322445) as to why this should not live in the mixin, so I have it being rendered in the tab component itself in the same way it was being rendered previously.
Note that this is not flagged because the new tab structure is not yet in use, other than the MVC backport which itself is flagged.
=> fix: Tab: Add title

components/tag-list/tag-list.js, lang/ar.js, lang/cy.js, lang/da.js, lang/de.js, lang/en-gb.js, lang/en.js, lang/es-es.js, lang/es.js, lang/fr-fr.js, lang/fr.js, lang/haw.js, lang/hi.js, lang/ja.js, lang/ko.js, lang/mi.js, lang/nl.js, lang/pt.js, lang/sv.js, lang/tr.js, lang/zh-cn.js, lang/zh-tw.js
[GAUD-5257](https://desire2learn.atlassian.net/browse/GAUD-5257)
This PR adds the tag list count to the custom role description as desired. As such, the count will be announced when the browser/screen-reader announces the role context.
[GAUD-5257]: https://desire2learn.atlassian.net/browse/GAUD-5257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update tag-list role description to include the list count.

components/tabs/tab-mixin.js, components/tabs/test/tabs.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8285)
Mark noticed when testing that if a tab was selected it would still fire the `d2l-tab-before-selected` event on click. This could lead to unintended impacts if consumers are relying on the event actually happening before selection rather than when already selected (e.g., in the LMS it could lead to duplicate page loads)
=> fix: Tabs: Do not dispatch d2l-tab-before-selected if tab is already selected

components/tabs/demo/tabs-array.js, components/tabs/demo/tabs.html, components/tabs/tab-mixin.js, components/tabs/tabs.js, components/tabs/test/tabs.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8109)
**Problem**:
When tab/tabpanels are generated from an array, if a tab is deselected via the array then the panel does not get deselected. This is because when the loop happens to deselect the panel [here](https://github.com/BrightspaceUI/core/blob/main/components/tabs/tabs.js#L1246) the previously selected tab already has `selected` set to false.
This was found to be an issue during the my-courses backport due to the tabs being rendered based on an array which specifies `selected` state ([here](https://github.com/Brightspace/d2l-my-courses-ui/blob/master/src/d2l-my-courses-container.js#L113)). The problem would result in showing the tab panel contents of any tab that had been selected within a single tab panel.
We could …
=> fix: Tabs: Tab/Tabpanel structure: Deselect panel when tab array de-selects tab

components/scroll-wrapper/demo/scroll-wrapper.html, components/scroll-wrapper/scroll-wrapper.js, components/table/demo/table.html
[GAUD-8353](https://desire2learn.atlassian.net/browse/GAUD-8353)
This PR updates `d2l-scroll-wrapper` to layout for print using a media-query only. Importantly, this avoids an async Lit update to re-layout, which is problematic because `window.print()` blocks JavaScript execution while the print dialog is open. Lit's async update cycle doesn't run in time.
The best practice should be to rely on a media-query alone, and _not_ rely on an async Lit update to re-layout the component for printing. It is possible to leverage the `beforeprint` / `afterprint` events, but again, the code must be synchronous. If we encounter cases where we really do need to wait for Lit's async life cycle to run before printing, we can wrap `window.print()` and manage the updates so that we don't call it until all …
=> Update d2l-scroll-wrapper to no require an async update layout for print

components/overflow-group/demo/demo-overflow-group.js, components/overflow-group/demo/overflow-group.html
We don't have to merge this if we don't think it's useful, but this reproduces the `d2l-overflow-group` issue I mentioned in standup.
=> GAUD-8414 - Adding a demo to demonstrate `d2l-overflow-group` using Lit comments and spaces as the text for the chomped buttons

mixins/loading-complete/README.md, mixins/loading-complete/loading-complete-mixin.js
We recently ran into an issue where resolveLoadingComplete was not called for a certain component state and found it would be valuable to trace back to the component where a promise has been left hanging
Ideally this message should only print in dev, though having this make it out into the wild may indicate other performance/usability issues.
=> MAN-4282: Add panic timer to LoadingCompleteMixin

components/breadcrumbs/breadcrumb.js, components/breadcrumbs/breadcrumbs.js
[GAUD-8429](https://desire2learn.atlassian.net/browse/GAUD-8429)
Update `d2l-breadcrumbs` and `d2l-breadcrumb` to use CSS logical properties instead of `RtlMixin`, etc.
[GAUD-8429]: https://desire2learn.atlassian.net/browse/GAUD-8429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from breadcrumbs.

components/button/button-add.js, components/typography/styles.js
[GAUD-8430](https://desire2learn.atlassian.net/browse/GAUD-8430)
This PR updates `d2l-button-add` to use CSS logical properties instead of `RtlMixin`, etc.
[GAUD-8430]: https://desire2learn.atlassian.net/browse/GAUD-8430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-button-add.

components/overflow-group/demo/demo-overflow-group.js, components/overflow-group/overflow-group.js, components/overflow-group/test/overflow-group.test.js
Putting this up for early review, will look at adding some tests.
Currently, `d2l-overflow-group` doesn't work with a `d2l-button` using `this.localize` - when chomped, it grabs the Lit comment as the first node:
This filters out comment nodes (and empty text nodes - do we want this?).
I'm currently not flagging this because:
1. The product running into this bug can't use our feature flags, as far as I know. It's also not released yet.
2. From what I can tell, this is not currently an issue anywhere. It only happens for `d2l-button` or `button` (`d2l-button-subtle`, `d2l-button-icon`, and `d2l-selection-action` have `text` values that are used). There are only a few uses of `d2l-overflow-group`, and they either use `subtle-button` or are in the LMS (which doesn't use `localize`, so no Lit …
=> GAUD-8414 - Fix d2l-overflow-group using localize with d2l-button

components/paging/pager-load-more.js
[GAUD-8442](https://desire2learn.atlassian.net/browse/GAUD-8442)
This PR removes the `RtlMixin` from `d2l-pager-load-more`. It was no longer needed since `offscreenStyles` were previously updated to use CSS logical properties.
[GAUD-8442]: https://desire2learn.atlassian.net/browse/GAUD-8442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-pager-load-more.

components/form/form-errory-summary.js
[GAUD-8438](https://desire2learn.atlassian.net/browse/GAUD-8438)
This PR removes `RtlMixin` from `d2l-form-error-summary`.
[GAUD-8438]: https://desire2learn.atlassian.net/browse/GAUD-8438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-form-error-summary

components/calendar/calendar.js
[GAUD-8431](https://desire2learn.atlassian.net/browse/GAUD-8431)
This PR removes `RtlMixin` from `d2l-calendar`. All of the `dir` dependencies were for keyboard interaction and setting animation in JavaScript. As such, this value is not needed until the user interacts, and we can simply use `document.documentElement.getAttribute('dir')` when the value is needed (this is the same approach we took for popover positioning).
[GAUD-8431]: https://desire2learn.atlassian.net/browse/GAUD-8431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-calendar.

components/dropdown/dropdown-button.js
[GAUD-8467](https://desire2learn.atlassian.net/browse/GAUD-8467)
This PR removes RtlMixin from the `d2l-dropdown-button` opener.
[GAUD-8467]: https://desire2learn.atlassian.net/browse/GAUD-8467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-dropdown-button.

components/meter/meter-circle.js, components/meter/meter-linear.js, components/meter/meter-radial.js, components/meter/meter-styles.js
[GAUD-8441](https://desire2learn.atlassian.net/browse/GAUD-8441)
This PR removes `RtlMixin` from the meter components. It was being used to force the writing direction to `ltr` when fractions are rendered (i.e. not percent).
[GAUD-8441]: https://desire2learn.atlassian.net/browse/GAUD-8441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from meter components.

components/dialog/dialog-fullscreen.js, components/dialog/dialog-mixin.js, components/dialog/dialog-styles.js, components/dialog/dialog.js
[GAUD-8435](https://desire2learn.atlassian.net/browse/GAUD-8435)
This PR removes `RtlMixin` from `DialogMixin` and the core dialog components.
There are [additional usages](https://search.d2l.dev/search?project=Brightspace&project=BrightspaceHypermediaComponents&project=BrightspaceUI&project=BrightspaceUILabs&project=D2L-LCS&project=lms&full=%22DialogMixin%28%22&defs=&refs=&path=&hist=&type=&xrd=&nn=6&si=full&si=full) of `DialogMixin` that will need to be switched to CSS logical properties before this can be merged, since they unfortunately assume that `DialogMixin` is including the `RtlMixin`.
[GAUD-8435]: https://desire2learn.atlassian.net/browse/GAUD-8435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from DialogMixin and dialog components.

components/scroll-wrapper/scroll-wrapper.js
[GAUD-8443](https://desire2learn.atlassian.net/browse/GAUD-8443)
This PR removes the `RtlMixin` from `d2l-scroll-wrapper`.
[GAUD-8443]: https://desire2learn.atlassian.net/browse/GAUD-8443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from d2l-scroll-wrapper.

components/scroll-wrapper/demo/scroll-wrapper-test.js, components/table/demo/table-test.js, helpers/demo/prism.html
[GAUD-8483](https://desire2learn.atlassian.net/browse/GAUD-8483)
This PR removes some `RtlMixin` usage from some test files.
[GAUD-8483]: https://desire2learn.atlassian.net/browse/GAUD-8483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from some test stuff.

helpers/focus.js
BSI needs to be able to get these focus ring styles outside of a browser context (at build time). This new CSS-only method supports that, and still falls back to `focus` styles in older browsers.
My plan is to flag this, but let BSI override that flag so it'll get the new styles every time. It means we'll be able to flag some of it, which feels better than none of it.
=> GAUD-8589 - Switch focus-visible to a CSS-only solution

components/link/link-styles.js, components/link/link.js, components/typography/styles.js, components/typography/test/styles.test.js, helpers/focus.js, helpers/internal/css.js
Exposing a method for BSI to use to get the link styles used by the component, rather than the [Sass file](https://github.com/BrightspaceUI/core/blob/a989989114bbf0a0649116b4c2fd285c820ae6ef/components/link/link.scss).
This copies the same pattern that [`typography` uses](https://github.com/BrightspaceUI/core/blob/a989989114bbf0a0649116b4c2fd285c820ae6ef/components/typography/styles.js).
BSI PR is here: https://github.com/Brightspace/brightspace-integration/pull/15610
=> GAUD-7874 - Expose link styles for BSI to use

components/calendar/README.md, components/inputs/docs/input-date-time.md, components/inputs/input-date-range.js, components/inputs/input-date-time.js, components/inputs/input-time-range.js, components/inputs/input-time.js, components/inputs/test/input-date-time-range.test.js, components/inputs/test/input-date-time.test.js, components/inputs/test/input-time.test.js, components/inputs/test/input-time.vdiff.js, helpers/test/dateTime.test.js, package-lock.json
- Adjusts #6081 for actual `intl` implementation ([@brightspaceui/intl](https://github.com/BrightspaceUI/intl/pull/273))
- Moves "timezone" to "time zone" where possible
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-8587)
=> Adjust for actual intl implementation

templates/primary-secondary/primary-secondary.js
Noticed this while spiking into templates. This has been there since the template was first written, and the browsers have just been  handling it. Shouldn't result in any changes.
=> fix: GAUD-8660 - Swap div and slot closing tags in the primary-secondary template footer

helpers/mathjax.js
Someone has decided that we don't, in fact, want this delayed until 20.25.11. 🙃
=> SHIELD-12869 - Default MathJax context feature to true for non-LMS contexts

components/tabs/demo/tabs.html, components/tabs/tab-mixin.js, components/tabs/test/tabs.test.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8605)
FYI @dlockhart 
**Problem**:
On initial load, the `d2l-tab-selected` event gets fired. This is potentially an issue if the consumer has specified `selected` and yet nothing new has been `selected`. I did keep the event firing on initial load if the tabs component itself is selecting which tab is `selected`.
This is consistent with the legacy behaviour where `d2l-tab-panel-selected` also fired on load. There could be consumers relying on this behaviour. Since the backport is still in progress there aren't many using this event yet, but I'll be testing them all out just in case.
Let me know thoughts on this. On one hand it makes sense to me to not fire an event when the state hasn't actually changed. On the other hand, if …
=> fix: Tab: Do not dispatch d2l-tab-selected on initial load if consumer specified selected

helpers/mathjax.js
I guess we also need these changes back in 20.25.9. 🤷 
This is an amalgamation of these two PRs: https://github.com/BrightspaceUI/core/pull/6100, https://github.com/BrightspaceUI/core/pull/6134
=> SHIELD-12881 - Backport changes to 20.25.9

components/list/list-item-expand-collapse-mixin.js, components/list/list-item-mixin.js
[GAUD-8691](https://desire2learn.atlassian.net/browse/GAUD-8691)
This PR clean up `RtlMixin` from `ListItemMixin` and `ListItemExpandCollapseMixin`.
[GAUD-8691]: https://desire2learn.atlassian.net/browse/GAUD-8691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove RtlMixin from ListItemMixin.

components/popover/popover-mixin.js
[GAUD-8718](https://desire2learn.atlassian.net/browse/GAUD-8718)
This PR updates the `PopoverMixin` wire-up of media-query handlers to be earlier, like `DropdownContentMixin`. I was optimistic in deferring this until the popover is opened, however the [opener code](https://github.com/BrightspaceUI/core/blob/main/components/dropdown/dropdown-opener-mixin.js#L234) relies on knowing the mobile mode when determining whether to open the popover when `open-on-hover` is being used. 
This fix is needed to address [this diff](https://github.com/BrightspaceHypermediaComponents/users/pull/494/files#r2394857904) using the new popover.
[GAUD-8718]: https://desire2learn.atlassian.net/browse/GAUD-8718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Wire up popover media-query handlers like old dropdown content mixin.

components/list/list-item-drag-drop-mixin.js
[Jira ticket](https://desire2learn.atlassian.net/browse/GAUD-8690)
**Problem**:
Drag & drop is currently broken on mobile. There's a console error about `setDragImage` not existing.
**Solution Notes**:
On mobile we simulate the drag and drop events so I believe there just isn't `setDragImage` available. Mobile dragging now works but there isn't a drag image. Not sure if there are thoughts on that or if we're okay with it just working.
=> fix: List item drag & drop: Check for setDragImage
