BrightspaceUI/core

components/typography/typography.js
index.html

The excluded (commented in code) style blocks contain mixins that we should deal with since the `@apply` is deprecated.  I will leave that for a future PR.  Two possible options (other ideas welcome!) are:
1. replace the mixins with global CSS properties.  Advantages: consumers have flexibility to exclude properties that are not needed for their use-case; consumers code is tidy.  Disadvantages: consumer may accidentally exclude a property; if changes are made to typography in the future, it will be a pain to update all the places.
2. factor the style selectors and associated properties out (from the font-faces) into one or more shared css templates that can be imported by consumers into their components, and have them use those class names in their local DOM.  Advantages: consumers don't …

Add typography.

---

index.html
package.json

This uses a simple little demo container that will render demo code with syntax highlighting sorta like the old Polymer demo-snippet.  Helpful for the time being, and we can pick out some of it's code if it's helpful once we decide what we want longer term for demos & docs.

Make demos a little more informative.

---

components/more-less/more-less.js

Otherwise I get the error `Uncaught SyntaxError: The requested module '../../../resize-observer-polyfill/dist/ResizeObserver.es.js' does not provide an export named 'ResizeObserver'`. Is this the correct order though?

fix ResizeObserver

---

components/button/button-subtle.js

I noticed that even when subtle button's `icon` attribute isn't set, the underlying `<d2l-icon>` was still getting rendered, just with no `icon` attribute itself.
This change only renders the icon if the attribute is set, saving us outputting a web component.

don't render icon if it's not set

---

components/demo/code-dark-plus-styles.js
components/demo/code-tomorrow-styles.js
components/demo/code-view-styles.js
components/demo/code-view.js
components/demo/demo-snippet-styles.js
components/demo/demo-snippet.js
demo/button/button-icon.html
demo/button/button-subtle.html
demo/icons/icon.html
demo/more-less/more-less.html
demo/styles.css

This moves the "code-view" code out of `d2l-demo-snippet` into a new `d2l-code-view` so that it can be used for more than just demoing and formatting HTML.  The `d2l-code-view` is configured to support `html`, `javascript`, `css`, `json`, and `bash`/`shell`.  We can configure it to load other language grammars if the need arises (Prism supports 176 languages).

Refactor d2l-demo-snippet so that code-view can be used for non-HTML code.

---

mixins/visible-on-ancestor-mixin.js

Lit was reflecting the `__voaState` property as the `__voastate` attribute, but the styles defined in this module where specifying `__voaState` (note the case difference).  All browsers except IE11 seemed to tolerate the difference.  This change makes explicitly specifies the attribute name to reflect, consistent with our existing pattern of separating with `-`, which results in exact CSS selector match for IE11.

Fix property/attribute name for visible-on-ancestor mixin.

---

components/meter/meter-linear.js
test/meter/meter-linear.visual-diff.html

I noticed an issue where the second box was using the `width: 100%` to the previous box that had an absolute position so it wasn't bounded. So with this change it is bounded by the `:host` that has the relative position.

Fixed progress bar not being limited to container

---

.travis.yml
components/button/button-subtle.js
package.json
test/button/button-icon.html
test/button/button-subtle.html
wct.conf-travis.json
wct.conf.json

Improve the contrast ratio for button text when button is hovered/focused.
`headless` was removed from running tests locally because of an issue with browser window focus causing `.focus()` to not run when `headless` and for the tests with `.focus()` to timeout. A travis wct config was added to run the tests headlessly, since they fail on travis when not run with `headless`.
I tried to use `MockInteractions.focus` here instead of `.focus()` but that seemed to not actually trigger the styles.

wcag: update button color when focus/hover

---

components/meter/meter-circle.js
mixins/localize-mixin.js
package.json

Edge:
Chrome:
I am still having issues where Edge and IE11 don't agree on how to position the text so as seen in the photo the text isn't quite in the middle.

Text for the d2l-meter-circle now shows up on edge and ie11

---

components/typography/styles.js
components/typography/typography.js

Mirrors [change in typography](https://github.com/BrightspaceUI/typography/pull/134). Will require new goldens.

labels should no longer have a responsive breakpoint

---

components/meter/meter-linear.js

Here is what happens with the text:
When text doesn't contain either {x/y} or {%} then it will move the text beside the number.
This is done to fit with the designs.
I also, switch to image route for screen reader support. NVDA and firefox don't support the progressBar role.
Out of scope:
Lang term for 'progress indicator'

Aria to work with NVDA and Firefox and Move text

---

package.json

`d2l-demo-snippet` depends on `d2l-code-view`, which depends on `prismjs`, so it needs to be a non-dev dependency in order to use these in other projects.

Fix code-view dependency.

---

components/icons/icon.js
directives/run-async.js
package.json

This PR uses the async rendering directive proposed by @justinfagnani, copied from his [runAsync PR](https://github.com/Polymer/lit-html/pull/657).  It cleans up the properties by avoiding the need for the private properties.  The rest of the logic is the same.
The async directive has potential use elsewhere with our hyper-media components, both for displaying alternative content while async state is pending, but also for visual-diff testing since the directive dispatches a promise-carrying event `pending-state`.
Per the directive comments, alternate views can be provided by the consumer for other states:
```
render() {
return html`${runAsync(this.icon ? this.icon : this.src, (term) => this._getIcon(term), {
success: (icon) => icon,
pending: () => 'Pending',
initial: () => 'Initial', …
```

Option 3 - Fix icon property update

---

components/icons/demo/icon.html
components/icons/icon.js
components/icons/test/icon.visual-diff.html
components/icons/test/icon.visual-diff.js

This PR updates the condition for inlining the SVG so that it will only do so provided the src is on the CDN.  Otherwise it will fallback to standard `img`.  The consequence to this is that any color overrides would not be applied.

Add icon source check to fetch/inline logic.

---

package.json

Now that https://github.com/Polymer/tools/issues/3394#event-2388950007 is fixed, we can also get `mocha` onto the latest and remove the greenkeeper ignore settings.

Update mocha now that wct-mocha is fixed

---

package.json

Switch back to use the latest version of `eslint-plugin-lit` since `viewBox` attribute parsing has been fixed with recent v1.1.1.

Use latest eslint plugin for lit.

---

components/colors/colors.js
components/typography/typography.js

This will make the path consistent with polymer's `custom-style` element ensuring they get deduplicated as expected.

Update the shadyCSS import path.

---

.travis.yml
README.md
cli/update-version.js
package.json

Swapping out `frauci` for a custom script.
The workflow is similar, but this script requires a commit message containing `[increment major/minor/patch]` -- otherwise it does nothing. 
If it sees that message, it will:
1. Update the version in `package.json` using the `npm version` command
2. Commit that change as BrightspaceGitHubReader, but with `[skip ci]` so that the change doesn't trigger another build
3. Add a tag matching the version number (but with a `v` in it)
4. Push the commit
5. Push the tag
6. Set `TRAVIS_TAG` environment variable to the tag, which will trigger the NPM deployment step

script to update the version

---

.travis.yml
cli/update-version.js

Some changes to how this works -- we can't set an environment variable like `TRAVIS_TAG` from inside a process and expect the rest of the Travis jobs to see the change. So I switched this to use the exit code from the `update-version` script to set another env variable that the deployment checks. 🤞

fixing deployment script

---

mixins/localize-mixin.js
package.json

BSI is currently breaking when trying to pull in the first use of the `meter` component with:
```
error:    Promise rejection: Error: Duplicate export 'parse'
error:    Error: Duplicate export 'parse'
```
Going to try reverting the version of `intl-messageformat` back to 2.2.0 (the same used by `@Polymer/app-localize-behavior`, which is used in the same `activities` component as the `meter`) to unblock for now.

Set the version of intl-messageformat back to 2.2.0

---

components/button/button.js
components/demo/demo-snippet-styles.js

When RTL mode is activated, the contents can rub up against the button:

adding right padding to demo container for when in RTL

---

cli/icon-generator.js
components/icons/README.md
components/icons/demo/icon.html
components/icons/icon.js
components/icons/test/icon.visual-diff.html
components/icons/test/icon.visual-diff.js

Now that the `icon` attribute must refer to one of our icons, we're not worried about collisions with Google's iconsets anymore. This let's us treat the `d2l-` prefix in the category as optional. Yay less code!

allowing the "d2l-" prefix in the category to be optional

---

components/meter/README.md
components/meter/demo/meter.html
components/meter/lang/en.json
components/meter/meter-circle.js
components/meter/meter-linear.js
components/meter/meter-mixin.js
components/meter/meter-radial.js
components/meter/test/meter-linear.visual-diff.html

Colin has done a lot of research on RTL and fractions.
He decided that using the fraction character `∕` instead of the slash character `/` gives better spacing.
He also found that fractions shouldn't be flipping in this context.
On some computers  `∕` seems to flip and I would consider that to be a defect but so far this is still a better solution. Matching OS and Browser won't reproduce the issue of flipping fraction character.
Since we will want to use the fraction character I am taking the ability away from the consumer to write the fraction on their own.

Update to match Colin's research RTL

---

directives/run-async.js
package.json

We were getting console errors for every instance of `d2l-icon` from this call https://github.com/BrightspaceUI/core/blob/master/components/icons/icon.js#L39
On chrome: `Uncaught (in promise) TypeError: Illegal invocation
at rc.dispatchEvent (webcomponents-sd.js:2231)
at run-async.js:129`
On firefox: `TypeError: 'dispatchEvent' called on an object that does not implement interface EventTarget.`
So we check that the `parentNode` is an element before calling `dispatchEvent` on it to avoid this error.

check if node is element before calling dispatchEvent

---

components/icons/fix-svg.js
components/icons/test/icon-custom.visual-diff.html
components/icons/test/icon-custom.visual-diff.js
components/icons/test/icon.visual-diff.html
components/icons/test/icon.visual-diff.js

Mark found a bug using perceptual diff where the dividers in the navbar were darker than they should be. Turns out this code that removes `fill` from the SVGs was only acting on `path` elements, whereas with the old icon code, it applied to any element -- including `circle` in this case.

removing fill from all elements, not just path

---

components/more-less/more-less.js

`height` property is defined as `The maximum height of the content when in "less" state.`, however it was being set as the content `height` instead of `max-height`. It was causing our component to have too much of a height when not needed, e.g.:
Was this intentionally set as the height style instead of max-height? If so, maybe we need another property the user can specify for height as well as max-height?

set max height of content instead of height [increment patch]

---

helpers/test/.eslintrc.json
helpers/test/dom-components.js
helpers/test/dom.html
test/index.html

This adds the unit tests for composed DOM helpers from [d2l-polymer-behaviors-ui](https://github.com/Brightspace/d2l-polymer-behaviors-ui/blob/master/test/dom.html).  A couple of small fixes were needed where a couple of tests were relying on some Polymer APIs.

Add unit tests for composed dom helpers.

---

components/button/demo/button-icon.html
components/button/demo/button-subtle.html
components/button/demo/button.html
components/button/demo/floating-buttons-in-frame.html
components/button/demo/floating-buttons-in-tabs.html
components/button/demo/floating-buttons-page.html
components/button/demo/floating-buttons.html
components/colors/demo/colors.html
components/demo/demo-page.js
components/demo/demo/demo-snippet.html
components/icons/demo/icon-custom.html
components/icons/demo/icon.html
components/meter/demo/meter.html
components/more-less/demo/more-less.html
components/typography/demo/typography.html

Noticed in @m6jones's list demo that the title was ending up as a tooltip on the entire demo. This is technically a breaking change, but I'll just go through the places using this and fix them.

Can't use "title" since it ends up as a tooltip

---

components/button/floating-buttons.js

Noticed this error buried in the console when running the tests in Firefox only:
I'm guessing this calculation is getting done either before, during or after the floating buttons have been removed from the DOM and no longer have an offsetParent. I tried reseting `_floating` to `false` in the disconnected callback but it didn't do anything.

not calculating if there's no parent

---

components/icons/fix-svg.js
components/icons/test/icon-custom.visual-diff.html
components/icons/test/icon-custom.visual-diff.js
components/icons/test/icon.visual-diff.html
components/icons/test/icon.visual-diff.js

I think this is our 3rd bug with this... we should have just [copied what the old fill-stripping code did](https://github.com/BrightspaceUI/icons/blob/v6.8.0/cli/iconset-builder.js#L16).
The bug here is that some of our icons (in this case [tier2:check-box](https://github.com/BrightspaceUI/core/blob/master/components/icons/images/tier2/check-box.svg?short_path=8d4168c)) contain fill colours other than ferrite and "none". If we strip them all, then when a new colour gets applied it will be applied to them all. Let's just strip ferrite -- at least things will be consistent.
This caused the following bug, where they were just trying to colour the checkbox blue:

only removing fill values that match ferrite

---

cli/icon-generator.js

When webpack builds the icons we end up with generic, numbered names due to the dynamic imports:
If we provide a `webpackChunkName` hint when generating the `presetIconLoader.js` file, we can get some more user-friendly output:

Add webpackChunkName hint

---

.travis.yml
package.json

@AllanKerr added some awesome features to `frau-ci` so that we can tell it that we only want it to increase the version when we explicitly ask for it. I think that was the only thing preventing us from using it instead of rolling our own `update-version.js` script.
Since testing this kind of requires Travis and testing out actual releases, if this ends up working I'll go back and clean up our script.

switching version updating to use frau-ci

---

helpers/README.md
helpers/requestIdleCallback.js

This is the `requestIdleCallback` shim from `d2l-polymer-behaviors-ui`.  Currently, it appears that the shim is being included via menus, but is actually "used" by a couple of other repos.
* [d2l-menu](https://github.com/BrightspaceUI/menu/blob/660ab50f2c7bb843cd50a6c028c318c10a1d379e/d2l-menu.js#L16) imports the shim and uses it
The following usages query the `window` and fall back directly to `setTimeout` without shimming the API (we should update these to import this shim, and remove the `|| setTimeout` from them):
* [d2l-enrollment-card](https://github.com/BrightspaceHypermediaComponents/enrollments/blob/49ec9a20366059f1a9f0b9d00b9ee5cc4a612fa8/components/d2l-enrollment-card/d2l-enrollment-card.js#L442)
* [d2l-course-image-tile](https://github.com/BrightspaceHypermediaComponents/1.x-hy …

Moving requestIdleCallback shim .

---

package.json

Tired of getting notifications about this every week. We can't upgrade `intl-messageformat` until either `app-localize-behavior` upgrades or we stop using it. Tracked in #148.

ignoring intl-messageformat greenkeeper updates

---

components/meter/meter-circle.js
components/meter/meter-linear.js
components/meter/meter-radial.js
components/meter/test/meter-circle.visual-diff.html
components/meter/test/meter-circle.visual-diff.js
components/meter/test/meter-linear.visual-diff.html
components/meter/test/meter-linear.visual-diff.js
components/meter/test/meter-radial.visual-diff.html
components/meter/test/meter-radial.visual-diff.js

See #188 for details. Essentially, when we render out the percent, the percent formatter rounds things to the nearest percent. So `0.4%` rounds down to `0%`. But we were still showing part of the linear/radial graph, which was confusing.
This changes it up so that if the percent rounds down to zero, we don't render any of the graph.

fixes #188: if percent rounds to zero, don't display visual lines

---

components/more-less/more-less.js
components/more-less/test/more-less.html
helpers/dispatchRenderEvent.js
helpers/localization.js
index.html
mixins/demo/localize-mixin.html
mixins/demo/localize-test.js
mixins/localize-mixin.js
mixins/test/localize-mixin.html
mixins/test/localize-test-elem.js

This splits out most of the localization code out of the mixin and into a separate importable module. The motivation is to allow our older Polymer `localize-behavior` to also import this code and reference it directly, instead of having its own copy.
Not only will that centralize all our localization code, but it will allow us to abandon `app-localize-behavior` and upgrade `intl-messageformat` at our leisure.
This also fixes #118, since only a single observer is installed on the page instead of one per element.

Localize refactor

---

helpers/localization.js
package.json

Now that we don't depend on `app-localize-behavior` anymore -- which was using an older version of `intl-messageformat` -- we can finally unpin.

unpinning intl-messageformat

---

helpers/localization.js
package.json

Undoing this change for now. When I [brought it into BSI](https://github.com/Brightspace/brightspace-integration/pull/1616/files), the build started failing on weird `Error: Duplicate export 'parse'` errors.

reversing intl-messageformat upgrade for now

---

mixins/demo/localize-test.js
mixins/localize-mixin.js
mixins/test/localize-mixin.html

@mpharoah-d2l noticed a bug with how we're blocking `shouldUpdate` from happening until the language has resolved: when `shouldUpdate` eventually passes, it triggers a call to `updated(changedProperties)`, except any properties that changed while it was blocked are lost.
This change remembers any properties that changed while it was waiting for the language to resolve, and then adds those back in when things finally become unblocked.

remember all properties that have changed while waiting

---

components/link/link.js

This was working previously since if you don't specify a type it just assumes `String` and uses the default converters.

fixing link type

---

mixins/demo/localize-mixin.html
mixins/demo/localize-test-no-resources.js
mixins/demo/localize-test.js
mixins/localize-mixin.js
mixins/test/localize-mixin.html

This changes the date/time/number formatting and parsing methods to just always use the document language instead of the one that gets resolved based on what text language resources exist.
It allows us to support the cases where a component simply doesn't have or need language resources and just wants to format a number, or where they have a subset of resources.

localize mixin should work even if no language resources exist

---

components/dialog/dialog-confirm.js

This change addresses two issue with the original logic:
* return as soon as focus is applied (minor opt)
* fallback to focusing on first (ex. if only button is a primary button)

Update dialog-confirm initial focus.

---

components/more-less/more-less.js

Lit-analyzer just started complaining about this (must be a new feature they added), and it's a totally valid complaint. We can't bind a boolean to a string attribute like `aria-expanded`.

fixing boolean attribute binding

---

helpers/README.md
helpers/announce.js
helpers/demo/announce-test.js
helpers/demo/announce.html
index.html

This helper defines a singleton `aria-live` container for messages and an `announce` helper that appends to it.  It is similar to the `iron-a11y-announcer` (which has some issues such as appending to the `head`, clobbering successive messages, not respecting the mode on its API).
I think the main reason for having such a container is: 
* `aria-live` elements must be defined as such when they are created and appended to the DOM
* one must not try to append messages until the browser has rendered the live region, otherwise those messages will not be announced 
I have another idea of creating some type of element or directive that consumers could use directly in their component templates, but the async nature of the `aria-live` setup makes things tricky. There may also be some unexpected …

Add announce helper for announcing messages.

---

components/demo/code-view.js
components/demo/demo-snippet.js
components/demo/demo/demo-snippet.html

Some components surface attributes on their host (ex. [ButtonMixin](https://github.com/BrightspaceUI/core/blob/master/components/button/button-mixin.js#L24)), resulting in those attributes being displayed in the formatted code in the demo-snippet.  This is misleading to those using the demo because it leads them to believe that the app must provide those attributes. 
This change adds support for demo code contained by a `template` element. The reasons this was not done from the beginning was: a) to enable demo pages to have more succinct demo snippets; and b) to enable demo pages to wire up event handlers to demo elements at page load-time.  We might eventually want to add an event `d2l-demo-snippet-ready` in the future as a hook, but there is no immediate need for that. 
Below, the …

Update d2l-demo-snippet to support template-based source code.

---

README.md
components/inputs/README.md
components/inputs/demo/input-select-test.js
components/inputs/demo/input-select.html
components/inputs/input-select-styles.js
components/inputs/test/input-select.visual-diff.html
index.html

This brings `<select>` input styling into Lit. There's no custom element here, it only exposes styles that consumers can apply to their own native `<select>`s inside their elements.
These changes do not yet bring it inline with the current design -- I have those changes ready and will add them in a follow-up PR. I just wanted to make these changes first so we could verify that they don't cause a visual diff change.
I've made a few modifications to the original Sass-based CSS:
- I removed `width: 100%` on the `<select>`. In most cases, we just want its width to be as wide as the largest option. In cases where width is constrained, consumers need to put a `width` or `max-width` on it anyway.
- I removed the CSS that was only applying things if `:not([multiple])`. Since consumers need to …

select inputs

---

components/button/floating-buttons.js
components/button/test/floating-buttons.html

When there is a horizontal scrollbar present in Windows, the calculation for whether or not to show the floating buttons no longer works properly. There's some weirdness where `getBoundingClientRect().top;` would calculate something different every other time (though if the `scrollbarHeightEstimate` is added, this no longer happens) so even when the floating buttons were showing as expected the calculated values were actually not what was expected/inconsistent with what was seen on chrome on mac.
This solution feels a bit hacky, so if there are alternative solutions/if there is a better way we have for detecting horizontal scroll I am very open to other options.
I removed the usage of `_containerTop` since its top is the same as the floating-buttons top (it was used at one point, but then …

Fix floating buttons when horizontal scrollbar exists

---

components/inputs/input-checkbox.js

This should have always been there.
Interestingly it's hard to catch these cases, since `d2l-demo-snippet` will put `dir="rtl"` on all the elements inside its shadow root when you press the button, which triggers the RTL CSS. But if the page itself has `dir="rtl"`, then you notice the problem.

checkbox should use RtlMixin

---

helpers/announce.js
helpers/demo/announce-test.js

This PR improves the behavior of the aria-live announce function. In short, aria-live is terribly frustrating for several reasons:
1. the aria-live region must be rendered before any changes are treated as updated, and a simple requestAnimationFrame is not a sufficient delay
2. the browser internally seems to keep track of the last message, and if it thinks an aria-live region change is the same as something is recently announced, it may ignore it even if it's a different node
3. the browser may or may not coalesce synchronous aria-live announcements... sometimes it will combine them into one announcement, sometimes it will announce them out of order, and sometimes it will only announce one 
4. if new aria-live region changes are made while a previous message is being announced, it may be …

Make aria-live announcer less flakey.

---

components/inputs/input-text.js
components/inputs/test/input-text.html

I'm removing this binding of the `required` attribute to the underlying `<input>` element. The reason being that when present, the `required` attribute causes an empty input to be immediately "invalid", which styles it red before the user has even had a chance to interact with it.
We don't use this attribute in MVC for this reason.
Eventually when we add in the concept of validation directly to our input components, we may be able to bring back some form of this -- maybe not initially but after a `validate()` call or something. We shall see.
This is only [used in one place](https://github.com/Brightspace/gbl-map-editor/blob/55ea6da886a7f7812f08db59f772dddeaaa3e041/src/components/view-map-activities.js#L109), and I've confirmed with @sgrinwis-d2l that this new behaviour is the one they're …

Removing binding of "required" to avoid initial invalid styles

---

components/typography/typography.js

Noticed this is a visual diff page where it was only including typography and labels were black instead of ferrite.

typography needs to reference colors

---

components/button/button-styles.js
components/button/test/button-icon.visual-diff.js
components/button/test/button-subtle.visual-diff.js
components/button/test/button.visual-diff.js
components/inputs/test/input-search.visual-diff.js

None of the other inputs have transitions on the focus styles anymore, and this is causing a lot of grief in our visual diff tests.

removing box-shadow transition on buttons

---

components/inputs/README.md
components/inputs/input-checkbox.js
components/inputs/test/input-checkbox.html

This is so that folks can simulate a user interaction with the checkbox in their tests without needing to reach into the shadow root and click on the underlying `input` element.

adding a method to simulate clicks on the checkbox

---

components/inputs/input-checkbox.js
components/inputs/test/input-checkbox.html

Re-created #310 (FYI @tylergee) as a branch so that visual diff tests could run.
This issue [is described here](Polymer/lit-element#601). Essentially what's happening is that by binding to the underlying input's attribute instead of its property, as long as all interaction happens with `<d2l-input-checkbox>`, all is well. But when the user interacts directly with the checkbox (as is bound to happen!), then subsequent manipulation of `<d2l-input-checkbox>` does nothing. Once interacted with, native checkbox inputs don't seem to care about whether or not they have a `checked` attribute -- they respect their property instead.

binding to input property to fix user interaction bug

---

components/inputs/README.md
components/inputs/input-fieldset.js
components/inputs/input-label-styles.js
components/inputs/input-text.js
components/inputs/test/input-label.visual-diff.html

* It had the same name as the style.js in typography.
* Also renamed the uses of it

Rename export const for input-label-styles.js

---

components/dialog/dialog-confirm.js

The children of the footer slot aren't being grabbed in Edge because the `.d2l-dialog-footer slot` selector doesn't match anything (they're direct children of the dialog, rather than in a slot), resulting in a null reference.

Accounting for when footer children aren't in a slot.

---

mixins/localize-mixin.js
package.json

Using the latest and ES6 module friendly version of `intl-messageformat`. Will need to work alongside [this new version](https://github.com/BrightspaceUI/localize-behavior/pull/30) of `localize-behavior`.

upgrading to intl-messageformat 7

---

package.json

Now that we're on the latest `intl-messageformat`, we don't need Greenkeeper to ignore this anymore.

remove override

---

mixins/demo/localize-test.js
mixins/localize-mixin.js
mixins/test/localize-mixin.html
package.json
wct.conf.json

With the new `intl-messageformat`, we need to include a polyfill for the `Intl.PluralRules` stuff, which doesn't exist in Edge or older versions of Safari.

Polyfill Intl.PluralRules

---

.travis.yml

Seems like this was locked [because node-sass didn't support version 13](https://github.com/BrightspaceUI/core/pull/257). If the build passes, it's fixed.

using the latest node version again

---

.travis.yml

`frau-ci` is a little quirky in that when you pass `-d=skip` (meaning you want it to _not_ do a release by default), it returns a `1` status code if no version increment happened. That allows us to pair it with setting the tag ONLY if `0` was returned. This was causing the whole stage to fail.
By moving this back into `after_success` -- but this time in its own stage -- it can fail and not fail the build.

moving version update to after_success since it can return 1 status code

---

components/dropdown/dropdown-content-mixin.js
components/dropdown/test/dropdown-content.test.js

1. Fix `vertical-offset` to function with or without the `px` suffix and to default back to `20px` if removed or set to an invalid value.
1. Fix `__openedChanged` so that it is only called when the `opened` value actually changes.
1. Remove `forceRender` and `render-content` because the performance optimization is no longer worth the additional complexity it adds.

Fix Inconsistencies with the Polymer Dropdown

---

components/inputs/README.md

Does this make things clearer?

making input "change" and "input" events more clear in the documentation

---

components/dropdown/dropdown-button-subtle.js
components/dropdown/dropdown-button.js

Pass the `disabled` attribute through to the inner `dropdown-button` and `dropdown-button-subtle` so that they get correctly styled when disabled.

Dropdown Button Disable

---

helpers/focus.js
helpers/test/focus.test.js

When an error occurs in the FACE editors, we want to focus on the first input field that is in error.
Doing this via mixins/events/etc might be tricky, fragile, and high-maintenance, due to the many different sub-editors on the page and the state management to support the new save-cancel workflow.
The alternative is to do a dom search, which is what this PR strives to help support.
Since our use case doesn't care about the _next_ focusable element but instead the next focusable element that is also in error, this PR adds an optional predicate which allows us to filter the nodes returned by `getFirstFocusableDescendant`. Now it will return the first node that is focusable _and_ fulfills the predicate.
If this is generally approved of, I can add some tests.
(And I had originally also added …

Add optional predicate to getFirstFocusableDescendant focus helper

---

components/dropdown/dropdown-content-mixin.js
components/dropdown/dropdown-content-styles.js

Dropdown width is determined by header, content or footer - whichever is widest.
Previously it only considered content.

Dropdown scales based on header&footer content

---

mixins/test/visible-on-ancestor-mixin.test.js
mixins/visible-on-ancestor-mixin.js

When the `connectedCallback` is run, there is no guarantee that the ancestors' shadow
DOMs have loaded. If the `d2l-visible-on-ancestor-target` is within an ancestor's
shadow DOM then the look up in `__voaInit` will fail and the `visible-on-ancestor-mixin`
will not find a target.
To account for the async loading of ancestors' shadow DOMs, this delays until the
next animation frame.

Fix issue where the d2l-visible-on-ancestor-target may not have loaded

---

components/menu/README.md
components/menu/menu-item-link.js

This affects any voice over users using iOS 13.
The anchor just isn't receiving any click event when voice over is on. I haven't been able to track down exactly what changed to cause this. I think this fix is fairly safe but let me know if there's something I'm missing or if there is potentially a better option. The `bubbles: false` is to prevent the `d2l-menu-item-select` event from being dispatched a second time.

Fix bug with clicking a menu-item-link with voiceover on

---

components/tooltip/demo/tooltip.html
components/tooltip/test/.eslintrc.json
components/tooltip/test/tooltip.test.js
components/tooltip/tooltip.js

- This pull request adds the logic to show the tooltip on `mouseenter`, `focus`, and if `force-show` is set.
- The tooltip is closed when it isn't hovered, focused, or `force-show` is set.
- Layout and positioning

Tooltip (1/2): Add tooltip show/hide logic

---

mixins/localize-mixin.js

This PR removes duplicate language tags from showing up in list of possible languages. This frees the clients from needing to do this deduping themselves (either indirectly via `import` or directly like I am here).
e.g. we currently see `["en-us","en","en-us","en","en-us","en"]` for simple English pages. With this, it's just `["en-us","en"]`

Remove lang duplicates

---

components/inputs/input-time.js
components/inputs/test/input-time.test.js

- Dropdown no longer appears when `input-time` component is disabled
- Fixed label issue for time dropdown. Combobox requires `aria-labelledby` instead of `aria-label`. Label now always exists, but is offscreen when hidden.
- Tweaked tests related to labels based on implementation changes

Time Input Dropdown Fixes

---

components/demo/demo-snippet.js

This change tweaks the placement of the stamped demo snippet so that `getPreviousFocusable` (in consumer code) will not walk the composed DOM from the `template` element which would result in incorrectly returning the last focusable inside the stamped demo element.
Alternatively, the order of the slots could have been reversed to fix this.  I chose the JS change since it offered ability to more clearly comment the reason without adding comments to the HTML template.

Tweak stamped snippet placement.

---

components/inputs/input-date.js

When pressing enter in legacy edge, open was run but then dropdown-opener's `toggleOpen` was also run (which I'm not really sure why that isn't happening on non-edge - dropdown-opener's `__onKeyPress` just isn't being called when `this._dropdown.open();` is in the input-date code but if I comment it out then `__onKeyPress` happens so I'm probably missing something in the dropdown logic). Overall `input-date` handling its own opening functionality seems a bit safer.

input-date: legacy edge: enter was not opening dropdown

---

components/calendar/calendar.js
components/calendar/test/calendar.test.js

When the calendar initially loads and there is no `selected-value`, focus date should be today. If the user navigates to another month then returns to the month containing today, focus date should be the first of the month.

Calendar: initial focus date should be today

---

components/tooltip/tooltip.js

1. Add `max-width` of `350px` to the tooltip content to prevent exceeding 350px if `no-wrap` is used.
2. Increase specificity of tooltip text color because in Edge Legacy, `.d2l-typography .d2l-body-small` has higher specificity
3. Move the target-position styling from being on and internal div to be on the tooltip itself.
- This change was made because the tooltip can potentially have an `offsetParent` meaning it ends up off the page. In situations like these the tooltip would still position and size correctly but the 0 by 0 tooltip itself would be off the page and trigger horizontal or vertical scroll.
- To avoid this, the tooltip itself needs to be positioned to align with its target rather than just moving the internal positioning div.

Tooltip Bug Fixes

---

components/inputs/demo/input-date-time.html

`required` is not yet supported by `input-date-time` so removing this demo in order to have it not be misleading at this point.

input-date-time: remove required demo

---

components/dropdown/test/dropdown-content.visual-diff.html
components/tooltip/test/tooltip.visual-diff.html
components/typography/typography.js
test/typography-preload.js

- Add typography preload to prevent visual diff tests failing due to the font not loading at initial page load. This change is required because browsers do not load fonts until they are displayed on the page. For visual diff tests without any text initially on the page, font loading gets missed by the `networkidle0` wait.

Visual Diff Typography Preload

---

components/list/list-item.js

TODO:
```js
render() {
return html`<d2l-list>${this.renderItems()}</d2l-list>`;
}
renderItems() {
return this.items.map(item => this.renderItem());
}
renderItem() {
return html`<d2l-list-item></d2l-list-item>`
}
```
In this case `parentNode` of `d2l-list-item` is a documentFragment (which in addition to not working properly, throws because fragments don't have `getAttribute`)

d2l-list-item: find d2l-list as ancestor

---

components/calendar/calendar.js

This doesn't fix the chrome/NVDA bug but should be fixed.

calendar: use string for aria-selected

---

components/dropdown/dropdown-menu.js

Fix for [DE38481](https://rally1.rallydev.com/#/detail/defect/379578838464?fdp=true): Time Input > Selected date scroll into view intermittent with Firefox and broken in Legacy Edge
- Firefox / LEdge now consistently scroll to visible item when opened

Fix for radio dropdown sometimes not scrolling

---

components/tooltip/tooltip.js

- Temporarily remove explicit announce for tooltips on non-interactive targets to avoid regressions where explicit announce is already being done due to poor accesibility support in the old tooltip.
- Removing because I found a couple regressions where stuff is being announced twice. Just want to revert this before branching then add it back tomorrow so I have all next release to fix any duplicate announces that get introduced.

Temporarily remove explicit announce for tooltips

---

components/tooltip/tooltip.js

- Fix defect where `document.creatElement('d2l-tooltip')` triggers an error due to attributes being set in the constructor.
- Error: `Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`
- Move `showing` to the `connectedCallback` so `setAttribute` isn't called in the constructor.
- I tried to create a test case that calls `createElement('d2l-tooltip')` but it doesn't seem to cause the exception to be thrown.

Fix Broken Tooltip Constructor

---

components/tooltip/README.md
components/tooltip/tooltip.js

- Add `console.warn` when tooltip is used in a way that may not be accessible.
- Add a README section on using tooltip in an accessible manner

Tooltip Accessibility Documentation

---

templates/primary-secondary/primary-secondary.js

When `width-type="normal"` is set, the combination of `max-width` and auto `margin` was allowing the template width to shrink below the desired 1230px if none of the slotted elements were wide enough. The template should always be 1230px wide if there is the space for it.
An alternative to setting `width: 100%` as I've done here would be to change the `minmax` min value to 410px (aka 1230/3), thus setting the lower bound of the grid width to 1230px in total. Not sure if there's a preference. (https://github.com/BrightspaceUI/core/blob/master/templates/primary-secondary/primary-secondary.js#L41)

Fix primary-secondary template width when width-type="normal"

---

components/inputs/input-text.js

This fixes of the problem of over-reading the placeholder on input.
Hover/click behavior seems to be working the same as before when hovering/clicking on the label text (checked chrome, legacy edge, firefox, safari).
The only other place I saw where we use the `label` wrapped around the `input` is `input-time` and I am hesitant to change that one due to it being a bit more complex, and it not using placeholders so it would not have the bug anyways.

input-text: use for/id for labeling

---

components/tooltip/README.md
components/tooltip/test/tooltip.test.js
components/tooltip/tooltip.js
helpers/focus.js

- This PR includes the changes in [Button Icon Tooltip Integration #500](https://github.com/BrightspaceUI/core/pull/500) excluding the actual integration commit.
1. Add `for-type` to allow it to either be a primary label or secondary descriptor.
1. Update tooltip accessibility warning to exclude hidden or disabled targets.
1. Fix tooltip race condition when it is shown then hidden extremely quickly causing cleanup to occur before show has finished.

Tooltip for-type

---

components/tabs/demo/tabs.html
components/tabs/tabs.js

The original code would have worked - this change just avoid possible JS error when `d2l-tab-panel-selected` or `d2l-tab-panel-text-changed` is dispatched from a nested set of tabs.

Improve event handling for nested tabs

---

components/dropdown/dropdown-content-mixin.js

For some unexplained reason, `??` causes Polymer build to explode. This is causing strange build errors in BSI where it can't find this file. Probably if `polymer build` encounters a syntax error or something it just dies and whatever called it assumes the file can't be found.

not using nullish coalescing operator 

---

package.json

`1.43.7` is the cert patch version, so merging this with `[increment patch]` should result in master release `1.43.8`.

Bump package.json version to skip cert version

---

components/tabs/tabs.js

Given this code will not be around for very long (famous last words), I opted to not include a full blown array polyfill, and I kept this code as close to the original as possible so that removing it is just a matter of deleting the conditional statements/else block, even though it results in a tiny bit of repeat.

Fix tabs find and findIndex for IE11.

---

components/inputs/input-text.js

This surfaced as a bug where the placeholder text was overlapping with the icon in input-date.
The problem was that input-date was within a div that was initially not displayed, and `offsetWidth` does not seem to work to calculate the slot content width if not displayed. This solution gets the slot content (`d2l-icon`) and calculates overall width using width and margins.

input-text: fix width calculation when not initially displayed

---

components/inputs/input-time.js

- When focusing on dropdown, screen readers read `<label text> list <timezone>`

Input-time: Screen readers read timezone

---

components/inputs/input-time.js
components/inputs/test/input-time.visual-diff.js

Updated `input-time` focus and keyboard behaviour to match `input-date`
- When input is focused pressing `down arrow` will open and focus the dropdown
- When dropdown is closed, focus moves back to the input instead of the next element on the page

Added down-arrow behaviour and improved focus for input-time

---

components/tooltip/tooltip.js

- Add flag to ensure the tooltip accessibility warning is only logged once to prevent log spam

Reduce Tooltip Accessibility Warning Frequency

---

components/inputs/input-time.js
components/menu/menu.js

Fix for [DE39048](https://rally1.rallydev.com/#/detail/defect/390426252452?fdp=true): Time Input > Down Arrow with value not in list should shift focus to item in list.
Opening dropdown with down arrow now moves focus to the menu correctly when value in input doesn't exist in dropdown (ex: 5:07 isn't in 30-minute increment list). Focus then starts at 12:00AM.
Also a fix for `Enter` press inconsistency / not opening dropdown after first press in Chrome/LEdge

Time Input: Down Arrow Focus Dropdown With Non-Matching Value

---

components/inputs/input-text.js

Bug: `input-date` with `rtl` had padding of 40 on both sides.
Solution notes: If there is no slot content, then the `_firstSlotWidth` or `_lastSlotWidth` should be reset to 0 (since dir was initially behaving as ltr then in a later render changing to rtl logic but these widths weren't changing to 0).

input-text: fix rtl in input-date

---

components/inputs/input-date.js

I'll add comments on the bugs that each part fixes, but in general the fixes/improvements are:
- Scroll behavior - `input-text` should remain visible when dropdown is opened given that it has focus. Especially important on mobile
- Tapping icon would clear the `value`
- `input-text` width was often not wide enough on iOS

input-date: Improve mobile experience

---

components/list/list-item-checkbox-mixin.js

Fixes a bug that prevented the checkbox from being focused when the action is clicked.
Caught in this story: [US115380](https://rally1.rallydev.com/#/detail/userstory/382436537132?fdp=true)

Focus the checkbox when label is clicked

---

.travis.yml
components/tabs/tab-panel-mixin.js
package.json

Withe the migration of tabs to Lit, my-courses is missing the first `d2l-tab-panel-selected` event which can get dispatched before the panels are connected or event listeners are setup.  It looks like the old behavior had this delay: https://github.com/BrightspaceUI/tabs/blob/master/d2l-tab-panel-behavior.js#L75

[20.20.6] - DE39211 - Delay tab panel selected event

---

components/menu/menu.js
components/menu/test/menu.test.js

If we want to make these checks case insensitive, here's a way to do it.

fixes #557: making key shortcuts to menu items case-insensitive

---

components/list/list-item-checkbox-mixin.js
components/list/list-item.js

When in strict mode (which we want to enable), `lit-analyzer` doesn't like putting attributes on elements that aren't actually real. So this switches list over to use either a CSS class or a `data-*` attribute in the places where it was using custom attributes.

Lit analyzer list fixes

---

components/dialog/README.md
components/dialog/demo/dialog-async.html
components/dialog/demo/dialog-container.js
components/dialog/demo/dialog-nested.html
components/dialog/demo/dialog.html
components/dialog/dialog-mixin.js
components/dialog/dialog-styles.js

The CSS change seems clean enough. The `data-dialog-action` stuff makes me feel a little bit sad, but the only way around this that I can think of would be to add `dialog-action` as a supported attribute on all our clickable things (`d2l-button`, etc.), which seems far worse.

Lit analyzer dialogs

---

components/alert/README.md
components/alert/alert-toast.js
components/alert/test/alert-toast.axe.js

- Change role from status to alert so it will be announced more consistently
- Change the timeout to 4s by default or 10s if there is a button action
This change will merge cleanly with @Scy-D2L 's change so it should be fine to merge it directly to `master`.

Improve alert-toast Accessibility

---

components/dialog/dialog-mixin.js
components/dialog/dialog.js

* use updated callback instead of attributeChangedCallback
* allows dialog to be initially rendered in `opened` state

Update dialog mixin to use updated callback.

---

components/inputs/input-time.js
components/inputs/test/input-time.axe.js

Fix for [DE39070](https://rally1.rallydev.com/#/detail/defect/391001767292?fdp=true): Time Input > JAWS > Time label not being read when tabbing in and [DE39071](https://rally1.rallydev.com/#/detail/defect/391002763524?fdp=true): Time Input > JAWS > Inconsistent Behaviour moving in and out for forms mode to select values

input-time JAWS fix / update to ARIA 1.2

---

components/inputs/input-date.js
components/inputs/input-text.js

Carin suggested that when a value is selected in the calendar, it should be announced first when the calendar closes, rather than later on during the screen reader reading.
I added `atomic` and `live` properties to `input-text` so I could pass those through from `input-date`. I did not call them `aria-atomic` and `aria-live` because that caused strange behaviour with Safari and Voiceover. If this seems okay I'll add it to the README.
Note that this does not fix this behaviour on JAWS and I have not been able to figure that out, so I'm open to suggestions there (e.g., I also tried announce, just for fun added a visible div in input-date with aria-live containing the date, nothing worked). JAWS seems to really want to read the title first (so maybe this is something we can revisit when we …

input-date: read selected value when changes

---

helpers/focus.js

The `img` tag should not be included in this list.  It causes image elements to get the focus even though they shouldn't, for example when placed inside dialogs before other focusable content. From a user perspective, the focus is _seemingly_ lost.  This has come up as an issue twice so far very recently.  This originally comes from legacy-land (at least 10 years ago), possibly with the intended usage of image maps.

Remove img from list of focusable elements.

---

lang/localize-core-element.js

Noticed that Polymer builds were failing with this error:
> Promise rejection: Error: ENOENT: no such file or directory, open '/home/travis/build/Brightspace/awards-leaderboard-ui/node_modules/@brightspace-ui/core/lang/tr-tr.js'

removing entry for Turkish

---

components/list/list-item-drag-handle.js

In windows the grid doesn't work the same as in macOS. Weirdly, this doesn't seem to be a problem with specific browsers but what OS they are on.
Basically on all browsers in windows this drag handle shows up like this: 
This PR fixes it so it shows up properly.

Fix window layout

---

cli/verify-translations.js
components/inputs/test/input-date.visual-diff.js

Otherwise new keys get added to the end instead of in alphabetical order

verify-translations script: sort keys

---

components/tooltip/tooltip.js

1. Fix bug causing tooltips to be shifted too far if their inner content is forced beyond the `max-width` of `350px` with `no-wrap` text or `min-width` CSS rules.
1. In Chrome `offsetParent` includes positioned nodes in ancestors' shadow DOM. In Firefox `offsetParent` positions relative to these but reports the `offsetParent` as the first positioned ancestor in the same DOM context. This causes `offsetTop` and `offsetLeft`
to be incorrect in Firefox if there is a positioned node in an ancestor's shadow DOM. To fix this, `offsetTop` and `offsetLeft` need to be computed using the `getOffsetParent` DOM helper rather than using the built-in properties.

Tooltip: Positioning and Width Bug Fixes Backport

---

.travis.yml

- Remove `after_success` because it wiped out the `TRAVIS_TAG` during build preventing the backport version being published to `npm`

Bump npm version for backport

---

package.json

I think these two need to be upgraded in lock-step in order to avoid the downstream issues we were seeing earlier. I'll switch `d2l-localize-behavior` as well, then test this out in BSI and `quiz-authoring`.
I've tried testing locally via `npm link` but it doesn't appear to be possible. If it doesn't work, I'll back this out (again).

upgrading intl-messageformat

---

.travis.yml

This should speed our CI builds up a bit. With this change, Travis CI won't run on branches other than release/maintenance branches named things like `1.x`, `1.53.x`, etc.

ci: only building master and release branches in CI

---

package.json

It looks like custom-elements.js does not get included when doing an npm i with the latest core and I think this is why.

package.json: Add custom-elements.json to files

---

helpers/dom.js
helpers/test/dom.test.js

`td`, `th`, and `table` tags are now only considered if there are no positioned ancestors rather than when they are first encountered. This aligns with [how `offsetParent` works according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent).

Fix getOffsetParent with table element and relative-ancestor

---

.travis.yml
helpers/dom.js
helpers/test/dom.test.js
package.json

- Backport of https://github.com/BrightspaceUI/core/pull/639
- `td`, `th`, and `table` tags are now only considered if there are no positioned ancestors rather than when they are first encountered. This aligns with [how `offsetParent` works according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent).

Backport fix getOffsetParent with table element and relative-ancestor

---

mixins/provider-mixin.md

The provider-mixin wasn't working for me, until I realized calling reqestInstance in the constructor wasn't hitting the event handler, and moved it to firstUpdated().
This just adds that note and changes the sample code accordingly.

provider-mixin readme example: firstUpdate

---

components/demo/code-view.js
components/demo/demo-snippet.js

The scenario is for live demos - have the code update when the component demoing changes.
`slotchange` doesn't seem to work for this and I wasn't sure how to force it to, but overall this seems to work.

demo snippet: add public functionality for forcing the code to update

---

.travis.yml

So since the getting of the languages was moved into the `visual-difference-testing` stage, that meant that when test:diff:golden was run, it wouldn't have the languages and then regenerated the goldens for calendar (e.g., https://github.com/BrightspaceUI/core/pull/656/commits/7822063aac63f8010b7547ef77fb16c1ccff07b9) then caused failures when running `npm run test:diff` with the languages after the regeneration.
I moved this back to as it was before - there might be a different way to do this instead (e.g., have some sort of script that gets run by visual-diff if it exists?)

visual-diffs: move language addon

---

components/list/list-item-drag-mixin.js
components/list/test/list-item-drag-mixin.test.js

[US115496](https://rally1.rallydev.com/#/detail/userstory/383979103344?fdp=true)
[Design Document](https://desire2learn.atlassian.net/wiki/spaces/POL/pages/996083189/US114586+wc-list+Refactor+for+Drag+n+Drop#newPositionEventDetails)
The new `NewPositionEventDetails` class is an event class with helper methods included. Currently, the event is not hooked up to anything - @m6jones 's work will be in tandem. The new class will replace the current `detail` in the 'd2l-list-item-position' event.
Comments will be reduced or eliminated when the drag n drop feature is merged into `master`.
- `targetKey`: The key of the node that is moving
- `destinationKey`: The key of the item in the position the node is moving to
- `temporaryMovement`: Whether the movement is entering or exiting a temporary …

Added NewPositionEventDetails

---

components/tooltip/tooltip.js

This is necessary because browsers include margin in `offsetTop` and `offsetLeft` when the `offsetParent` is the `body`. To avoid positioning incorrectly in this case we need to set `parentTop` and `parentLeft` to `0` so any `margin` will be included in the calculation. Only using the `offsetParent`'s bounding client rect excludes `margin`.

Fix positioning defect with body as offsetParent

---

components/list/list-item-generic-layout.js
components/list/list-item.js

[US115503](https://rally1.rallydev.com/#/detail/userstory/384004440540?fdp=true)
[Design Document](https://desire2learn.atlassian.net/wiki/spaces/POL/pages/996083189/US114586+wc-list+Refactor+for+Drag+n+Drop#d2l-list-item)
[UX Designs](http://design.d2l/components/lists/)
* `d2l-list-item` now uses the `d2l-list-item-generic-layout` component to generate the dom
* New hover and focus states added to styles for selectable list items
* Properties for focus state added to capture all `focusin` events within the item
* New selected style
**Note: Colours are not well represented in gif**
**Actual Colours**
- There is new spacing for this UX that will be in a future PR
- Mixin integration
- Checkbox action is broken; this is expected before mixin integration 
- The grid will not work yet, as it …

Feature: Update list item to use list-item-generic-layout

---

components/list/list-item-generic-layout.js
components/list/list-item.js

* Changes the target of row movements in `list-item-generic-layout` to use the `role="rowgroup"` instead of tag name so that other types of list item components may be grid enabled
* Adds the `role` logic to list-item in preparation for mixin integration. This logic currently exists in `ListItemMixin`

Allow list item to be grid enabled

---

components/list/README.md
components/list/demo/list.html
components/list/list-item-checkbox-mixin.js
components/list/list-item-generic-layout.js
components/list/list-item-mixin.js
components/list/list-item-role-mixin.js
components/list/list-item.js
components/list/test/list-item-generic-layout.test.js
components/list/test/list-item-role-mixin.test.js

[US115502](https://rally1.rallydev.com/#/detail/userstory/384002687644?fdp=true)
[Design Document](https://desire2learn.atlassian.net/wiki/spaces/POL/pages/996083189/US114586+wc-list+Refactor+for+Drag+n+Drop#d2l-list-item)
- Adds the `ListItemMixin` and `ListItemCheckboxMixin` to the `ListItem`
- Removes the logic now contained in these mixins from the `ListItem`
- Grid can now be enabled on default lists using the `grid` property
- New demo snippet showing grid enabled added
- `ListItemDragMixin` will be integrated when it is finished and tested
- Fixes for NVDA screen reading with grid (currently doesn't play nicely)
- Unit tests for generic list item were changed to use `d2l-list-item`
- New demo snippet allows for manual testing

Integrate mixins into d2l-list-item (Part 1)

---

components/switch/switch-visibility.js
lang/ar.js
lang/da.js
lang/de.js
lang/en.js
lang/es.js
lang/fr.js
lang/ja.js
lang/ko.js
lang/nl.js
lang/pt.js
lang/sv.js
lang/tr.js
lang/zh-tw.js
lang/zh.js

This PR adds translations for the "Visibility" verbiage.  We were previously holding off on this in case Design required something different.
The `VisibilitySwitch` provides a custom getter/setter for the `text` property to check for custom text, and if none provided, will localize the default text.

Add translations for d2l-switch-visibility.

---

components/list/list.js

Context:
US118212 - https://rally1.rallydev.com/#/357252966636d/detail/userstory/402324092656
This PR fixes the NDVA weird behavior that was reading out cells letter by letter. 
Adding application seems to fix it because it indicates to NDVA that the list and all of its children should be treated similarly to an application.
In addition, `application=role` will be applied to the list when the grid flag is on. 
Quality:
I tested it in http://localhost:8000/components/list/demo/list-item-sample.html

Fix NVDA keyboard shortcuts behavior when gird is on list

---

README.md

I separated out the inputs into their specific docs to make it more clear what ones there are

readme: separate out inputs, add breadcrumbs, calendar

---

components/form/form-element-mixin.js
components/form/test/form-element.test.js

- Add `requestValidate` to allow ancestors to prevent their children from auto-validating.
- Rather than calling `validate` directly, form elements will call `requestValidate`, this allows ancestor elements to allow or prevent descendants from validating themselves by cancelling the `d2l-form-element-should-validate` event.

Add requestValidate to FormElementMixin

---

components/form/form-element-mixin.js
components/form/test/form-element.test.js

- The `invalid` attribute is used to style custom form-elements error state. All error styling should be based on this attribute. Previously this was done using `aria-invalid`.
- The `forceInvalid` property was added so that custom form elements can be forced into an invalid state even if they didn't fail validation. An example use case is in the `input-date-range` component when the start date is later than the end date. Even though neither of the inner `date-range` components failed validation we want to be able to show them in their error state.

Add invalid and force-invalid to FormElementMixin

---

components/form/form-element-mixin.js
components/form/test/form-element.test.js

- This allows validate to be called during live validation to remove errors if the component becomes valid but not show new errors if the component goes from a valid to an invalid state.
- This is required because our designs for live validation only have new errors shown on focus out.
- For a `d2l-input-text` the usage would look something like this with `requestValidate(false)` when the text value changes and `requestValidate(true)` on blur.
```
updated(changedProperties) {
super.updated(changedProperties);
changedProperties.forEach((oldVal, prop) => {
if (prop === 'value') {
this._prevValue = (oldVal === undefined) ? '' : oldVal;
this.requestValidate(false); // don't show new errors but clear existing errors if we go from invalid to valid
}
});
}
_handleBlur(e) {
this._focused = false; …
```

Add showErrors to FormElementMixin validate

---

components/alert/alert-toast.js
components/alert/alert.js
components/button/button-icon.js
components/button/button-subtle.js
components/dropdown/dropdown-content-mixin.js
components/inputs/input-text.js
components/inputs/input-time-range.js
components/inputs/input-time.js
components/list/list.js
components/more-less/more-less.js
components/status-indicator/status-indicator.js
components/tooltip/tooltip.js

Found this because the `lint:lit` step was yelling at me when trying to use a tooltip with `align="start"` (`Type '"start"' is not assignable to '"('start'" | "'end')"'`) so this fixes that, and I confirmed that `lint` does yell with this syntax if a value is not one of those values, and that the `|string` works for `input-time`.

jsdoc type fix: remove brackets wrapping type values

---

components/inputs/test/input-date-time-range.axe.js

The testing of this behaviour should be covered in the inner component axe tests.

input-date-time-range: remove flaky focus test

---

components/list/list-item-drag-drop-mixin.js
components/list/list-item-drag-handle.js

Abbie: Re: Clicking the drag handle -- I’m thinking we should only make it change to keyboard on click if it’s already focused. I don’t want mouse users to get disoriented if they click right on the drag handle the first time.

fix: Click Focus, Click Keyboard

---

components/alert/test/alert.axe.js
components/inputs/input-text.js
components/inputs/input-time-range.js
components/status-indicator/test/status-indicator.axe.js

The two culprits were `no-unknown-attribute` and `no-incompatible-type-binding`.
- `no-unknown-attribute` errored because we marked attributes as `@ignore` so they wouldn't be documented but apparently Lit Analyzer doesn't like that because it also then thinks they don't exist.
- `no-incompatible-type-binding` errored because we're passing values Lit Analyzer thinks are strings into what is effectively an enum type. Having to add comment types in these cases feels pretty bad so not sure if anyone has any thoughts on disabling this rule.

Fix lit analyzer errors

---

templates/primary-secondary/demo/index.html
templates/primary-secondary/primary-secondary.js

On mobile when the secondary panel is repositioned below the primary panel, it can be quite a long scroll to the footer. This change makes the footer sticky on mobile devices.
Tested on Safari & Chrome on iOS, and Chrome on Android.
Demo using the FACE assignment editor:
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F391269578948

US116586 Sticky footer for primary-secondary-template on mobile

---

components/dropdown/README.md
components/dropdown/dropdown-button-subtle.js

There are case(s) in Brightspace that use dropdowns with subtle button openers that also have title text, which currently we don't support other than by using a `d2l-button-subtle` + `d2l-dropdown` instead of just using `d2l-dropdown-button-subtle`.

feat: add description property to d2l-dropdown-button-subtle

---

components/list/list-item-generic-layout.js

**Destined for 20.20.8 CERT** #741 
- Prevents a console error when people have focusable items and are not using grid
- Turns off `preventFocus` and `preventClick` on the content area. Some peeps are using content areas to do fancy things with focusable elements, such as accordions, and we don't have a good general alternative for this currently

fix: setFocusInfo shouldn't be called for those not using grid

---

components/list/list-item-generic-layout.js

Our nifty `preventFocus` and `preventClick` functions caused a regression for the awards tool. 
- Remove these functions and replace them with a console warning.
- Remove `setFocusInfo` for those not using `grid`

fix: Prevent focus and prevent click should not break existing functionality

---

components/alert/README.md
components/alert/alert-toast.js
components/alert/alert.js
components/alert/demo/alert-toast.html
components/alert/demo/alert.html
components/alert/test/alert-toast.test.js
components/alert/test/alert.test.js

This fixes #759.
I've also proceeded to update the event names for the alert to be present tense.  I suspect the past-tense names were an artifact of the previous Polymer alerts.  Unfortunately this will require a little cleanup in apps.  I would have left it as it, except that I did not want `d2l-alert` and `d2l-alert-toast` following different convention, and I also didn't want to continue with the past-tense naming since there is strong precedent for present tense in dropdown, dialog, browser events, and other components.

Add alert-toast-close event so consumers can keep their private properties in sync.

---

components/dropdown/dropdown-button-subtle.js

Check if the description is `undefined` before adding it to `dropdown-button-subtle`, so the `aria-label` on the `button` isn't set to `undefined` (which NVDA will read out).

fix: Avoid setting undefined aria-label

---

components/list/list-item-content.js
components/list/list-item-generic-layout.js

There was a problem with consistent evaluation with a list item having a name that is way too long and single character. Things started to over extend to different parts grid cells. Here is the fix:
Picture of the problem:

Fix overflow on list containers.

---

helpers/test/dismissible.test.js

I tried some other timeout related changes but rearranging the tests seemed to be the only change that helped. I reran several times and all passed (we'll see if this works out in the long run). Haven't dug much into why this works. This flakiness only seems to happen on chrome and when the full test suite is run.

dismissible tests: fix flakiness

---

components/tooltip/README.md
components/tooltip/demo/tooltip.html
components/tooltip/tooltip.js

Added the `announced` attribute so that initially this is opt-in in order to avoid repetition when used with components that have already added their own `announce`.
`innerText` seems to work but I'm wondering if there is something else I should be using?

tooltip: announce inner text when used with custom elements

---

components/inputs/demo/input-number.html
components/inputs/input-number.js

This PR includes the following:
~ removed `width` from attributes
~ removed label `id` and input `aria-labelledby` attributes
~ changed `step` attribute type to `String`

Suggested fixes

---

components/form/form-element-mixin.js
components/inputs/input-date-range.js
components/inputs/input-date-time-range.js

1. When composing multiple form elements, inner form elements were firing composed events meaning the inner form element could wipe out errors for the elements their contained within.
- **Fix:** Change `d2l-form-errors-change` event to not be composed so its only sent from the top level custom form element and move the event to `requestValidate` so it respects `validate` being overridden.
1. When composing multiple form elements, the order errors were displayed in the tooltip and the error summary would differ if there was both an error in an inner component and an ancestor that contains it.
- **Fix:** Change the order errors are returned when `validate` is overridden.

fix: FormElementMixin error bubbling

---

components/form/form-element-mixin.js
components/form/test/form-element.js
components/inputs/input-date-range.js
components/inputs/input-date-time-range.js
components/inputs/input-date-time.js
components/inputs/input-date.js
components/inputs/input-text.js
components/inputs/input-time-range.js

- Remove all of the `validationMessageFlagName` overrides in favor of a single `validationMessage` method to override to make it easier to understand and use `FormElementMixin`.
- Remove `labelText` since the additional complexity of having to understand the difference between `labelText`, `label`, and where to use them wasn't worth it. Now users can provide a `label` property if they want to use the built-in default error messages or just write their own messages with their own labels as they please.

refactor: Simplify FormElementMixin validateMessage and label

---

components/form/form-element-mixin.js
components/form/test/form-element.test.js
components/inputs/input-text.js

- Remove `FormElementMixin.setCustomValidity`
- This is redundant with the ability to override `validationMessage` and setting `setValidity({ customError: true })` so removing it to simplify the interface.
- Add `FormElementMixin` `name` property
- Name is used by all form elements during submission so it should be a property of all of them rather than having to add it explicitly to every single form element
- Remove `FormElementMixin.checkValidity`
- This is redundant with `validity.valid` so removing it to simplify the interface

refactor: Additional FormElementMixin Simplifcations

---

components/calendar/calendar.js
components/inputs/input-date.js

Bug:
When an iOS user using VoiceOver changing the month (e.g., by clicking the previous or next button) VoiceOver states the month/year is the previous (e.g., if when they started navigating the calendar they were viewing September 2018, when they change months VoiceOver would still state "September 2018". VoiceOver would also state the incorrect month if the user navigates to the heading).
Solution information:
If the live region text is a `div` instead of a `h2` then it doesn't have this problem. Carin suggested using a region to wrap a calendar in this case, as removing the heading removes a way for users to navigate quickly around the page. The `label` option was added as regions should have unique names, and a scenario where they might not is when used within `input-date` if there …

fix: iOS live region when changing month

---

components/icons/demo/icon.html
package.json

This was only needed for IE11 and only used in our demo page.

removing fetch polyfill

---

templates/primary-secondary/primary-secondary.js

fix a problem where a z-index is set on a container and constrains child elements like d2l-overlay from setting a z-index to appear on top, This is a cert fix related to pr #806

fix: defect de40213 rubric buttons hidden behind face footer

---

components/dialog/test/dialog-helper.js
components/dropdown/test/dropdown-helper.js
components/tooltip/test/tooltip-helper.js

This PR removes the duplicate getEvent implementation for visual-diff tests, in favor of new Puppeteer helper in visual-diff library.  This is the analogous of oneEvent from `@open-wc/testing`, except that it is called from the Puppeteer side.

Use visual-diff oneEvent and eliminate duplicate getEvent impls.

---

components/list/demo/list-demo-drag-n-drop-usage.js
components/list/list-item-drag-handle.js
lang/en.js

Context:
DE39907 - https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F407158647016
Fix screen reader text when we focus on the drag handle of an item in the list. 
Went from `Reorder action` to `Reorder item action for <name>`.
Quality:
Tested locally.

DE39907 Fix drag focus text for screen readers

---

README.md

We don't want people accidentally trigger major version bumps so clarifying that it is in the message body rather than the head like the others.

Update Semantic Release Versioning Info

---

components/inputs/input-time.js
package.json

We were seeing some flaky test failures in Firefox in BrowserStack that I think are related to the usage of the `Date` object here to build up the intervals. So possibly a timezone edge case. Switched it to just use math and that seems to have solved things.

using math instead of Dates to build time intervals

---

components/form/test/form-element-localize-helper.test.js
components/inputs/test/input-number.axe.js
components/inputs/test/input-number.test.js
components/inputs/test/input-text.test.js

Fixed a couple unit tests that were breaking because of the lang term change in the [previous PR](https://github.com/BrightspaceUI/core/pull/819).
Added unit tests for:
~ constructor
~ default property values
~ min/max fraction digits
~ validation
Added accessibility tests for:
~ normal (only label)
~ default value
~ required
~ disabled
~ placeholder
~ hidden label
~ focused

Accessibility and unit tests

---

components/inputs/input-number.js

- `FormElementMixin` was refactored to not need `ValiditionType` and `d2l-form-element-should-validate`. This is the corresponding `input-number` change.

Refactor input-number to use the new FormElementMixin nesting

---

lang/en.js

Context:
Add more information to screen readers on drag and drop handle.
Quality:

Add more information for list item drag handle keyboard mode

---

components/skeleton/demo/skeleton-mixin.html
components/skeleton/demo/skeleton-test-paragraphs.js
components/skeleton/skeleton-mixin.js
components/typography/styles.js

This builds on the [draft skeleton mixin pull request](https://github.com/BrightspaceUI/core/pull/853), adding support for "paragraph skeletons", as defined on design.d2l:
- Ability to "skeletize" blocks/paragraphs of text before we know how many lines the actual text will take up
- Consumers would choose between 2-line, 3-line and 5-line skeletons based on the expected size of the field
- Skeletons would be applied to one of our existing typography styles (standard, compact or small), and the size of the skeleton should match the font size of the style
- We'd prefer a single render path, allowing apps to apply skeleton styles to existing paragraph elements, instead of needing to render something like a `<d2l-skeleton-paragraph lines="5">` when they want skeletons to be displayed, and …

Skeleton Paragraphs

---

components/dropdown/dropdown-content-mixin.js
components/dropdown/test/dropdown-content-contained.visual-diff.html

Dropdown content clipping would normally be an issue in the LMS also, except the LMS has some "special" styles that override the opener's default position from `relative` to `static`, effectively making the dropdown content positioned `absolute` with respect to the document (instead of the opener within a bounding container).  In such a case, we do not need adjust the dropdown content position and dimensions according to what would normally be the bounding container (the wrapper element within `d2l-scroll-wrapper`).

fix: add check for opener position to know if content is absolute wrt document

---

components/inputs/input-number.js
components/inputs/test/input-number.test.js

I noticed for max-fraction-digits=0 (integers only), the max-fraction-digits was resolving to "undefined".
So this PR includes the following:
~ remove conditions inside options for formatting number (not needed anymore because there is no loss of type since the function is not exported anywhere; i.e. undefined changes to type String when passed in from another component)
~ do not export formatValue function (not used anywhere else)
~ added unit tests for max-fraction-digits=0
~ included unit test for checking default value on "title" property

Zero max fraction digits bug

---

helpers/getLocalizeResources.js

Related to https://github.com/Brightspace/lms/pull/1736 we want OSLO to remove cached 404 (and other possible) errors when the ETag changes (new lang terms overriden).

fix: OSLO remove 404 cached responses when ETag changes

---

components/inputs/input-number.js
components/inputs/input-time.js
components/inputs/test/input-number.test.js
components/inputs/test/input-time.test.js

Fixing a couple bugs with time and numeric input that I discovered building the demo for the meeting today. When the language on the document changes, we want all the UI controls to re-render in that language.

Update on language change

---

README.md
components/form/README.md

I think having a single place we can send people (and link to in other places) to learn about forms would be nice. Also this makes browsing the source on GitHub nicer.

adding an entrypoint for all the form documentation

---

components/form/form-element-mixin.js

While investigating some performance slowness, I noticed that the date input (and likely others but didn't look) was rendering 3 times initially. One of those times was being caused by this `requestUpdate`, but there still weren't any actual errors.
This change makes things so that only if an error is actually removed or added that wasn't there before does it cause a re-render.

only requesting an update if something changed

---

mixins/provider-mixin.js
mixins/provider-mixin.md

This PR factors the `requestInstance` logic out into a helper that can be used outside the context of a web component.  I've run into a case where I need the ability to request an instance from a custom tinyMCE plugin.

Add request instance helper.

---

components/tooltip/tooltip.js

- A race condition in `d2l-tooltip` can cause it to start open when the page loads. This could happen anywhere but has only been reproduced with site tabs.
- When tooltips are connected to the page they check to see if their target has focus to determine if they should start open or closed. On initial load this code can be triggered with a `null` target which causes the tooltip to start open if the `activeElement` is also `null`. In most cases `updated` is run afterwards which properly sets the `_isFocused` value to `false`. Some pages have load timing that changes the order these run in causing the tooltips to start open.
- Fix the initial load check to also check if the target is non-null so we never initially show the tooltip unless it has an actual target with focus.

Fix defect where tooltips would incorrectly start open

---

.travis.yml
components/tooltip/tooltip.js

- A race condition in `d2l-tooltip` can cause it to start open when the page loads. This could happen anywhere but has only been reproduced with site tabs.
- When tooltips are connected to the page they check to see if their target has focus to determine if they should start open or closed. On initial load this code can be triggered with a `null` target which causes the tooltip to start open if the `activeElement` is also `null`. In most cases `updated` is run afterwards which properly sets the `_isFocused` value to `false`. Some pages have load timing that changes the order these run in causing the tooltips to start open.
- Fix the initial load check to also check if the target is non-null so we never initially show the tooltip unless it has an actual target with focus.

Backport: Fix defect where tooltips would incorrectly start open

---

components/more-less/more-less.js

chrome 74                Tests failed: Error thrown outside of test function: Cannot read property 'removeEventListener' of null
HTMLElement.disconnectedCallback at /components/@brightspace-ui/core/components/more-less/more-less.js:132
HTMLElement.<anonymous> at /components/@polymer/test-fixture/test-fixture.js:256
HTMLElement.forElements at /components/@polymer/test-fixture/test-fixture.js:260
HTMLElement.removeElements at /components/@polymer/test-fixture/test-fixture.js:255
HTMLElement.restore at /components/@polymer/test-fixture/test-fixture.js:214
Context.<anonymous> at /components/wct-browser-legacy/browser.js:1827
For some reason, on the ci linux side, it also needs Line 113 to be null checked.

fix more-less component is throwing null exception in some unit test cases

---

components/more-less/more-less.js

adding the `semantic-release` commit message formatting that I missed last time.  Sorry for the back and forth PRs.

fix: more-less.js

---

components/card/card.js
components/card/test/card.test.js

The enrollment card Polymer element is binding the card's `href` to a `null` value. Back when this was Polymer, that resulted in no `href` being set, but that's not the case in Lit so we need to handle it specially.

fix: do not render href if null

---

templates/primary-secondary/primary-secondary.js

- Step size is now based on a desired size of 80px used to calculate the number of steps rather than always being fixed at 6 steps.

Refactor primary-secondary keyboard step size

---

mixins/focus-visible-polyfill-mixin.js

I noticed the following JS error in Kibana from Spark since this was introduced:
> TypeError: window.applyFocusVisiblePolyfill is not a function
at shadowRoot.window.applyFocusVisiblePolyfill.window.addEventListener.once (https://s.brightspace.com/lib/bsi/20.20.12-83/unbundled/button-styles.js:1:310)
So somehow, despite the event [not being fired until after the global is introduced](https://github.com/WICG/focus-visible/blob/master/src/focus-visible.js#L297), it's still not there when this code runs. Very confusing, but 🤷

fix: extra check to make sure polyfill is really there

---

components/dropdown/demo/dropdown-menu.html
components/dropdown/dropdown-menu.js
components/dropdown/test/dropdown-menu.test.js
components/menu/README.md
components/menu/demo/menu.html
components/menu/menu-item-link.js

Selecting a menu item did not previously close menus,
because they were expected to navigate to another page.
If the target is a new tab, the original page would remain
intact, with the drop-down menu still open.
This change will close drop-down menus whenever a menu
item link is selected. Also, passes `download` attribute through to anchor.

Close drop-dropdown menu on link select

---

components/form/docs/form-native.md
components/form/docs/form.md
components/form/form-native.js
components/form/form.js
mixins/test/localize-mixin.test.js

The native `<form>` element is block by default, so ours should be too.
Fixed some file locations in the READMEs while I was in here.

fix: making form elements block

---

directives/run-async.js

This ends up throwing an exception if for example a `<d2l-icon>`'s icon property changes (which acts as the `runAsync` key) while the original task is still pending. Seems safe to just abort and not throw here.

fix: do not throw if the key (e.g. icon) changes while still pending

---

components/dropdown/dropdown-opener-mixin.js

While testing `@brightspace-ui-labs/media-player`, we found that the `<d2l-button-icon>`'s were clickable with mouse, enter, or spacebar. The settings menu has a `<d2l-button-icon class="dropdown-opener">` to toggle it, but the toggling is only handled by mouse or enter.
This change would allow the dropdown menu to be toggled with spacebar as well.

Toggle dropdown opener on spacebar

---

components/dialog/dialog-mixin.js

This change is to use our custom dialog rather than the native dialog when a nested MVC dialog is opened.  We need to opt out of native dialogs in this case because they are rendered on the "top layer" above all other elements regardless of their `z-index` or stacking context, while currently, our MVC dialogs are rendered and positioned with `z-index`.

Use non-native dialog impl when nested MVC dialog is opened.

---

components/dropdown/dropdown-content-mixin.js

Seeing a frequent JavaScript error originating from here in production.
> Uncaught TypeError: Cannot read property 'removeEventListener' of null
Call stack:
> TypeError: Cannot read property 'removeEventListener' of null
at HTMLElement.disconnectedCallback (https://s.brightspace.com/lib/bsi/20.20.11-110/unbundled/dropdown-content-styles.js:1:2605)
And occasionally the call stack includes information from Cypress (test automation software):
> TypeError: The following error originated from your application code, not from Cypress.
> 
> Cannot read property 'removeEventListener' of null
> 
> When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
> 
> This behavior is configurable, and you can choose to turn this off by listening to …

safety check around removing event listener

---

templates/primary-secondary/primary-secondary.js

I didn't update the header and footer z-index because [the other z-index change](https://github.com/BrightspaceUI/core/pull/944) was enough to fix the consistent eval issues and I don't want to make unnecessary changes this close to branching.
If dropdowns or tooltips open in the secondary panel they may get cut off. This
happens because the aside inside the secondary panel only takes up the height of its
content, not the height of its panel.
This is fixed by forcing the aside to always be the height of the panel

Fix secondary panel height

---

components/inputs/input-date-range.js
components/inputs/input-date-time-range.js
components/inputs/input-time-range.js

Use case: in the LMS adding the range components in the hidden input nodes need to update when a change occurs.

input ranges: fire change event when endValue updates due to autoShiftDates

---

components/html-block/html-block.js

MathJax creates (or passes on) some hidden `MathML` for screen readers. However, if the containing `MathML` is large enough (ex: contains `semantics` tags), it can push the width of its container (which might make some unnecessary horizontal scrollbars).
Adding a `position: absolute` to take it out of the visual flow of the document (since you can't see it anyway) so it doesn't add any width. Shouldn't affect screen reading either (tested with JAWS and NVDA w/MathPlayer just in case).
[Before](https://user-images.githubusercontent.com/52549862/99118385-0ea9fc80-25bd-11eb-80b2-906b85ad6a3b.png) and [after](https://user-images.githubusercontent.com/52549862/99118278-db676d80-25bc-11eb-99a7-0556bdff6b1a.png).

Adding absolute positioning to hidden MathML

---

components/tooltip/tooltip.js

In cases where the tooltip has the document as its offset parent and the document has scroll, the tooltip was not accounting for scroll when positioning itself.
It now correctly accounts for scroll.

Fix tooltip positioning for document parent with scroll

---

components/list/README.md
components/list/list-item-mixin.js

This functionality is now provided by `ListItemLinkMixin`, so this is just cleaning up now that usages of `ListItemMixin` have been updated.

Remove link/actionHref stuff from ListItemMixin.

---

components/skeleton/skeleton-mixin.js

Basically, using `skeletonMixin(ListItemMixin(...))` will remove the ListItemMixin styles without this fix.

fix: Allow skeleton Mixin to be apart of a Mixin chain

---

README.md

Because core is slightly different.

docs: fix visual-diff test path for core

---

templates/primary-secondary/primary-secondary.js

Fixes: https://trello.com/c/DwgFvfRz/262-rtl-new-picker-causes-horizontal-scroll-in-rhp
**Cause:**
By setting the `time` field with the new date picker a horizontal scrollbar appears in the secondary panel.
**Initial investigation:**
`label` for the `time` fields triggers an overflow in the x-axis and so a horizontal scrollbar appears as the `label` is set to render at `left: -10000px`. Setting it to `right: -10000px` maintains functionality and has no overflow/horizontal scrollbar, not sure if the RTL mixin needs a fix to get this to happen.
**Before:**
**After:**

Fix RTL label causing an `overflow-x` which creates horizontal scrollbar

---

helpers/announce.js

Fixes https://github.com/BrightspaceUI/core/issues/526
This fix checks if a message has already been added to the aria-live container. If not, it performs as before. If it has, it removes then re-adds it (otherwise it might not actually get read). 
This was tested with the `input-time-range` component validation which can end up adding the text of multiple "Start time must be before end time" tooltips to the announcement if the user is quickly tabbing around.
This assumes that there isn't a scenario where there should be duplicate messages that are repeated in succession. A different fix will need to be made if that is the case.

announce: remove duplication of messages

---

helpers/getLocalizeResources.js
helpers/test/getLocalizeResources.test.js

[DE41794](https://rally1.rallydev.com/#/110294864140d/dashboard?detail=%2Fdefect%2F466890048628)
This fixes an issue where Firefox private browsers could not use OSLO (and so not get overrides) because they would try to use the batch call but then fail when trying to open CacheStorage because it is not available in private mode.
**More info:**
https://bugzilla.mozilla.org/show_bug.cgi?id=1320796
https://bugzilla.mozilla.org/show_bug.cgi?id=1112134

fix: Verify cache storage is available before trying to use batch route

---

CODEOWNERS

This won't do a lot if you're watching the whole `core` repo anyways, but I think it would result in one less email.  If you aren't watching it, then you'd no longer get notified about the visual-diff PRs unless you caused the commit that opened it.  For whatever reason, I couldn't do `screenshots/ci/golden/`, I had to pick just one level.
Thoughts?

Remove code owners for the visual-diff goldens

---

CODEOWNERS

Actually, I think this is what we want.  The other canceled everything out for some reason.

Fix CODEOWNERS for visual-diff goldens

---

components/calendar/calendar.js

The biggest culprits were:
- `_focusDate` which sometimes was being set to the same value multiple times, so work was done to minimize that.
- Unnecessary `await this.updateComplete`

calendar: reduce renders

---

components/inputs/input-search.js

`-webkit-appearance: none` seems to be [the way to fix this](https://css-tricks.com/almanac/properties/a/appearance/).
Before:
After:

fix: suppressing iOS's rounded corners on search inputs

---

components/inputs/input-textarea.js

Adding this property temporarily so that we can switch consumers to use this component.  This will be removed once consumers are updated to stop accessing the textarea directly.

Temporarily adding this method to facilitate transition.

---

components/inputs/input-date.js

This was noticed in activities where the input-date was unnecessarily wide. The input is initially hidden and so the hidden divs here that are used to calculate the maxWidth don't actually have widths themselves when `firstUpdated` is run. I moved this calculation into a ResizeObserver which seems to solve this issue.
In fixing this I also noticed that the info tooltip was showing up when the input-date was disabled so I hid that.

input-date: use resizeobserver for getting hiddenContentWidth

---

components/dialog/dialog.js
helpers/README.md
helpers/viewport-size.js

This is an alternate solution to #1074 -- thank you @AKobets for bringing this to our attention!
This bug was introduced back in November when we [switched from % units to viewport units](#966). That solved a bunch of problems, but also introduced a new one. Mobile devices use the full device size for `vh` and `vw`, _including_ any browser/device chrome above or below the actual browser viewport. Sometimes that chrome slides away when the user scrolls, which is why [they made this choice](https://bugs.webkit.org/show_bug.cgi?id=141832).
The solution I'm going with here is the one [discussed in this blog post](https://bugs.webkit.org/show_bug.cgi?id=141832). It uses JavaScript to expose the `window.innerHeight` and `window.innerWidth` as CSS custom properties. Then our CSS can use those …

fix: using window's inner height/width instead of vh/vw units

---

components/list/README.md
components/list/demo/list-item-actions.html
components/list/list-item-link-mixin.js
components/list/test/list.test.js

This PR surfaces a custom event for the primary navigation action on list items, so that consumers can wire-up for things like telemetry.  Without this, consumers are forced to wire-up click and key handlers on the list-item, which doesn't always translate to navigation when there are other things the user can interact with, such as selection, drag & drop, secondary actions, etc.

Add d2l-list-item-link-click event so consumers can use (ex. telemetry).

---

components/dropdown/dropdown-content-mixin.js

This is to fix the case with html editor where the dropdowns are opening in the incorrect direction. I found that the values used in the left position calculation here https://github.com/BrightspaceUI/core/blob/master/components/dropdown/dropdown-content-mixin.js#L591 seemed really off (e.g., target width was 44, space around was -20) and that if I set bounded to false then things were fine. I also noticed that `getBoundingAncestor` for these cases was just returning the opener (`d2l-button-subtle`) since it was going into this case https://github.com/BrightspaceUI/core/blob/master/helpers/dom.js#L17. This is one of those fixes where it fixes the case at hand and the visual diffs locally were fine but I don't know if it was like this for a reason.

dropdown: use opener's parent for running getBoundingAncestor

---

components/list/list-item-drag-drop-mixin.js
components/list/list-item-mixin.js

All hover effects should _not_ be triggered by hovering `d2l-list-item-generic-layout` itself, but by hovering its child elements (inside its 1px borders).
This prevents the background color from changing before any actionable child elements are hovered.
Fix is for all action, button, and selectable list-items.
(green background color is just for GIF contrast)

fix: list-item hover gap caused by border

---

components/inputs/input-number.js
package-lock.json

The parameter here that's changing is whether or not to "show new errors". I think the reasoning for passing in `false` here was to avoid validating partial input while the user was still typing, instead waiting for the `blur` event to fire. But the numeric input only updates `value` on-blur anyway, not as the user types. @krshnpatel not sure if you remember more details here?
The problem with passing `false` is that validation is skipped if `value` is set programatically using JavaScript. This happens a lot in the MVC/legacy frameworks where we have wrappers around the component with their own APIs. I think we _do_ want to validate whenever `value` changes regardless.
The outcome of this change are:
* For `required` values, if a value isn't provided validation doesn't occur since `value` …

fix: validate numeric inputs whenever the value changes

---

components/inputs/test/input-date-time-range.test.js

Opening as draft in order to rerun the tests several times.
Should fix https://github.com/BrightspaceUI/core/issues/1083.
This is likely cause by the same problem as https://github.com/BrightspaceUI/core/pull/1101, which is the timezone not yet being set, and there isn't an event to listen to that I'm aware of so a timeout should help with this.

input-date-time-range: attempt to fix flaky tests

---

components/inputs/test/input-date-time-range.test.js

Problem:
Between 5 - 6 pm some of the tests end up being run on a machine that has its timezone set to Central Europe Time. In 2020, CET had Daylight Savings time end on Oct 25. Since our difference calculation for shifting dates is done using `Date`, because of the time change it becomes off by 1 hour (https://github.com/BrightspaceUI/core/blob/master/components/inputs/input-date-time-range.js#L34).
"Solution":
I shifted all the tests to be further from that time shift.
What does this mean:
This is how our old date picker behaved as well and is not new. How it normally exhibits itself is that when a user picks a date that moves start to one side of daylight savings and end to the other side, the end time shifts by an hour. This usually should seem fine to a user since they would in …

input-date-time-range: change test to no longer flake

---

.eslintrc.json
mixins/localize-dynamic-mixin.js
mixins/localize-mixin.js
mixins/localize-mixin.md
package-lock.json

Adds a proper `localize-dynamic` mixin to simplify individual component complexity. Docs have been updated with example usage.
Dependent upon:
~https://github.com/Brightspace/brightspace-integration/pull/3350~
~https://github.com/Brightspace/eslint-config-brightspace/pull/39~

Add support for dynamically imported translation resources

---

components/inputs/input-number.js

Numeric inputs were incorrectly showing the invalid tooltip on-hover when they were in a disabled state:
As you can see, internally `d2l-input-text` was already suppressing the red outline and the invalid icon when it's disabled.

fix: don't show invalid tooltip when disabled

---

components/html-block/README.md
components/html-block/demo/html-block.html
components/html-block/html-block.js
helpers/mathjax.js
index.html

This PR allows consumers to specify an optional MathJax config object when using an HTML block. Right now this is used to enable (or disable) LaTeX rendering within MathJax.

US125413 - Allow support for LaTeX rendering in our MathJax implementation

---

.eslintrc.json
mixins/localize-dynamic-mixin.js

Remove the missing file warning to decrease confusion and noise, and fix Firefox.

Remove missing file warning

---

components/skeleton/skeleton-mixin.js

Some components use low-level z-index for their own purposes, and sometimes the value can be slightly higher than the skeleton z-index.  In order to provide some room for components to do their stacking, while still ensuring the skeleton stacks on top, this PR increases the z-index slightly.

Bump up z-index for skeleton to provide room for low-level stacking.

---

components/icons/images/tier1/file-archive.svg
components/icons/images/tier2/file-archive.svg

The `fill="none"` wasn't letting the ferrite colour we apply from `<d2l-icon>` pass through, so the icon was working as an `<img src>` and as a background image, but not from within `d2l-icon`.

fix: removing none fill on file archive icons

---

components/menu/menu-item-link.js
components/menu/test/menu-item-link.test.js

Tried a few approaches but short of removing the `<a>` entirely this was the only one that worked across Voiceover for iOS and macOS.
Applying `role="presentation"` on the `menu-item-link` and `menuitem` on the anchor was promising, but because focus is going to the menu-item Voiceover on macOS reads out "menu item text presentation". 🤦

fix: sprouting aria-label

---

components/overflow-group/test/overflow-group.visual-diff.js

This just delays the test by a few hundred milliseconds so that the icons will definitely have time to load in before we start taking screen shots. 
There is probably a better fix we can put in here to avoid this being an issue with icons in general. I think the reason we are seeing these tests being flaky and not the dropdown-openers ones as well is because the dropdown menu gets rendered later (once we determine its necessary for the overflow group to have it).

Fix overflow group test flakiness, use waitForTimeout to delay test execution

---

components/overflow-group/demo/overflow-group.html
components/overflow-group/overflow-group.js

Changes: 
- Pass click handlers through so menu-items fire their respective buttons click handlers through the dropdown menu.
- change the way throttle is being imported to prevent other packages loading 
- changes incorrect class name in the demo page

Minor fixes for overflow group

---

components/inputs/input-number.js
components/inputs/input-styles.js
components/inputs/input-text.js

See the [PR in table](https://github.com/BrightspaceUI/table/pull/235) for the full description of why this is needed. I'm hoping this is temporary until a better solution can be devised as part of the Lit migration of table sticky headers.
There is [a PR into the LMS](https://github.com/Brightspace/lms/pull/8475) to set this variable from the grades page.

feat: adding a position override for text inputs

---

components/inputs/test/input-number.test.js

Probably good to get this fix in [separate from the input number changes](#1260).

accidentally was running only input-number tests

---

components/inputs/demo/input-number.html
components/inputs/docs/input-number.md
components/inputs/input-number.js
components/inputs/test/input-number.test.js
components/inputs/test/input-percent.test.js

Lots of tricky stuff at play here, so would definitely appreciate feedback.
This fixes some major issues with how `value` (and `valueTrailingZeroes`), `minFractionDigits` and `maxFractionDigits` work together. These were problems before the trailing-zeroes stuff, but we just weren't testing/looking for it.
The problem is this: while the element is initializing, property setters get called out of order. So initially, the constructor sets default values -- which may be `undefined`. Then one by one, if an attribute is set, the property setter will get called with that attribute. But if you have properties that are interdependent on each other -- like is the case here where value gets rounded based on `maxFractionDigits`, this is problem.
As an example, I noticed that `<d2l-input-number …

fix: properly handle min/max fraction digits

---

components/card/card.js

The link inside `d2l-card` does not cover the entire card if there are borders, causing the hover states of the card and link to be out of sync. Additionally, when the card "floats" on hover, it jumps up 4px. If approached from the bottom, this causes jittering as it is no longer hovered within those 4px.
This simply resizes the link on all edges as appropriate. Tested in the demo page.
Before and after:

Fix wonky edges of d2l-card

---

components/dropdown/demo/dropdown-menu.html
components/hierarchical-view/hierarchical-view-mixin.js

This PR addresses two issues:
* ancestor views stealing focus away from nested custom views
* click and key events propagating outside the custom view
To prevent ancestor views from stealing focus, we temporarily remove `tabindex` from composed ancestors when drilled into custom views, and we restore them when drilling out.  Focusable items nested within other focusable items is kinda of a recipe for disaster.
For the click & key events, we simply call `stopPropagation` as they bubble to the custom view container.
I added some comments to the focus-capture code in effort to save some headaches of others that may read this code later, since it cost us both some time to figure it out.

hierarchical view fixes for better custom view support

---

components/inputs/input-number.js
components/inputs/test/input-number.test.js

Slight regression caused by #1260. Previously setting the value to empty string -- which [the monolith does](https://search.d2l.dev/xref/lms/lp/framework/web/D2L.Web/ui/Edit/JavaScript/EditNumber.js?r=dae941fe#32) to "clear" the input -- would result in an `undefined` value. After the recent changes, value would become `0`.
🎩  to @Dan-DeAraujo and the UI automation for catching this!

fix: treat setting value to empty string the same as clearing it

---

components/dialog/dialog-fullscreen.js
components/dialog/dialog.js
mixins/async-container/async-container-mixin.js

This PR fixes and issue where async dialogs could remain in their initial loading state forever if the dialog's local DOM is re-rendered.  In such a case, the async container would no longer have a handler for the `pending-state` event because it was previously being wired up in the `AsyncContainerMixin` `firstUpdated` method, which only runs once. The fix is to wire up for `pending-state` in `render`.

Wire-up for pending-state in render for d2l-dialog and d2l-dialog-fullscreen.

---

components/dialog/dialog-mixin.js

Rally: [US125198](https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F502279656304)
EDIT - Using `autofocus` is unnecessary here, culprit appears to be a RAF that occurs prior to initial focus
~~Overrides~~ Addresses an accessibility defect with the `dialog-confirm` component where NVDA will occasionally read off the one element focused by `_focusFirst` instead of the actual dialog text. This issue is present in all dialogs that use the dialog mixin.
~~The native `<button>` autofocus attribute (accessible through d2l-button) appears to perform the same functionality while avoiding DOM traversal and retaining screen reader compatibility.~~

fix: NVDA reads buttons instead of dialog text

---

components/focus-trap/focus-trap.js

Cert for #1351, porting only the actual fix and excluding the test and package-lock updates.

DE43639 Cert 21.06: Check for null in focus-trap focus() method

---

components/table/table-wrapper.js

When integrating this into the LMS I noticed the corners weren't rounding. It's because in MVC we include a reset stylesheet that sets the border-collapse on all tables to "collapse"... even though the default user agent style is now "separate". So need to explicitly set this here.

fix: setting border-collapse to override reset stylesheets

---

components/dialog/dialog-fullscreen.js

Safari 13 does not have the addEventListener method, specifically it can not listen for the 'change' event. An alternative is to use addListener, but it is a deprecated API. Instead, if the browser does not support addEventListener, no listener will be added at all. The typography will stay the same from when it was loaded (ie. a mobile page will stay mobile-styled).

Only add event listener if method exists (prevents issues on safari)

---

components/table/table-wrapper.js

Now that extra 👀  are on tables, it was noticed that in a few places in the LMS when the code to apply the first/last row and cell CSS classes runs, the rows aren't visible yet so nothing gets applied. This results in missing borders and no rounded corners:
This actually isn't a new problem -- I went back to the May release and the old Polymer tables had the same issue. In this instance it's a timing issue -- the table is in our legacy tabs and there's an HTML editor on the page and things just take a while to load up. But in theory the table could be legitimately hidden (maybe in a dialog that isn't open yet or an inactive tab) and that would result in the same broken behaviour.
The fix is to use an `IntersectionObserver` to detect when the table enters the viewport for the first time. …

fix: use IntersectionObserver to apply classes

---

components/dialog/demo/dialog-fullscreen.html
components/dialog/dialog-mixin.js
helpers/README.md
helpers/focus.js
helpers/test/focus.test.js

Traversing up the tree will allow us to restore focus to the first visible element when the original opening element is hidden, as in the case of a dropdown. Currently, if the original opener is hidden, the focus is lost 😢

Created focus helper to traverse up the tree to find focusable ancestor 

---

components/scroll-wrapper/scroll-wrapper.js

Very slight tweak to this behaviour to only add a tab stop on the scrollable area if it's actually overflowing.

fix: only make scroll area focusable if it's overflowing

---

README.md
index.html
mixins/demo/labelled-mixin.html
mixins/labelled-mixin.js
mixins/labelled-mixin.md
mixins/test/label-mixin.test.js

This PR adds two mixins, `LabelMixin` and `LabelledMixin` that enables elements within custom element's shadowDOM to be labelled by elements outside that shadowDOM.  For instance, it enables the following scenarios as showing in the demo page:
```html
<table>
<tr>
<td><d2l-demo-input labelled-by="topping-1"></d2l-demo-input></td>
<td><span id="topping-1" class="d2l-label-text">Caramel</span></td>
</tr>
<tr>
<td><d2l-demo-input label="Sprinkles"></d2l-demo-input></td>
<td><span class="d2l-label-text">Sprinkles</span></td>
</tr>
<tr>
<td><d2l-demo-input labelled-by="topping-3"></d2l-demo-input></td>
<td><d2l-demo-text id="topping-3" text="Hard Chocolate Coating"></d2l-demo-text></td>
</tr>
</table>
```
The idea is that a labelled custom element containing some element that requires a label, …

Add LabelMixin and LabelledMixin.

---

mixins/labelled-mixin.js
mixins/labelled-mixin.md
mixins/test/label-mixin.test.js

This PR updates the `LabelMixin` to listen for `d2l-label-change` event which provides consumers greater flexibility to compose their labelling elements - i.e. they may have a child component in their shadowDOM that provides the labelling value.

d2l-label-change event for LabelMixin.

---

.github/workflows/ci.yml
.github/workflows/license-checker.yml
.github/workflows/release.yml
.github/workflows/visual-diff.yml

We are planning on bumping the version of Puppeteer used in visual-diff and so this PR is to bump the node version to the current LTS version.

Bump node version used in GitHub actions

---

components/table/table-wrapper.js

Just noticed errors in Safari as it doesn't support `requestIdleCallback`. It doesn't seem to break anything in most scenarios as the class names get applied by the mutation observer.

fix: importing rIC shim for Safari

---

components/filter/README.md
components/filter/demo/filter.html
components/filter/filter-dimension-set.js
components/filter/filter.js
components/filter/test/filter-dimension-set.test.js
components/filter/test/filter.test.js
lang/en.js

Was working on adding the search input, but it actually made sense to get this in first so I can hook into the loading flow when a search is occurring.
This PR does a few things:
- In the multiple dimension scenario, instead of finding the first focusable item in the hierarchical view we now focus on the return button.  This helps with the case where the contents are still loading, and is actually what the design calls for and I just missed it.
- Allow the consumer to set a `loading` property to tell us to show that dimension's loading state (which for the set type is just a loading spinner)
- Fire an event when a dimension is opened for the first time.  This will be used by consumers to tell them to set the `loading` property and start loading that dimension's values if they are using …

US127106 - Ability to lazy load filter values

---

helpers/announce.js

Proposed fix for [DE44142](https://rally1.rallydev.com/#/431372673576d/iterationstatus?Iteration=%2Fiteration%2F450584189160&Name=Tooltip%20on%20input-number%20causes%20screen%20jitter%20when%20displayed%2C%20due%20to%20'announced'%20functionality%20&Priority=Low&Project=https%3A%2F%2Frally1.rallydev.com%2Fslm%2Fwebservice%2Fv2.x%2Fproject%2F431372673576&Severity=Minor%20Problem&detail=%2Fdefect%2F602453030253&iteration=u&rankTo=BOTTOM&fdp=true?fdp=true)
My hope here is that enforcing a 0px height onto this temporary div will **not** effect the functionality of said div (which, to my understanding, is only to facilitate screen readers).
At least in the case of the CPD tool, this removes any vertical space taken up by the temporary div, which eliminates the potential for any vertical …

Enforce 0px height on div created by announce.js helper

---

components/filter/demo/filter.html
components/filter/filter.js
components/filter/test/filter.test.js
lang/en.js

This PR does two things:
- Enhance the screen reader experience a bit more for the loading state (until we add more to the loading spinner itself)
- Handle a filter dimension that has no values, and utilize the same screen reader enhancements to announce this as well

US122213 - Configure filter empty state

---

helpers/mathjax.js

This is now in use, so it's important we get this back in sync with the LMS.

DE44176 - Support begin, ref, and eqref LaTeX delimiters

---

components/inputs/input-text.js
components/inputs/test/input-text.test.js

Apparently [Safari has a bug](#1458) (thanks @wongvincent) where if you set the `value` property (even to the same thing it already was), it will always move focus to the end of the input. This is a problem, because we're listening to the `oninput` event on the input and internally reflecting that to our `value` property (so consumers can access it) which in turn causes a re-render which then moves the cursor to the end -- not a good experience as the user types.
The solution is to create our own getter/setter for it, so setting `_value` from `oninput` won't cause a re-render.
While testing this I noticed that hovering while focused also caused an unnecessary re-render so I changed that logic a bit as well.

fix: don't re-render unnecessarily

---

components/inputs/input-search.js
components/inputs/input-text.js
components/inputs/test/input-search.test.js
components/inputs/test/input-text.test.js

In fixing #1458 with text-inputs, Dave noticed that search inputs would also be affected and because it wasn't using `d2l-input-text` would need the same fix applied. That got me thinking... why aren't search inputs using text inputs?
I think it was either a chicken & egg situation, or initially because text inputs didn't supports the right/left slots and search needed them search did its own thing. Well that's no longer true, and switching this over yields some pretty nice code duplication savings!

fix: switch search inputs to use text input

---

components/inputs/input-date.js

On initial load sometimes the hidden calendar height would be 0 at first and then because we disconnect it would never be updated, so `min-height` would go from 415 (a better estimate) to 0 and never to a more expected value.

input-date: fix hidden calendar height

---

components/dialog/dialog-mixin.js

This PR has two goals:
1. Make sure we're always waiting for the dialog service to be created before checking for it (presuming we're in an FRA).
2. Lazy-load the service so we only connect one ifrau client (and only create one dialog service) for all dialog components.
The root of this issue was the discovery (thanks @dbatiste for helping me debug this!) that Lit does not wait for `connectedCallback()` to finish before moving on to `updated()`. So it was possible (in fact, likely) for the check for `this._ifrauDialogService` to run before the service was actually created. This led to dialogs opening in the wrong location in FRAs if they opened too soon after first being attached to the DOM, as they would size themselves against the document.

Make sure ifrau dialog service has loaded before we try to check for it in iframed FRAs

---

components/dropdown/dropdown-content-mixin.js

I previously set the width to the maximum if no width was provided. This was causing some whitespace to be added when not necessary (like https://d2l.slack.com/archives/C0PHG3QB0/p1626188846406100). I'm wrapping the width setting to maximum for the tray-style only, as it is still needed there.

fix: Dropdown width should fit content rather than using the maximum width

---

components/card/card.js
components/card/test/card.visual-diff.js

Reverts BrightspaceUI/core#1472
The card changes aren't working in the lms as they are within our demo page. Since branching is occurring today thought It would be best to revert this while working on a fix.

Revert "Focus visible for card"

---

.github/workflows/release.yml
components/button/button-icon.js
components/button/button-mixin.js
components/button/button-subtle.js
components/button/button.js
mixins/theme-mixin.js
package.json

I actually don't think we should make the switch yet as I have a few times run the analyzer and noticed that there was at least one missing component, and we can't have that. I'll work on a way to figure out when that's happening. There also still seems to be a lot of active development going on.
If we don't want to make the switch over yet, the changes here do still work with the web-component-analyzer, and I've been able to make the changes necessary to documentation in such a way that it supports both formats, so we can be updating the jsdoc comments as we go in hopes of using this analyzer while still having Daylight work.

Component analyzer: Switch to @custom-elements-manifest/analyzer

---

.github/workflows/ci.yml
.github/workflows/license-checker.yml
.github/workflows/release.yml
.github/workflows/visual-diff.yml

Now that this is built into the `setup-node` action, seems like we can save some code by using it. Not sure whether no longer skipping the NPM install step will make things super slow, but I'll test that out.

ci: using built-in caching from setup-node

---

components/dialog/dialog-fullscreen.js
components/dialog/dialog-mixin.js
components/dialog/dialog.js

A couple of the dialog styles were overriding dialog-mixin and adding a height attribute. The problem occurs with iFrames, where a 100vh or 100% is interpreted as the height of the iFrame, rather than the viewport. This was causing super tall dialogs with the footer cut off and buttons inaccessible. 
This PR adds an override to the height of d2l-dialog-inner with the calculated height when given by the ifrauContext (minus required padding). The d2l-dialog-outer height setting is removed. 
When the dialog is NOT in an iframe, the d2l-dialog-outer height is set as previously, with no override for d2l-dialog-inner. Unfortunately, I had to add an attribute, in-iframe, for the CSS to style based on whether or not its in an iframe. Open to naming suggestions here or a way to not have to use an …

fix: US130144: dialogs getting cut off in iframes due to incorrect height settings

---

components/inputs/input-number.js

This isn't really a defect but it is causing issues with `d2l-rubric` CI and current workflows. Sadly, `d2l-rubric` is still using polymer and uses polymer related tooling for some of it's CI and development workflow. We are planning to upgrade to lit but for now this is a workaround to allow us to use the new `d2l-input-number` component in polymer.

fix: remove use of nullish coalescing operator (workaround for `d2l-rubric`)

---

components/dialog/dialog-fullscreen.js
components/dialog/dialog-mixin.js
components/dialog/dialog.js

The last PR, https://github.com/BrightspaceUI/core/pull/1511, got the dialogs to appear the correct height. Now, the override is needed for the "top" of the dialog. Otherwise, it will stay fixed to the top of the page.

US130144: add top override for iframe dialogs to continuously move dialog down the page

---

components/inputs/input-number.js
components/inputs/input-text.js
components/inputs/test/input-number.test.js

Thanks @margaree for finding this bug! A common user interaction is to tab into the input (which "selects" everything in it) and then type something new. If that first character was a decimal, we'd suppress it since the input already contained a decimal.
This change additionally checks to see if the selection range "covers" the existing decimal and if so, we don't suppress.

fix: do not suppress decimal if selection range covers it

---

components/filter/filter.js
components/filter/test/filter.test.js

When consumers decide to use the "manual" `search-type`, they have to physically remove options from the filter on search.  This avoids a lot of syncing work on our end and matches how all the consumers currently using HM search work anyways.  But when this happens, we no longer "know" how many options there are and how many are selected.  So we don't want to recount in this scenario.

Fix filter counts for the manual search type

---

components/form/form-element-mixin.js
components/form/form-mixin.js
components/inputs/docs/input-date-time.md
components/inputs/input-date-range.js
components/inputs/input-date-time-range.js
components/inputs/input-date-time.js
components/inputs/input-date.js
components/inputs/input-time-range.js
components/inputs/input-time.js
mixins/localize-mixin.js

Changes:
- prep `input-date-time.md` for Daylight
- component file tweaks to wording to get things like tense consistent
- `@ignore` for some properties coming from mixins, and some events (this is also affecting the old analyzer)

Daylight: date & time inputs

---

components/dropdown/dropdown-content-mixin.js

Dave Lockhart found this issue during the testing of d2l-dropdown. In some cases, the _openedChanged function runs before the content inside the dropdown has a chance to fully render. This is causing "this.__getContentContainer()" to return null in some cases, causing Javascript errors in the console. 
Note that this only occurs on Firefox, and only on some dropdowns in the LMS. The dropdown still appears and is clickable despite the error. Adding an await to wait for all updates to complete ensures the content can be found in all cases.
I'll also be certfixing this into 20.21.8, as the console error occurs there as well.

DE44538: Wait for content to fully render before getting the contentContainer

---

components/dropdown/dropdown-content-mixin.js

Backport to 20.21.8 for https://github.com/BrightspaceUI/core/pull/1523.

fix: DE44538: Wait for content to fully render before getting the contentContainer

---

components/dropdown/dropdown-content-mixin.js

Backport to 20.21.8 for #1523.
NOTE: this is the second attempt at backporting. The first attempt failed to release due to my mistake in not branching from the last release action. This caused semantic release trying to re-release 1.150.5 rather than the new patch 1.150.6. See https://github.com/BrightspaceUI/core/pull/1530 for the issue.

fix: DE44538: Wait for content to fully render before getting the contentContainer 

---

components/calendar/README.md
components/link/README.md

May 2020 is a 6 row so the autoSize then works correctly from the start.
Link using autoSize was resizing when certain properties were changed, so I hard set the size. I'm adding a `xsmall` height, so there will be a separate PR for that in documentation.

Daylight: tweaks to link and calendar

---

components/calendar/README.md

Attributes should be on single line or else they don't seem to update (something potentially to look into in documentation as well, not sure on fix complexity).

Daylight: Calendar: Attributes should be on single line

---

components/tooltip/tooltip.js
mixins/localize-mixin.js

Just fixing up an "easy win" in the Lit 2.0 migration. `_getUpdateComplete` [was renamed to](https://lit.dev/docs/releases/upgrade/#update-to-renamed-apis) `getUpdateComplete` but was also backported so we can just start using it now.

fix: using getUpdateComplete instead of _getUpdateComplete

---

components/filter/test/filter.test.js
components/inputs/input-date.js
components/inputs/input-percent.js
components/inputs/input-text.js
components/inputs/input-time.js

Another quick Lit 2.0 fix. `requestUpdate` [no longer returns a Promise](https://lit.dev/docs/releases/upgrade/#litelement) in Lit 2.0, so instead you're supposed to `await elem.updateComplete` which was always a thing we could have done.

fix: awaiting updateComplete instead of requestUpdate()

---

components/table/README.md
components/table/demo/table-test.js
components/table/table-col-sort-button.js
components/table/table-wrapper.js

This one was a bit complex to get working in Daylight due to not really being a component. I ended up utilizing the demo test-table for the live demo, partially because it is difficult to create a component in the documentation repo and have that imported into a demo. I added a few rows to the demo in order to better showcase sticky-headers and also added `no-column-border`.
I just kept the gifs for sortable column buttons and selection since that was simpler. Those are also shown in the live demo, though their properties can't be interacted with since it's more a demo of the wrapper.

Daylight: Table

---

components/icons/icon.js

Just a couple small tweaks to our icon component:
1. I noticed in the Lit documentation that there's a `unsafeSVG` directive which is preferable here to the scarier `unsafeHTML`.
2. Using a `<template>` to temporarily store the SVG DOM while we manipulate it should be slightly better since templates aren't part of the main DOM so the browser skips certain steps (like fetching image paths).

fix: using unsafeSVG and a template

---

lang/fr.js

Based on the convo here: https://github.com/BrightspaceUI/core/pull/1553#discussion_r680142768
The government of Canada site uses `Rechercher`, Ontario's site and Quebec's immigration site use `Recherche`, CBC uses both... I think we're probably good with either, rather than "Search in progress" as below.

Change French translation for search placeholder

---

components/tooltip/test/tooltip-helper.js
package-lock.json
package.json

Now that the `ignorePackages` is in version 0.16, this upgrades core to it. I made all the fixes previously, but this reverts the `visual-diff` one since it's no longer needed with that option.

upgrading to eslint-config-brightspace version 0.16

---

components/inputs/input-number.js

[DE43948](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F601576690591&fdp=true?fdp=true): Update score out of field to be d2l-input-numeric in FACE Assignments
When the `input-number` component is re-rendered (e.g. due to conditional rendering), `autofocus` does not work and component validation isn't triggered correctly for reasons unclear.
Awaiting `input-text` to `updateComplete` let's us access the component when it has finished rendering.
This problem surfaced when trying to update the score input in FACE Assignments to use `input-number` over `input-text`.

`input-number`: `await` wrapped `input-text` to render so it can focus

---

components/dialog/demo/dialog-async-content.js
components/icons/icon.js
directives/run-async/run-async.js
directives/run-async/test/.eslintrc.json
directives/run-async/test/run-async.test.js
mixins/async-container/demo/async-item.js
mixins/async-container/test/async-item.js

The Lit 2.0 migration of directives is pretty significant, so I wrote some unit tests around the existing Lit 1.0 directive to help avoid regressions.
I'll leave this open until @dbatiste has had a chance to review.
To make room for the tests, I also decided to move the directive into its own directory. Technically this is a breaking change, but a quick code search revealed that we're only using this internally inside core, so seems safe-ish.

Lit 2.0: run-async tests

---

components/inputs/input-number.js
components/inputs/test/input-number.test.js

Another issue @matthe97w uncovered.
Normally, when you press ENTER in a text input it will automatically fire the `change` event if the value has actually changed. But we were accidentally suppressing that as part of our code that suppresses non-numeric characters, which meant focus needed to be lost before the `change` event would fire.
This corrects that.

fix: allow ENTER to be pressed to trigger change event

---

.github/workflows/visual-diff.yml
directives/run-async/run-async.js

Building on the new unit tests, this converts the directive to follow the new Lit 2.0 class-based syntax:
https://lit.dev/docs/templates/custom-directives/#async-directives
The big change with the class-based directives is that a `WeakMap` is no longer needed for state, which can instead move into the class. This simplifies things a bit in that you always have access to that state in the callbacks and don't need to keep grabbing it and confirming that it's valid.
Things also get split out into `render()` (which can run on the server) and `update()` which does not. So that's where I put the firing of the `pending-state` event.

Lit 2.0: convert run-async directive to class-based syntax

---

components/inputs/input-time.js

Fixes https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fdefect%2F605123292669&fdp=true
The issue is that when an EOD time (i.e. 11:59 PM) is entered manually, the seconds value is set to 0, and when the default value of END_OF_DAY is used, the seconds value is set to 59. The causes problems when comparing times.

fix: seconds value of manully entered EOD time

---

package.json

Now that we're using the Lit 2.0 directive syntax, we need an explicit dependency on `lit-html` >= `1.4.1` which is when it was added. Without this, some FRAs are failing to install core.
🎩 -tip to @tylergee for noticing this!

Explicit dependency on lit-html 1.4.1

---

components/demo/demo-snippet.js

This allows elements that want to use scroll wrapper and overflow to display correctly in demo snippets. It will hide the overflow and allow scrolling with arrow buttons when `overflow-hidden` is supplied. This also makes the code view always be the same width as the demo snippet when it is part of the snippet. It will still have the maximum width by itself.
These changes were mainly done to support rubrics so we can switch to using the standard demo snippet. It was tested with core demo pages as well as rubrics.
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/9043211/131190781-03633b2f-64df-4d17-bf67-146a813a9c8b.png)|![image](https://user-images.githubusercontent.com/9043211/131190749-7020763f-e540-467e-bf83-0ae300a67c5a.png)|

fix: demo snippet styling

---

components/filter/README.md
components/filter/demo/filter-search-demo.js
components/filter/demo/filter.html
components/filter/filter-dimension-set.js
components/filter/filter.js
components/filter/test/filter.axe.js
components/filter/test/filter.test.js

This PR adds the ability to turn on `selection-single` for the set dimension, so that only one value can be selected from the list.  When the value selected changes, the batched change event will have two changes in the array - one turning on the new filter value, and one turning off the old filter value.  Therefore no special function/handling is needed for a `selection-single` list versus a multi-select one.
This PR doesn't adjust filter counts for this case.  After talking to Jeff, we decided we're going to remove the "All" language and keeping track of the total.  It has the potential to cause more confusion than help, and is not super intuitive in the single selection case anyways.  It also simplifies integrating the future `count-badge`.  This functionality will be removed in the …

US126584 - Add selection-single to d2l-filter-dimension-set

---

components/dialog/dialog-mixin.js
components/dropdown/dropdown-content-mixin.js
helpers/ifrauBackdropService.js

Currently, the trays work by being pinned to one side by using something like bottom: 0. However, this doesn't work in iframes, where the inner height and width of the window is actually the height and width of the iframe (much larger than the screen). In those cases, pinning to the bottom requires users to scroll to the bottom of the iframe, rather than having the tray pop up in the viewport. 
This PR leverages the existing IfrauDialogService to add/remove backdrops on iframed pages as needed. I've pulled out the logic into a helper, since it's identical to the dialog-mixin usage.

Adding logic for dropdown mobile trays to work in Iframes/ non-responsive screens

---

components/filter/filter.js
components/filter/test/filter.test.js
lang/ar.js
lang/cy.js
lang/da.js
lang/de.js
lang/en.js
lang/es-es.js
lang/es.js
lang/fr-fr.js
lang/fr.js
lang/ja.js
lang/ko.js
lang/nl.js
lang/pt.js
lang/sv.js
lang/tr.js
lang/zh-tw.js
lang/zh.js

We're no longer going to say "All" when every filter has been selected, since this implies having everything selected is the same as having nothing selected (which might not be true).

US126584 - Remove max count functionality in filter

---

mixins/rtl-mixin.js
mixins/test/rtl-mixin.test.js

In doing some performance tracing, you end up seeing a non-zero amount of time spent setting `dir="ltr"` on every element, some of which is causing a style recalculation/repaint.
Since are styles only ever target `dir="rtl"` we can optimize the performance by not reflecting the attribute when the document direction is left-to-right.

fix: don't reflect LTR direction attribute for performance

---

README.md

Since `mocha` isn't installed globally by the command above, you need `npx` in front for it to work.

docs: prefix visual diff commands with "npx"

---

components/table/table-wrapper.js

This is pretty bad! We're doing the one thing you're never supposed to do -- read something that would force layout to be calculated and then immediately write inside a loop. It's [the main example](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_layout_thrashing) of layout thrashing. Oops!

fix: avoid layout thrashing inside a loop

---

components/inputs/input-text.js

Our text inputs have some code that measures the widths of its slots in order to apply that same amount of padding, essentially reserving room for the absolutely positioned slots.
This measuring via `getBoundingClientRect()` forces the browser to paint the screen -- possibly before it's ready to do so. In performance speak, this is called a [forced synchronous layout](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_forced_synchronous_layouts).
When the page just has one or two of these components on a page, it's not super noticeable... but the grades "spreadsheet view" could potentially have _thousands_ of them, and the more elements on the screen the longer it takes to paint, which creates an exponentially slower …

fix: avoid and defer measuring slot sizes to improve performance

---

.github/workflows/perf.yml
components/inputs/input-text.js
components/inputs/test/input-text.perf.js
helpers/perfMonitor.js
karma.perf.conf.js
package.json
tools/perf-test-helper.js

This adds some experimental performance testing of our components to core, starting with `<d2l-input-text>`.
How this works:
- Components add a "performance monitor" controller. Once we go to Lit 2, this can be a proper Reactive Controller and all the hooks will work automatically.
- The performance monitor calculates the amount of time that passes between when the component is connected and when it renders. It then fires an event that we can listen for elsewhere.
- I've created a special Chai plugin so you can create a fixture and then assert that `.it.is.performant(val)`. The value you pass in there is the expected average render time of the component. Coming up with this value is going to take a bit of trial & error. I'm hoping the variance in CI isn't too high.
For now I'll make this …

testing performance of text input

---

templates/primary-secondary/primary-secondary.js

This is required to get the dropdown trays (specifically user-profile-card" to render correctly on top of the primary-secondary footer. Without this, the footer goes overtop of the close button of the tray making it not clickable. With this change, the page functions normally, and the dropdown can go on top of the footer when it opens.  The z-index was added here for a previous bug (https://github.com/BrightspaceUI/core/pull/770), which looks like it it is still fixed when the footer has a z-index of 1. I took a look at the LMS and the primary-secondary pages appear to look the same.
Here's a before and after:
I was wondering why this issue didn't appear with the date-picker, and it seems to do with the HTML order that determines the stacking context on each page.

fix: US130195 - Lower z-index for primary-secondary footer

---

components/hierarchical-view/hierarchical-view-mixin.js

In hierarchical view's `connectedCallback`, it's making a call to `this.__autoSize()` (inside an rAF). That method checks `offsetParent` and gets a bounding rectangle -- both of which force layout. But hierarchical view is almost always inside a menu, which is almost always hidden inside a dropdown -- so there's nothing to calculate (yet).
This change adds an intersection observer (my new favourite toy) to determine when the hierarchical view first becomes visible. At that point it can automatically size itself.

HierarchicalView performance fix

---

components/typography/typography.js
components/typography/typography.scss

The existing fonts we were using -- specifically "Arabic Typesetting" -- resulted in really small, really serif-y and were hard to read both in Arabic and with Latin characters:
Mostly we never noticed this because most machines don't actually have "Arabic Transparent" or "Arabic Typesetting" installed, and when that's the case it falls back to Windows' default "sans-serif" font of "Segoe UI". So this change just uses "Segoe UI" on Windows (and keeps Geeza Pro on macOS). Segoe UI should be on all Windows machines dating back to at least Vista, but even if it's not available this change means it'll use the system's default sans-serif font which should still be fine.
With the change:

fix: switching Arabic font on Windows to "Segoe UI"

---

components/filter/README.md
components/filter/demo/filter-search-demo.js
components/filter/filter.js
components/filter/test/filter.test.js

Having the consumer remove the values when doing manual search caused lots of complications with single selection, searching, and clearing.  Instead, they will now pass us an array of the keys they want displayed for that search value.
This PR also fixes the issue where selecting + single selection + manual search is broken.

US131759 - Simplify manual search for filter

---

components/list/list-item-checkbox-mixin.js
components/list/test/list-item-checkbox-mixin.test.js
components/selection/selection-input.js
components/selection/selection-mixin.js

This PR updates `d2l-selection-input` to not delay dispatching `d2l-selection-change` event with rAF.  In the single selection scenario, two events are dispatched if a previously selected item becomes unselected as a result of a newly selected item.  By not delaying the dispatch statement, the two events should be dispatched in the same frame, making consumer code less fragile.  Also, I think this also improves some jankiness observed when toggling the selected state.

Update d2l-selection-input to not delay dispatching d2l-selection-change.

---

components/status-indicator/README.md

@GeorgePlukov, I also noticed the bullet points (Best Practices) somehow get periods added at render time. Any idea how to stop that? Couldn't find anything about it on the web.

Removing duplicate js import

---

components/selection/selection-mixin.js
components/selection/test/selection.test.js

This PR addresses a timing issues that manifest in this test error:
>SelectionObserverMixin
:heavy_multiplication_x: unregisters and registers the SelectionMixin component
Chrome 93.0.4577.63 (Mac OS 10.15.7)
AssertionError: expected ‘none’ to equal ‘some’
If inputs were subscribed after the observers, the observer's `selectionInfo` could be out of date if the newly subscribed inputs result in a change in a selection change, because up until now, subscribing inputs did not cause the observers to be notified with updated `selectionInfo`.  It is not guaranteed that the inputs will be subscribed before the observers or vice versa.  I think that this issue could actually manifest itself in the wild, not just a test.
Previously (before my changes  [initial nested …

Update the SelectionMixin to update observers when new inputs are subscribed.

---

components/dropdown/dropdown-content-mixin.js

This solves the weird behaviour when the data-mobile property sometimes does not get set after the screen changes to mobile, causing some funky styling. See GIFs below. It might also be a performance improvement since we can rely on the property rather than asking the mediaQueryList if we are in mobile mode. This fix should also fix similar problems with the daylight site as well. 
Before:
After:

fix: DE45163 - query the useMobileStyling property rather than the mediaQueryList 

---

components/filter/README.md
components/filter/demo/filter-search-demo.js
components/filter/demo/filter.html
components/filter/filter.js
components/filter/test/filter.test.js

This is a step to make the upcoming clear button PR cleaner.  In order to pass info about whether a dimension has been cleared, the `d2l-filter-change` event has been reformatted.  I've also broken out `_dispatchChangeEventNow` and `_setDimensionChangeEvent`, which will be used when clearing to set all values and then immediately send the event.
Before:
```
detail: {
changes: [
{
dimension: "course",
value: { key: "art", selected: false },
},
{
dimension: "course",
value: { key: "biology", selected: true },
},
{
dimension: "role",
value: { key: "admin", selected: false },
},
{ ... }
]
}
```
Now:
```
detail: {
dimensions: [
{
dimensionKey: "course",
changes: [
{ valueKey: "art", selected: false },
{ valueKey: "biology", selected: true }
],
(eventually info about whether this dimension was …
```

Reformat the d2l-filter-change event

---

components/html-block/html-block.js

In non-Chromium browsers, setting the shadowroot's innerHTML this way wipes out its styles (thanks for looking into that, @dlockhart!). This means the host styles don't get applied and wrapping stops functioning. Instead of replacing the inner HTML, append to it instead to ensure we keep any styles that may be there.

Don't wipe out shadowroot styles in non-Chromium browsers

---

components/hierarchical-view/hierarchical-view-mixin.js
components/menu/test/menu-rtl.visual-diff.js
components/menu/test/menu.visual-diff.js

In the filter, the combination of the dropdown header and hierarchical-view content rendering at the same time means Safari sometimes throws the `ResizeObserver loop completed with undelivered notifications` error.  This didn't occur when the filter header was smaller, but adding the clear button means it might trigger a resize.
I tested in `filter`, `menu`, `dropdown` and `hierarchical-view` and don't see any behaviour change with delaying this event a frame.

DE45328 - Delay hierarchical-view-resize event to prevent ResizeObserver errors

---

components/form/test/form-error-summary.test.js

Skipping this flaky test which is failing in Firefox a lot since the move to `@web/test-runner`. I'll investigate it separately.

skip flaky test

---

components/alert/test/alert.test.js
components/card/card.js
components/demo/code-view.js
components/dialog/dialog-styles.js
components/dropdown/dropdown-content-mixin.js
components/html-block/test/html-block.test.js
components/inputs/input-checkbox.js
components/inputs/input-text.js
components/inputs/input-textarea.js
components/inputs/test/input-text.test.js
components/inputs/test/input-time-range.test.js
components/list/list-item-drag-drop-mixin.js
components/tooltip/tooltip.js
mixins/test/localize-mixin.test.js

Just some follow up legacy-Edge cleanup (and a bit of IE11 cleanup) after @svanherk removed it from our unit testing.
I've only cleaned up things that would impact our testing code -- there are still a bunch of legacy-Edge hacks/references in the actual code which I think we want to leave in until we get the official "all clear".

Cleanup legacy-Edge from Tests

---

components/dropdown/dropdown-content-mixin.js
components/inputs/input-date.js

Legacy screens are not responsive, meaning setting bottom: 0 will put the date-picker way at the bottom of the page rather than at the bottom of the screen. I initially tried to remedy this by setting the bottom to be the difference between window and screen sizes, but that hasn't been working consistently as Mark found in his testing. 
I've got a new approach where the bottom is still set to zero (at the bottom of the page), but the calendar is scrolled into view and fully visible. Once the calendar is closed, the focus is shifted back to the text input for the date. I don't think moving to the bottom of the page should be an issue since there is no guarantee we can see the text input anyways, it could be blocked behind the tray. Note that this change will affect the non-responsive pages …

DE45295: Fixing date-picker positioning on legacy screens

---

components/filter/demo/filter-search-demo.js
components/filter/filter.js
components/filter/test/filter.test.js

The disabled state of select all is a bit hard to see and isn't providing any value in the loading and empty states, so we now just hide it instead of disabling it.

US131477 - Hide select all when loading or empty

---

components/filter/filter.js
components/filter/test/filter.test.js

Thanks to @annabelsegalld2l for catching this!  Pressing `esc` in the header of a nested dimension would close the dropdown (because `dropdown` was handling it), whereas pressing it in the content/list would return to the dimension list (because `hierarchical-view` was handling it).  We want it to always return to the dimension list so I need to handle it manually in the header.  This also fixes a bug where I wasn't setting `this._activeDimensionKey` to `null` if the `esc` method was used instead of the back button, so the header wasn't updating correctly.

US131477 - Fix esc behaviour in filter

---

components/filter/filter.js
components/filter/test/filter.test.js

We also want the user to be able to press the left arrow key in a nested dimension and go back to the dimension list.  So just adjusting the previous behaviour to handle this for `esc`.

US131477 - Add left arrow functionality to filter

---

components/list/list-item-checkbox-mixin.js
components/selection/selection-input.js
mixins/demo/labelled-mixin.html
mixins/labelled-mixin.js
mixins/test/label-mixin.test.js

If the `label` attribute is missing on one of our input elements, or if `labelled-by` is pointing to an element that doesn't exist or has an empty label, it's a P1 accessibility violation. We're pretty inconsistent with how we notify developers of missing labels -- sometimes we do nothing, occasionally we `console.warn` in `firstUpdated`.
This change attempts to centralize the reporting of that error from `LabelledMixin` in a way that doesn't initially blow up for all the existing implementations that might be unknowingly missing labels. It will throw the error but not block rendering, so that we can go through the error logs and find any problem areas.
If this approach looks good, I'll do some follow-up PRs to actually adopt the `LabelledMixin` in more (or all) of our input components. …

LabelledMixin validation of missing labels

---

components/tooltip/tooltip.js

Currently, the count badges are throwing accessibility warnings with the tooltip, even though they have the correct role. Adding the img role to the interactive roles removes the warning. 
I did also try out the announced property on the tooltip (made for custom elements), but it's behaviour was not quite what I wanted. When it announces the tooltip text, it announces the text of all the tooltips on the page (which would get super repetitive).

fix: add img to interactive tooltip roles to suppress tooltip warning

---

components/list/demo/list-item-custom.js
components/list/demo/list-nested.html
components/list/list-item-checkbox-mixin.js
components/list/list-item-mixin.js
components/selection/selection-mixin.js
components/selection/test/selection.test.js

This PR updates the wire-up of a parent list-item as an observer of a nested list to be done via a custom `d2l-selection-provider-connected` event rather than `slotchange` event.  This is because consumers of the `ListItemMixin` (such as HM components) may populate the nested slot with "default" content, such that the `slotchange` event does not get dispatched. It also updates the demo page to help facilitate testing, although it is not included in the demo index because it is subject to change since the docs and demos will be rewritten.

Support nested content in custom list-items.

---

components/inputs/input-date-time.js
components/inputs/input-date.js
components/inputs/input-number.js
components/inputs/input-percent.js
components/inputs/input-text.js
components/inputs/input-textarea.js
components/inputs/input-time.js
components/inputs/test/input-date-time.axe.js
components/inputs/test/input-date.axe.js
components/inputs/test/input-number.axe.js
components/inputs/test/input-percent.axe.js
components/inputs/test/input-search.test.js
components/inputs/test/input-text.axe.js
components/inputs/test/input-text.test.js
components/inputs/test/input-textarea.axe.js
components/inputs/test/input-time.axe.js
components/list/list-item-checkbox-mixin.js
mixins/labelled-mixin.js

`LabelledMixin` is a pretty sweet way to get consistent labelling & missing label exception handling across all our components. It also supports `labelled-by`, which is pretty sweet.
So this PR updates almost all of our inputs to use it: `d2l-input-text`, `d2l-input-textarea`, `d2l-input-date`, `d2l-input-time`, `d2l-input-date-time`, `d2l-input-number` and `d2l-input-percent`.
There are a few like the date/time range components and the checkbox/radio components where it would either be difficult (the ranges have multiple labels) or weird (checkboxes and radios use fieldsets), so I left those for now.

Use LabelledMixin in our input components

---

components/html-block/html-block.js

If an `html-block` is detached from the DOM, we disconnect its template observer. However, when re-connecting to the DOM, we never re-attach it. This leads to an interesting problem where if the template contents change, there's no way for the component to pick up and act on that change.

Re-connect template observer if html-block is re-connected to the DOM

---

components/dropdown/dropdown-opener-mixin.js
components/dropdown/test/dropdown-content.test.js

After some testing, looks like the touchstart event is a duplicate of the clicking action. Removing that listener will simplify the code a bit!
Also, I changed the dropdown click behaviour to lock open the dropdown, so that if users click on the dropdown, they can hover away and the dropdown will not close. This is consistent with the old user-profile card. Clicking inside the dropdown, similar to clicking the opener, should allow the dropdown to be kept open. I added a test for this as well.
Also, I fixed the opener check in the listeners. There are generally two cases with the mouseup/leave events:
- Src element is the opener itself (ie. d2l-dropdown-more, this is how most of our buttons work)
- Src element is some element within the button (ie. a span within the opening button)
- We …

feat: US133079: Removing the touchstart event, fixing opener check

---

components/demo/demo-snippet.js

Add a `fullscreen` property to `DemoSnippet`. This will enable consumers to have fullscreen demo snippets.

Add `fullscreen` property to `DemoSnippet`

---

helpers/README.md
helpers/composeMixins.js

Proposed addition as an aside from some of the [rubrics Lit conversion work](https://github.com/Brightspace/d2l-rubric/pull/1295#discussion_r743976360) that Mango is doing
```js
class ExampleComponent extends LocalizeMixin(EntityMixin(LitElement)) {
// ...
}
```
```js
class ExampleComponent extends composeMixins(
LitElement,
EntityMixin,
LocalizeMixin,
) {
// ...
}
```
Using the helper is more readable, allows for cleaner diffs, and makes it easier to add and arrange mixins in a logical fashion.

Add compose mixins helper

---

components/dropdown/dropdown-content-mixin.js
components/loading-spinner/loading-spinner.js

Legacy edge is gone so we are safe to remove these styleSubtree CSS setters 🎉 
I did test on a current Edge version to make sure it was still working by setting the vertical-offset attribute.

feat: Removing IE11 CSS variable setters

---

components/button/README.md

Found because of the new Daylight visual-diffs🎉
I moved these to be on one line in a previous PR and forgot to remove the space

fix: remove button space

---

components/dropdown/test/dropdown-content.visual-diff.js
components/filter/test/filter.visual-diff.js

For dropdowns with empty content, the focus should go to the close button on the mobile tray. Sometimes, the tests get flaky because the close button is not getting focused on. The dropdown requests a new frame before focusing, so adding that to the test as will **should** stop the flakiness. 
I'll rerun a couple of times to make sure the flake doesn't happen again.

Visual diffs: add a requestAnimationFrame to mobile dropdowns

---

components/dropdown/dropdown-content-mixin.js
components/dropdown/dropdown-opener-mixin.js

Just lumped two one-liners into one PR here. 
1. The hovering dropdown was previously forcing focus on click events, similar to keyboard openings. I've changed it to not apply focus, to be consistent with our other dropdown behaviour (note that the PR that George is working on might force focus anyways, but not visibly).
2. Adding an applyFocus detail to the focus-enter event. This will allow consumers to know if the focus was actually applied to the first element. The focus-enter event will always be dispatched regardless of applying focus, so adding the detail lets consumers know when to override that focus (ie. profile card will use this to force focus on another element, but only on keyboard events).

fix: fixing hovering dropdown focus behaviour on click - should not force focus

---

components/inputs/input-date-time.js

Older tools like polymer don't recognize the ?. syntax, leading to some transpile errors. See https://github.com/BrightspaceHypermediaComponents/activities/runs/4291411518?check_suite_focus=true for an example.

fix: remove optional chaining syntax to prevent transpile errors in activities

---

components/html-block/demo/html-block.html
components/html-block/html-block.js
components/html-block/test/html-block.test.js
helpers/mathjax.js

This is a shot at supporting synchronous rendering within the html-block component. There are a couple things to point out here:
- We can't synchronously render math. The MathJax shadowDOM adaptor is incompatible with this, since it itself pulls the rendering elements into a new document, manipulates them, and then renders them back to the DOM. MathJax's APIs seem to expect a full document as input, so I see no way around this.
- Related to the above, we need to prevent any renderers with this requirement from running if we're in non-deferred mode. I figure that's the purpose the `canRenderInline` property on the renderers can serve.
- Given that this should only be used in specific LMS use cases, I've effectively made this behaviour opt-in via replacing the usual `template` with a `div` …

Support synchronous (non-deferred) rendering in html-block

---

components/html-block/demo/html-block.html
components/html-block/html-block.js
components/html-block/test/html-block.test.js
helpers/mathjax.js

MathJax allows a global scale property to be attached to its output renderers that renders math at some fixed scale (perhaps unsurprisingly) larger or smaller than the surrounding text. This is configurable within the LMS, but it turns out it hasn't been functional in the component.
MathJax creates a test element within the document and tries to compute its style to figure out all of its base measurements (font-size, ex-height, etc.), which it then multiplies by the scaling factor. However, we use two layers of temp elements that aren't attached to the DOM, so `window.getComputedStyle` returns empty attributes when MathJax does this checking. Hence it ignores that scale factor entirely.
Proposed solution: Within the html-block component, attach the temp element to the render container and …

US133950 - Keep temp elements connected to the DOM during rendering so MathJax can find style properties

---

components/form/form-element-mixin.js
components/form/test/form-element.test.js
components/inputs/test/input-number.test.js

Automatically call `requestValidate` when a custom validator is added to prevent race conditions when attempting to validate based on a custom validator.

Revalidate inputs when a custom validator is attached

---

components/count-badge/test/count-badge-icon.visual-diff.html

This also must have gotten missed when we removed it everywhere.

removing polyfill

---

README.md
controllers/subscriber/README.md
controllers/subscriber/subscriberControllers.js
controllers/subscriber/subscriberControllers.md
controllers/subscriber/test/.eslintrc.json
controllers/subscriber/test/subscriberControllers.test.js
package.json
web-test-runner.config.js

Cleaned up version of https://github.com/BrightspaceUI/core/pull/1901.  Creates a new `controllers` folder with new subscriber controllers inside, along with tests and a README.  The README was surprisingly difficult to write and I don't love it - feedback welcome

US134384 - Add new subscription controllers

---

components/filter/filter.js
components/filter/test/filter.test.js

This was an easily separated piece.  These three functions will be needed by the applied filters lab component, who can request to clear an individual active filter (when the user removes a tag) or request to clear all active filters (by pressing the "clear filters" button).  When all filters are cleared, the component moves focus back to the filter (even if we don't want to keep that functionality in the final `core` version, having a `focus` function on the filter isn't a bad thing).

US134386 - Add public filter functions needed by the applied filters lab component

---

.github/dependabot.yml

I don't really remember why we were locking Mocha to version 8, but 1) core doesn't have an explicit dependency on Mocha anymore and b) we're now successfully using Mocha 9 for visual-diff testing so any issues should be resolved.

removing mocha dependency lock

---

package-lock.json
package.json

None of the breaking changes seem to impact us, and this passes locally.
I'll update the `npm init` generator shortly.

upgrading to use eslint version 8

---

.github/dependabot.yml

While reviewing this I noticed we had ignored these upgrades through the PR workflow but should probably list them out explicitly here, along with the reason.
I'm going to make this change to the `npm init` generator too, otherwise new repos will suddenly get Dependabot PRs to upgrade Lit.

explicitly ignoring dependabot updates

---

components/filter/filter.js
components/filter/test/filter.test.js

For the filter count tests I just want to check the count logic, I don't actually check the DOM nodes being rendered. So here I'm stubbing out `requestUpdate` so that setting `_totalAppliedCount` in `_setFilterCounts` doesn't cause a render.  This will avoid errors around missing labels.  I could also add `text` info to the data, but I don't need the DOM nodes anyways so figured this was more performant.
The `LabelledMixin` could also be enhanced to not warn about missing labels of disconnected nodes, but it will get this for free when/if we move it to the new [`idSubscriberController`](https://github.com/BrightspaceUI/core/blob/main/controllers/subscriber/subscriberControllers.js#L98).

Fix Filter tests in Lit 2

---

components/count-badge/count-badge-mixin.js
components/demo/code-view.js
components/filter/filter.js
components/filter/test/filter.test.js
components/form/form-element-mixin.js
components/list/demo/list-drag-and-drop.js

This PR, in combination with https://github.com/BrightspaceUI/core/pull/1945, allows core to transition to lit 2 with changes to the package-lock only.  I am following the changes outlined in https://lit.dev/docs/releases/upgrade/. 
I also had to make changes to the filter unit tests due to some issues with sinon stubs and internal lit changes.

US134551 - Lit 2 Prep - Non-breaking Compatibility changes for lit 2

---

components/filter/test/filter.test.js

This worked for me locally and in Sauce, but CI seems to have some trouble with it.  I've adjusted the test to just unselect the value of the `single-selection` list instead of selecting a new one (which causes an unselect and a reselect).  I'm having trouble finding a consistent timing setup that works for that.

Fix Flaky Filter Test

---

components/button/test/button-icon.perf.js
components/card/test/card-footer-link.axe.js
components/dialog/test/dialog-confirm.test.js
components/dropdown/dropdown-content-mixin.js
components/form/form-element-mixin.js
components/inputs/test/input-number.perf.js
components/list/demo/list-item-custom.js
components/list/list-item-generic-layout.js
components/menu/menu-item.js
helpers/demo/announce-test.js
package.json

This PR ignores the `no-unknown-tag-name` warnings because we know these are broken ([more info here](https://github.com/runem/lit-analyzer/issues/34)).  It also tries to fix a number of real warnings, getting our total down from 99 to 66.
These are the remaining warnings we'd need to fix to get rid of all analyzer warnings:
- `animate` directive:
- Unknown property `animate` (will go away with Lit 2)
- `FormElementMixin`:
- `forceInvalid` is ignored
- `invalid` is ignored
- `noValidate` is ignored
- `d2l-input-date`:
- `has-now` is ignored
- `novalidateminmax` is ignored
- `d2l-input-number`:
- `trailing-zeroes` is ignored
- `value-trailing-zeroes` is ignored
- `d2l-selection-input`:
- `hovering` is ignored
- `_indeterminate` is ignored
- `d2l-table`:
- Placing `selected` on `tr`s
- …

Ignore broken analyzer warning and fix other easy warnings

---

components/html-block/html-block.js
components/html-block/test/html-block.test.js
helpers/mathjax.js

The problem with not bothering to render math at all when `noDeferredRendering` is set is that we're still reliant on MathJax's global rendering in that case... But if we don't run the renderer we never load MathJax!
So I'm not tied to this solution necessarily, but it feels like the cleanest... Pass `noDeferredRendering` to the renderers as an option and let them figure out how they should support it. The math renderer can still load MathJax if needed and then bail before doing any inline replacements. Other renderers can, in theory, do something entirely different.

Make sure MathJax loads even if only a single non-deferred html-block is loaded on the page

---

components/inputs/input-checkbox.js

When the offscreen description is inside the `<label>`, assistive technology like NVDA reads it twice since technically it's also part of the primary label.
This change moves it outside to solve that. Confirmed that this solves the issue.

fix: moving checkbox description

---

components/inputs/input-radio-styles.js

This PR fixes focus/hover styles for input-radio in Safari. The previously used override was not sufficient.
Previously it looked like:
Now it looks like (consistent with other browsers):
For context, this was discovered and raised where single-select list-items are being used in a dialog and the outline was being cut off due to the dialog's overflow properties:

Update input-radio-styles to hide outline in Safari.

---

.github/workflows/update-package-lock.yml
CODEOWNERS

Have it set to run every morning and to auto-approve and auto-merge.  To do that, I need to undo the code reviewers approval requirement for `package-lock.json` and I'll turn on the auto-merge functionality in this repo.
Once merged, I'll manually trigger it to make sure everything works properly

Add update-package-lock workflow

---

lang/es.js
lang/fr-fr.js
lang/ja.js
lang/nl.js
lang/zh.js

Changing all the count badge langterms back to using "{number}+" rather than multi-word langterms. We never heard back from localization, so we are keeping with our decision to not localize the term.

DE45955: change all count badge plus langterms to "{number}+"

---

components/dialog/dialog-mixin.js
components/dialog/test/dialog-mixin.visual-diff.js
components/dropdown/test/dropdown-content.test.js
components/filter/filter.js
components/filter/test/filter.test.js
components/hierarchical-view/hierarchical-view-mixin.js
components/hierarchical-view/test/hierarchical-view.test.js
components/inputs/test/input-date.visual-diff.js
components/menu/test/menu.test.js
components/menu/test/menu.visual-diff.js
components/tooltip/test/tooltip.test.js
helpers/dismissible.js
helpers/test/dismissible.test.js

Native/OS elements like `<select>` and `<dialog>` dismiss when Escape is pressed on `keydown`. But because our dismiss code is listening for `keyup`, in these scenarios we execute a second dismiss action.
For example, a dialog or dropdown which has a `<select>` in it -- if the user opens the `<select>` and then presses Escape, the OS/browser will dismiss it and prevent default on that `keydown` event. But a `keyup` event still fires, which hits our dismissible code and closes the dialog or dropdown. Not what we want.
By listening to the `keydown` event instead, the `preventDefault` works and our code doesn't run in this scenario.
🎩 -tip to @jguann for raising this and @jorge-ramirez-arredondo for your help with the solution!

fix: dismissing on keydown so Esc on native elements like selects works

---

components/dropdown/README.md

updated properties of subtle button dropdown to include h-align

README: Include h-align property for subtle button

---

components/dropdown/README.md
components/dropdown/dropdown-button-subtle.js

h-align property was present for `d2l-button-subtle` but not `d2l-dropdown-button-subtl`e component. 
This PR adds the h-align property to the `d2l-dropdown-button-subtle` component

added h-align property to dropdown-button-subtle

---

components/meter/README.md

The `{%}` causes `illegal tag syntax` errors with 11ty 1.0. I tried to rephrase to avoid that piece.

fix: Daylight: Meter: Percentage replacement causing build issues

---

cli/clean.js
cli/icon-generator.js

@emsandrews noticed that on Windows, our icon generation step in `npm run build` was failing. This started happening when I converted core to ESM, which no longer exposes `__dirname` as a global.
While what we had here is [often recommended](https://techsparx.com/nodejs/esnext/dirname-es-modules.html) as an equivalent way to get `__dirname` in ESM-land, [this StackOverflow](https://stackoverflow.com/a/50052194) recommends using `fileURLToPath`, which indeed works. There are even comments talking about the Windows issues with the original solution.

fix: Windows-friendly way to get __dirname

---

components/count-badge/count-badge-icon.js
components/scroll-wrapper/scroll-wrapper.js
components/selection/selection-mixin.js
mixins/rtl-mixin.js

Currently, the count bubble is appearing on the incorrect side for RTL languages, until the badge is re-rendered (only on focus, which does not always happen). This leads to the bubbles swapping sides as you tab through the badges.
I was able to narrow down the issue to the RTL mixin not adding the dir="rtl" attribute until the count badge has already rendered. To fix this we can call the mixin's private property, _dir, which does get updated in its constructor. A bunch of places are already doing so (I assume because of similar timing issues?), see https://search.d2l.dev/search?full=%22this._dir%22&defs=&refs=&path=&hist=&type=&xrd=&nn=7&si=full&searchall=true&si=full. I don't think this is a great solution as we shouldn't be touching the mixin's private properties 😞 
An alternative …

RTL fix for count-badge-icon

---

mixins/rtl-mixin.js

Previously in the Daylight site `_dir` wasn't exposed because we filter out properties that start with underscores. The recent change to make `dir` public added this property to the properties tables for components that use `RtlMixin`.
This change just adds a description and values to `dir`, which does end up providing an easy to way to test RTL functionality in components that have it.

fix: Ignore dir in documentation

---

components/dropdown/dropdown-opener-mixin.js

This was causing issues with downstream polymer builds (found while working in [Brightspace/brightspace-activity-details-ui](https://github.com/Brightspace/brightspace-activity-details-ui)).

fix: remove use of optional chaining

---

components/dialog/README.md
components/dialog/demo/dialog.html
components/dialog/dialog.js

Original Rally Story: 
[DE46715](https://rally1.rallydev.com/#/?detail=/defect/622118312995&fdp=true): [A11y] Update all FACE help dialogs focus to be on the close (x) button instead of the okay button
In FACE quiz accessibility reviews it was pointed out that when the user opens the help dialog with the screen reader, the focus goes directly to the footer making it difficult for non-sighted users to access the dialog content. 
The original suggestion was to have the focus land on the close button at the top so users could navigate to the content text more easily, but based on my conversation with Dave B this would require larger changes to the dialog component. 
This is an alternative solution where there is an optional property added to the dialog that allows the content to be read out …

DE46715 added ariaDescribeContent property for a11y

---

components/list/list-header.js
components/list/list-item-mixin.js

Changes in order for the latest list item changes to be properly reflected in the Daylight site:
- Added `@ignore` to `slim` since it sounds like we wouldn't want that appearing in Daylight if we are planning to remove it
- Changed `@type` for `padding-type` to contain the possible options

fix: Daylight: List items: documentation changes

---

components/inputs/input-number.js
components/inputs/test/input-number.test.js

This is related to DS12459, which is being investigated by @tylergee and Team Borg. I'm going to backport it to `20.22.2` and `20.22.1`.
Little known fact (by me at least):
> If number is longer than 21 digits, JavaScript uses exponential (aka scientific) notation. JavaScript also uses exponential notation if number starts with “0.” followed by more than five zeros.
It's that second case of a number starting with zero and then having more than five zeroes that comes up in the defect. It results in `0.0000005` being saved as `5e-7.0000000` which then causes our .NET parsing code to explode.
The solution is to leverage the `Intl.NumberFormat` API to do all the heavy lifting for us.

fix: format using Intl API to avoid scientific notation

---

components/inputs/input-number.js
components/inputs/test/input-number.test.js

It was determined that this didn't need to be hotfixed, so reverting this out to prevent it accidentally getting released. @grant-cleary FYI.

fix: revert of #2071

---

components/inputs/docs/input-search.md
components/selection/selection-action-dropdown.js
components/table/README.md

Changes:
- search: make h3 title consistent with other components
- selection-action-dropdown: the other selection components hide this event with the `Internal event` description so this change does the same
- table: the second properties table is shown in Daylight so this makes the format of the tables on this page consistent with the generated properties tables

fix: Daylight: Minor documentation tweaks to table, input-search, and selection-action-dropdown

---

components/list/list-item-mixin.js

This PR fixes and issue regarding stacking context / `z-index` when using the html-editor in fullscreen mode within a list-item.  It is caused by list-items having their own stacking context, which was previously added to address https://github.com/BrightspaceUI/core/pull/1457.  The solution to this is the exact same as for tooltips and dropdowns inside of list-items - to bump up the `z-index` when the element is in a state where it would overlap other list-items.  It leverages the existing `d2l-fullscreen-within` event that the editor already dispatches for other reasons related to dialogs.
Screenshot showing the issue:

Fix list-items z-index to allow for embedded fullscreen html-editor.

---

components/dialog/dialog-mixin.js

An issue was reported in #web-platform about a scrollbar appearing for the confirm dialog at large font sizes. Digging into the height calculation, the footer had a height of 110.39 but that was being rounded down, causing the height to be slightly off and the scrollbar to appear. Using `getBoundingClientRect().height` instead of `scrollHeight` allow for us to get the demo value.
~I'm going to run this through visual diff before opening it for reviews in order to check if this breaks anything.~ Tests passed

fix: Dialog: Height calculation could be slightly off because of rounding

---

templates/primary-secondary/primary-secondary.js

Cert fix of https://github.com/BrightspaceUI/core/pull/2120
The 20.22.3 release of core was `1.231.1` (https://github.com/Brightspace/brightspace-integration/blob/20.22.3/package-lock.json#L1571). I had done a fix release after that so there is a `1.231.2`. The changes between the two are here https://github.com/BrightspaceUI/core/compare/v1.231.1...v1.231.2 . The changes I had made were documentation ones, so the riskiest ones that aren't in already would be the package-lock changes, but those seem like they'd be fine.

fix: Primary-secondary template: Remove -webkit-overflow-scrolling: cert fix

---

components/dropdown/README.md
components/inputs/docs/input-date-time.md

Changes the following:
- Removes the specialized script from the top demos in dropdown and input-date-time in order to use the `autoOpen` script already in Daylight, which will have a faster timeout
- Removes auto-opening for date/time inputs (not dropdowns - an alternative will be happening there within the documentation repo)

fix: Daylight: dropdowns: tweaks to auto-opening behaviour

---

components/list/list-item-mixin.js

This PR back-ports https://github.com/BrightspaceUI/core/commit/4dd515ca301048c36aca289a2ad042344e874dc3 to `v1.231`.

Backport fix to list-items z-index to allow for embedded fullscreen html-editor

---

components/tooltip/tooltip.js

Work is being done in Daylight to separate out more advanced properties from ones a user is more likely to need/use. PR https://github.com/BrightspaceUI/documentation/pull/596 . This is the first component that adds that `ADVANCED:` to the front of the description in order to filter those properties.
I'll be waiting to merge this until the corresponding Daylight PR is ready to merge, then I'll likely bump the version of core with this change in that PR.

fix: Daylight: Tooltip: Add ADVANCED in front of advanced properties

---

components/list/list-item-mixin.js

This PR updates the z-index of list-items to allow for the case where the editor is within a list-item, toggled to fullscreen mode while the floating workflow buttons are also displayed.

Update list-item z-index for fullscreen html-editor in list-item with floating workflow buttons

---

components/list/list-item-mixin.js

This PR back-ports: https://github.com/BrightspaceUI/core/pull/2137

Back-port fix for fullscreen elements inside of list-items when floating workflow buttons are present.

---

components/inputs/input-date-range.js
components/inputs/input-date-time-range.js
components/inputs/input-date.js
components/inputs/input-number.js
components/inputs/input-text.js
components/inputs/input-textarea.js
components/inputs/input-time-range.js

This will hide them under the "show advanced properties" part of the properties table. 
This was a best guess and I leaned more towards show too many than show less. Let me know if there's others I missed or if any of these should probably be shown by default.

fix: Daylight: Add "Advanced" to more advanced properties

---

components/html-block/html-block.js

There's CSS in the html-block component that applies when `dir="rtl"` so it seems likely to me that we want this mixin applied. The only thing I'm unsure about is if we're unsure about applying this blindly to user-provided HTML, but the HTML control implicitly does this so I suspect it's still what we want.

HTML block component should respect document dir

---

.github/workflows/update-package-lock.yml

Thanks to @devpow112 for the callout (https://github.com/BrightspaceUI/core/pull/2129#pullrequestreview-887226110)!  Previously, additional commits added to an open `package-lock.json` update PR wouldn't trigger ci (found during the BSI migration).  I [fixed the action](https://github.com/BrightspaceUI/actions/pull/55/files) and [updated the README instructions](https://github.com/BrightspaceUI/actions/pull/56/files), but didn't add the fix to `core`.  Doing that here!

Fix update-package-lock workflow credentials

---

components/list/list-item-mixin.js

This PR fixes an issue in Safari where the fullscreen html-editor (`position: fixed;`) within the list-item is not stacked properly.  I only observe this issue at larger viewport heights - resizing the browser to be shorter can cause the editor to suddenly appear.  Oddly, it can also appear by adjusting the editor's `z-index` to be smaller in the dev console, which is also counter to what one would expect.  This seems like a buggy behaviour with Safari.  Changing the positioning of the list-item when an element within is fullscreen addresses the issue.
Screenshot showing the incorrect behaviour:
Screenshot showing the corrected behaviour:

Update list-item to be absolute positioned when fullscreen within for Safari.

---

components/list/list-item-mixin.js

This PR is the 2nd attempt to work around some buggy behaviour in Safari.  The stacking context is messed up - the fullscreen editor should be on top.  This scenario is more complex (fullscreen editor in list-item in scroll-wrapper in fullscreen dialog) than the previous scenario, though it is not clear why Safari is messing up.
Before the fix:
After the fix:

Attempt 2 for fixing stacking issue with fullscreen editor in list items.

---

components/tooltip/demo/tooltip.html
components/tooltip/tooltip.js
helpers/README.md
helpers/dom.js
helpers/test/dom.test.js

Before we can change our button-like components to leverage `aria-describedby` for their `description` attributes, we need to fix `<d2l-tooltip>` (which also uses `aria-labelledby` and `aria-describedby`) so that it doesn't clobber any existing values in those attributes.
To solve that, I created two DOM helpers which can be used to manipulate space-separated ID-list attributes. I switched tooltip to use them.

feat: adding id-list attribute manipulation helpers

---

components/button/README.md
components/button/button-icon.js
components/button/button-subtle.js
components/button/button.js
components/button/test/button-icon.axe.js
components/button/test/button-subtle.axe.js
components/button/test/button.axe.js

As requested by @aid848, this switches our button-like components to use `aria-describedby` for their descriptions instead of `aria-label`. We feel as though having `description` be a supplementary label and not a primary label is both more to the spirit of the attribute name and more useful overall.
I've [audited the places](https://rally1.rallydev.com/#/15545167705ud/custom/21568985922?detail=%2Fuserstory%2F628716941319) using `description` (there were 8) and none of them were of concern or [have been addressed](https://github.com/Brightspace/lms/pull/20344).

feat: button descriptions use aria-describedby

---

components/inputs/test/input-helper.js
components/inputs/test/input-time.visual-diff.js

Ran several times locally and with this pattern I didn't see flake. I'll try several times here too and we'll see.

Visual-diff: Input-time: Use timeout to fix flakiness

---

components/list/list-item-mixin.js

This PR back-ports this fix: https://github.com/BrightspaceUI/core/pull/2205

Back-port fix for fullscreen elements within list-items.

---

components/button/button-mixin.js
components/card/card.js
components/filter/filter.js
components/focus-trap/focus-trap.js
components/inputs/input-checkbox.js
components/inputs/input-date-range.js
components/inputs/input-date-time-range.js
components/inputs/input-date-time.js
components/inputs/input-date.js
components/inputs/input-number.js
components/inputs/input-percent.js
components/inputs/input-search.js
components/inputs/input-text.js
components/inputs/input-textarea.js
components/inputs/input-time-range.js
components/inputs/input-time.js
components/link/link.js
components/selection/selection-action-dropdown.js
components/selection/selection-action.js
components/selection/selection-select-all-pages.js
components/selection/selection-select-all.js
components/switch/switch-mixin.js
components/table/table-col-sort-button.js
mixins/focus-mixin.js
mixins/focus-mixin.md
mixins/test/focus-mixin.test.js

Like optional chaining, `polymer-cli` hates the new-style static getters. While this is a great opportunity to force repos to switch to `@web/test-runner` and remove `polymer-cli` entirely, it could slow down the Lit 2 upgrade. So for now, I'm putting this back to use the old syntax.

fix: going back to a polymer-cli friendly static getter

---

components/demo/code-view.js

I'm trying to get a demo working for a client and to show how to build our components with Rollup, but the `rollup-plugin-dynamic-import-variables` plugin that we use to fix our dynamic import language files doesn't allow arbitrary variables in imports.
Regardless, I don't think this hack is needed anymore as Polymer CLI should be abandoned easily enough, IE11/Edge are gone and I tested this in Firefox and it was fine.

fix: demo import

---

mixins/arrow-keys-mixin.md

Noticed this when using the mixin for tags - I think the current README example just wouldn't work?  Or am I missing something?
Also fixed a typo in the function name.

Fix some typos, add some more detail to ArrowKeysMixin README

---

components/tabs/tab-panel-mixin.js

This was noticed [in my-courses](https://github.com/Brightspace/d2l-my-courses-ui/pull/922/). Tab panels were relying on the `attributeChangedCallback` to update the `aria-label` and fire the `d2l-tab-panel-text-changed` event -- which `<d2l-tabs>` uses to keep the actual tab label updated.
But `attributeChangedCallback` isn't called when properties are set directly. This switches to using `updated()`. I've tested this in my-courses and it addresses the issue.

fix: handling text change in updated

---

components/filter/filter.js

There seems to be a potential race condition when adding a new `d2l-filter-dimension-set-value`, where the element is attached and fires an event to the dimension saying its text has been changed, before the dimension has fired its event to tell the filter about the new value.  This isn't a problem (the first event can just be safely ignored), but the check here wasn't accounting for the fact that it might not be able to find a value for a value event.

fix: Fix event race condition in filter

---

components/list/list-item-generic-layout.js

This was showing itself in Daylight and possibly within another team's feature.
The `control-action` slot div that wraps this https://github.com/BrightspaceUI/core/blob/main/components/list/list-item-checkbox-mixin.js#L164 (which is what triggers the click workflow to select/unselect) sometimes had no height/width resulting in no clickable area. Actually specifying a 100% height and width, which seems to be what it ends up with by default when working properly, seems to fix this.
I have done some quick testing in Safari and Chrome on Mac on the demo page and on Daylight (list and filter pages). If the visual-diffs pass and this solution seems good I'll do some more cross-browser/device testing as well.

fix: List: Safari: selectable items are not always selectable

---

components/inputs/input-text.js

This PR updates the `aria-label` to include the `unit`.  Previously, when the label was hidden, an accessible `unit` would not be rendered or announced because it is rendered as part of the `label`.  I also played around with rendering the unit as part of the aria description, but appending to the label provided the best announcement, and also keeps it consistent with how it's announced when the label is visible.

Fix input-text to include the unit in the aria-label.

---

components/list/demo/list-drag-and-drop.js
components/list/list-item-drag-handle.js
components/list/list-item-generic-layout.js
components/list/test/list-item-drag-handle.test.js
components/list/test/list-item-generic-layout.test.js

`DE47878` refers to the the first list option being selected when the filter is opened using the enter key.  This is an issue with `d2l-list` listening to `keyup` events instead of `keydown`, mixed with moving `focus` into the dropdown on open.
This PR switches everything that happens on `keyup` to instead happen on `keydown`, and removes the code that was previously suppressing all the corresponding `keydown` events.

DE47878 - Switch list to acting on keydown events instead of keyup

---

components/tag-list/README.md
components/tag-list/tag-list.js

The tag-list example has been updated to show off the line clamping/hiding.
`_lines` changing should also trigger a re-render.

fix: tag-list: Update example, _lines property

---

tools/mathjax-test-context.js

We are currently using this is rubrics vdiff, tests and demo pages to auto setup the mathjax context. I'd like to include it with the core (similar to https://github.com/BrightspaceUI/core/blob/main/tools/resize-observer-test-error-handler.js) so that we can use it from this component across multiple repos in testing scenarios (similar to https://github.com/BrightspaceUI/core/blob/main/web-test-runner.config.js#L31-L37).

Add mathjax test context

---

components/list/list-item-mixin.js

This PR fixes the primary action styling so that the underline and color are only applied on the content when the content action is hovered or focused (i.e. not secondary actions).

Fix list-item primary content action styling.

---

components/html-block/README.md
components/html-block/demo/html-block.html
index.html
tools/mathjax-test-context.js

Also update documentation. Should have done this with my other PR but didn't. This expands on #2288 and switches `core` demos to use the new file. Required a bit of re-work since didn't realize we had a demo page that disabled it. This should work, you need to explicitly set `latex=false` on a URL for a demo page or test to disable the test context render latex property, otherwise it's enabled.

Use mathjax context in demos

---

tools/mathjax-test-context.js

Adding warning so if this accidently get's used incorrectly within a component we can see this message. Add on to #2289.

fix: add mathjax test context warning message

---

components/list/list-item-drag-handle.js

This PR fixes an issue where NVDA announces the position and instruction for keyboard "move" button three times when moving an item up. (it would announce once as expected when moving down). Removing the `aria-live` fixes the issue, and the position & instruction are announced once as expected, moving up or down. Checked behaviour with both NVDA and VoiceOver.

Fix so that NVDA doesn't announce list items 3 times when moving them up with keyboard.

---

components/tag-list/tag-list-item-mixin.js

If the focus is coming directly from the tag list item host (such as the case where the arrowKeysMixin moves the focus), then the container should be focused. 
If the focus bubbles up from an item inside the tag (ie. profile tags contain the profile card dropdown inside them), then do not force focus on the container.

Ignore focus events coming from inside tag items to prevent focus looping

---

package-lock.json

Picks up any lock file updates since version `2.x` was created a few weeks ago and merges them into the newly created `1.x` branch. Should also find any visual-diffs that may have snuck in since then so we can get them merged before the colour changes.

fix: updated package-lock

---

components/inputs/demo/input-time-range.html
components/inputs/test/input-time-range.test.js

I went to look into https://github.com/BrightspaceUI/core/issues/1751 and it seems to already be fixed. I added the previously broken case from the issue to the demo page and tested across chrome, firefox, Safari, and Edge, and then added back the previously ordered unit tests from the PR mentioned in the issue.

Issue 1751: d2l-input-time-range: Add tests to prevent regression and confirm fix

---

components/html-block/README.md

The README was left slightly inaccurate after some of my recent work. It's required that the `mathjax` context be set any time math is to be rendered.

Make sure to set MathJax context in html-block demo

---

components/tag-list/tag-list.js
lang/ar.js
lang/cy.js
lang/da.js
lang/de.js
lang/en.js
lang/es-es.js
lang/es.js
lang/fr-fr.js
lang/fr.js
lang/hi.js
lang/ja.js
lang/ko.js
lang/nl.js
lang/pt.js
lang/sv.js
lang/tr.js
lang/zh-cn.js
lang/zh-tw.js

Changes to the following:
- Fix the description being read on VoiceOver
- Improve keyboard navigation experience for screen reader users
The keyboard changes are a bit "bold" so let me know if they disobey some sort of recommended pattern.

fix: tag-list: accessibility improvements

---

.github/workflows/release.yml

This action was blowing up on the new comments in our translations as it was treating the JS files as JSON. It's also completely redundant since the translations would fail validation in CI if any language files were missing entries.
Since the action is only used in core and htmleditor, I'm removing it from both and will delete the action itself after.

fix: removing the redundant prepare translations step

---

components/dialog/dialog-confirm.js
components/dialog/dialog-fullscreen.js
components/dialog/dialog-mixin.js
components/dialog/dialog.js

The comment documentation of `d2l-dialog-before-close` doesn't work as expected (description ends up empty) because it needs to be above the `dispatchEvent`, which also needs to contain the event name (e.g., the actual contents of `abortEvent` would need to be within `this.dispatchEvent`). This is a bit complicated in this case because of the function returning `abortEvent.defaultPrevented` and so in this case it makes sense to document in each case that is using the `DialogMixin`.

fix: Dialog: Move location of documentation of d2l-dialog-before-close

---

components/html-block/html-block.js

The `d2l-html-block-rendered` class will soon be used to target CSS on things outside of the html-block component, so we should be sure it doesn't get changed lightly.
Alternatively, if we want to switch up the CSS to target and use a different class, that's also fine... Though the same caveat applies in that case.

Add comment indicating importance of d2l-html-block-rendered class

---

components/tag-list/demo/tag-list.html
components/tag-list/tag-list.js
mixins/interactive-mixin.js
mixins/test/interactive-mixin.test.js

This PR addresses two a11y issues with the `InteractiveMixin`:
1. VoiceOver + Safari: reads the label, not the description/instructions when tabbing to the interactive wrapper. Pressing `Enter` does move focus into the tag list but nothing is announced about the tags
2. NVDA + Firefox: reads the label and the description/instructions but it prevents the user from toggling when pressing `Enter` (without NVDA on the keyboard interactions work fine)
The solution to the above issues is to change the rendering so that the toggle is an offscreen `button` (keyboard access only) that is sibling to the interactive contents, instead of nesting the contents within a toggle `div`.  Seemingly, screen readers do not like it when focusables are nested within other focusables.

InteractiveMixin A11y Fixes

---

components/html-block/html-block.js

Noticed this when I was doing something else, but I think this was just a miss from when I originally broke these styles out into a separate export. The intent was to leave `:host`-specific selectors in the component proper because it's not clear that they're always going to be applicable to an arbitrary consumer.

Shift htmlBlockStyles text-align style back into component

---

components/dialog/dialog-mixin.js

Safari shipped native `<dialog>`s in version 15.4 and our fullscreen dialog in mobile viewports is very broken. I'm also seeing focus-trap issues when the native `<dialog>` is used.
Since this is affecting production and we need to cert & hotfix it quickly, this is a temporary fix that will just cause Safari to fall back to the non-native dialog solution that it's been using previously. That'll buy us time to address this properly.

fix: temporary fix to not use native dialogs in Safari

---

components/dialog/test/dialog-mobile-dropdown.visual-diff.js

Try to address the visual-diff flake with the mobile dropdown in nested dialog tests

Visual Diff Flake

---

components/list/README.md
components/list/demo/list.html
components/list/list-item-generic-layout.js
components/list/list-item-mixin.js
mixins/arrow-keys-mixin.js
mixins/interactive-mixin.js

This PR updates the list-item components to support interactive elements inside their content.  The consumer must specify `no-primary-action` to ensure the interactive elements are not blocked by action layers for mouse users.

Update list-items to support interactive element in list-item content.

---

components/dialog/dialog.js

Noticed this JS error gets thrown during dialog initialization in `_updateOverflow` if the viewport is initially small enough to fall into the "mobile" category.
The reason is that `_updateSize` is called from `resize()` which is called from `_handleResize()` which is called [from Dialog's constructor](https://github.com/BrightspaceUI/core/blob/main/components/dialog/dialog.js#L109). In Lit 2, the constructor runs before there's a shadow root.
In mobile mode, the code skips past all [this autoSize logic](https://github.com/BrightspaceUI/core/blob/main/components/dialog/dialog-mixin.js#L461) which has a bunch of `await this.updateComplete`s in it and therefore defers the run long enough for the component to have rendered.

fix: content not available early in mobile rendering pipeline

---

components/dialog/dialog-mixin.js
components/tag-list/test/tag-list.visual-diff.js

Native `<dialog>` elements essentially implement the `inert` behaviour in that they come with their own focus trap logic, so we don't need `<d2l-focus-trap>` when native dialogs are used.
The only difference between theirs and ours is that focus will cycle up to the browser chrome and then back into the window, just like it normally does -- which I think is better anyway.

fix: exclude d2l-focus-trap for native dialogs

---

helpers/mathjax.js

Occurs to me that I missed the `noDeferredRendering` case. Not sure we need to bother backporting this because it's already a bit of an edge case, but we should still fix it.

Make sure we're also fixing newlines in noDeferredRendering case

---

components/html-block/README.md
components/html-block/html-block.js

Backport of this PR into 2.10.x: https://github.com/BrightspaceUI/core/pull/2439

Allow html-block to render inline

---

components/html-block/html-block.js

I believe we only want this specified for untrusted HTML. Otherwise if we were to try to render a profile card or something of the like inside an html-block and it didn't fit the bounds of the component, we wouldn't have a means to position it properly outside of fixed positioning shenanigans.

Remove relative positioning; consumers should decide this

---

components/html-block/demo/html-block.html
helpers/mathjax.js

The MathJax output processor we're using loads a bunch of TeX extensions automatically, but this loading is lazy and only happens when math using it is detected on the page. This means, however, that we also need to explicitly wait for these extensions to load before we can typeset anything.
Context: The symptom here was that the LaTeX `\color` command wasn't always working properly. A forced re-render of the math seemed to kick it into functioning properly, hence my realization that the extension wasn't always loading when first typesetting.

Make sure autoloaded MathJax extensions are actually loaded before typesetting

---

helpers/mathjax.js

While `string.prototype.replaceAll` is supported in all of our supported browsers, including all of our maintenance versions, it's easy enough to just switch to using `replace` with regex to make that almost universal. So... May as well.

Use safer replace API to support older browsers

---

components/switch/switch-visibility.js

`text` in visibility switch was using the definition in the mixin, which marks it as required. For visibility switch, it is not required since it does have the fallback default of "Visibility".

fix: Daylight: Visibility switch: override text definition

---

components/dropdown/dropdown-content-mixin.js

This PR fixes the dropdown content positioning logic to handle the target wrapping case.  The problem would only arise when the dropdown was previously shown with the target not wrapping, and then subsequently shown with the target wrapping.
For example, before fix, not wrapping:
Then resize to cause wrapping, before fix, wrapping:
After fix, wrapping:

Update dropdown position logic to handle wrapping case

---

components/calendar/calendar.js
components/calendar/test/calendar.visual-diff.js
components/filter/test/filter.visual-diff.js
components/inputs/input-date.js
components/inputs/input-number.js
components/inputs/input-time.js
components/inputs/test/input-date.visual-diff.js
components/inputs/test/input-time.visual-diff.js
mixins/localize-mixin.js
mixins/test/localize-mixin.test.js

This PR does a few things:
- Update the name of the localize event we fire to be more accurate.  I audited all outside usages and they're all using the Polymer behaviour, which does still fire the old event.
- Make that event no longer `bubble` or `composed`, because it doesn't need to be.
- Fire the event every time the resources change, not just after the first time.  This doesn't change how anything works here in `core` (because we always listen in `firstUpdated`, meaning we miss the first event and will only get language updates) but this is helpful for HM components using OSLO.  They may get their data faster then the langterms, and they need to know when to update any stored terms.  Ideally they don't store these terms, but we have some components that send these terms in an event, …

US138697 - Update localize event

---

tools/mathjax-test-context.js

Had some demo pages that were auto adding this script via the dev server config and had also explicitly added it. This cause errors about `disabled` being already defined. Just removing intermediate variable to avoid issue.

fix: adjust mathjax demo helper

---

components/filter/README.md

There was 3 missing "forward slashes" to indicate closing tag elements which I have added and corrected.

Fix typo in components/filter README

---

components/backdrop/backdrop.js

I noticed this in a test fixture in another repo where it opened a dialog but then didn't close the dialog before moving on to the next fixture. The backdrop would then try to hide itself but it had already been detached from the DOM, so `parent` became `null`.

fix: check for null parent

---

components/selection/selection-mixin.js
components/selection/test/selection.test.js

https://rally1.rallydev.com/#/?detail=/defect/638775912441&fdp=true
Changed the Selection-Mixin, selecting all items in the list will only check off elements that are enabled.
Would it be worth adding a disabled element to the select-all example on the Daylight site?

DE48739 - Select-all button no longer checks off disabled selection-items

---

components/selection/README.md

This pull request contains many changes to the Selection component documentation page on Daylight. 
Changes:
- Added a ‘Use Case’ header to the top of the page to make the use case of SelectionMixin more clear and direct consumers to the d2l-list component if needed. I am open to better names for this header.
- Changed SelectionMixin explanation to improve clarity.
- Changed name CustomComponent to DemoComponent in SelectionMixin example for consistency with other examples.
- Added links to SelectionMixin whenever “selection control” is mentioned in descriptions in the other selection components.
- Removed references to selection-for in demo examples as examples did not use it. Replaced with explanation of selection-for.
- Altered various demos on the page to improve clarity and UX.

oelhanafey/Selection Documentation Updates

---

components/menu/README.md

Nested menus on the menu component page ([Link to Daylight](https://daylight.d2l.dev/components/menu/#nested-menus)) did not have a live code demo showing how to create nested menus.
I made the demo code visible and shortened the example to make the code more readable. I maintained all of the important things that the demo is showing (multi-level nested menus, multiple nested menus in a single menu) but removed some of the excess menu-items.

Documentation: Added live code demo to nested menus

---

components/validation/README.md

This PR corrects the example in the readme for `d2l-validator-custom`. The event is dispatched on the validator, not the element being validated. The tests are working as expected.

Fix the readme example for d2l-validator-custom.

---

components/menu/menu.js
components/menu/test/menu.test.js

Using both `LocalizeDynamicMixin` and `MenuItemMixin` in a component is resulting in the `menu` trying to get its menu-items before their `role` attribute has been set (because of the delay in updating caused by `LocalizeDynamicMixin`).  There's a number of ways we could try to solve this (changes to how localizing works, using a MutationObserver in `menu`, adding a way for menu items to re-trigger the menu initializing code, etc.) This PR first checks that all the potential menu items have updated before checking their `role` attribute.

fix: Have menu wait before checking the role of its menu items

---

components/filter/README.md

The links don't work in the README and also don't work in Daylight. With this change they will at least work in Daylight.
This adds a simple demo for `Filter Dimension: Set Value` and hides its properties table. It was originally not included (see https://github.com/BrightspaceUI/core/pull/1776#discussion_r722613522 for context) but my feeling is at this point it's useful for consistency in how we communicate properties and for having the single source of truth for our properties.

fix: filter: Add demo for "Filter Dimension: Set Value" and fix links

---

components/tooltip/tooltip-help.js

[Related US](https://rally1.rallydev.com/#/15545167705d/dashboard?detail=%2Fuserstory%2F639335980519)
Necessary for backport into Grades.
Small PR. Contains changes decided from discussion with Jeff and Nicole [here](https://d2l.slack.com/archives/C03H8KH2FKN/p1657307056131889).
In particular to note: [this ](https://d2l.slack.com/archives/C03H8KH2FKN/p1657556062926539?thread_ts=1657307056.131889&cid=C03H8KH2FKN) and [this](https://d2l.slack.com/archives/C03H8KH2FKN/p1657556573509059?thread_ts=1657307056.131889&cid=C03H8KH2FKN).

Help Tooltip > Allow opener text to inherit cursor from ancestor, but always keep tooltip contents as text cursor

---

components/dropdown/dropdown-opener-mixin.js

I have a scenario where a `dropdown-opener-mixin` consumer also displays a tooltip on hover/focus. This is likely going to become more common going forward.
The issue is that we'd like to suppress the tooltip when the dropdown is open... otherwise you get this crazy fun:
Unfortunately, dropdown opener mixin consumers currently have no way to know when the dropdown is opened/closed. So this change switches `_isOpen` from a "private" property to a public state property.
At this time, I don't _think_ we want to document this, so I've added `@ignore`.

feat: make dropdown open state available to mixin consumers

---

components/tooltip/test/tooltip.test.js
components/tooltip/tooltip.js

Ran into this issue in a scenario where a tooltip is conditionally rendered. When the tooltip is initially rendered, it adds `aria-labelledby` (or `aria-describedby`) to the target pointing back at the tooltip -- all good.
But then when it's removed and then re-added later, now the target will have TWO values for `aria-labelledby`, only one of which is now valid.

fix: clean up aria-describedby/labelledby on tooltip target

---

helpers/prism.js

When code is long, CodeMirror allows horizontal scrolling of the code, which causes the code to scroll underneath the code numbers container, so we prefer an opaque color for the line-numbers background. This change converts from the semi-transparent HEX color to the equivalent opaque color. We don't need to worry about different background colors since they are present for light & dark color schemes. The light scheme already uses an opaque color.
Example showing issue.

Update Prism line-numbers background-color
